Repository yuzu-emu/yuzu, pull requests merged in 2018-10, with the labels that each got.

#1330 TLDS: Add 1D sampler
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: gpu-new

#1407 aoc_u: Implement functions and add support for DLC loading
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/romfs_factory.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/aoc/aoc_u.h
Labels: canary-merge

#1432 service/lbl: Update service function table
  src/core/hle/service/lbl/lbl.cpp
Labels: hle-new

#1436 submission_package: Cleanup and bug fixes
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
Labels: bug, style

#1429 configure_input: Make analog mapping strings translatable
  src/yuzu/configuration/configure_input.cpp
Labels: frontend-fix

#1433 services/fsp_srv: Amend service function table
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: hle-new

#1431 configure_audio: Minor cleanup-related changes
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_audio.h
Labels: style

#1428 configure_graphics: Make functions internally linked where applicable
  src/yuzu/configuration/configure_graphics.cpp
Labels: style

#1434 aoc_u: Fix edge case with DLC that causes breaks
  src/core/hle/service/aoc/aoc_u.cpp
Labels: core-fix

#1415 file_sys: Add support for loading IPS patches
  src/core/CMakeLists.txt
  src/core/file_sys/ips_layer.cpp
  src/core/file_sys/ips_layer.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/nso.cpp
  src/core/loader/nso.h
  src/yuzu/game_list_worker.cpp
Labels: canary-merge, core-new

#1442 text_formatter: Avoid unnecessary string temporary creation in PrintMessage()
  src/common/logging/text_formatter.cpp
Labels: style

#1439 kernel/thread: Make all instance variables private
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/gdbstub/gdbstub.cpp
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/mutex.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/wait_object.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: style

#1445 thread: Make the scheduler pointer a regular pointer
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: style

#1440 ui_settings: Place definition of the theme array within the cpp file
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/ui_settings.cpp
  src/yuzu/ui_settings.h
Labels: style

#1447 kernel/mutex: Amend behavior of TransferMutexOwnership()
  src/core/hle/kernel/mutex.cpp
Labels: hle-fix

#1449 qt: Update telemetry links
  src/yuzu/configuration/configure_web.cpp
  src/yuzu/main.cpp
Labels: bug

#1437 Implemented Depth Compare, Shadow Samplers and Texture Processing Modes for TEXS and TLDS
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/textures/texture.h
Labels: canary-merge

#1446 gl_rasterizer: Implement accelerated Fermi2D copies.
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
  src/video_core/gpu.cpp
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: canary-merge

#1396 loader: Add support for packed updates
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/romfs_factory.h
  src/core/file_sys/submission_package.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nax.cpp
  src/core/loader/nax.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
  src/yuzu/game_list_worker.cpp
Labels: core-new

#1457 Unmapping an unmapped buffer should succeed
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
Labels: hle-fix

#1424 ips_layer: Add support for IPSwitch executable patches
  src/common/hex_util.cpp
  src/common/hex_util.h
  src/core/file_sys/ips_layer.cpp
  src/core/file_sys/ips_layer.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
Labels: core-new

#1423 fsmitm_romfsbuild: Add support for stubbing and IPS patches in LFS
  src/core/file_sys/fsmitm_romfsbuild.cpp
  src/core/file_sys/fsmitm_romfsbuild.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/romfs.cpp
  src/core/file_sys/romfs.h
Labels: core-new

#1455 Fixed smo softlock due to incorrect effect state updating
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
Labels: bug, canary-merge, hle-fix

#1462 ips_layer: Minor miscellaneous changes
  src/core/file_sys/ips_layer.cpp
  src/core/file_sys/ips_layer.h
Labels: style

#1465 telemetry_session: Minor miscellaneous changes
  src/core/telemetry_session.cpp
  src/core/telemetry_session.h
Labels: style

#1466 gl_shader_decompiler: Remove unused variables in TMML's implementation
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: style

#1464 patch_manager: Return a std::unique_ptr from ParseControlNCA() and GetControlMetadata() instead of a std::shared_ptr
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
  src/yuzu/game_list_worker.cpp
Labels: style

#1461 ips_layer: Silence truncation and conversion warnings
  src/core/file_sys/ips_layer.cpp
Labels: style

#1469 kernel/thread: Use a regular pointer for the owner/current process
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/core.cpp
  src/core/core.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/tests/core/arm/arm_test_common.cpp
Labels: style

#1425 gl_shader_decompiler: Implement geometry shaders
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/utils.h
Labels: canary-merge, gpu-new

#1460 Implemented Scissor Testing
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: canary-merge

#1476 nvhost_as_gpu: Flush/invalidate CPU VAddr on UnmapBuffer.
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
Labels: canary-merge

#1472 svc: Add missing address range sanitizing checks to MapMemory/UnmapMemory
  src/core/hle/kernel/errors.h
  src/core/hle/kernel/svc.cpp
Labels: canary-merge, hle-fix

#1474 HwOpus, Implemented DecodeInterleavedWithPerformance
  src/core/hle/service/audio/hwopus.cpp
Labels: canary-merge

#1482 thread: Remove unnecessary memset from ResetThreadContext()
  src/core/hle/kernel/thread.cpp
Labels: style

#1481 svc: Fix typos in sanitizing checks for MapMemory/UnmapMemory
  src/core/hle/kernel/svc.cpp
Labels: hle-fix

#1483 kernel/process: Make CodeSet a regular non-inherited object
  src/core/hle/kernel/object.cpp
  src/core/hle/kernel/object.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/loader/elf.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
Labels: style

#1492 svc: Implement svcGetProcessInfo
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
Labels: hle-new

#1480 Introduce 3D Swizzle seamlessly
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
  src/video_core/textures/texture.h
  src/yuzu/debugger/graphics/graphics_surface.cpp
Labels: canary-merge

#1491 filesystem: Make CreateFactories() and InstallInterface() take a VfsFilesystem by reference
  src/core/core.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: style

#1486 key_manager/partition_data_manager: Minor changes
  src/core/crypto/key_manager.cpp
  src/core/crypto/key_manager.h
  src/core/crypto/partition_data_manager.cpp
  src/core/crypto/partition_data_manager.h
Labels: style

#1500 crypto: Various crypto fixes for quickstart guide
  src/core/crypto/partition_data_manager.cpp
  src/yuzu/main.cpp
Labels: core-fix

#1499 nro/nso: Minor error handling changes
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nro.cpp
  src/core/loader/nro.h
  src/core/loader/nso.cpp
  src/core/loader/nso.h
Labels: style

#1494 aoc: Fix various bugs in current AOC implementation
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/hle/service/aoc/aoc_u.cpp
Labels: core-fix

#1504 file_sys/control_metadata: Get rid of magic constants
  src/core/file_sys/control_metadata.cpp
Labels: style

#1487 yuzu/main: Apply the [[maybe_unused]] attribute to the parameter of SetDiscordEnabled
  src/yuzu/main.cpp
Labels: style

#1473 web_service: Make linkage of web_service-related externals and the library private
  src/common/web_result.h
  src/core/CMakeLists.txt
  src/web_service/telemetry_json.cpp
  src/web_service/telemetry_json.h
  src/web_service/verify_login.cpp
  src/web_service/web_backend.cpp
  src/web_service/web_backend.h
Labels: build-system

#1508 file_sys/registered_cache: Use unique_ptr and regular pointers instead of shared_ptrs where applicable
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/bis_factory.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/sdmc_factory.cpp
  src/core/file_sys/sdmc_factory.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/ns/pl_u.cpp
  src/yuzu/game_list_worker.cpp
  src/yuzu/game_list_worker.h
Labels: style

#1509 savedata_factory: Add DeviceSaveData and fix TemporaryStorage
  src/core/file_sys/savedata_factory.cpp
Labels: core-fix

#1496 Implement Arrays on Tex Instruction
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge

#1498 svc: Clarify enum values for AddressSpaceBaseAddr and AddressSpaceSize in svcGetInfo()
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc.h
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
Labels: hle-fix

#1497 Implement flushing in the rasterizer cache
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: canary-merge

#1505 Implemented 3D Textures
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1510 XCI: Add function for checking the existence of the program NCA
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/loader/xci.cpp
Labels: style

#1522 core: Remove unnecessary assert in ArmInterface()
  src/core/core.cpp
Labels: style

#1511 content_archive: Minor reorganization changes
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
Labels: style

#1523 svc: Add missing error checks in svcArbitrateLock/svcArbitrateUnlock
  src/common/alignment.h
  src/core/hle/kernel/svc.cpp
Labels: hle-fix

#1529 crypto: Use compressed sizes in offset calculation for KIP decompression
  src/core/crypto/partition_data_manager.cpp
Labels: bug

#1516 hid: Minor cleanup-related changes
  src/core/hle/service/hid/controllers/controller_base.cpp
  src/core/hle/service/hid/controllers/controller_base.h
  src/core/hle/service/hid/controllers/debug_pad.cpp
  src/core/hle/service/hid/controllers/debug_pad.h
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/gesture.h
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/keyboard.h
  src/core/hle/service/hid/controllers/mouse.cpp
  src/core/hle/service/hid/controllers/mouse.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/controllers/stubbed.cpp
  src/core/hle/service/hid/controllers/stubbed.h
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
  src/core/hle/service/hid/controllers/xpad.cpp
  src/core/hle/service/hid/controllers/xpad.h
Labels: style

#1530 aoc_u: Stub GetAddOnContentListChangedEvent
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/aoc/aoc_u.h
Labels: core-fix

#1526 service: Update function tables
  src/core/hle/service/am/omm.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/es/es.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/set/set_cal.cpp
Labels: hle-new

#1520 svc: Add missing sanitizing checks for MapSharedMemory/UnmapSharedMemory
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
Labels: hle-new

#1501 gl_shader_decompiler: Implement H* instructions
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1546 service: Update service function tables
  src/core/CMakeLists.txt
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applet_ae.cpp
  src/core/hle/service/am/applet_oe.cpp
  src/core/hle/service/am/idle.cpp
  src/core/hle/service/am/tcap.cpp
  src/core/hle/service/am/tcap.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/lbl/lbl.cpp
  src/core/hle/service/npns/npns.cpp
  src/core/hle/service/npns/npns.h
  src/core/hle/service/prepo/prepo.cpp
  src/core/hle/service/service.cpp
Labels: hle-new

#1538 svc: Fix vma boundary check in svcQueryMemory
  src/core/hle/kernel/svc.cpp
Labels: hle-fix

#1541 web_service/CMakeLists: Make the CPPHTTPLIB_OPENSSL_SUPPORT constrained to the web_service library only
  src/web_service/CMakeLists.txt
Labels: build-system

#1537 gl_shader_decompiler: Minor changes
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: style

#1543 CMakeLists: Use target_compile_definitions instead of add_definitions to define YUZU_ENABLE_COMPATIBILITY_REPORTING
  src/yuzu/CMakeLists.txt
Labels: build-system

#1470 Implemented Alpha Test using Shader Emulation
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
Labels: canary-merge

#1539 maxwell_dma: Silence compilation warnings
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_compute.cpp
  src/video_core/engines/maxwell_dma.cpp
Labels: style

#1540 kernel/process: Make the handle table per-process
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/process.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: hle-fix

#1553 common: Remove memory_util.h/.cpp
  CMakeLists.txt
  src/common/CMakeLists.txt
  src/common/memory_util.cpp
  src/common/memory_util.h
Labels: build-system, style

#1542 CMakeLists: Use PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR
  CMakeLists.txt
  src/web_service/CMakeLists.txt
  src/yuzu/CMakeLists.txt
Labels: build-system

#1468 qt: Add UI to manage emulated user profiles
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
  src/core/hle/service/am/am.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_system.ui
  src/yuzu/main.cpp
  src/yuzu_cmd/config.cpp
Labels: core-new, frontend-new

#1561 file_sys: Remove unused variables
  src/core/crypto/key_manager.cpp
  src/core/file_sys/vfs.cpp
Labels: style

#1560 maxwell_3d/decoders: Remove unused variables
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/textures/decoders.cpp
Labels: style

#1562 aoc_u: Make use of previously-unused CheckAOCTitleIDMatchesBase() function
  src/core/hle/service/aoc/aoc_u.cpp
Labels: style

#1563 perf_stats: Remove unused variable within DoFrameLimiting()
  src/core/perf_stats.cpp
Labels: style

#1566 bootmanager: Use QStringLiteral instead of std::string to represent the window title.
  src/yuzu/bootmanager.cpp
Labels: style

#1567 game_list: Make game list column headers translatable
  src/yuzu/game_list.cpp
Labels: frontend-fix

#1568 game_list: Use QFileInfo instead of common's file functions
  src/yuzu/game_list.cpp
Labels: frontend

#1564 npad: Remove unused controller variable from OnInit()
  src/core/hle/service/hid/controllers/npad.cpp
Labels: style

#1571 graphic_breakpoints: Correct translation of strings in BreakpointModel's data() function
  src/yuzu/debugger/graphics/graphics_breakpoints.cpp
  src/yuzu/debugger/graphics/graphics_breakpoints_p.h
Labels: frontend-fix

#1565 time_stretch: Remove unused m_channel_count member variable
  src/audio_core/time_stretch.cpp
  src/audio_core/time_stretch.h
Labels: style

#1558 yuzu/configuration/config: Use a std::unique_ptr for qt_config instead of a raw pointer
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
Labels: style

#1570 profile_manager: Use std::optional instead of boost::optional
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
  src/core/hle/service/am/am.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/main.cpp
Labels: style

#1575 game_list_worker: Use QString's formatting instead of fmt in FormatPatchNameVersions()
  src/yuzu/game_list_worker.cpp
Labels: frontend

#1524 rasterizer: Fix Layered Textures Loading and Cubemaps
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/textures/decoders.cpp
Labels: canary-merge

#1577 kernel/error: Amend error return code values
  src/core/hle/ipc.h
  src/core/hle/kernel/errors.h
  src/core/hle/kernel/server_port.cpp
  src/core/hle/kernel/shared_memory.cpp
  src/core/hle/kernel/svc.cpp
Labels: hle-fix

#1583 ips_layer: Use rle_size instead of data_size in RLE patch application
  src/core/file_sys/ips_layer.cpp
Labels: core-fix

#1557 Implement the LoadNro functions from the ldr:ro service.
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
  src/core/hle/service/ldr/ldr.cpp
  src/core/loader/nro.cpp
  src/core/loader/nro.h
Labels: canary-merge, hle-new

#1587 configure_system: Minor cleanup-related changes
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
Labels: style

#1569 yuzu/main: Notify user of loading errors with Amiibo data
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nfp/nfp.h
  src/yuzu/main.cpp
Labels: frontend

#1430 vfs: Remove InterpretAsDirectory and related functions
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/partition_filesystem.cpp
  src/core/file_sys/partition_filesystem.h
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
  src/core/file_sys/vfs.h
  src/core/file_sys/vfs_layered.cpp
  src/core/file_sys/vfs_layered.h
  src/core/file_sys/vfs_real.cpp
  src/core/file_sys/vfs_real.h
  src/core/file_sys/vfs_vector.cpp
  src/core/file_sys/vfs_vector.h
  src/core/file_sys/xts_archive.cpp
  src/core/file_sys/xts_archive.h
Labels: core-fix

#1533 Implemented Shader Local Memory
  src/video_core/engines/shader_bytecode.h
  src/video_core/engines/shader_header.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1597 configure_system: Indicate when filesystem operations fail
  src/yuzu/configuration/configure_system.cpp
Labels: frontend

#1602 key_manager: Use isxdigit instead of isdigit when reading key file
  src/core/crypto/key_manager.cpp
Labels: core-fix

#1600 loader/nsp: Move secondary loader initialization to constructor
  src/core/loader/nsp.cpp
Labels: core-fix

#1593 svc: Implement svcGetInfo command 0xF0000002
  src/core/hle/kernel/process.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc.h
  src/core/hle/kernel/thread.h
Labels: hle-new

#1601 Improved Shader accuracy on Vertex and Geometry Shaders.
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#1580 Implemented Mipmaps
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/textures/decoders.h
Labels: canary-merge

#1611 core: Add missing const variants of getters for the System class
  src/core/core.cpp
  src/core/core.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/svc.cpp
Labels: style

#1621 hle_ipc: Make GetDomainMessageHeader return a regular pointer
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/server_session.cpp
Labels: style

#1624 general: Remove unused boost inclusions where applicable
  src/core/file_sys/fsmitm_romfsbuild.h
  src/core/hle/kernel/mutex.cpp
  src/yuzu/debugger/wait_tree.h
Labels: style
