Repository yuzu-emu/yuzu, pull requests merged in 2018-11, with the labels that each got.

#1626 service/usb: Update IPdSession's function table
  src/core/hle/service/usb/usb.cpp
Labels: hle

#1622 maxwell_3d: Restructure macro upload to use a single macro code memory.
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/macro_interpreter.cpp
  src/video_core/macro_interpreter.h
Labels: canary-merge, gpu-fix

#1623 Improve OpenGL state handling
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: canary-merge, gpu-fix

#1615 configure_system: Contrain profile usernames to 32 characters
  src/core/hle/service/acc/profile_manager.h
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/util/limitable_input_dialog.cpp
  src/yuzu/util/limitable_input_dialog.h
Labels: frontend-fix

#1625 Implement ASTC Textures 5x5 and fix a bunch of ASTC texture problems
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/textures/astc.cpp
  src/video_core/textures/astc.h
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
  src/yuzu/debugger/graphics/graphics_surface.cpp
Labels: canary-merge, gpu-fix, gpu-new

#1639 qt: Add help option to open yuzu folder
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: frontend-new

#1441 logging: Add DebuggerBackend for logging to Visual Studio
  src/common/logging/backend.cpp
  src/common/logging/backend.h
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: canary-merge

#1616 Implement Cube Arrays
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/surface.cpp
  src/video_core/surface.h
Labels: canary-merge, gpu-new

#1635 Implement multi-target viewports and blending
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: canary-merge, gpu-new

#1630 memory_manager: Do not MapBufferEx over already in use memory.
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: canary-merge, gpu-fix

#1646 svcBreak now dumps information from the debug buffer passed
  src/core/hle/kernel/svc.cpp
Labels: hle

#1661 rasterizer_cache: Add missing virtual destructor to RasterizerCacheObject
  src/video_core/CMakeLists.txt
  src/video_core/rasterizer_cache.cpp
  src/video_core/rasterizer_cache.h
Labels: style

#1654 gl_rasterizer: Skip VAO binding if the state is clean.
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: canary-merge, gpu-fix

#1648 Implement 3 coordinate array in TEXS instruction
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1660 Map more missing opengl states
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/textures/texture.h
Labels: gpu-new

#1670 csrng: Add config option to set RNG seed
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/spl/module.cpp
  src/core/hle/service/spl/module.h
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: hle-new

#1628 Implement SurfaceTarget Texture2DArray
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: canary-merge, gpu-new

#1608 [ns|fsp_srv]: Implement various functions to boot Checkpoint
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
  src/core/hle/service/ns/ns.cpp
  src/core/loader/nro.cpp
Labels: core-new

#1683 audio_core/audio_renderer: Fix typo in AuxInfo member name
  src/audio_core/audio_renderer.h
Labels: style

#1682 hle/audren_u: Implement Get/SetRenderingTimeLimit
  src/core/hle/service/audio/audren_u.cpp
Labels: hle-new

#1680 kernel/process: Migrate heap-related memory management out of the process class and into the vm manager
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
Labels: hle-fix, hle-new, style

#1686 qt: Move Open yuzu Folder action from Help to File
  src/yuzu/main.ui
Labels: canary-merge, frontend

#1662 gl_rasterizer_cache: CopySurface optimization
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: canary-merge, gpu-fix

#1679 svc: Use proper random entropy generation algorithm
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
  src/core/settings.h
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.ui
Labels: hle-fix

#1684 common/string_util: Minor cleanup
  src/common/string_util.cpp
  src/common/string_util.h
Labels: style

#1688 service: Mark MakeFunctionString with the [[maybe_unused]] attribute.
  src/core/hle/service/service.cpp
Labels: style

#1689 hid/npad: Add missing break in switch statement within Controller_NPad::OnUpdate
  src/core/hle/service/hid/controllers/npad.cpp
Labels: hle-fix

#1690 nfp: Correct erroneous sizeof expression within GetTagInfo()
  src/core/hle/service/nfp/nfp.cpp
Labels: hle-fix

#1695 yuzu/configure_system: Mark the entropy mask string as nontranslatable
  src/yuzu/configuration/configure_system.ui
Labels: style

#1696 service/acc: Correct error case within TrySelectUserWithoutInteraction()
  src/core/hle/service/acc/acc.cpp
Labels: hle-fix

#1697 acc/profile_manager: Minor cleanup-related changes
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
Labels: style

#1637 Improved GPU Caches lookup Speed
  src/video_core/rasterizer_cache.h
Labels: canary-merge, gpu-fix

#1691 service/audren_u: Forward RequestUpdateAuto through the same function as RequestUpdate
  src/core/hle/service/audio/audren_u.cpp
Labels: hle-new

#1618 patch_manager: Add support for dumping uncompressed NSOs
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/bis_factory.h
  src/core/file_sys/patch_manager.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/loader/nso.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: core-new

#1687 kernel/thread: Deduplicate scheduler switching code
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: style

#1699 csrng: Use random integer distribution instead of raw engine
  src/core/hle/service/spl/module.cpp
Labels: canary-merge, hle-fix

#1706 file_sys/errors: Clean up error code values
  src/core/file_sys/errors.h
  src/core/hle/result.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: style

#1676 gl_state: Amend compilation warnings
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: style

#1632 game_list: Optimize game list refresh
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_gamelist.cpp
  src/yuzu/configuration/configure_gamelist.ui
  src/yuzu/game_list.cpp
  src/yuzu/game_list_worker.cpp
  src/yuzu/ui_settings.h
Labels: frontend-fix

#1714 kernel/errors: Clean up error codes
  src/core/hle/kernel/errors.h
  src/core/hle/kernel/svc.cpp
Labels: style

#1719 hwopus: DecodeInterleavedWithPerformance: Fix ordering of output parameters.
  src/core/hle/service/audio/hwopus.cpp
Labels: audio-fix, canary-merge

#1711 Added various bluetooth based cmds for palma
  src/core/hle/service/btdrv/btdrv.cpp
  src/core/hle/service/btm/btm.cpp
Labels: canary-merge, hle-new

#1671 vi: Implement TransactParcel for Disconnect and DetachBuffer
  src/core/hle/service/vi/vi.cpp
Labels: canary-merge, hle-new

#1730 gl_rasterizer: Remove default clip distance
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: gpu-fix

#1702 Tegra::Texture::UnswizzleTexture: Eliminated unnessessary memory allocation and copy
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
Labels: canary-merge, gpu-fix

#1619 Handle missing git info when building
  externals/cmake-modules/GetGitRevisionDescription.cmake.in
Labels: build-system

#1555 travis: Use pre-built image for clang-format target
  .travis/clang-format/build.sh
  .travis/clang-format/deps.sh
  .travis/clang-format/docker.sh
Labels: build-system

#1693 Missing ogl states
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/textures/texture.h
Labels: canary-merge, gpu-new

#1717 textures/decoders: Replace magic numbers
  src/video_core/textures/decoders.cpp
Labels: gpu

#1634 hid: Add support for multiplayer and multilayout controllers
  src/core/frontend/input.h
  src/core/hle/service/hid/controllers/debug_pad.cpp
  src/core/hle/service/hid/controllers/debug_pad.h
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/keyboard.h
  src/core/hle/service/hid/controllers/mouse.cpp
  src/core/hle/service/hid/controllers/mouse.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
  src/core/hle/service/hid/hid.cpp
  src/core/settings.cpp
  src/core/settings.h
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.h
  src/yuzu/configuration/configure_general.ui
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input.h
  src/yuzu/configuration/configure_input.ui
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_input_player.ui
  src/yuzu/configuration/configure_mouse_advanced.cpp
  src/yuzu/configuration/configure_mouse_advanced.h
  src/yuzu/configuration/configure_mouse_advanced.ui
  src/yuzu/configuration/configure_touchscreen_advanced.cpp
  src/yuzu/configuration/configure_touchscreen_advanced.h
  src/yuzu/configuration/configure_touchscreen_advanced.ui
  src/yuzu_cmd/config.cpp
Labels: frontend-new, hle-new

#1738 kernel/resource_limit: Clean up interface
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/resource_limit.cpp
  src/core/hle/kernel/resource_limit.h
  src/core/hle/kernel/svc.cpp
Labels: hle, style

#1739 lm: Implement SetDestination by doing nothing
  src/core/hle/service/lm/lm.cpp
Labels: hle-new

#1749 file_sys/card_image: Provide named members for the GamecardInfo struct
  src/core/file_sys/card_image.h
Labels: style

#1746 kernel/process: Move <random> include to the cpp file
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
Labels: style

#1733 ldr: Clean up error codes
  src/core/hle/service/ldr/ldr.cpp
Labels: style

#1734 kernel/shared_memory: Make data members private, plus minor interface changes
  src/core/hle/kernel/shared_memory.cpp
  src/core/hle/kernel/shared_memory.h
  src/core/hle/kernel/svc.cpp
Labels: style

#1751 maxwell_3d: Initialize rasterizer color mask registers as enabled.
  src/video_core/engines/maxwell_3d.cpp
Labels: canary-merge, gpu-fix

#1758 common/math_util: Minor cleanup
  src/common/math_util.h
Labels: style

#1742 am/applets: Minor cleanup
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/am/applets/software_keyboard.cpp
  src/core/hle/service/am/applets/software_keyboard.h
Labels: style

#1753 Use default values for unknown framebuffer pixel format
  src/video_core/gpu.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: canary-merge, gpu-new

#1771 common: Remove bit_set.h
  src/common/CMakeLists.txt
  src/common/bit_set.h
Labels: style

#1737 Implemented Fast Layered Copy
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-new

#1764 macro_interpreter: Implement AddWithCarry and SubtractWithBorrow.
  src/video_core/macro_interpreter.cpp
  src/video_core/macro_interpreter.h
Labels: canary-merge, gpu-new

#1765 audout_u: Add support for multiple IAudioOut streams.
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audout_u.h
Labels: audio-fix, canary-merge

#1775 maxwell_3d: Implement alternate blend equations.
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: canary-merge, gpu-new

#1779 debug_pad: Avoid loading input for nonexistent buttons (Home and Screenshot)
  src/core/hle/service/hid/controllers/debug_pad.cpp
Labels: hle-fix

#1762 nvhost_ctrl_gpu: Implement IoctlGetGpuTime.
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
Labels: canary-merge, hle-new

#1766 Properly Implemented TXQ Instruction
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#1756 gl_shader_decompiler: Fix register overwriting on texture calls
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: gpu-fix

#1736 Added predicate comparison LessEqualWithNan
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1773 common/thread: Minor cleanup
  src/common/thread.cpp
  src/common/thread.h
Labels: style

#1777 core: Relocate CPU core management to its own class
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/cpu_core_manager.cpp
  src/core/cpu_core_manager.h
Labels: style

#1770 applets: Add StubApplet and use it as fallback when AppletId is not implemented
  src/core/CMakeLists.txt
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/stub_applet.cpp
  src/core/hle/service/am/applets/stub_applet.h
Labels: canary-merge, hle

#1741 software_keyboard: Minor changes
  src/yuzu/applets/software_keyboard.cpp
  src/yuzu/applets/software_keyboard.h
Labels: bug, style

#1744 shader_cache: Only lock covered instructions.
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
Labels: canary-merge, gpu-fix

#1769 gl_shader_decompiler: Rename cc to condition code and name internal flags
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: gpu-fix

#1747 patch_manager: Add support for applying LayeredFS patches to ExeFS
  src/core/file_sys/patch_manager.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: core-new

#1708 Report resolution scaling support for vi and am
  src/core/hle/service/am/am.cpp
  src/core/hle/service/vi/vi.cpp
  src/yuzu/configuration/configure_graphics.ui
Labels: frontend-new, hle

#1785 Add support for clear_flags register
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: canary-merge, gpu-new

#1725 Update OpenGL's backend version from 3.3 to 4.3
  externals/glad/include/glad/glad.h
  externals/glad/src/glad.c
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: canary-merge, gpu

#1731 filesystem: Clear registered union paths on factory creation
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
Labels: frontend-fix

#1641 sm: Implement RegisterService and UnregisterService
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
Labels: hle-new

#1787 memory_manager: Do not allow 0 to be a valid GPUVAddr.
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: canary-merge, gpu-fix

#1791 nvdrv: Implement/stub DumpGraphicsMemoryInfo and GetStatus.
  src/core/hle/service/nvdrv/interface.cpp
  src/core/hle/service/nvdrv/interface.h
Labels: canary-merge, hle-new

#1783 gl_shader_decompiler: Implement clip distances
  src/video_core/engines/shader_bytecode.h
  src/video_core/engines/shader_header.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1782 Fixed Coordinate Encodings in TEX and TEXS instructions
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#1760 gl_shader_decompiler: Implement R2P_IMM
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1793 service/sm: Take std::string by const reference in UnregisterService
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
Labels: style

#1763 gl_shader_decompiler: Implement BFI_IMM_R
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1784 GPU States: Implement Polygon Offset. This is used in SMO all the time.
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: gpu-new

#1723 gl_rasterizer: Skip VB upload if the state is clean.
  src/video_core/command_processor.cpp
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: gpu-fix

#1805 svc: Implement svcCreateResourceLimit, svcGetResourceLimitCurrentValue(), svcGetResourceLimitLimitValue(), and svcSetResourceLimitLimitValue()
  src/core/hle/kernel/resource_limit.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
Labels: hle-new

#1804 gdbstub: Silence value truncation warning within FpuWrite()
  src/core/gdbstub/gdbstub.cpp
Labels: style

#1812 control_metadata: Correct typo in language name (Portugese -> Portuguese)
  src/core/file_sys/control_metadata.cpp
Labels: bug

#1802 profile_manager: Save and load ProfileData from disk
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
Labels: hle-fix

#1811 yuzu/input: Minor changes
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input.h
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_mouse_advanced.cpp
  src/yuzu/configuration/configure_mouse_advanced.h
Labels: style

#1814 file_sys/registered_cache: Use regular const references instead of std::shared_ptr for InstallEntry()
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/yuzu/main.cpp
Labels: style

#1735 Texture decoder: Implemented Tile Width Spacing
  src/video_core/engines/fermi_2d.cpp
  src/video_core/morton.cpp
  src/video_core/morton.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
  src/video_core/textures/texture.h
Labels: gpu-fix

#1792 gpu: Rewrite GPU command list processing with DmaPusher class.
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/video_core/CMakeLists.txt
  src/video_core/command_processor.h
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_compute.cpp
  src/video_core/engines/maxwell_compute.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/macro_interpreter.cpp
Labels: canary-merge, gpu-fix, gpu-new

#1817 npad: Use NPadIdToIndex to prevent invalid array access
  src/core/hle/service/hid/controllers/npad.cpp
Labels: hle-fix

#1786 Add Depth Clamp Support
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: canary-merge, gpu-new

#1808 Fix clip distance and viewport
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: canary-merge, gpu-fix

#1768 Uncheck automatically joycons docked when docked mode is enable
  src/yuzu/configuration/configure_input.cpp
Labels: frontend-fix

#1829 service/set: Implement MakeLanguageCode
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set.h
Labels: hle-new
