Repository yuzu-emu/yuzu, pull requests merged in 2018-09, with the labels that each got.

#1212 core/core: Replace includes with forward declarations where applicable
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/core.cpp
  src/core/core.h
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/elf.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
  src/core/perf_stats.cpp
  src/core/perf_stats.h
  src/core/telemetry_session.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/yuzu/debugger/wait_tree.cpp
  src/yuzu/debugger/wait_tree.h
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/game_list_p.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu_cmd/yuzu.cpp
Labels: style

#1228 filesystem: Move dir retrieval after path checking in DeleteFile()
  src/core/hle/service/filesystem/filesystem.cpp
Labels: style

#1213 filesystem/maxwell_3d: Various changes to boot Project Octopath Traveller
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
  src/video_core/engines/maxwell_3d.cpp
Labels: canary-merge

#1230 ssl: Move SSL class to cpp file
  src/core/hle/service/ssl/ssl.cpp
  src/core/hle/service/ssl/ssl.h
Labels: style

#1235 file_sys: Replace includes with forward declarations where applicable
  src/core/crypto/key_manager.cpp
  src/core/crypto/key_manager.h
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/bis_factory.h
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/control_metadata.h
  src/core/file_sys/nca_metadata.cpp
  src/core/file_sys/nca_metadata.h
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/romfs.h
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/core/hle/service/ns/pl_u.cpp
  src/yuzu/game_list.cpp
  src/yuzu/main.cpp
Labels: style

#1232 gl_shader_decompiler: Use used_shaders member variable directly within GenerateDeclarations()
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: style

#1237 Optimizations
  src/core/core.cpp
  src/core/core.h
  src/video_core/command_processor.cpp
  src/video_core/gpu.h
Labels: canary-merge

#1238 common/logging: Minor changes
  src/common/logging/filter.h
  src/common/logging/log.h
  src/common/logging/text_formatter.h
Labels: style

#1178 file_sys: Add Nintendo Submissions Package (NSP) file format
  src/core/CMakeLists.txt
  src/core/crypto/key_manager.cpp
  src/core/crypto/key_manager.h
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/yuzu/game_list.cpp
  src/yuzu/main.cpp
Labels: core-new

#1217 renderer_opengl: Implement a buffer cache.
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: canary-merge, gpu-new

#1179 file_sys: Add support for BKTR format (Game Updates)
  src/core/CMakeLists.txt
  src/core/crypto/aes_util.cpp
  src/core/crypto/ctr_encryption_layer.cpp
  src/core/file_sys/card_image.cpp
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/nca_patch.cpp
  src/core/file_sys/nca_patch.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/romfs_factory.h
  src/core/file_sys/submission_package.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/deconstructed_rom_directory.h
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nca.cpp
  src/core/loader/nca.h
  src/core/loader/nro.cpp
  src/core/loader/nro.h
  src/core/loader/nsp.cpp
  src/core/loader/xci.cpp
  src/core/telemetry_session.cpp
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/game_list_p.h
  src/yuzu/main.cpp
Labels: core-new

#1242 file_sys/submission_package: Replace includes with forward declarations where applicable
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
Labels: style

#1243 gl_rasterizer: Implement a VAO cache.
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: canary-merge, gpu-fix

#1257 core: Migrate current_process pointer to the kernel
  src/core/core.cpp
  src/core/core.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
Labels: core-fix, style

#1259 yuzu: Move GameListWorker to its own source files
  src/yuzu/CMakeLists.txt
  src/yuzu/game_list.cpp
  src/yuzu/game_list_p.h
  src/yuzu/game_list_worker.cpp
  src/yuzu/game_list_worker.h
Labels: style

#1246 gl_rasterizer: Use baseInstance instead of moving the buffer points.
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: canary-merge, gpu-fix

#1256 Initial support for non-2D textures
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/textures/texture.h
Labels: canary-merge, gpu-fix, gpu-new

#1261 shader_decompiler: Implemented (Partialy) TXQ
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1272 GPU/DMA: Partially implemented the 'enable_2d' bit in the DMA engine.
  src/video_core/engines/maxwell_dma.cpp
Labels: gpu-new

#1268 shader_decompiler: Implemented TMML
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge

#1283 service: Remove unused g_kernel_named_ports variable
  src/core/hle/service/service.cpp
Labels: style

#1282 yuzu: Move compatibility list specifics to their own source files
  src/yuzu/CMakeLists.txt
  src/yuzu/compatibility_list.cpp
  src/yuzu/compatibility_list.h
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/game_list_p.h
  src/yuzu/game_list_worker.cpp
  src/yuzu/game_list_worker.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: style

#1281 gl_rasterizer: Implement multiple color attachments.
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-new

#1264 video_core: Optimize the command processor.
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.h
  src/video_core/command_processor.cpp
  src/video_core/command_processor.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/gpu.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: canary-merge, gpu-new

#1284 gl_rasterizer_cache: Implement RenderTargetFormat::BGRA8_SRGB.
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-new

#1285 gl_rasterizer_cache: Only use depth for applicable texture formats.
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: canary-merge, gpu-fix

#1286 gl_rasterizer: Implement clear for non-zero render targets.
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: canary-merge, gpu-new

#1275 Port #4141 from citra: Joystick hotplug support
  src/input_common/main.cpp
  src/input_common/main.h
  src/input_common/sdl/sdl.cpp
  src/input_common/sdl/sdl.h
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/configure_input.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: canary-merge

#1269 Use open-source shared fonts if no dumped file is available
  externals/CMakeLists.txt
  externals/open_source_archives/CMakeLists.txt
  externals/open_source_archives/Readme.md
  externals/open_source_archives/include/FontChineseSimplified.ttf.h
  externals/open_source_archives/include/FontChineseTraditional.ttf.h
  externals/open_source_archives/include/FontExtendedChineseSimplified.ttf.h
  externals/open_source_archives/include/FontKorean.ttf.h
  externals/open_source_archives/include/FontNintendoExtended.ttf.h
  externals/open_source_archives/include/FontStandard.ttf.h
  src/core/CMakeLists.txt
  src/core/hle/service/ns/pl_u.cpp
Labels: canary-merge

#1293 externals: Place font data within cpp files
  externals/open_source_archives/CMakeLists.txt
  externals/open_source_archives/include/FontChineseSimplified.h
  externals/open_source_archives/include/FontChineseSimplified.ttf.h
  externals/open_source_archives/include/FontChineseTraditional.h
  externals/open_source_archives/include/FontChineseTraditional.ttf.h
  externals/open_source_archives/include/FontExtendedChineseSimplified.h
  externals/open_source_archives/include/FontExtendedChineseSimplified.ttf.h
  externals/open_source_archives/include/FontKorean.h
  externals/open_source_archives/include/FontKorean.ttf.h
  externals/open_source_archives/include/FontNintendoExtended.h
  externals/open_source_archives/include/FontNintendoExtended.ttf.h
  externals/open_source_archives/include/FontStandard.h
  externals/open_source_archives/include/FontStandard.ttf.h
  externals/open_source_archives/src/FontChineseSimplified.cpp
  externals/open_source_archives/src/FontChineseTraditional.cpp
  externals/open_source_archives/src/FontExtendedChineseSimplified.cpp
  externals/open_source_archives/src/FontKorean.cpp
  externals/open_source_archives/src/FontNintendoExtended.cpp
  externals/open_source_archives/src/FontStandard.cpp
  src/core/hle/service/ns/pl_u.cpp
Labels: externals

#1295 gl_rasterizer_cache: Improve accuracy of caching and copies.
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-fix

#1300 service/audio: Replace includes with forward declarations where applicable
  src/core/hle/service/audio/audio.cpp
  src/core/hle/service/audio/audio.h
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audout_u.h
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/audren_u.h
  src/core/hle/service/audio/hwopus.cpp
Labels: style

#1301 game_list: Resolve variable shadowing within LoadCompatibilityList()
  src/yuzu/game_list.cpp
Labels: style

#1296 service/prepo: Move class into the cpp file
  src/core/hle/service/prepo/prepo.cpp
  src/core/hle/service/prepo/prepo.h
Labels: style

#1304 svc: Do nothing in svcOutputDebugString() if given a length of zero
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
Labels: hle-fix, performance, style

#1303 kernel/errors: Amend invalid thread priority and invalid processor ID error codes
  src/core/hle/kernel/errors.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
Labels: hle-fix

#1263 shader_decompiler: Implemented (Partially) Texture Processing Modes
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1297 pl_u: Eliminate mutable file-scope state
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/ns/pl_u.h
Labels: style

#1287 Use ARB_multi_bind for uniform buffers
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: gpu-fix

#1307 services/pl_u: Add missing Korean font to the fallback case for shared fonts
  src/core/hle/service/ns/pl_u.cpp
Labels: hle-fix

#1309 service: Use nested namespace specifiers where applicable
  src/core/hle/service/acc/acc_su.h
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
Labels: style

#1310 kernel/thread: Include thread-related enums within the kernel namespace
  src/core/hle/kernel/thread.h
  src/core/hle/service/vi/vi.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: style

#1271 GPU: Basic implementation of the Kepler Inline Memory engine (p2mf).
  src/video_core/CMakeLists.txt
  src/video_core/command_processor.cpp
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: gpu-new

#1273 Shaders: Implemented multiple-word loads and stores to and from attribute memory.
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: gpu-fix

#1335 game_list_p: Take map iterator contents by const reference
  src/yuzu/game_list_p.h
Labels: style

#1320 cubeb_sink: Correct context name in ListCubebSinkDevices()
  src/audio_core/cubeb_sink.cpp
Labels: style

#1315 kernel/svc: Handle a few error cases within memory-related functions
  src/core/hle/kernel/errors.h
  src/core/hle/kernel/svc.cpp
Labels: hle-fix

#1321 cubeb_sink: Get rid of variable shadowing within CubebSink's constructor
  src/audio_core/cubeb_sink.cpp
Labels: style

#1318 services/sm: Amend error code constants
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
Labels: hle-fix

#1316 gl_shader_decompiler: Get rid of variable shadowing within LEA instructions
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: style

#1314 audio_core/time_stretch: Silence truncation warnings in Process()
  src/audio_core/time_stretch.cpp
Labels: style

#1313 kernel/errors: Amend error code for ERR_NOT_FOUND
  src/core/hle/kernel/errors.h
Labels: hle-fix

#1312 service/vi: Replace includes with forward declarations where applicable
  src/core/hle/service/service.cpp
  src/core/hle/service/vi/vi.cpp
  src/core/hle/service/vi/vi.h
Labels: style

#1311 Optimized Texture Swizzling
  src/video_core/textures/decoders.cpp
Labels: canary-merge, gpu-fix

#1279 shader_decompiler: Implemented (Partialy) Control Codes and CSETP
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge

#1342 gl_shader_decompiler: Avoid truncation warnings within LD_A and ST_A code
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: style

#1346 svc_wrap: Convert the PARAM macro into a function
  src/core/hle/kernel/svc_wrap.h
Labels: style

#1341 core/core_cpu: Replace exclusive monitor include with forward declaration
  src/core/core_cpu.cpp
  src/core/core_cpu.h
Labels: style

#1319 audio_core: Replace includes with forward declarations where applicable.
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/audio_core/stream.cpp
  src/audio_core/stream.h
  src/audio_core/time_stretch.h
Labels: style

#1361 xts_archive/nax: Minor interface changes
  src/core/file_sys/xts_archive.cpp
  src/core/file_sys/xts_archive.h
  src/core/loader/nax.cpp
  src/core/loader/nax.h
Labels: performance, style

#1363 control_metadata: Move language name array definition to the cpp file
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
Labels: style

#1358 savedata_factory: Add TemporaryStorage SaveDataType
  src/core/file_sys/savedata_factory.cpp
Labels: core-fix

#1352 ring_buffer: Use std::hardware_destructive_interference_size to determine alignment size for avoiding false sharing
  src/common/ring_buffer.h
Labels: performance, style

#1367 game_list: Handle plurals within setFilterResult() better
  src/yuzu/game_list.cpp
Labels: frontend-fix

#1364 file-sys: Default heavy-weight class destructors in the cpp file
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/file_sys/nca_metadata.cpp
  src/core/file_sys/nca_metadata.h
  src/core/file_sys/partition_filesystem.cpp
  src/core/file_sys/partition_filesystem.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/romfs_factory.h
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/core/file_sys/submission_package.h
  src/core/file_sys/vfs_concat.cpp
  src/core/file_sys/vfs_concat.h
  src/core/file_sys/vfs_offset.cpp
  src/core/file_sys/vfs_offset.h
  src/core/file_sys/vfs_vector.cpp
  src/core/file_sys/vfs_vector.h
  src/core/file_sys/xts_archive.cpp
  src/core/file_sys/xts_archive.h
Labels: style

#1371 arm_interface: Replace kernel vm_manager include with a forward declaration
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/hle/kernel/mutex.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: style

#1372 kernel/thread: Use owner_process when setting the page table in SetupMainThread()
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: style

#1337 yuzu-cmd: Add filesystem service initializer call
  src/yuzu_cmd/yuzu.cpp
Labels: frontend-fix

#1379 gl_stream_buffer: Fix use of bitwise OR instead of logical OR in Map()
  src/video_core/renderer_opengl/gl_stream_buffer.cpp
Labels: bug

#1382 gl_state: Remove unused type alias
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: style

#1380 shader_bytecode: Make operator== and operator!= of IpaMode const qualified
  src/video_core/engines/shader_bytecode.h
Labels: style

#1378 process: Make a few member variables private where applicable
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: style

#1347 Implemented fatal:u properly
  src/core/hle/service/fatal/fatal.cpp
  src/core/hle/service/fatal/fatal.h
  src/core/hle/service/fatal/fatal_u.cpp
Labels: hle-fix, hle-new

#1365 file_sys: Add support for LayeredFS mods
  src/common/common_paths.h
  src/common/file_util.cpp
  src/common/file_util.h
  src/core/CMakeLists.txt
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/bis_factory.h
  src/core/file_sys/fsmitm_romfsbuild.cpp
  src/core/file_sys/fsmitm_romfsbuild.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/romfs.cpp
  src/core/file_sys/romfs.h
  src/core/file_sys/vfs.cpp
  src/core/file_sys/vfs.h
  src/core/file_sys/vfs_concat.cpp
  src/core/file_sys/vfs_concat.h
  src/core/file_sys/vfs_layered.cpp
  src/core/file_sys/vfs_layered.h
  src/core/file_sys/vfs_real.cpp
  src/core/file_sys/vfs_real.h
  src/core/file_sys/vfs_static.h
  src/core/file_sys/vfs_vector.cpp
  src/core/file_sys/vfs_vector.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: canary-merge, core-new

#1398 travis: Make macOS builds utilize Xcode 10
  .travis.yml
Labels: build-system

#1401 vfs: Minor cleanup related changes to layered VFS code
  src/core/core.cpp
  src/core/file_sys/fsmitm_romfsbuild.cpp
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/romfs.cpp
  src/core/file_sys/vfs.cpp
  src/core/file_sys/vfs.h
  src/core/file_sys/vfs_concat.cpp
  src/core/file_sys/vfs_concat.h
  src/core/file_sys/vfs_layered.cpp
  src/core/file_sys/vfs_layered.h
  src/core/file_sys/vfs_static.h
  src/core/file_sys/vfs_vector.cpp
  src/core/file_sys/vfs_vector.h
  src/yuzu/main.cpp
Labels: style

#1400 service: Add missing headers inclusions where applicable
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/fatal/fatal.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/sm/controller.cpp
Labels: style

#1399 kernel/scheduler: Take ARM_Interface instances by reference
  src/core/core_cpu.cpp
  src/core/core_cpu.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
Labels: style

#1404 fsmitm_romfsbuild: Minor changes
  src/core/file_sys/fsmitm_romfsbuild.cpp
Labels: style

#1377 Improved Fast Swizzle and Legacy Swizzle
  src/video_core/textures/decoders.cpp
Labels: canary-merge

#1395 process/vm_manager: Initial modifications to load NPDM metadata
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
  src/core/gdbstub/gdbstub.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/shared_memory.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/elf.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
  src/core/memory.cpp
  src/core/memory.h
  src/tests/core/arm/arm_test_common.cpp
Labels: hle-fix, hle-new

#1412 kernel/object: Remove unnecessary std::move from DynamicObjectCast()
  src/core/hle/kernel/object.h
  src/core/hle/kernel/wait_object.h
Labels: style

#1414 loader: Make the Load() function take a process as a regular reference, not a SharedPtr
  src/core/core.cpp
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/deconstructed_rom_directory.h
  src/core/loader/elf.cpp
  src/core/loader/elf.h
  src/core/loader/loader.h
  src/core/loader/nax.cpp
  src/core/loader/nax.h
  src/core/loader/nca.cpp
  src/core/loader/nca.h
  src/core/loader/nro.cpp
  src/core/loader/nro.h
  src/core/loader/nso.cpp
  src/core/loader/nso.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
Labels: style

#1417 svc: Implement svcGetThreadContext
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/savedata_factory.cpp
  src/core/gdbstub/gdbstub.cpp
  src/core/hle/kernel/errors.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/shared_memory.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/service/fatal/fatal.cpp
  src/core/hle/service/ns/pl_u.cpp
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/elf.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
  src/core/memory.cpp
  src/tests/core/arm/arm_test_common.cpp
  src/yuzu/main.cpp
Labels: hle-fix, hle-new
