Repository yuzu-emu/yuzu, pull requests merged in 2018-08, with the labels that each got.

#871 audio_core: Add configuration settings.
  src/audio_core/audio_out.cpp
  src/audio_core/stream.cpp
  src/core/settings.h
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure.ui
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_audio.h
  src/yuzu/configuration/configure_audio.ui
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: canary-merge

#851 Added ability to change username & language code in the settings ui. Added IProfile::Get and SET::GetLanguageCode for libnx tests
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set.h
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.ui
  src/yuzu_cmd/default_ini.h
Labels: canary-merge

#927 gl_shader_decompiler: Fix TEXS mask and dest.
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge

#925 Implement audren audio output
  src/audio_core/CMakeLists.txt
  src/audio_core/audio_out.cpp
  src/audio_core/audio_out.h
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/audio_core/buffer.h
  src/audio_core/codec.cpp
  src/audio_core/codec.h
  src/audio_core/cubeb_sink.cpp
  src/audio_core/cubeb_sink.h
  src/audio_core/null_sink.h
  src/audio_core/sink.h
  src/audio_core/sink_stream.h
  src/audio_core/stream.cpp
  src/audio_core/stream.h
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audout_u.h
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/audren_u.h
Labels: canary-merge, hle-new, unimplemented

#930 address_arbiter: Return by value from GetThreadsWaitingOnAddress()
  src/core/hle/kernel/address_arbiter.cpp
Labels: style

#929 gdbstub: Minor changes
  src/core/gdbstub/gdbstub.cpp
  src/core/gdbstub/gdbstub.h
Labels: style

#932 core_timing: Use transparent functors where applicable
  src/core/core_timing.cpp
  src/core/core_timing.h
Labels: style

#933 memory: Correct prototype of ZeroBlock
  src/core/memory.h
Labels: bug, style

#945 qt/main: Better file-existence checking within OnMenuRecentFile() and UpdateUITheme()
  src/yuzu/main.cpp
Labels: frontend-fix

#934 core_timing: Make GetGlobalTimeUs() return std::chrono::microseconds
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/perf_stats.cpp
  src/core/perf_stats.h
Labels: style

#936 gl_rasterizer_cache: Avoid superfluous surface copies.
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-fix

#940 kernel/event: Make data members private
  src/core/hle/kernel/event.h
  src/yuzu/debugger/wait_tree.cpp
Labels: style

#942 qt: Minor cleanup-related changes
  src/yuzu/about_dialog.cpp
  src/yuzu/about_dialog.h
  src/yuzu/bootmanager.h
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/debugger/graphics/graphics_surface.cpp
  src/yuzu/debugger/graphics/graphics_surface.h
  src/yuzu/debugger/wait_tree.cpp
  src/yuzu/debugger/wait_tree.h
  src/yuzu/game_list_p.h
  src/yuzu/main.h
Labels: style

#944 qt: Don't show error dialog when canceling the Load Folder dialog
  src/yuzu/main.cpp
Labels: frontend-fix

#946 qt/main: Collapse if statement in UpdateRecentFiles()
  src/yuzu/main.cpp
Labels: style

#943 game_list: Join declarations and assignments in onTextChanged()
  src/yuzu/game_list.cpp
Labels: style

#941 GDBStub works with both Unicorn and Dynarmic now
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/core.cpp
  src/core/core.h
  src/core/gdbstub/gdbstub.cpp
  src/yuzu/configuration/configure_debug.ui
Labels: core-fix

#947 game_list: Use QString::fromStdString() where applicable instead of c_str()
  src/yuzu/game_list.cpp
Labels: frontend-fix, style

#931 loader: Make AppLoader_NCA rely on directory loading code
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/deconstructed_rom_directory.h
  src/core/loader/nca.cpp
  src/core/loader/nca.h
Labels: core-fix

#961 loader: Fix scope error in DeconstructedRomDirectory
  src/core/loader/deconstructed_rom_directory.cpp
Labels: core-fix, regression

#951 externals: Update glad to 0.1.26
  externals/glad/include/glad/glad.h
  externals/glad/src/glad.c
Labels: externals

#949 client_port: Make all data members private
  src/core/hle/kernel/client_port.cpp
  src/core/hle/kernel/client_port.h
  src/core/hle/kernel/server_session.cpp
Labels: style

#952 service: Add usb services
  src/common/logging/backend.cpp
  src/common/logging/log.h
  src/core/CMakeLists.txt
  src/core/hle/service/service.cpp
  src/core/hle/service/usb/usb.cpp
  src/core/hle/service/usb/usb.h
Labels: hle-new

#959 Make building cubeb optional
  src/audio_core/CMakeLists.txt
Labels: build-system

#953 service/time: Amend command IDs of ToPosixTime() and ToPosixTimeWithMyRule()
  src/core/hle/service/time/time.cpp
Labels: hle-fix

#955 nvflinger: Use std::string_view in OpenDisplay()
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
Labels: style

#950 qt/hotkey: Get rid of global hotkey map instance
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_dialog.h
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.h
  src/yuzu/hotkeys.cpp
  src/yuzu/hotkeys.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: style

#960 service/apm: Add the apm:sys service
  src/core/hle/service/apm/apm.cpp
  src/core/hle/service/apm/interface.cpp
  src/core/hle/service/apm/interface.h
Labels: core-new

#954 services/hid: Add ActivateNpadWithRevision() to the hid function info array
  src/core/hle/service/hid/hid.cpp
Labels: hle-new

#957 nvflinger: Correct typo in name of composition event
  src/core/hle/service/nvflinger/nvflinger.cpp
Labels: hle-fix

#920 content_archive: Add support for titlekey cryptography
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
Labels: canary-merge, core-new

#963 Fixed the sRGB pixel format
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: gpu-fix

#964 Lowered down the logging for command processor methods
  src/video_core/command_processor.cpp
Labels: gpu-fix

#967 file_util: Avoid sign-conversions in WriteArray() and ReadArray()
  src/common/file_util.h
Labels: style

#973 acc: Stub GetUserCount.
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/acc_u0.cpp
Labels: hle-new

#965 hle: Remove unused romfs.cpp/.h
  src/core/CMakeLists.txt
  src/core/hle/romfs.cpp
  src/core/hle/romfs.h
Labels: style

#958 nvdrv: Get rid of global std::weak_ptr
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/core/hle/service/nvdrv/nvdrv.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/service.cpp
Labels: style

#969 externals/CMakeLists: Add EXCLUDE_FROM_ALL to lz4's add_subdirectory() command
  externals/CMakeLists.txt
Labels: externals

#850 Add Icons and Metadata Support
  CMakeModules/CopyYuzuQt5Deps.cmake
  appveyor.yml
  src/core/file_sys/card_image.cpp
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/control_metadata.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/deconstructed_rom_directory.h
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nca.cpp
  src/core/loader/nca.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure.ui
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_gamelist.cpp
  src/yuzu/configuration/configure_gamelist.h
  src/yuzu/configuration/configure_gamelist.ui
  src/yuzu/game_list.cpp
  src/yuzu/game_list_p.h
  src/yuzu/main.cpp
  src/yuzu/ui_settings.h
Labels: canary-merge, frontend-new

#966 common: Convert type traits templates over to variable template versions where applicable
  src/common/alignment.h
  src/common/bit_set.h
  src/common/file_util.h
  src/common/hash.h
  src/common/x64/xbyak_util.h
Labels: style

#980 renderer_opengl: Use trace log in a few places.
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: gpu-fix

#975 am: Stub SetScreenShotImageOrientation.
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: canary-merge, hle-new

#979 maxwell_to_gl: Implement VertexAttribute::Size::Size_8_8.
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: canary-merge, gpu-new

#978 nvhost_gpu: Don't over copy IoctlSubmitGpfifo.
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
Labels: canary-merge, hle-fix

#981 maxwell_3d: Use correct const buffer size and check bounds.
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: canary-merge, gpu-fix

#976 gl_shader_decompiler: Let OpenGL interpret floats.
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#982 gl_shader_decompiler: Stub input attribute Unknown_63.
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#987 vector_math: Use variable template version of is_signed in Vec classes
  src/common/vector_math.h
Labels: style

#977 gl_rasterizer_cached: Implement RenderTargetFormat::B5G6R5_UNORM.
  src/video_core/gpu.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-new

#988 common/color: Minor cleanup
  src/common/color.h
Labels: style

#984 gl_rasterizer: Do not render when no render target is configured.
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: canary-merge, gpu-fix

#993 Implement VertexAttribute::Size::Size_16_16_16_16 and PrimitiveTopology::Points.
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: canary-merge, gpu-new

#994 gl_rasterizer_cache: Use std::vector::assign vs resize() then copy for the non-tiled case
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: style

#992 gl_shader_decompiler: Declare predicates on use.
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#999 gl_rasterizer_cache: Avoid iterator invalidation issues within InvalidateRegion()
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: canary-merge, gpu-fix

#998 Implement SNORM for BC5/DXN2
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: gpu-new

#991 maxwell_3d: Ignore macros that have not been uploaded yet.
  src/video_core/engines/maxwell_3d.cpp
Labels: canary-merge, gpu-fix

#990 fsp_srv: Emplace entries first when building index instead of emplacing last
  src/core/file_sys/directory.h
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: style

#989 common/logging: Add missing service log categories
  src/common/logging/backend.cpp
  src/common/logging/log.h
Labels: hle-fix

#997 core: Make function reference parameters const where applicable
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
Labels: style

#1002 textures: Refactor out for Texture/Depth FormatFromPixelFormat.
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
  src/yuzu/debugger/graphics/graphics_surface.cpp
Labels: gpu-fix

#1008 Revert "gl_state: Temporarily disable culling and depth test."
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: canary-merge

#1011 Implements VertexAttributes Size_32_32_32 and Size_8_8.
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: canary-merge, gpu-new

#1015 qt/gamelist: Minor cleanup-related changes
  src/yuzu/game_list_p.h
Labels: style

#848 Implement R16S & R16UI & R16I RenderTargetFormats & PixelFormats and more (R16_UNORM needed by Fate Extella)
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: gpu-new

#1003 video_core: Use variable template variants of type_traits interfaces where applicable
  src/video_core/command_processor.h
  src/video_core/engines/shader_bytecode.h
Labels: style

#1016 video_core: Get rid of global variable g_toggle_framelimit_enabled
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/settings.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/renderer_base.cpp
  src/video_core/renderer_base.h
  src/video_core/video_core.cpp
  src/video_core/video_core.h
Labels: style

#970 loader: Add more descriptive errors
  src/core/core.cpp
  src/core/core.h
  src/core/file_sys/card_image.cpp
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/partition_filesystem.cpp
  src/core/file_sys/program_metadata.cpp
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/elf.cpp
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nca.cpp
  src/core/loader/nro.cpp
  src/core/loader/xci.cpp
  src/yuzu/game_list.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: core-fix

#1009 Implement render target formats RGBA8_SNORM and RG8_SNORM.
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-new

#1010 gl_shader_decompiler: Improve handling of unknown input/output attributes.
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#1024 GPU/Maxwell3D: Implemented an alternative set of blend factors.
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: canary-merge

#1027 gl_shader_decompiler: Fix GLSL compiler error with KIL instruction.
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#1006 GL renderer: Pick the streambuffer from citra and use them.
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/gl_stream_buffer.cpp
  src/video_core/renderer_opengl/gl_stream_buffer.h
Labels: canary-merge, gpu-fix

#1040 gl_shader_decompiler: Implement XMAD instruction.
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge

#1041 Kernel/Mutex: Don't duplicate threads in the mutex waiter list.
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
Labels: core-fix

#1042 Fixed a bunch of race conditions when running in multicore mode.
  src/core/core_cpu.cpp
  src/core/core_cpu.h
  src/core/core_timing.cpp
  src/core/hle/kernel/thread.cpp
Labels: core-fix

#1036 scheduler: Make HaveReadyThreads() a const member function
  src/common/thread_queue_list.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
Labels: style

#1043 Use an approximated amortized amount of ticks when advancing timing.
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/core_cpu.cpp
  src/core/hle/kernel/svc.cpp
Labels: core-fix

#1031 card_image: Simplify return statement of GetSubdirectories()
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
Labels: style

#1032 vfs: Use sanitized paths within MoveFile() and MoveDirectory()
  src/core/file_sys/vfs.cpp
Labels: core-fix

#1046 Added missing channel devices
  src/core/CMakeLists.txt
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.h
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/core/hle/service/nvdrv/devices/nvhost_vic.h
  src/core/hle/service/nvdrv/nvdrv.cpp
Labels: canary-merge

#1062 common: Remove unused old breakpoint source files
  src/common/CMakeLists.txt
  src/common/break_points.cpp
  src/common/break_points.h
Labels: build-system, style

#1066 CMakeLists: Add architecture detection for AArch64
  CMakeLists.txt
Labels: build-system

#1063 common/xbyak_abi: Mark defined functions in header as inline
  src/common/x64/xbyak_abi.h
  src/common/x64/xbyak_util.h
Labels: style

#1068 gl_rasterizer_cache: Implement G8R8S format.
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-new

#1071 gl_shader_decompiler: Several fixes for indirect constant buffer loads.
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#1070 gl_rasterizer: Fix upload size for constant buffers.
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: canary-merge, gpu-fix

#1069 maxwell_to_gl: Properly handle UnsignedInt/SignedInt sizes.
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: canary-merge, gpu-fix

#1051 Core::CoreTiming: add UnscheduleEventThreadsafe
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/hle/kernel/thread.cpp
Labels: canary-merge

#1005 file_sys: Add support for registration format
  src/common/CMakeLists.txt
  src/common/file_util.cpp
  src/common/file_util.h
  src/common/hex_util.cpp
  src/common/hex_util.h
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/crypto/key_manager.cpp
  src/core/crypto/key_manager.h
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/bis_factory.h
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/file_sys/nca_metadata.cpp
  src/core/file_sys/nca_metadata.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/romfs.cpp
  src/core/file_sys/vfs_concat.cpp
  src/core/file_sys/vfs_concat.h
  src/core/file_sys/vfs_real.cpp
  src/core/file_sys/vfs_real.h
  src/core/file_sys/vfs_vector.cpp
  src/core/file_sys/vfs_vector.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/loader/loader.cpp
  src/yuzu/game_list.cpp
  src/yuzu/game_list_p.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: canary-merge, core-new

#1075 loader/{nca, xci}: Remove unnecessary includes and unused member variables
  src/core/loader/nca.cpp
  src/core/loader/nca.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
Labels: style

#1085 common: Namespace hex_util.h/.cpp
  src/common/hex_util.cpp
  src/common/hex_util.h
  src/core/crypto/key_manager.cpp
  src/core/file_sys/registered_cache.cpp
Labels: style

#1084 gl_rasterizer_cache: Treat Depth formats differently from DepthStencil.
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-fix

#1019 Rasterizer: Manually implemented instanced rendering.
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
Labels: gpu-fix

#838 Port #3616 from Citra: "appveyor: set jobs to 4 for mingw"
  appveyor.yml
Labels: build-system

#1101 Shaders: Implemented a stack for the SSY/SYNC instructions.
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#1089 Shaders: Corrected the 'abs' and 'neg' bit usage in the float arithmetic instructions.
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#1017 New account backend to allow for future extended support
  src/core/CMakeLists.txt
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/acc_aa.cpp
  src/core/hle/service/acc/acc_aa.h
  src/core/hle/service/acc/acc_su.cpp
  src/core/hle/service/acc/acc_su.h
  src/core/hle/service/acc/acc_u0.cpp
  src/core/hle/service/acc/acc_u0.h
  src/core/hle/service/acc/acc_u1.cpp
  src/core/hle/service/acc/acc_u1.h
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
Labels: canary-merge

#1064 common/telemetry: Migrate core-independent info gathering to common
  src/common/telemetry.cpp
  src/common/telemetry.h
  src/core/telemetry_session.cpp
Labels: style

#1122 acc/profile_manager: General cleanup
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
Labels: style

#1126 telemetry_session: Don't allocate std::string instances for program lifetime in GetTelemetryId() and RegenerateTelemetryId()
  src/core/telemetry_session.cpp
Labels: style

#1133 gl_stream_buffer: Add missing header guard
  src/video_core/renderer_opengl/gl_stream_buffer.h
Labels: style

#1145 vfs: Replace mode.h include with forward declarations where applicable
  src/core/file_sys/vfs.cpp
  src/core/file_sys/vfs.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: style

#1088 PL:U Added BFTTF loading(Loading from System NAND dumps)
  src/core/hle/service/ns/pl_u.cpp
Labels: canary-merge

#1151 Revert "Shader: Use the right sampler type in the TEX, TEXS and TLDS …"
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
Labels: canary-merge, gpu-fix

#1147 logging/text_formatter: Use empty braces for initializing CONSOLE_SCREEN_BUFFER_INFO instance
  src/common/logging/text_formatter.cpp
Labels: style

#1124 GPU: Implemented logic ops.
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: canary-merge, gpu-new

#1156 gl_shader_decompiler: Implement LOP3
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1153 gl_rasterizer: Implement partial color clear, stencil clear, and stencil test.
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: canary-merge, gpu-new

#1160 gl_rasterizer_cache: Several improvements
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-fix

#1065 qt: Add filename and title id to window title while running
  src/core/core.h
  src/yuzu/main.cpp
Labels: frontend-new

#1094 file_sys: Add support for NAX archives
  src/core/CMakeLists.txt
  src/core/crypto/aes_util.cpp
  src/core/crypto/ctr_encryption_layer.cpp
  src/core/crypto/key_manager.cpp
  src/core/crypto/key_manager.h
  src/core/crypto/xts_encryption_layer.cpp
  src/core/crypto/xts_encryption_layer.h
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/sdmc_factory.cpp
  src/core/file_sys/sdmc_factory.h
  src/core/file_sys/vfs.cpp
  src/core/file_sys/vfs.h
  src/core/file_sys/xts_archive.cpp
  src/core/file_sys/xts_archive.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nax.cpp
  src/core/loader/nax.h
  src/core/loader/xci.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/game_list.cpp
  src/yuzu/game_list_p.h
  src/yuzu/main.cpp
Labels: canary-merge, core-new

#1166 filesystem: Fix typo in log message
  src/core/hle/service/filesystem/filesystem.cpp
Labels: style

#1167 gl_rasterizer: Correct assertion condition in SyncLogicOpState()
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: gpu-fix

#1180 set: Fixed GetAvailableLanguageCodes() to follow the max_entries
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set.h
Labels: hle-fix

#1171 core: Remove always true conditionals in Load()
  src/core/core.cpp
Labels: style

#1162 PL:U Added SharedFonts loading via TTF
  src/core/hle/service/ns/pl_u.cpp
Labels: canary-merge, hle-new

#1174 debug_utils: Minor individual interface changes
  src/core/core.h
  src/video_core/debug_utils/debug_utils.cpp
  src/video_core/debug_utils/debug_utils.h
  src/yuzu/debugger/graphics/graphics_breakpoints.cpp
  src/yuzu/debugger/graphics/graphics_surface.cpp
Labels: style

#1176 svc: Return process title ID if queried in GetInfo()
  src/core/hle/kernel/svc.cpp
Labels: hle-fix

#1128 hex_util: Replace logic_errors with LOG_CRITICAL
  src/common/hex_util.cpp
Labels: core-fix

#1187 registered_cache: Get rid of variable shadowing in ProcessFiles()
  src/core/file_sys/registered_cache.cpp
Labels: style

#1175 core: Namespace all code in the arm subdirectory under the Core namespace
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/arm/exclusive_monitor.cpp
  src/core/arm/exclusive_monitor.h
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/arm/unicorn/arm_unicorn.h
  src/core/core.h
  src/core/core_cpu.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: style

#1170 file_util: Correct return value in early exit of ReadFileToString()
  src/common/file_util.cpp
Labels: style

#1177 kernel/error: Amend several error codes
  src/core/hle/kernel/errors.h
  src/core/hle/kernel/handle_table.cpp
  src/core/hle/kernel/handle_table.h
  src/core/hle/kernel/shared_memory.cpp
Labels: hle-fix

#1165 renderer_opengl: Implement a new shader cache.
  src/video_core/CMakeLists.txt
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
Labels: canary-merge, gpu-fix

#1194 gl_shader_cache: Remove unused program_code vector in GetShaderAddress()
  src/video_core/renderer_opengl/gl_shader_cache.cpp
Labels: style

#1191 hle/result: Make ResultVal's move constructor as noexcept
  src/core/hle/result.h
Labels: style

#1192 gl_rasterizer: Remove unused variables
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: style

#1193 gpu: Make memory_manager private
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/memory.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/yuzu/debugger/graphics/graphics_surface.cpp
Labels: style

#1172 Shaders: Implemented IADD3
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1198 kernel: Eliminate kernel global state
  src/core/core.cpp
  src/core/core.h
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/client_port.cpp
  src/core/hle/kernel/client_port.h
  src/core/hle/kernel/client_session.cpp
  src/core/hle/kernel/client_session.h
  src/core/hle/kernel/event.cpp
  src/core/hle/kernel/event.h
  src/core/hle/kernel/handle_table.cpp
  src/core/hle/kernel/handle_table.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/mutex.cpp
  src/core/hle/kernel/mutex.h
  src/core/hle/kernel/object.cpp
  src/core/hle/kernel/object.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/resource_limit.cpp
  src/core/hle/kernel/resource_limit.h
  src/core/hle/kernel/server_port.cpp
  src/core/hle/kernel/server_port.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/server_session.h
  src/core/hle/kernel/shared_memory.cpp
  src/core/hle/kernel/shared_memory.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/timer.cpp
  src/core/hle/kernel/timer.h
  src/core/hle/kernel/wait_object.cpp
  src/core/hle/kernel/wait_object.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/nvdrv/interface.cpp
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/sm/sm.cpp
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/elf.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
  src/tests/core/arm/arm_test_common.cpp
  src/tests/core/arm/arm_test_common.h
  src/yuzu/debugger/wait_tree.cpp
Labels: style

#1200 gl_shader_decompiler: Improve IPA for Pass mode with Position attribute.
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-fix

#1203 gl_shader_decompiler: Implement POPC
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu-new

#1204 core: Make the main System class use the PImpl idiom
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: style

#1092 Implement BC6H_UF16 & BC6H_SF16
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/textures/decoders.cpp
Labels: gpu-new
