Repository yuzu-emu/yuzu, pull requests merged in 2019-10, with the labels that each got.

#2929 ci: Merge patreon tagged PRs from public repository during merge step.
  .ci/scripts/merge/apply-patches-by-label-private.py
  .ci/scripts/merge/apply-patches-by-label.py
  .ci/templates/mergebot-private.yml
Labels: build-system-new

#2904 Signal styleset changes at a better time
  src/core/hle/service/hid/controllers/npad.cpp
Labels: canary-merge, hle-fix, mainline-merge

#2932 ci: Iterate through GitHub pages for pull requests
  .ci/scripts/merge/apply-patches-by-label-private.py
  .ci/scripts/merge/apply-patches-by-label.py
Labels: build-system-fix

#2937 ci: Add windows MSVC builds to patreon and mainline pipelines
  .ci/scripts/windows/upload.ps1
  .ci/templates/build-msvc.yml
  .ci/templates/build-single.yml
  .ci/templates/mergebot.yml
  .ci/templates/release-download.yml
  .ci/yuzu-mainline-step2.yml
  .ci/yuzu-patreon-step2.yml
Labels: build-system-fix, build-system-new

#2898 Port citra-emu/citra#4004: "qt_themes: add two colorful themes"
  license.txt
  src/yuzu/uisettings.cpp
  src/yuzu/uisettings.h
Labels: frontend-new

#2936 [crypto] Use IsAllZeroArray helper function
  src/core/crypto/key_manager.cpp
Labels: canary-merge, mainline-merge

#2896 Port citra-emu/citra#4950: "Add FPS to SDL title bar"
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.h
  src/yuzu_cmd/yuzu.cpp
Labels: frontend-new

#2917 TextureCache: Add the ability to deduce if two textures are depth on blit.
  src/video_core/texture_cache/texture_cache.h
Labels: canary-merge, gpu-fix, mainline-merge, performance

#2888 Shader_IR: Implement a full control flow decompiler for the shader IR.
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/ast.cpp
  src/video_core/shader/ast.h
  src/video_core/shader/compiler_settings.cpp
  src/video_core/shader/compiler_settings.h
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/control_flow.h
  src/video_core/shader/decode.cpp
  src/video_core/shader/expr.cpp
  src/video_core/shader/expr.h
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: gpu-new

#2943 ci: Add custom titlebars for mainline and patreon
  .ci/scripts/linux/docker.sh
  .ci/scripts/linux/exec.sh
  .ci/scripts/windows/docker.sh
  .ci/scripts/windows/exec.sh
  .ci/templates/build-msvc.yml
  .ci/templates/build-single.yml
  .ci/templates/build-standard.yml
  .ci/templates/build-testing.yml
  .ci/yuzu-mainline-step2.yml
  .ci/yuzu-patreon-step2.yml
  src/common/CMakeLists.txt
  src/common/scm_rev.cpp.in
  src/common/scm_rev.h
  src/yuzu/main.cpp
Labels: build-system-fix, build-system-new

#2942 Silence miscellaneous warnings
  src/common/file_util.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/apm/controller.cpp
  src/core/hle/service/apm/controller.h
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/core/hle/service/bcat/module.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/hid/controllers/debug_pad.cpp
  src/core/hle/service/hid/controllers/debug_pad.h
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/gesture.h
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/keyboard.h
  src/core/hle/service/hid/controllers/mouse.cpp
  src/core/hle/service/hid/controllers/mouse.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/stubbed.cpp
  src/core/hle/service/hid/controllers/stubbed.h
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
  src/core/hle/service/hid/controllers/xpad.cpp
  src/core/hle/service/hid/controllers/xpad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/yuzu/configuration/configure_service.cpp
  src/yuzu/game_list.cpp
  src/yuzu/game_list_p.h
  src/yuzu/game_list_worker.cpp
  src/yuzu/game_list_worker.h
  src/yuzu_tester/config.cpp
Labels: style

#2953 qt: Fix game name format error
  src/yuzu/main.cpp
Labels: build-system-fix

#2954 gl_shader_disk_cache: Properly ignore existing cache
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
Labels: canary-merge, mainline-merge, opengl

#2890 hid: Implement DeactivateNpad
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: hle-new

#2956 ci: Add TAR-XZ compression to MSVC builds
  .ci/scripts/windows/upload.ps1
Labels: build-system-new

#2961 ci: Correct azure tag and release names
  .ci/templates/build-mock.yml
  .ci/templates/merge-private.yml
  .ci/templates/merge.yml
  .ci/templates/release-github.yml
  .ci/templates/release-private-tag.yml
  .ci/yuzu-mainline-step2.yml
  .ci/yuzu-patreon-step2.yml
Labels: build-system-fix, build-system-new

#2654 lm: Rewrite logger to use core reporting services
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/lm/lm.cpp
  src/core/hle/service/lm/lm.h
  src/core/hle/service/lm/manager.cpp
  src/core/hle/service/lm/manager.h
  src/core/hle/service/service.cpp
  src/core/reporter.cpp
  src/core/reporter.h
Labels: canary-merge, hle-new

#2927 gl_rasterizer: Fix polygon offset units
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: canary-merge, gpu-fix, mainline-merge, opengl

#2928 maxwell_3d: Add dirty flags for depth bounds values
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
Labels: gpu

#2910 Port citra-emu/citra#4930: "Pause when in background"
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/uisettings.h
Labels: frontend-new

#2930 file_sys: Add code to access raw gamecard partitions and lazily load them
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/partition_filesystem.cpp
  src/core/file_sys/partition_filesystem.h
Labels: canary-merge, core-new, mainline-merge

#2968 yuzu/configure_input_player: Fix input handling for ZL and ZR from controllers with analog triggers
  src/yuzu/configuration/configure_input_player.cpp
Labels: mainline-merge

#2897 pl_u: Move open source font archives and fix NAND error
  externals/CMakeLists.txt
  externals/open_source_archives/CMakeLists.txt
  externals/open_source_archives/Readme.md
  externals/open_source_archives/include/FontChineseSimplified.h
  externals/open_source_archives/include/FontChineseTraditional.h
  externals/open_source_archives/include/FontExtendedChineseSimplified.h
  externals/open_source_archives/include/FontKorean.h
  externals/open_source_archives/include/FontNintendoExtended.h
  externals/open_source_archives/include/FontStandard.h
  externals/open_source_archives/src/FontChineseSimplified.cpp
  externals/open_source_archives/src/FontChineseTraditional.cpp
  externals/open_source_archives/src/FontExtendedChineseSimplified.cpp
  externals/open_source_archives/src/FontKorean.cpp
  externals/open_source_archives/src/FontNintendoExtended.cpp
  externals/open_source_archives/src/FontStandard.cpp
  src/core/CMakeLists.txt
  src/core/file_sys/system_archive/data/font_chinese_simplified.cpp
  src/core/file_sys/system_archive/data/font_chinese_simplified.h
  src/core/file_sys/system_archive/data/font_chinese_traditional.cpp
  src/core/file_sys/system_archive/data/font_chinese_traditional.h
  src/core/file_sys/system_archive/data/font_extended_chinese_simplified.cpp
  src/core/file_sys/system_archive/data/font_extended_chinese_simplified.h
  src/core/file_sys/system_archive/data/font_korean.cpp
  src/core/file_sys/system_archive/data/font_korean.h
  src/core/file_sys/system_archive/data/font_nintendo_extended.cpp
  src/core/file_sys/system_archive/data/font_nintendo_extended.h
  src/core/file_sys/system_archive/data/font_standard.cpp
  src/core/file_sys/system_archive/data/font_standard.h
  src/core/file_sys/system_archive/shared_font.cpp
  src/core/file_sys/system_archive/shared_font.h
  src/core/file_sys/system_archive/system_archive.cpp
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/ns/pl_u.h
Labels: hle-fix, mainline-merge

#2965 Core Timing: Rework Core Timing to run all cores evenly.
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/core_cpu.cpp
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/cpu_core_manager.cpp
  src/tests/core/core_timing.cpp
Labels: core-fix

#2977 common: Rename binary_find.h to algorithm.h
  src/common/CMakeLists.txt
  src/common/algorithm.h
  src/video_core/texture_cache/surface_base.cpp
  src/video_core/texture_cache/surface_base.h
Labels: general

#2972 {bcat, gpu, nvflinger}: Remove trivial usages of the global system accessor
  src/core/hle/service/am/am.cpp
  src/core/hle/service/bcat/backend/backend.cpp
  src/core/hle/service/bcat/backend/backend.h
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/core/hle/service/bcat/backend/boxcat.h
  src/core/hle/service/bcat/module.cpp
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/video_core/gpu.cpp
Labels: general

#2981 gl_shader_decompiler: Minor cleanup-related changes
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/node.h
Labels: general

#2982 texture_cache: Avoid unnecessary surface copies within PickStrategy() and TryReconstructSurface()
  src/video_core/texture_cache/texture_cache.h
Labels: general

#2978 video_core/texture_cache: Amend Doxygen references
  src/video_core/texture_cache/texture_cache.h
Labels: style

#2980 maxwell_3d: Silence truncation warnings
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/control_flow.h
Labels: general

#2990 core: Resolve -Wreorder warnings
  src/core/core.cpp
  src/core/memory/cheat_engine.cpp
Labels: general

#2989 service/apm/controller: Minor interface changes
  src/core/hle/service/apm/controller.cpp
  src/core/hle/service/apm/controller.h
Labels: general

#2979 video_core/macro_interpreter: Make definitions of most private enums/unions hidden
  src/video_core/macro_interpreter.cpp
  src/video_core/macro_interpreter.h
Labels: general

#2966 Implement a series of ASTC formats and R4G4B4A4 format
  src/video_core/morton.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/surface.cpp
  src/video_core/surface.h
Labels: gpu-new, mainline-merge

#2992 dmnt_cheat_vm: Correct register Restore and ClearRegs behavior
  src/core/memory/dmnt_cheat_vm.cpp
Labels: bug

#2993 vk_shader_decompiler: Mark operator() function parameters as const references
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Labels: general

#2994 video_core/shader/ast: Minor changes to ASTPrinter
  src/video_core/shader/ast.cpp
  src/video_core/shader/ast.h
Labels: general

#3003 maxwell_3d: Reduce FlushMMEInlineDraw logging to Trace
  src/video_core/engines/maxwell_3d.cpp
Labels: general

#2983 gl_shader_decompiler/vk_shader_decompiler: Resolve implicit fallthrough cases
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Labels: gpu

#2995 shader_ir/memory: Ignore global memory when tracking fails
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/shader_ir.h
Labels: gpu, mainline-merge

#2991 hid/npad: Minor cleanup
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
Labels: bug, general

#3022 ci: Add build name to archive root folder
  .ci/scripts/common/post-upload.sh
  .ci/scripts/linux/upload.sh
  .ci/scripts/windows/upload.ps1
  .ci/scripts/windows/upload.sh
  .ci/templates/build-msvc.yml
Labels: build-system-fix

#3024 video_core/shader: Resolve instances of variable shadowing
  src/video_core/shader/decode/arithmetic_integer.cpp
  src/video_core/shader/decode/image.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/decode/shift.cpp
  src/video_core/shader/decode/video.cpp
  src/video_core/shader/decode/warp.cpp
Labels: general

#3028 shader_bytecode: Make Matcher constexpr capable
  src/video_core/engines/shader_bytecode.h
Labels: general

#3013 Shader_Ir: Fix TLD4S from using a component mask.
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/shader_ir.h
Labels: gpu-fix, mainline-merge

#3027 shader_ir: Use std::array with std::pair instead of std::unordered_map
  src/video_core/shader/shader_ir.cpp
Labels: general, mainline-merge

#2976 Implement Fast BRX, fix TXQ and addapt the Shader Cache for it
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/common/hash.h
  src/video_core/CMakeLists.txt
  src/video_core/engines/const_buffer_engine_interface.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/ast.cpp
  src/video_core/shader/const_buffer_locker.cpp
  src/video_core/shader/const_buffer_locker.h
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/control_flow.h
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/expr.h
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: gpu-fix, gpu-new, mainline-merge

#3033 astc: Silence implicit conversion warnings
  src/video_core/textures/astc.cpp
Labels: style

#3034 maxwell_3d: Silence implicit conversion warnings
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
Labels: style

#2971 Kernel: Implement a New Thread Scheduler V2
  src/common/multi_level_queue.h
  src/core/core.cpp
  src/core/core.h
  src/core/core_cpu.cpp
  src/core/core_cpu.h
  src/core/cpu_core_manager.cpp
  src/core/gdbstub/gdbstub.cpp
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/mutex.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/wait_object.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: core-new

#3004 maxwell_3d: Remove unused entries
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/textures/texture.h
Labels: style

#3007 savedata_factory: Automatically create certain savedata
  src/core/file_sys/savedata_factory.cpp
Labels: canary-merge, hle-fix, mainline-merge

#3035 rasterizer_accelerated: Add intermediary for GPU rasterizers
  src/video_core/CMakeLists.txt
  src/video_core/rasterizer_accelerated.cpp
  src/video_core/rasterizer_accelerated.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: gpu

#3046 gl_state: Miscellaneous clean up
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: opengl

#3038 kernel/scheduler: Minor changes
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
Labels: style
