Repository yuzu-emu/yuzu, pull requests merged in 2019-03, with the labels that each got.

#2181 service/audio/audren_u: Implement OpenAudioRendererAuto
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/audren_u.h
Labels: audio-issue, audio-new

#2180 service/audio: Provide an implementation of ExecuteAudioRendererRendering
  src/core/hle/service/audio/audren_u.cpp
Labels: audio-issue, audio-new

#2173 yuzu/compatdb: Remove unused lambda capture
  src/yuzu/compatdb.cpp
Labels: style

#2182 fuck git for ruining my day, I will learn but I will not forgive
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: canary-merge

#2189 web_service: Remove unnecessary inclusions
  src/web_service/verify_login.h
  src/web_service/web_backend.cpp
Labels: style

#2188 logging/backend: Move CreateEntry into the Impl class. Relocate local static to a class variable
  src/common/logging/backend.cpp
  src/common/logging/backend.h
Labels: style

#2165 gl_rasterizer: Unbind textures but don't apply the gl_state
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_state.cpp
Labels: canary-merge, performance

#2198 {kernel/thread, video_core/surface}: Remove obsolete TODOs
  src/core/hle/kernel/thread.cpp
  src/video_core/surface.cpp
Labels: style

#2203 video_core/engines: Remove unnecessary includes
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_base.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
Labels: style

#2200 hle/service/audio: Extract audio error codes to a header
  src/core/CMakeLists.txt
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/errors.h
Labels: audio-fix

#2194 svc: Move memory range checking functions to the VMManager class
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
Labels: style

#2204 yuzu/debugger/wait_tree: Remove use of global CurrentProcess accessor
  src/yuzu/debugger/wait_tree.cpp
  src/yuzu/debugger/wait_tree.h
Labels: style

#2201 hle/service/audio/audout_u: Correct lack of return in failure case of AppendAudioOutBufferImpl()
  src/core/hle/service/audio/audout_u.cpp
Labels: audio-fix, audio-issue

#2199 kernel/address_arbiter: Convert the address arbiter into a class
  src/core/core.cpp
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/address_arbiter.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc.cpp
  src/tests/core/arm/arm_test_common.cpp
Labels: style

#2190 core: Remove the global telemetry accessor function
  src/core/core.cpp
  src/core/core.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/yuzu/compatdb.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: style

#2197 core/hle/ipc: Remove unnecessary includes
  src/core/hle/ipc.h
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/result.h
  src/core/hle/service/am/applets/software_keyboard.cpp
  src/core/hle/service/am/applets/software_keyboard.h
Labels: style

#2055 Asynchronous GPU command processing
  src/core/core.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/memory.cpp
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/video_core/CMakeLists.txt
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_asynch.h
  src/video_core/gpu_synch.cpp
  src/video_core/gpu_synch.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: canary-merge, gpu, gpu-new, performance

#2206 service/audio/audout_u: Only actually stop the audio stream in StopAudioOut if the stream is playing
  src/core/hle/service/audio/audout_u.cpp
Labels: audio-issue, hle-issue

#2202 kernel/client_session, kernel/server_session: Make data members private
  src/core/hle/kernel/client_session.cpp
  src/core/hle/kernel/client_session.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/server_session.h
  src/core/hle/service/sm/controller.cpp
Labels: style

#2196 web_browser: Add shortcut to Enter key to exit applet
  src/yuzu/applets/web_browser.cpp
  src/yuzu/main.cpp
Labels: frontend-new, request

#2195 kernel/shared_memory: Get rid of the use of global accessor functions within Create()
  src/core/hle/kernel/shared_memory.cpp
Labels: style

#2208 video_core/gpu: Make GPU's destructor virtual
  src/video_core/gpu.h
  src/video_core/gpu_asynch.h
  src/video_core/gpu_synch.h
Labels: gpu-issue

#2209 video_core/gpu_thread: Silence a -Wreorder warning
  src/video_core/gpu_thread.h
Labels: style

#2210 kernel/hle_ipc: Convert std::shared_ptr IPC header instances to std::optional
  .travis.yml
  .travis/macos/build.sh
  src/common/bit_field.h
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/server_session.cpp
Labels: style

#2218 yuzu_cmd/config: Silent implicit cast warning
  src/yuzu_cmd/config.cpp
Labels: style

#2219 core/settings: Log more setting values
  src/core/settings.cpp
Labels: core-fix

#2217 gl_rasterizer: Minor logger changes
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: gpu

#2220 audio_core/cubeb_sink: Convert _MSC_VER ifdefs to _WIN32
  src/audio_core/cubeb_sink.cpp
  src/audio_core/cubeb_sink.h
Labels: audio-fix

#2143 gl_rasterizer_cache: Create texture views for array discrepancies
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-fix

#2147 shader_ir: Remove "extras" from the MetaTexture
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu

#2193 kernel/scheduler: Pass in system instance in constructor
  src/core/core_cpu.cpp
  src/core/core_cpu.h
  src/core/cpu_core_manager.cpp
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
Labels: style

#2207 service/audio/hwopus: Move decoder state to its own class
  src/core/hle/service/audio/hwopus.cpp
Labels: hle-issue, style

#2215 gl_rasterizer: Encapsulate sampler queries into methods
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/textures/texture.h
Labels: style

#2222 service/service: Remove unncessary calls to c_str()
  src/core/hle/service/service.cpp
Labels: style

#2211 kernel: Make the address arbiter instance per-process
  src/core/core.cpp
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/address_arbiter.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
  src/tests/core/arm/arm_test_common.cpp
Labels: kernel-issue

#2166 service/vi: Unstub GetDisplayService
  src/core/hle/ipc_helpers.h
  src/core/hle/service/vi/vi.cpp
  src/core/hle/service/vi/vi.h
  src/core/hle/service/vi/vi_m.cpp
  src/core/hle/service/vi/vi_m.h
  src/core/hle/service/vi/vi_s.cpp
  src/core/hle/service/vi/vi_s.h
  src/core/hle/service/vi/vi_u.cpp
  src/core/hle/service/vi/vi_u.h
Labels: hle-issue, hle-new

#2187 Port various Citra changes to input_common, including deadzone support
  src/input_common/CMakeLists.txt
  src/input_common/main.cpp
  src/input_common/main.h
  src/input_common/sdl/sdl.cpp
  src/input_common/sdl/sdl.h
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/sdl/sdl_impl.h
  src/yuzu/bootmanager.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: canary-merge

#2223 core/hle/result: Tidy up the base error code result header.
  src/core/hle/ipc_helpers.h
  src/core/hle/result.h
  src/core/hle/service/service.cpp
Labels: style

#2226 kernel/server_port: Make data members private
  src/core/hle/kernel/client_port.cpp
  src/core/hle/kernel/server_port.cpp
  src/core/hle/kernel/server_port.h
  src/core/hle/service/sm/sm.h
Labels: style

#2227 renderer_opengl/gl_global_cache: Add missing override specifiers
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.h
Labels: style

#2230 kernel/process: Remove use of global system accessors
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
Labels: style

#2233 video_core/morton: Miscellaneous changes
  src/video_core/morton.cpp
  src/video_core/morton.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: style

#2048 Port citra-emu/citra#3924: "citra_qt: Settings (configuration) rework"
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
Labels: canary-merge, frontend-fix

#2237 gpu: Use host address for caching instead of guest address.
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/memory.cpp
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/gpu.h
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_asynch.h
  src/video_core/gpu_synch.cpp
  src/video_core/gpu_synch.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/rasterizer_cache.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
Labels: canary-merge, gpu-fix, gpu-new, performance, style

#2242 kernel/thread: Remove WaitCurrentThread_Sleep() and ExitCurrentThread()
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: style

#2241 CMakeLists: Remove now-unnecessary GCC special-casing
  CMakeLists.txt
Labels: build-system

#2129 Correct CNTPCT from using CPU Cycles to using Clock Cycles
  src/common/CMakeLists.txt
  src/common/uint128.cpp
  src/common/uint128.h
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/core_timing_util.cpp
  src/core/core_timing_util.h
Labels: canary-merge

#2243 memory: Simplify rasterizer cache operations.
  src/core/memory.cpp
  src/core/memory.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: canary-merge

#2244 video_core: Refactor to use MemoryManager interface for all memory access.
  src/video_core/dma_pusher.cpp
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/gpu.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/morton.cpp
  src/video_core/morton.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.h
  src/video_core/renderer_opengl/gl_primitive_assembler.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
  src/yuzu/debugger/graphics/graphics_surface.cpp
Labels: canary-merge, gpu

#2245 kernel/thread: Actually remove the definition of ExitCurrentThread()
  src/core/hle/kernel/thread.cpp
Labels: style

#2249 ipc_helpers: Allow pushing and popping floating-point values
  src/core/hle/ipc_helpers.h
Labels: hle-issue

#2252 core: Move PageTable struct into Common.
  src/common/CMakeLists.txt
  src/common/memory_hook.cpp
  src/common/memory_hook.h
  src/common/page_table.cpp
  src/common/page_table.h
  src/core/CMakeLists.txt
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
  src/core/memory.cpp
  src/core/memory.h
  src/core/memory_setup.h
  src/tests/core/arm/arm_test_common.cpp
  src/tests/core/arm/arm_test_common.h
Labels: canary-merge

#2238 kernel/thread: Amend conditional test and assignment within UpdatePriority()
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: kernel-issue

#2254 input_common/sdl_impl: Minor cleanup in SDLState constructor
  src/input_common/sdl/sdl_impl.cpp
Labels: style

#2259 fsp_srv: Unstub SetCurrentProcess
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
Labels: hle-new

#2258 service/am: Supply remaining missing IAudioController functions
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: hle-new

#2264 core/loader: Remove vestigial Linker class
  src/core/CMakeLists.txt
  src/core/loader/linker.cpp
  src/core/loader/linker.h
  src/core/loader/nro.h
  src/core/loader/nso.h
Labels: style

#2239 Port citra-emu/citra#4684: "frontend: qt: fix a freeze where if you click on entry in the game list too fast, citra will hang"
  src/yuzu/bootmanager.cpp
Labels: frontend-fix

#2224 hwopus: Leverage multistream API for decoding regular Opus packets
  src/core/hle/service/audio/hwopus.cpp
Labels: canary-merge, hle-issue

#2247 common/thread_queue_list: Remove unnecessary dependency on boost
  src/common/CMakeLists.txt
  src/common/thread_queue_list.h
Labels: style

#2267 Fix crash caused by #2238.
  src/core/hle/kernel/thread.cpp
Labels: canary-merge

#2272 common/CMakeLists: Amend boost dependency
  src/common/CMakeLists.txt
Labels: build-system

#2268 core/kernel: Migrate CodeSet to its own source files
  src/core/CMakeLists.txt
  src/core/hle/kernel/code_set.cpp
  src/core/hle/kernel/code_set.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/loader/elf.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
Labels: style

#2273 common/uint128: Add missing header guard
  src/common/uint128.cpp
  src/common/uint128.h
Labels: style

#2262 file_sys/content_archive: Amend name of Data_Unknown5 enum entry
  src/core/file_sys/content_archive.h
  src/core/file_sys/registered_cache.cpp
Labels: style

#2090 Port citra-emu/citra#4244 and citra-emu/citra#4599: Changes to BitField
  src/common/bit_field.h
  src/common/swap.h
  src/core/hle/ipc.h
  src/core/hle/service/hid/controllers/debug_pad.h
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/controllers/touchscreen.h
  src/core/hle/service/lm/lm.cpp
  src/core/hle/service/nvdrv/devices/nvdevice.h
  src/tests/CMakeLists.txt
  src/tests/common/bit_field.cpp
Labels: core-fix

#2260 input_common/sdl: Correct return values within GetPollers implementations
  src/input_common/sdl/sdl.h
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/sdl/sdl_impl.h
Labels: bug

#1933 file_sys: Implement parser and interpreter for game memory cheats
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.h
  src/core/file_sys/cheat_engine.cpp
  src/core/file_sys/cheat_engine.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/hle/kernel/vm_manager.h
  src/core/hle/service/hid/hid.h
  src/core/loader/nso.cpp
Labels: canary-merge, core-new

#2276 service/am: Add function table for IDebugFunctions
  src/core/hle/service/am/am.cpp
Labels: hle-issue

#2275 kernel/vm_manager: Amend flag value for code data
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
  src/core/hle/service/ldr/ldr.cpp
Labels: kernel-issue

#2274 core/memory: Remove unnecessary includes
  src/core/memory.h
Labels: style

#2234 core/hle/kernel: Make Mutex a per-process class.
  src/core/hle/kernel/mutex.cpp
  src/core/hle/kernel/mutex.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
Labels: kernel-issue, style

#2277 Revert "Devirtualize Register/Unregister and use a wrapper instead."
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu, gpu-fix

#2256 gpu: Rewrite MemoryManager based on the VMManager implementation.
  src/common/common_types.h
  src/common/page_table.cpp
  src/common/page_table.h
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/memory.cpp
  src/video_core/dma_pusher.h
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.h
  src/video_core/renderer_opengl/gl_primitive_assembler.cpp
  src/video_core/renderer_opengl/gl_primitive_assembler.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/yuzu/debugger/graphics/graphics_surface.cpp
  src/yuzu/debugger/graphics/graphics_surface.h
Labels: canary-merge

#2279 file_sys/cheat_engine: Remove use of global system accessors
  src/core/core.cpp
  src/core/file_sys/cheat_engine.cpp
  src/core/file_sys/cheat_engine.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/loader/nso.cpp
Labels: style

#2280 loader/nso: Minor refactoring
  src/core/file_sys/patch_manager.cpp
  src/core/loader/nso.cpp
  src/core/loader/nso.h
Labels: style

#2221 set_sys: Implement GetFirmwareVersion(2) for libnx hosversion
  src/core/CMakeLists.txt
  src/core/file_sys/errors.h
  src/core/file_sys/system_archive/system_archive.cpp
  src/core/file_sys/system_archive/system_version.cpp
  src/core/file_sys/system_archive/system_version.h
  src/core/hle/service/set/set_sys.cpp
  src/core/hle/service/set/set_sys.h
Labels: canary-merge, hle-new

#2232 core/hle/kernel: Split transfer memory handling out into its own class
  src/core/CMakeLists.txt
  src/core/hle/kernel/object.cpp
  src/core/hle/kernel/object.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/transfer_memory.cpp
  src/core/hle/kernel/transfer_memory.h
Labels: canary-merge, hle-new, kernel-issue

#2288 core/cheat_engine: Make MemoryReadImpl and MemoryWriteImpl internally linked
  src/core/file_sys/cheat_engine.cpp
Labels: style

#2286 kernel/kernel: Remove unnecessary forward declaration
  src/core/hle/kernel/kernel.h
Labels: style

#2287 core/core_timing: Make callback parameters consistent
  src/audio_core/stream.cpp
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
  src/core/hle/service/nvflinger/nvflinger.cpp
Labels: style

#2285 kernel/process: Remove unused AddressMapping struct
  src/core/hle/kernel/process.h
Labels: style

#2295 video_core/gpu: Amend typo in GPU member variable name
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: style

#2296 video_core: Add missing override specifiers
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_vulkan/vk_resource_manager.cpp
  src/video_core/renderer_vulkan/vk_resource_manager.h
Labels: style

#2284 kernel/vm_manager: Unify heap allocation/freeing functions
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
Labels: canary-merge, kernel-issue

#2265 Replace old Thread Queue for a new Multi Level Queue
  src/common/CMakeLists.txt
  src/common/bit_util.h
  src/common/multi_level_queue.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/tests/CMakeLists.txt
  src/tests/common/bit_utils.cpp
  src/tests/common/multi_level_queue.cpp
Labels: canary-merge, hle-new, performance

#2266 Kernel: Fixes to Arbitration and SignalProcessWideKey Management
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/yuzu/debugger/wait_tree.cpp
Labels: canary-merge

#2307 service/fatal: Name FatalInfo structure members
  src/core/hle/service/fatal/fatal.cpp
Labels: hle-fix, hle-issue

#2308 kernel/scheduler: Minor tidying up
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/core/hle/kernel/thread.cpp
Labels: style

#2298 video_core/{gl_rasterizer, gpu_thread}: Remove unused class variables where applicable
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: style

#2297 video_core: Amend constructor initializer list order where applicable
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
Labels: style

#2303 common/thread: Remove unused functions
  src/common/thread.cpp
  src/common/thread.h
Labels: style

#2304 kernel/process: Report total physical memory used to svcGetInfo slightly better
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
Labels: kernel-issue
