Repository yuzu-emu/yuzu, pull requests merged in 2019-04, with the labels that each got.

#2312 general: Use deducation guides for std::lock_guard and std::unique_lock
  src/common/detached_tasks.cpp
  src/common/logging/backend.cpp
  src/common/thread.h
  src/common/threadsafe_queue.h
  src/core/core_cpu.cpp
  src/core/frontend/emu_window.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/perf_stats.cpp
  src/input_common/keyboard.cpp
  src/input_common/motion_emu.cpp
  src/input_common/sdl/sdl_impl.cpp
  src/video_core/debug_utils/debug_utils.cpp
  src/video_core/debug_utils/debug_utils.h
  src/video_core/gpu_thread.h
  src/video_core/rasterizer_cache.h
  src/web_service/web_backend.cpp
  src/yuzu/applets/profile_select.cpp
  src/yuzu/applets/software_keyboard.cpp
  src/yuzu/applets/web_browser.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
Labels: style

#2281 kernel/codeset: Make CodeSet's memory data member a regular std::vector
  src/core/hle/kernel/code_set.h
  src/core/hle/kernel/process.cpp
  src/core/loader/elf.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
Labels: style

#2313 kernel/resource_limit: Remove the name member from resource limits
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/resource_limit.cpp
  src/core/hle/kernel/resource_limit.h
Labels: kernel-issue

#2270 kernel/svc: Implement svcGetProcessList and svcGetThreadList
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
  src/core/hle/kernel/thread.cpp
Labels: hle-new, kernel-issue

#2326 yuzu/applets/{profile_select, software_keyboard}: Use QDialogButtonBox standard buttons instead of custom ones where applicable
  src/yuzu/applets/profile_select.cpp
  src/yuzu/applets/software_keyboard.cpp
Labels: frontend-issue

#2314 kernel/thread: Minor interface cleanup
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/readable_event.cpp
  src/core/hle/kernel/readable_event.h
  src/core/hle/kernel/server_port.cpp
  src/core/hle/kernel/server_port.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/server_session.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/wait_object.h
Labels: style

#2305 kernel/shared_memory: Sanitize supplied size when unmapping
  src/core/hle/kernel/shared_memory.cpp
  src/core/hle/kernel/shared_memory.h
  src/core/hle/kernel/svc.cpp
Labels: kernel-issue

#2323 yuzu/debugger/profiler: Remove unnecessary includes
  src/yuzu/debugger/profiler.cpp
  src/yuzu/debugger/profiler.h
Labels: style

#2294 service/am: Implement EnterFatalSection/LeaveFatalSection
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: hle-new

#2324 kernel/object: Remove unused handle type entry
  src/core/hle/kernel/object.cpp
  src/core/hle/kernel/object.h
Labels: style

#2299 gl_shader_manager: Remove reliance on a global accessor within MaxwellUniformData::SetFromRegs()
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
Labels: style

#2093 Better LZ4 compression utilization for the disk based shader cache and the yuzu build system
  src/common/CMakeLists.txt
  src/common/lz4_compression.cpp
  src/common/lz4_compression.h
  src/core/CMakeLists.txt
  src/core/loader/nso.cpp
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
Labels: canary-merge, core-fix

#2095 frontend: Open transferable shader cache for a selected game in the gamelist
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: frontend-new

#2328 service/am: Correct behavior of CreateTransferMemoryStorage()
  src/core/hle/kernel/transfer_memory.cpp
  src/core/hle/kernel/transfer_memory.h
  src/core/hle/service/am/am.cpp
Labels: hle-fix

#2330 common/lz4_compression: Remove #pragma once directive from the cpp file
  src/common/lz4_compression.cpp
Labels: style

#2332 yuzu/main: Remove unnecessary includes
  src/yuzu/main.cpp
Labels: style

#2333 video_core/renderer_opengl: Remove unnecessary includes
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_primitive_assembler.cpp
  src/video_core/renderer_opengl/gl_primitive_assembler.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: style

#2331 yuzu/main: Minor adjustments to OnTransferableShaderCacheOpenFile()
  src/yuzu/main.cpp
Labels: style

#2336 gl_shader_decompiler: Fix TXQ types
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: gpu-fix

#2335 hle/service: Resolve unused variable warnings
  src/core/hle/service/am/am.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/sockets/sfdnsres.cpp
  src/core/hle/service/spl/module.cpp
  src/core/hle/service/ssl/ssl.cpp
  src/core/hle/service/vi/vi.cpp
Labels: style

#2292 file_sys/control_metadata: Amend naming of members
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
Labels: canary-merge, style

#2282 gpu_thread: Improve synchronization by using CoreTiming.
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
Labels: canary-merge, gpu, gpu-fix, gpu-new

#2338 filesystem: Use a std::string_view in OpenFile()
  src/core/hle/service/filesystem/filesystem.cpp
Labels: style

#2351 video_core/macro_interpreter: Simplify GetRegister()
  src/video_core/macro_interpreter.cpp
Labels: style

#2349 yuzu/debugger/graphics/graphics_surface: General cleanup
  src/yuzu/debugger/graphics/graphics_surface.cpp
Labels: frontend-issue, style

#2344 hle/result: Remove unnecessary bitfield entry for ResultCode
  src/core/hle/result.h
Labels: style

#2329 kernel/svc: Properly sanitize mutex address in WaitProcessWideKeyAtomic
  src/core/hle/kernel/svc.cpp
Labels: kernel-issue

#2337 gl_shader_decompiler: Rename GenerateTemporal() to GenerateTemporary()
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: style

#2343 file_sys/program_metadata: Remove obsolete TODOs
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
Labels: style

#2327 gl_shader_decompiler: Return early when an operation is invalid
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge

#2339 service/fsp_srv: Update SaveDataInfo and SaveDataDescriptor structs
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: style

#2341 file_sys/nca_metadata: Remove unnecessary comparison operators for TitleType
  src/core/file_sys/nca_metadata.cpp
  src/core/file_sys/nca_metadata.h
Labels: style

#2347 video_core/gpu_thread: Silence truncation warning in ThreadManager's constructor
  src/video_core/gpu_thread.cpp
Labels: style

#2334 core: Add missing override specifiers where applicable
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/arm/unicorn/arm_unicorn.h
  src/core/hle/service/audio/audin_u.cpp
  src/core/hle/service/audio/audrec_u.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
  src/core/hle/service/nvdrv/interface.h
  src/core/hle/service/nvdrv/nvmemp.h
  src/core/hle/service/service.h
  src/core/hle/service/set/set_cal.h
  src/core/hle/service/ssl/ssl.cpp
  src/core/hle/service/vi/vi.cpp
  src/core/loader/xci.h
Labels: style

#2340 file_sys/fsmitm_romfsbuild: Utilize a string_view in romfs_calc_path_hash
  src/core/file_sys/fsmitm_romfsbuild.cpp
Labels: style

#2350 video_core/memory_manager: Mark a few member functions with the const qualifier
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: style

#2346 video_core/engines: Remove unnecessary inclusions where applicable
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
Labels: style

#2240 Port citra-emu/citra#4651: "gdbstub: Fix some bugs in IsMemoryBreak() and ServeBreak. Add workaround to let watchpoints break into GDB."
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/arm/unicorn/arm_unicorn.h
  src/core/gdbstub/gdbstub.cpp
Labels: core-fix

#2342 common/multi_level_queue: Silence truncation warnings
  src/common/bit_util.h
  src/common/multi_level_queue.h
Labels: style

#2325 kernel/server_session: Provide a GetName() override
  src/core/hle/kernel/server_session.h
Labels: kernel-issue

#2317 Implement SyncPoint Register in the GPU.
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
Labels: gpu, gpu-new

#2352 memory_manager: Improved implementation of read/write/copy block.
  src/video_core/gpu.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: canary-merge, gpu-fix

#2362 core/memory: Remove unused enum constants
  src/core/memory.h
Labels: style

#2356 kernel/{server_port, server_session}: Return pairs instead of tuples from pair creation functions
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/client_port.cpp
  src/core/hle/kernel/server_port.cpp
  src/core/hle/kernel/server_port.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/server_session.h
Labels: style

#2321 gl_state: Rework to enable individual applies
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: canary-merge

#2361 core/memory: Minor simplifications to page table management
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/scheduler.cpp
  src/core/memory.cpp
  src/core/memory.h
  src/tests/core/arm/arm_test_common.cpp
Labels: style

#2306 shader_ir: Implement AOFFI for TEX and TLD4
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/shader/track.cpp
Labels: canary-merge, gpu-new

#2371 kernel/process: Set page table when page table resizes occur.
  src/core/hle/kernel/process.cpp
Labels: core-fix

#2368 Correct LOP_IMM encoding
  src/video_core/engines/shader_bytecode.h
Labels: gpu-fix

#2369 gl_backend: Align Pixel Storage
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: gpu-fix

#2370 yuzu/loading_screen: Resolve runtime Qt string formatting warnings
  src/yuzu/loading_screen.cpp
Labels: style

#2132 Port citra-emu/citra#4437: "citra-qt: Make hotkeys configurable via the GUI (Attempt 2)"
  src/yuzu/CMakeLists.txt
  src/yuzu/applets/profile_select.cpp
  src/yuzu/applets/profile_select.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure.ui
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_dialog.h
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.h
  src/yuzu/configuration/configure_general.ui
  src/yuzu/configuration/configure_hotkeys.cpp
  src/yuzu/configuration/configure_hotkeys.h
  src/yuzu/configuration/configure_hotkeys.ui
  src/yuzu/hotkeys.cpp
  src/yuzu/hotkeys.h
  src/yuzu/hotkeys.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/ui_settings.cpp
  src/yuzu/ui_settings.h
  src/yuzu/util/sequence_dialog/sequence_dialog.cpp
  src/yuzu/util/sequence_dialog/sequence_dialog.h
Labels: canary-merge, frontend-new

#2366 Correct XMAD mode, psl and high_b on different encodings.
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/xmad.cpp
Labels: gpu-fix

#1957 file_sys: Provide generic interface for accessing game data
  src/core/core.cpp
  src/core/core.h
  src/core/crypto/key_manager.cpp
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
  src/core/hle/service/am/applets/web_browser.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/loader/nso.cpp
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/game_list_worker.cpp
  src/yuzu/game_list_worker.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu_cmd/yuzu.cpp
Labels: canary-merge, core-new

#2354 video_core/texures/texture: Remove unnecessary includes
  src/video_core/dma_pusher.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/textures/convert.cpp
  src/video_core/textures/convert.h
  src/video_core/textures/texture.h
Labels: style

#2353 yuzu/debugger: Remove graphics surface viewer
  src/yuzu/CMakeLists.txt
  src/yuzu/debugger/graphics/graphics_surface.cpp
  src/yuzu/debugger/graphics/graphics_surface.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: frontend-issue

#2377 kernel/server_session: Remove obsolete TODOs
  src/core/hle/kernel/server_session.cpp
Labels: style

#2345 gl_rasterizer: Use ARB_multi_bind to update buffers with a single call per drawcall
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/utils.cpp
  src/video_core/renderer_opengl/utils.h
Labels: canary-merge, gpu, performance

#2278 video_core: Implement API agnostic view based texture cache
  src/video_core/CMakeLists.txt
  src/video_core/texture_cache.cpp
  src/video_core/texture_cache.h
Labels: canary-merge, gpu-new

#2388 kernel: Make handle type declarations constexpr
  src/core/hle/kernel/client_port.h
  src/core/hle/kernel/client_session.h
  src/core/hle/kernel/process.h
  src/core/hle/kernel/readable_event.h
  src/core/hle/kernel/resource_limit.h
  src/core/hle/kernel/server_port.h
  src/core/hle/kernel/server_session.h
  src/core/hle/kernel/shared_memory.h
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/writable_event.h
Labels: kernel-issue, style

#2360 kernel/svc: Deglobalize the supervisor call handlers
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/arm/unicorn/arm_unicorn.h
  src/core/core_cpu.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc.h
  src/core/hle/kernel/svc_wrap.h
Labels: style

#2392 common/swap: Minor cleanup and improvements to byte swapping functions
  src/common/swap.h
Labels: performance, style

#2391 common/scope_exit: Replace std::move with std::forward in ScopeExit()
  src/common/scope_exit.h
Labels: style

#2017 Frontend: Migrate to QOpenGLWindow and support shared contexts
  src/core/frontend/emu_window.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.h
Labels: frontend-new, gpu

#2386 gl_shader_manager: Move code to source file and minor clean up
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
Labels: style

#2381 fsp_srv: Minor cleanup related changes
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: style

#2357 Add a toggle to force 30FPS mode
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
Labels: canary-merge, gpu-new

#2378 ldr: Minor amendments to IPC-related parameters
  src/core/hle/service/ldr/ldr.cpp
Labels: hle-fix, style

#2398 kernel/thread: Remove BoostPriority()
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: kernel-issue, style

#2393 kernel/svc: Implement svcMapProcessCodeMemory/svcUnmapProcessCodeMemory
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
Labels: canary-merge, hle-new, kernel-issue

#2382 service: Update service function tables
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc_su.cpp
  src/core/hle/service/acc/acc_u0.cpp
  src/core/hle/service/acc/acc_u1.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applet_ae.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/apm/interface.cpp
  src/core/hle/service/audio/audin_u.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/btdrv/btdrv.cpp
  src/core/hle/service/caps/caps.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/ldn/ldn.cpp
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/npns/npns.cpp
  src/core/hle/service/pctl/module.cpp
  src/core/hle/service/pm/pm.cpp
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set_cal.cpp
  src/core/hle/service/set/set_sys.cpp
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/ssl/ssl.cpp
  src/core/hle/service/time/interface.cpp
Labels: hle-issue

#2401 common/{lz4_compression, zstd_compression}: Add missing header guards
  src/common/lz4_compression.h
  src/common/zstd_compression.h
Labels: style

#2376 yuzu/configure_hotkey: Minor changes
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_hotkeys.cpp
  src/yuzu/configuration/configure_hotkeys.h
Labels: frontend-fix

#2092 shader/memory: Implement STG and global memory flushing
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-new

#2405 CMakeLists: Define QT_USE_QSTRINGBUILDER for the Qt target
  src/yuzu/CMakeLists.txt
  src/yuzu/game_list_p.h
Labels: build-system

#2384 gl_rasterizer: Apply just the needed state on Clear
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: canary-merge, gpu, performance

#2348 Implement Bindless Textures on Shader Decompiler and GL backend
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-new

#2318 gl_sampler_cache: Port sampler cache to OpenGL
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_sampler_cache.cpp
  src/video_core/renderer_opengl/gl_sampler_cache.h
  src/video_core/renderer_vulkan/vk_sampler_cache.cpp
  src/video_core/renderer_vulkan/vk_sampler_cache.h
  src/video_core/sampler_cache.cpp
  src/video_core/sampler_cache.h
Labels: canary-merge, gpu, performance

#2397 kernel/thread: Remove unused guest_handle member variable
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.h
Labels: kernel-issue, style

#2374 core: Reorganize boot order
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/arm/unicorn/arm_unicorn.h
  src/core/core.cpp
  src/core/cpu_core_manager.cpp
  src/core/cpu_core_manager.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/deconstructed_rom_directory.h
  src/core/loader/elf.cpp
  src/core/loader/elf.h
  src/core/loader/loader.h
  src/core/loader/nax.cpp
  src/core/loader/nax.h
  src/core/loader/nca.cpp
  src/core/loader/nca.h
  src/core/loader/nro.cpp
  src/core/loader/nro.h
  src/core/loader/nso.cpp
  src/core/loader/nso.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
  src/core/memory.cpp
  src/core/memory.h
  src/video_core/gpu.h
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_asynch.h
  src/video_core/gpu_synch.cpp
  src/video_core/gpu_synch.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/video_core.cpp
  src/video_core/video_core.h
Labels: canary-merge, style

#2421 kernel/svc: Name supervisor call 0x36
  src/core/hle/kernel/svc.cpp
Labels: kernel-issue

#2414 yuzu/bootmanager: Resolve constructor initializer list warnings
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
Labels: style

#2415 kernel/wait_object: Make GetHighestPriorityReadyThread() a const member function
  src/core/hle/kernel/wait_object.cpp
  src/core/hle/kernel/wait_object.h
Labels: style

#2409 shader_ir/decode: Miscellaneous fixes to half-float decompilation
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/arithmetic_half.cpp
  src/video_core/shader/decode/arithmetic_half_immediate.cpp
  src/video_core/shader/decode/half_set.cpp
  src/video_core/shader/decode/half_set_predicate.cpp
  src/video_core/shader/decode/hfma2.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-fix, gpu-new

#2400 Implement Kepler Memory on both Linear and BlockLinear.
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
Labels: gpu-new

#2411 GPU Manager: Implement ReadBlockUnsafe and WriteBlockUnsafe
  src/video_core/dma_pusher.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
Labels: canary-merge

#2403 Support compressed formats on linear textures.
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: canary-merge

#2420 service/audctl: Implement GetTargetVolumeMin() and GetTargetVolumeMax()
  src/core/hle/service/audio/audctl.cpp
  src/core/hle/service/audio/audctl.h
Labels: hle-new

#2383 gl_shader_decompiler: Disable variable AOFFI on unsupported devices
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
Labels: canary-merge, gpu

#2425 Fix flipping on some games by applying Y direction register
  src/video_core/renderer_opengl/gl_shader_gen.cpp
Labels: gpu-fix

#2422 gl_state: Fix samplers memory corruption
  src/video_core/renderer_opengl/gl_state.cpp
Labels: gpu-fix

#2404 CMakeLists: Ensure we specify Unicode as the codepage on Windows
  src/CMakeLists.txt
  src/yuzu_cmd/yuzu.cpp
Labels: build-system

#2228 applets: Add AppletManager and implement PhotoViewer and Error applets
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.h
  src/core/frontend/applets/error.cpp
  src/core/frontend/applets/error.h
  src/core/frontend/applets/general_frontend.cpp
  src/core/frontend/applets/general_frontend.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/am/applets/error.cpp
  src/core/hle/service/am/applets/error.h
  src/core/hle/service/am/applets/general_backend.cpp
  src/core/hle/service/am/applets/general_backend.h
  src/core/hle/service/am/applets/profile_select.cpp
  src/core/hle/service/am/applets/profile_select.h
  src/core/hle/service/am/applets/software_keyboard.cpp
  src/core/hle/service/am/applets/software_keyboard.h
  src/core/hle/service/am/applets/stub_applet.h
  src/core/hle/service/am/applets/web_browser.cpp
  src/core/hle/service/am/applets/web_browser.h
  src/yuzu/CMakeLists.txt
  src/yuzu/applets/error.cpp
  src/yuzu/applets/error.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: canary-merge, frontend-new, hle-new

#2426 Port citra-emu/citra#4748: "Launch directly in Mac without terminal"
  .travis/macos/upload.sh
Labels: build-system

#2424 Allow picking a Compatibility Profile for OpenGL.
  src/core/settings.cpp
  src/core/settings.h
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu_cmd/config.cpp
Labels: canary-merge, frontend-new

#2416 kernel/svc: Clean up wait synchronization related functionality
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/wait_object.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: kernel-issue

#2423 Corrections on Half Float operations: HADD2 HMUL2 and HFMA2
  src/video_core/shader/decode/arithmetic_half.cpp
  src/video_core/shader/decode/hfma2.cpp
Labels: canary-merge, gpu-fix

#2322 video_core: Silent -Wswitch warnings
  src/video_core/dma_pusher.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/conversion.cpp
  src/video_core/shader/decode/xmad.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/surface.cpp
Labels: style

#2412 kernel/vm_manager: Remove usages of global system accessors
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
Labels: style

#2100 gl_shader_disk_cache: Improve precompiled shader cache generation speed and size
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
Labels: canary-merge, gpu-fix

#2406 Port citra-emu/citra#3839: "travis: use prebuilt image"
  .travis/linux-mingw/build.sh
  .travis/linux-mingw/deps.sh
  .travis/linux-mingw/docker.sh
  .travis/linux/build.sh
  .travis/linux/deps.sh
  .travis/linux/docker.sh
  CMakeModules/GenerateSCMRev.cmake
Labels: build-system, canary-merge
