Repository yuzu-emu/yuzu, pull requests merged in 2019-07, with the labels that each got.

#2659 rasterizer_cache: Protect inherited caches from submission level
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.cpp
Labels: canary-merge

#2604 Implemented INotificationService
  src/core/CMakeLists.txt
  src/core/hle/service/friend/errors.h
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/friend/friend.h
  src/core/hle/service/friend/interface.cpp
Labels: canary-merge, hle-new

#2563 gl_shader_cache: Use static constructors for CachedShader initialization
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
Labels: gpu, style

#2608 Implement Time::GetSharedMemoryNativeHandle
  src/core/CMakeLists.txt
  src/core/hle/service/service.cpp
  src/core/hle/service/time/interface.cpp
  src/core/hle/service/time/interface.h
  src/core/hle/service/time/time.cpp
  src/core/hle/service/time/time.h
  src/core/hle/service/time/time_sharedmemory.cpp
  src/core/hle/service/time/time_sharedmemory.h
Labels: canary-merge, hle-new

#2613 Implemented InitializeApplicationInfo & InitializeApplicationInfoRestricted
  src/core/CMakeLists.txt
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/acc_u0.cpp
  src/core/hle/service/acc/errors.h
Labels: canary-merge, hle-new

#2638 set: Implement GetQuestFlag with config option
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set.h
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: hle-new

#2658 IAudioDevice::QueryAudioDeviceOutputEvent
  src/core/hle/service/audio/audren_u.cpp
Labels: canary-merge

#2670 gl_shader_cache: Make CachedShader constructor private
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
Labels: gpu-fix

#2555 kernel/process: Decouple TLS handling from threads
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
Labels: kernel-issue

#2677 kernel/vm_manager: Handle stack/TLS IO region placement a little better
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
  src/core/memory.cpp
  src/core/memory.h
Labels: core-fix

#2674 core/reporter: Minor changes
  src/core/reporter.cpp
  src/core/reporter.h
Labels: style

#2642 fsp-srv: Implement Access Logging Functionality
  src/core/core.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/reporter.cpp
  src/core/reporter.h
Labels: canary-merge, hle-new

#2651 apm: Initial implementation of performance config and boost mode
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/applet_ae.cpp
  src/core/hle/service/am/applet_oe.cpp
  src/core/hle/service/apm/apm.cpp
  src/core/hle/service/apm/apm.h
  src/core/hle/service/apm/controller.cpp
  src/core/hle/service/apm/controller.h
  src/core/hle/service/apm/interface.cpp
  src/core/hle/service/apm/interface.h
  src/core/hle/service/service.cpp
Labels: canary-merge, hle-new

#2657 hid:StartLrAssignmentMode, hid:StopLrAssignmentMode, hid:SwapNpadAssignment
  src/core/CMakeLists.txt
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/errors.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: canary-merge, hle-new

#2661 audren: Only manage wave buffers with a size
  src/audio_core/audio_renderer.cpp
Labels: audio-fix, canary-merge

#2706 Add Pipeline Definitions for Azure CI
  .ci/scripts/.gitkeep
  .ci/yuzu-mainline.yml
  .ci/yuzu-patreon.yml
  .ci/yuzu.yml
Labels: build-system

#2691 video_core: Add missing override specifiers
  src/video_core/renderer_opengl/gl_sampler_cache.h
  src/video_core/renderer_vulkan/vk_sampler_cache.h
Labels: style

#2650 mii: Implement IDatabaseService SetInterfaceVersion
  src/core/hle/service/mii/mii.cpp
Labels: canary-merge, hle-new

#2611 pm: Implement various pm commands for finding process and title IDs
  src/core/hle/service/pm/pm.cpp
  src/core/hle/service/pm/pm.h
  src/core/hle/service/service.cpp
Labels: hle-new

#2700 IFriendService::GetFriendList
  src/core/hle/service/friend/friend.cpp
Labels: hle-new

#2686 vk_scheduler: Drop execution context in favor of views
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.h
Labels: gpu-fix

#2697 gl_rasterizer: Amend documentation comment for ConfigureFramebuffers()
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: style

#2714 Add Repository Sync Pipeline
  .ci/yuzu-repo-sync.yml
Labels: build-system

#2724 service/am: Implement SetAutoSleepDisabled/IsAutoSleepDisabled
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: hle-new

#2723 core/arm: Remove obsolete Unicorn memory mapping
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/arm/unicorn/arm_unicorn.h
  src/core/core_cpu.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/settings.cpp
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
  src/yuzu_tester/config.cpp
  src/yuzu_tester/default_ini.h
Labels: cpu-fix

#2717 Restore memory perms on svcUnmapMemory/UnloadNro
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/ldr/ldr.cpp
Labels: hle-fix, kernel-fix

#2609 Implement a New Shader Scanner, Decompile Flow Stack and implement BRX BRA.CC
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/control_flow.h
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/node.h
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-new

#2692 shader/texture: Add F16 support for TLDS
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/texture.cpp
Labels: canary-merge, gpu-new

#2690 Implement MapPhysicalMemory/UnmapPhysicalMemory
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
  src/video_core/gpu.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: canary-merge, kernel-new

#2675 buffer_cache: Implement a generic buffer cache and its OpenGL backend
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache.h
  src/video_core/engines/maxwell_3d.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/utils.cpp
  src/video_core/renderer_opengl/utils.h
Labels: canary-merge, gpu-new

#2705 GPU: Fixes to Texture Cache and Include Microprofiles for GL State/BufferCopy/Macro Interpreter
  src/video_core/macro_interpreter.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/texture_cache/surface_base.cpp
  src/video_core/texture_cache/surface_base.h
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: gpu-fix

#2695 gl_shader_decompiler: Implement gl_ViewportIndex and gl_Layer in vertex shaders
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-new

#2565 shader/track: Track indirect buffers
  src/video_core/shader/decode/image.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/shader/track.cpp
Labels: gpu-fix

#2726 core: Remove CurrentArmInterface() global accessor
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/core.h
Labels: core-fix

#2740 shader/decode/other: Correct branch indirect argument within BRA handling
  src/video_core/shader/decode/other.cpp
Labels: gpu-fix

#2738 shader-ir: Minor cleanup-related changes
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/decode/xmad.cpp
  src/video_core/shader/node_helper.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/shader/track.cpp
Labels: canary-merge, style

#2687 kernel/process: Allocate the process' TLS region during initialization
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
Labels: canary-merge, kernel-fix

#2752 azure: Fix clang-format and releases
  .ci/templates/build-standard.yml
  .ci/templates/build-testing.yml
  .ci/templates/release.yml
Labels: build-system-new

#2693 shader/half_set_predicate: Implement missing HSETP2 variants
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/half_set_predicate.cpp
  src/video_core/shader/node.h
Labels: canary-merge, gpu-new

#2735 Rework Dirty Flags in GPU Pipeline, Optimize CBData and Redo Clearing mechanism
  src/video_core/dma_pusher.cpp
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: canary-merge, gpu-new, performance

#2734 gl_rasterizer: Implement compute shaders
  src/video_core/engines/kepler_compute.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_opengl/gl_shader_util.cpp
Labels: canary-merge, gpu-new

#2754 Fix README change mistake
  .ci/templates/build-single.yml
  .ci/templates/build-testing.yml
  README.md
Labels: build-system-fix

#2704 maxwell3d: Implement Conditional Rendering
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: canary-merge, gpu-new

#2743 Downgrade and suppress a series of GPU asserts and debug messages.
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/shader/decode/arithmetic.cpp
  src/video_core/shader/decode/arithmetic_half_immediate.cpp
  src/video_core/shader/decode/ffma.cpp
  src/video_core/shader/decode/half_set_predicate.cpp
  src/video_core/shader/decode/hfma2.cpp
Labels: style

#2689 yuzu/main: Make error messages within OnCoreError more localization-friendly
  src/yuzu/main.cpp
Labels: frontend-fix

#2737 Shader_Ir: Correct tracking to track from right to left
  src/video_core/shader/track.cpp
Labels: canary-merge, gpu-fix

#2739 video_core/control_flow: Minor changes/warning cleanup
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/control_flow.h
  src/video_core/shader/decode.cpp
  src/video_core/texture_cache/surface_base.cpp
Labels: style

#2592 Implement GPU Synchronization Mechanisms & Correct NVFlinger
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.h
  src/core/hardware_interrupt_manager.cpp
  src/core/hardware_interrupt_manager.h
  src/core/hle/service/nvdrv/devices/nvdevice.h
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.h
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/core/hle/service/nvdrv/devices/nvhost_vic.h
  src/core/hle/service/nvdrv/devices/nvmap.cpp
  src/core/hle/service/nvdrv/devices/nvmap.h
  src/core/hle/service/nvdrv/interface.cpp
  src/core/hle/service/nvdrv/interface.h
  src/core/hle/service/nvdrv/nvdata.h
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/core/hle/service/nvdrv/nvdrv.h
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/service.cpp
  src/core/hle/service/vi/vi.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_asynch.h
  src/video_core/gpu_synch.cpp
  src/video_core/gpu_synch.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
Labels: canary-merge, gpu-fix, gpu-new
