Repository yuzu-emu/yuzu, pull requests merged in 2019-05, with the labels that each got.

#2408 Port citra-emu/citra#4215: "travis: Use Ninja for Travis builds"
  .travis/linux-mingw/docker.sh
  .travis/linux/docker.sh
  .travis/macos/build.sh
Labels: build-system, canary-merge

#2449 gl_rasterizer: Silence unused variable warnings
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/shader/decode/texture.cpp
Labels: style

#2448 common/zstd_compression: Remove #pragma once directive from source file
  src/common/zstd_compression.cpp
Labels: style

#2447 core/frontend/emu_window: Make GraphicsContext's destructor virtual
  src/core/frontend/emu_window.cpp
  src/core/frontend/emu_window.h
Labels: core-fix

#2451 travis: Update to using Xcode 10.2
  .travis.yml
Labels: build-system

#2429 Corrections and Implementation on GPU Engines
  src/video_core/CMakeLists.txt
  src/video_core/engines/engine_upload.cpp
  src/video_core/engines/engine_upload.h
  src/video_core/engines/fermi_2d.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/gpu.cpp
Labels: canary-merge

#2453 core/memory: Remove unused FlushMode enum
  src/core/memory.h
Labels: style

#2459 configure_dialog: Remove the Whats This? button from the dialog
  src/yuzu/configuration/configure_dialog.cpp
Labels: frontend-issue

#2456 yuzu/compatdb: Remove unnecessary qualifiers
  src/yuzu/compatdb.cpp
Labels: style

#2458 yuzu/hotkeys: Remove unnecessary constructor
  src/yuzu/hotkeys.h
Labels: style

#2445 Port citra-emu/citra#4749: "web_service: Misc fixes"
  src/core/telemetry_session.cpp
  src/core/telemetry_session.h
Labels: core-fix

#2443 gl_shader_disk_cache: Skip stored shader variants instead of asserting
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
Labels: canary-merge

#2442 Fix Layered ASTC Textures
  src/video_core/textures/astc.cpp
Labels: canary-merge, gpu-fix

#2454 src/CMakeLists: Add /Zc:externConstexpr to the MSVC build flags
  src/CMakeLists.txt
Labels: build-system

#2437 service/audctl: Update documentation comments to be relative to 8.0.0
  src/core/hle/service/audio/audctl.cpp
Labels: hle-issue

#2413 Rasterizer Cache: refactor flushing & optimize memory usage of surfaces
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_global_cache.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache.h
Labels: canary-merge, gpu

#2450 CMakeLists: Explicitly specify -Wall for the non-MSVC case
  src/CMakeLists.txt
Labels: build-system

#2460 CMakeLists: Specify /volatile:iso for MSVC
  src/CMakeLists.txt
Labels: build-system

#2461 video_core: Remove a few unused variables and functions
  src/video_core/gpu_thread.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/textures/astc.cpp
Labels: style

#2462 video_core/memory_manager: Minor tidying
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: style

#2477 yuzu_cmd: Make OpenGL's context current
  src/yuzu_cmd/yuzu.cpp
Labels: canary-merge, gpu-fix

#2457 yuzu/{about_dialog, main}: Specify string conversions explicitly for SCM-related info
  src/yuzu/about_dialog.cpp
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: frontend-issue, style

#2498 yuzu/util: Remove unused spinbox.cpp/.h
  src/yuzu/CMakeLists.txt
  src/yuzu/util/spinbox.cpp
  src/yuzu/util/spinbox.h
Labels: frontend-issue, style

#2476 yuzu/bootmanager: Explicitly enable deprecated OpenGL features on compat
  src/yuzu/bootmanager.cpp
Labels: canary-merge, gpu-fix

#2473 CMakeLists: Handle VS 2019 in a less annoying manner
  CMakeLists.txt
Labels: build-system

#2496 gl_shader_gen: std::move objects where applicable
  src/video_core/renderer_opengl/gl_shader_gen.cpp
Labels: gpu, style

#2493 yuzu/applets/profile_select: Mark header string as translatable
  src/yuzu/applets/profile_select.cpp
Labels: frontend-issue

#2488 kernel/svc: Mark GetThreadList() and UnmapProcessCodeMemory() as internally linked
  src/core/hle/kernel/svc.cpp
Labels: kernel-issue, style

#2486 core/kernel/object: Rename ResetType enum members for clarity
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/object.h
  src/core/hle/kernel/readable_event.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/btdrv/btdrv.cpp
  src/core/hle/service/btm/btm.cpp
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/nvdrv/interface.cpp
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/vi/display/vi_display.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: kernel-issue, style

#2492 yuzu/debugger: Specify string conversions explicitly
  src/yuzu/debugger/graphics/graphics_breakpoints.cpp
  src/yuzu/debugger/profiler.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: frontend-issue, style

#2490 ipc_helpers: Amend floating-point type in Pop<double> specialization
  src/core/hle/ipc_helpers.h
Labels: bug

#2484 maxwell_to_gl: Add TriangleFan primitive topology
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: gpu-new

#2471 video_core/engines/engine_upload: Minor tidying
  src/video_core/engines/engine_upload.cpp
  src/video_core/engines/engine_upload.h
Labels: gpu, style

#2483 gl_rasterizer: Limit OpenGL point size to a minimum of 1
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: gpu-fix

#2480 gl_rasterizer: Pass the right number of array quad vertices count
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: gpu-fix

#2487 service/am: Add missing return in error case for IStorageAccessor's Read/Write()
  src/core/hle/service/am/am.cpp
Labels: hle-fix, hle-issue

#2470 video_core/engines/maxwell_3d: Simplify for loops into ranged for loops within InitializeRegisterDefaults()
  src/video_core/engines/maxwell_3d.cpp
Labels: gpu, style

#2469 video_core/engines/maxwell_3d: Add is_trivially_copyable_v check for Regs
  src/video_core/engines/maxwell_3d.h
Labels: gpu

#2472 maxwell_3d: reduce severity of different component formats assert.
  src/video_core/engines/maxwell_3d.cpp
Labels: canary-merge

#2468 yuzu: Remove explicit types from locks where applicable
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/yuzu/applets/error.cpp
Labels: style

#2466 GPU/MMEInterpreter: Ignore the 'exit' flag when it's executed inside a delay slot.
  src/video_core/macro_interpreter.cpp
Labels: gpu-fix, gpu-issue

#2463 service/set: Correct and simplify behavior related to copying language codes
  src/core/hle/service/set/set.cpp
Labels: hle-fix

#2467 video_core/gpu_thread: Remove redundant copy constructor for CommandDataContainer
  src/video_core/gpu_thread.h
Labels: style

#2439 service/audren_u: Get rid of magic values within GetAudioRendererWorkBufferSize
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/audren_u.h
Labels: canary-merge, hle-issue, hle-new

#2495 gl_shader_disk_cache: Minor cleanup
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
Labels: gpu, style

#2497 shader/shader_ir: Minor changes
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/shader/track.cpp
Labels: gpu, style

#2452 Correct possible error on Rasterizer Caches
  src/video_core/rasterizer_cache.h
Labels: gpu-fix

#2410 kernel/svc: Reorganize and fix up the initial handling of svcSetThreadCoreMask()
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.h
Labels: kernel-issue

#2441 shader: Implement AL2P and ALD.PHYS
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-new

#2499 yuzu/configuration: Specify string conversions explicitly
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_gamelist.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_mouse_advanced.cpp
  src/yuzu/configuration/configure_per_general.cpp
  src/yuzu/configuration/configure_profile_manager.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_web.cpp
Labels: frontend-issue, style

#2494 gl_shader_decompiler: Add AddLine() overloads with single function that forwards to libfmt
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: gpu, style

#2503 yuzu/game_list: Specify string conversions explicitly
  src/yuzu/bootmanager.cpp
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/game_list_p.h
  src/yuzu/game_list_worker.cpp
  src/yuzu/loading_screen.cpp
  src/yuzu/util/util.cpp
Labels: frontend-issue, style

#2455 configuration/config: Move config loading and saving to functions based off groups
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
Labels: style

#2508 shader/shader_ir: Make Comment() take a std::string by value
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: style

#2505 externals: Update glad to support OpenGL 4.6 compatibility profile
  externals/glad/include/KHR/khrplatform.h
  externals/glad/include/glad/glad.h
  externals/glad/src/glad.c
Labels: externals

#2489 Port citra-emu/citra#4716: "HLE/IPC: HLEContext can memorize the client thread and use it for SleepClientThread"
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/service/vi/vi.cpp
Labels: canary-merge, hle-fix

#2504 yuzu/configuration/config: Specify string conversions explicitly
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
Labels: frontend-issue, style

#2485 shader/memory: Implement generic memory stores and loads (ST and LD)
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-new

#2358 gl_shader_cache: Use shared contexts to build shaders in parallel at boot
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/yuzu/bootmanager.cpp
Labels: canary-merge, gpu-new

#2513 yuzu/main: Specify string conversions explicitly
  src/yuzu/CMakeLists.txt
  src/yuzu/applets/error.cpp
  src/yuzu/applets/software_keyboard.cpp
  src/yuzu/applets/software_keyboard.h
  src/yuzu/main.cpp
Labels: frontend-issue, style

#2517 configure_hotkeys: Minor cleanup
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_hotkeys.cpp
  src/yuzu/configuration/configure_hotkeys.h
  src/yuzu/util/sequence_dialog/sequence_dialog.cpp
Labels: frontend-issue, style

#2511 common/file_util: Minor cleanup
  src/common/file_util.cpp
  src/common/file_util.h
  src/yuzu_cmd/config.cpp
Labels: style

#2509 service/aoc_u: Minor cleanup
  src/core/hle/service/aoc/aoc_u.cpp
Labels: style

#2516 renderer_opengl/utils: Use a std::string_view with LabelGLObject()
  src/video_core/renderer_opengl/utils.cpp
  src/video_core/renderer_opengl/utils.h
Labels: style

#2524 gl_shader_gen: Always declare extensions after the version declaration
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
Labels: canary-merge, gpu-fix

#2519 loader/nso, core/core_timing_util: Silence sign-comparison warning
  src/core/core_timing_util.cpp
  src/core/loader/nso.cpp
Labels: style

#2446 shader: Implement S2R Tid{XYZ} and CtaId{XYZ}
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-new

#2431 yuzu: Implement a caching mechanism for the game list
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_per_general.cpp
  src/yuzu/game_list_worker.cpp
  src/yuzu/main.cpp
  src/yuzu/ui_settings.h
Labels: canary-merge, frontend-new

#1931 mii: Implement MiiManager backend and several mii service commands
  src/common/CMakeLists.txt
  src/common/uuid.cpp
  src/common/uuid.h
  src/core/CMakeLists.txt
  src/core/frontend/applets/profile_select.cpp
  src/core/frontend/applets/profile_select.h
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
  src/core/hle/service/am/applets/profile_select.cpp
  src/core/hle/service/am/applets/profile_select.h
  src/core/hle/service/mii/mii.cpp
  src/core/hle/service/mii/mii_manager.cpp
  src/core/hle/service/mii/mii_manager.h
  src/yuzu/applets/profile_select.cpp
  src/yuzu/applets/profile_select.h
  src/yuzu/configuration/configure_profile_manager.cpp
  src/yuzu/main.h
Labels: canary-merge, hle-new

#2530 common/math_util: Provide a template deduction guide for Common::Rectangle
  src/common/math_util.h
Labels: style

#2528 input_common/sdl/sdl_impl: Silence sign conversion warnings
  src/input_common/sdl/sdl_impl.cpp
Labels: style
