Repository yuzu-emu/yuzu, pull requests merged in 2019-08, with the labels that each got.

#2770 ci: Fix Azure PR Builds
  .ci/templates/build-single.yml
  .ci/templates/build-standard.yml
  .ci/templates/build-testing.yml
  .ci/yuzu-mainline.yml
  .ci/yuzu-verify.yml
Labels: build-system-fix

#2772 yuzu/CMakeLists: Remove qt5_wrap_ui macro usage
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_gamelist.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_input_simple.cpp
  src/yuzu/configuration/configure_per_general.cpp
  src/yuzu/configuration/configure_web.cpp
  src/yuzu/debugger/console.cpp
  src/yuzu/game_list.cpp
  src/yuzu/game_list_p.h
  src/yuzu/game_list_worker.cpp
  src/yuzu/hotkeys.cpp
  src/yuzu/main.cpp
  src/yuzu/uisettings.cpp
  src/yuzu/uisettings.h
Labels: build-system-new

#2766 Port citra-emu/citra#4849: "Qt: Fixed behaviour of buttons by connecting functors to correct signals"
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_simple.cpp
  src/yuzu/configuration/configure_mouse_advanced.cpp
  src/yuzu/configuration/configure_profile_manager.cpp
  src/yuzu/configuration/configure_touchscreen_advanced.cpp
Labels: frontend-fix

#2768 decode/half_set_predicate: Fix predicates
  src/video_core/shader/decode/half_set_predicate.cpp
Labels: canary-merge, gpu-fix

#2778 shader_ir: Implement NOP
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/other.cpp
Labels: canary-merge, gpu-new

#2747 service/audren_u: Unstub ListAudioDeviceName
  src/core/hle/service/audio/audio.cpp
  src/core/hle/service/audio/audio.h
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audout_u.h
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/audren_u.h
  src/core/hle/service/service.cpp
Labels: canary-merge, hle-fix

#2773 yuzu-tester/yuzu: Remove unused variable
  src/yuzu_tester/yuzu.cpp
Labels: style

#2753 Shader_Ir: Implement F16 Variants of F2F, F2I, I2F.
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/conversion.cpp
  src/video_core/shader/node.h
Labels: canary-merge, gpu-new

#2777 half_set_predicate: Fix HSETP2_C constant buffer offset
  src/video_core/shader/decode/half_set_predicate.cpp
Labels: canary-merge, gpu-fix

#2786 shader_ir: Implement VOTE on Nvidia drivers
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/warp.cpp
  src/video_core/shader/node.h
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-new

#2758 shader/decode: Implement S2R Tic
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-new

#2783 Implement a New LLE Buffer Cache
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache.h
  src/video_core/buffer_cache/buffer_block.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/map_interval.h
  src/video_core/gpu.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: canary-merge, gpu-new

#2742 gl_texture_cache: Miscellaneous texture buffer fixes
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/textures/texture.h
Labels: gpu-fix

#2820 video_core: Silent miscellaneous warnings
  src/video_core/buffer_cache/buffer_block.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/shader/decode/float_set.cpp
  src/video_core/shader/decode/float_set_predicate.cpp
  src/video_core/shader/decode/integer_set.cpp
  src/video_core/shader/decode/integer_set_predicate.cpp
  src/video_core/shader/decode/predicate_set_register.cpp
  src/video_core/texture_cache/surface_params.h
  src/video_core/texture_cache/texture_cache.h
Labels: canary-merge, style
