Repository yuzu-emu/yuzu, pull requests merged in 2019-06, with the labels that each got.

#2525 yuzu: Remove unused birthday setting
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_system.ui
Labels: frontend-issue

#2529 yuzu/bootmanager: Minor interface tidying
  src/core/frontend/framebuffer_layout.cpp
  src/core/frontend/framebuffer_layout.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
Labels: frontend-issue

#2536 game_list_worker: Use QFile over our own IOFile instance or std streams for the game list cache
  src/yuzu/game_list_worker.cpp
Labels: frontend-issue

#2515 yuzu/configuration/configure_graphics: Eliminate type narrowing in a connect call
  src/yuzu/configuration/configure_graphics.cpp
Labels: frontend-issue

#2534 gl_shader_cache: Minor style changes
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
Labels: style

#2527 yuzu/{profile_select, software_keyboard}: Tidy up interface
  src/yuzu/applets/profile_select.cpp
  src/yuzu/applets/profile_select.h
  src/yuzu/applets/software_keyboard.cpp
  src/yuzu/applets/software_keyboard.h
  src/yuzu/main.cpp
Labels: frontend-issue

#2510 Implement/Fix IApplicationFunctions::GetDesiredLanguage
  src/core/CMakeLists.txt
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/ns/errors.h
  src/core/hle/service/ns/language.cpp
  src/core/hle/service/ns/language.h
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/ns.h
  src/core/hle/service/ns/ns_language.h
Labels: canary-merge, hle-fix

#2541 input_common/sdl/sdl_impl: Minor cleanup
  src/input_common/sdl/sdl.h
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/sdl/sdl_impl.h
Labels: bug, style

#2526 core/telemetry_session: Remove usages of the global system accessor
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/loader/loader.h
  src/core/telemetry_session.cpp
  src/core/telemetry_session.h
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: core-fix

#2512 gl_shader_decompiler: Pessimize uniform buffer access on AMD's prorpietary driver
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge, gpu

#2521 yuzu/configuration: Make function naming consistent
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_audio.h
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.h
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_dialog.h
  src/yuzu/configuration/configure_gamelist.cpp
  src/yuzu/configuration/configure_gamelist.h
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.h
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_hotkeys.cpp
  src/yuzu/configuration/configure_hotkeys.h
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input.h
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_input_simple.cpp
  src/yuzu/configuration/configure_input_simple.h
  src/yuzu/configuration/configure_mouse_advanced.cpp
  src/yuzu/configuration/configure_mouse_advanced.h
  src/yuzu/configuration/configure_per_general.cpp
  src/yuzu/configuration/configure_per_general.h
  src/yuzu/configuration/configure_profile_manager.cpp
  src/yuzu/configuration/configure_profile_manager.h
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_touchscreen_advanced.cpp
  src/yuzu/configuration/configure_touchscreen_advanced.h
  src/yuzu/configuration/configure_web.cpp
  src/yuzu/configuration/configure_web.h
  src/yuzu/main.cpp
Labels: style

#2419 lr: Add command handler skeletons for Open*LocationResolver
  src/core/hle/service/ncm/ncm.cpp
Labels: hle-new

#2540 gl_shader_decompiler: Remove guest "position" varying
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
Labels: gpu

#2550 yuzu/CMakeLists: Pass compilation flags that make it more difficult to cause bugs in Qt code
  src/yuzu/CMakeLists.txt
Labels: build-system

#2552 shader: Use shared_ptr to store nodes and move initialization to file
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/arithmetic.cpp
  src/video_core/shader/decode/arithmetic_half.cpp
  src/video_core/shader/decode/arithmetic_half_immediate.cpp
  src/video_core/shader/decode/arithmetic_immediate.cpp
  src/video_core/shader/decode/arithmetic_integer.cpp
  src/video_core/shader/decode/arithmetic_integer_immediate.cpp
  src/video_core/shader/decode/bfe.cpp
  src/video_core/shader/decode/bfi.cpp
  src/video_core/shader/decode/conversion.cpp
  src/video_core/shader/decode/ffma.cpp
  src/video_core/shader/decode/float_set.cpp
  src/video_core/shader/decode/float_set_predicate.cpp
  src/video_core/shader/decode/half_set.cpp
  src/video_core/shader/decode/half_set_predicate.cpp
  src/video_core/shader/decode/hfma2.cpp
  src/video_core/shader/decode/integer_set.cpp
  src/video_core/shader/decode/integer_set_predicate.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/decode/predicate_set_predicate.cpp
  src/video_core/shader/decode/predicate_set_register.cpp
  src/video_core/shader/decode/register_set_predicate.cpp
  src/video_core/shader/decode/shift.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/decode/video.cpp
  src/video_core/shader/decode/xmad.cpp
  src/video_core/shader/node_helper.cpp
  src/video_core/shader/node_helper.h
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/shader/track.cpp
Labels: gpu

#2558 shader: Move Node declarations out of the shader IR header
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/shader/node.h
  src/video_core/shader/node_helper.h
  src/video_core/shader/shader_ir.h
Labels: gpu

#2514 video_core: Drop OpenGL core in favor of OpenGL compatibility
  src/core/settings.cpp
  src/core/settings.h
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_primitive_assembler.cpp
  src/video_core/renderer_opengl/gl_primitive_assembler.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/textures/texture.h
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
Labels: canary-merge

#2293 core: Remove duplicated account JPEG data structure
  src/core/CMakeLists.txt
  src/core/constants.cpp
  src/core/constants.h
  src/core/hle/service/acc/acc.cpp
  src/yuzu/applets/profile_select.cpp
Labels: hle-fix

#2553 yuzu/configuration: Make all widgets and dialogs aware of language changes
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_audio.h
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.h
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_dialog.h
  src/yuzu/configuration/configure_gamelist.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.h
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_hotkeys.cpp
  src/yuzu/configuration/configure_hotkeys.h
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input.h
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_input_simple.cpp
  src/yuzu/configuration/configure_input_simple.h
  src/yuzu/configuration/configure_mouse_advanced.cpp
  src/yuzu/configuration/configure_mouse_advanced.h
  src/yuzu/configuration/configure_per_general.cpp
  src/yuzu/configuration/configure_per_general.h
  src/yuzu/configuration/configure_profile_manager.cpp
  src/yuzu/configuration/configure_profile_manager.h
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_touchscreen_advanced.cpp
  src/yuzu/configuration/configure_touchscreen_advanced.h
  src/yuzu/configuration/configure_web.cpp
  src/yuzu/configuration/configure_web.h
Labels: frontend-issue

#2564 kepler_compute: Minor changes
  src/video_core/engines/kepler_compute.h
Labels: gpu-fix, style

#2570 kernel/svc: Handle TotalPhysicalMemoryAvailableWithoutMmHeap and TotalPhysicalMemoryUsedWithoutMmHeap
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
Labels: kernel-issue

#2571 kernel/process: Make Create()'s name parameter be taken by value
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
Labels: kernel-issue

#2577 file_sys/card_image: Minor cleanup
  src/core/file_sys/card_image.cpp
Labels: style

#2580 kernel/vm_manager: Remove redundant Reset call in destructor
  src/core/hle/kernel/vm_manager.cpp
Labels: kernel-issue

#2538 shader: Split SSY and PBK stack
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/node.h
Labels: canary-merge, gpu-fix

#2562 video_core/engines: Move ConstBufferInfo out of Maxwell3D
  src/video_core/CMakeLists.txt
  src/video_core/engines/const_buffer_info.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: gpu

#2474 CMake: Get Git submodule dependencies via CMake
  .travis/linux-mingw/build.sh
  CMakeLists.txt
Labels: build-system

#2590 service/audio/audren_u: Correct event reset type for the system event
  src/core/hle/service/audio/audren_u.cpp
Labels: hle-fix

#2596 Revert PR 2590.
  src/core/hle/service/audio/audren_u.cpp
Labels: canary-merge, regression

#2291 yuzu_tester: Add and implement testing utility for homebrew
  src/CMakeLists.txt
  src/yuzu_tester/CMakeLists.txt
  src/yuzu_tester/config.cpp
  src/yuzu_tester/config.h
  src/yuzu_tester/default_ini.h
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.cpp
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
  src/yuzu_tester/resource.h
  src/yuzu_tester/service/yuzutest.cpp
  src/yuzu_tester/service/yuzutest.h
  src/yuzu_tester/yuzu.cpp
  src/yuzu_tester/yuzu.rc
Labels: frontend-new, hle-new

#2482 core: Add detailed local reporting feature for development
  src/core/CMakeLists.txt
  src/core/arm/arm_interface.cpp
  src/core/arm/arm_interface.h
  src/core/core.cpp
  src/core/core.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/am/applets/error.cpp
  src/core/hle/service/am/applets/general_backend.cpp
  src/core/hle/service/am/applets/general_backend.h
  src/core/hle/service/fatal/fatal.cpp
  src/core/hle/service/prepo/prepo.cpp
  src/core/hle/service/service.cpp
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/deconstructed_rom_directory.h
  src/core/loader/loader.h
  src/core/loader/nax.cpp
  src/core/loader/nax.h
  src/core/loader/nca.cpp
  src/core/loader/nca.h
  src/core/loader/nso.cpp
  src/core/loader/nso.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
  src/core/reporter.cpp
  src/core/reporter.h
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
  src/yuzu_cmd/config.cpp
Labels: core-new, hle-new

#2546 loader, file_sys: Add support for parsing and loading KIP (Kernel Internal Process) files
  src/core/CMakeLists.txt
  src/core/crypto/partition_data_manager.cpp
  src/core/file_sys/kernel_executable.cpp
  src/core/file_sys/kernel_executable.h
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
  src/core/loader/kip.cpp
  src/core/loader/kip.h
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/yuzu/game_list.cpp
Labels: canary-merge, core-new

#2575 kernel: Differentiate kernel and user processes when picking ID
  src/core/core.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/tests/core/arm/arm_test_common.cpp
Labels: hle-new

#2602 service/acc: Silence truncation warnings
  src/core/hle/service/acc/acc.cpp
Labels: style

#2579 gl_device: Fix TestVariableAoffi test
  src/video_core/renderer_opengl/gl_device.cpp
Labels: gpu-fix

#2607 glue: Implement arp:w and arp:r services
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/hle/service/arp/arp.cpp
  src/core/hle/service/arp/arp.h
  src/core/hle/service/glue/arp.cpp
  src/core/hle/service/glue/arp.h
  src/core/hle/service/glue/bgtc.cpp
  src/core/hle/service/glue/bgtc.h
  src/core/hle/service/glue/errors.h
  src/core/hle/service/glue/glue.cpp
  src/core/hle/service/glue/glue.h
  src/core/hle/service/glue/manager.cpp
  src/core/hle/service/glue/manager.h
  src/core/hle/service/service.cpp
Labels: hle-new

#2548 applets: Implement backend and default frontend for Parental Controls and EShop (ShopN) applets
  src/core/frontend/applets/general_frontend.cpp
  src/core/frontend/applets/general_frontend.h
  src/core/frontend/applets/web_browser.cpp
  src/core/frontend/applets/web_browser.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/applet_ae.cpp
  src/core/hle/service/am/applet_ae.h
  src/core/hle/service/am/applet_oe.cpp
  src/core/hle/service/am/applet_oe.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/am/applets/general_backend.cpp
  src/core/hle/service/am/applets/general_backend.h
  src/core/hle/service/am/applets/web_browser.cpp
  src/core/hle/service/am/applets/web_browser.h
  src/core/hle/service/service.cpp
  src/yuzu/applets/web_browser.cpp
  src/yuzu/applets/web_browser.h
  src/yuzu/main.cpp
Labels: frontend-new, hle-new

#2533 memory: Add class to manage and enforce memory freezing
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/tools/freezer.cpp
  src/core/tools/freezer.h
Labels: core-new

#2583 Core_Timing: Make core_timing threadsafe by default.
  src/audio_core/stream.cpp
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/hle/kernel/thread.cpp
  src/tests/core/core_timing.cpp
Labels: canary-merge
