Repository yuzu-emu/yuzu, pull requests merged in 2019-01, with the labels that each got.

#1970 core/kernel: Remove unnecessary inclusions
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/client_session.cpp
  src/core/hle/kernel/client_session.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/server_session.h
  src/core/hle/kernel/wait_object.cpp
  src/core/hle/kernel/wait_object.h
  src/core/hle/kernel/writable_event.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/vi/vi.cpp
Labels: style

#1969 yuzu: Fix truncation warnings within UI code
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_per_general.cpp
Labels: style

#1961 gl_rasterizer_cache: Texture view if shader samples array but OGL is not
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-fix

#1977 service/vi: Log more information where applicable
  src/core/hle/service/vi/vi.cpp
Labels: style

#1941 qt: Use ProfileSelectionDialog when selecting user for save data
  src/yuzu/main.cpp
Labels: frontend-new

#1942 qt: Add setting to prompt for user on game boot
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/ui_settings.h
Labels: frontend-new

#1978 service/vi: Implement SetDisplayEnabled()
  src/core/hle/service/vi/vi.cpp
Labels: hle-new

#1976 service/vi: Implement OpenDefaultDisplay in terms of OpenDisplay
  src/core/hle/service/vi/vi.cpp
Labels: hle-new

#1979 Fixed botw deadlock due to incorrect event signal type
  src/core/hle/service/nvflinger/nvflinger.cpp
Labels: canary-merge, hle-fix

#1975 service/vi: Minor updates and corrections to the DisplayInfo struct
  src/core/hle/service/vi/vi.cpp
Labels: canary-merge, hle-fix

#1980 Proper no message handling for AM::PopMessage
  src/core/hle/service/am/am.cpp
Labels: canary-merge, hle-fix

#1981 Return no application area when games try to open an application area
  src/core/hle/service/nfp/nfp.cpp
Labels: canary-merge, hle-fix

#1990 gl_rasterizer_cache: Use GL_STREAM_COPY for PBOs
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: canary-merge

#1992 qt: Move profile manager to own UI tab
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/configure.ui
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_profile_manager.cpp
  src/yuzu/configuration/configure_profile_manager.h
  src/yuzu/configuration/configure_profile_manager.ui
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_system.ui
Labels: frontend

#1989 service/vi: Unstub IApplicationDisplayService's SetLayerScalingMode
  src/core/hle/service/vi/vi.cpp
Labels: hle-fix

#1999 gl_shader_cache: Use dirty flags for shaders
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
Labels: canary-merge, gpu, performance

#1959 settings: Add support for setting the RTC manually
  src/core/core.cpp
  src/core/hle/service/time/time.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: hle-new

#2036 file_sys/directory: Remove unused DirectoryBackend class
  src/core/file_sys/directory.h
Labels: style

#2033 gl_rasterizer: Silent unsafe mix warning
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: style

#2031 yuzu/web_browser: Minor cleanup
  src/core/core.cpp
  src/core/core.h
  src/core/frontend/applets/web_browser.cpp
  src/core/frontend/applets/web_browser.h
  src/core/hle/service/am/applets/web_browser.cpp
  src/yuzu/applets/web_browser.cpp
  src/yuzu/applets/web_browser.h
Labels: style

#2002 gl_rasterizer: Use DSA for VAOs and buffers
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_resource_manager.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/gl_stream_buffer.cpp
  src/video_core/renderer_opengl/gl_stream_buffer.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: canary-merge, gpu

#2008 gl_rasterizer_cache: Use dirty flags for framebuffers
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu, performance

#2035 yuzu/configuration: Remove unnecessary inclusions where applicable
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_per_general.cpp
  src/yuzu/configuration/configure_per_general.h
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_touchscreen_advanced.h
Labels: style

#1927 video_core: Replace gl_shader_decompiler with an IR based decompiler
  src/video_core/CMakeLists.txt
  src/video_core/engines/shader_bytecode.h
  src/video_core/engines/shader_header.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/arithmetic.cpp
  src/video_core/shader/decode/arithmetic_half.cpp
  src/video_core/shader/decode/arithmetic_half_immediate.cpp
  src/video_core/shader/decode/arithmetic_immediate.cpp
  src/video_core/shader/decode/arithmetic_integer.cpp
  src/video_core/shader/decode/arithmetic_integer_immediate.cpp
  src/video_core/shader/decode/bfe.cpp
  src/video_core/shader/decode/bfi.cpp
  src/video_core/shader/decode/conversion.cpp
  src/video_core/shader/decode/decode_integer_set.cpp
  src/video_core/shader/decode/ffma.cpp
  src/video_core/shader/decode/float_set.cpp
  src/video_core/shader/decode/float_set_predicate.cpp
  src/video_core/shader/decode/half_set.cpp
  src/video_core/shader/decode/half_set_predicate.cpp
  src/video_core/shader/decode/hfma2.cpp
  src/video_core/shader/decode/integer_set.cpp
  src/video_core/shader/decode/integer_set_predicate.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/decode/predicate_set_predicate.cpp
  src/video_core/shader/decode/predicate_set_register.cpp
  src/video_core/shader/decode/register_set_predicate.cpp
  src/video_core/shader/decode/shift.cpp
  src/video_core/shader/decode/video.cpp
  src/video_core/shader/decode/xmad.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: gpu-new

#2058 video_core: Silent implicit conversion warning
  src/video_core/video_core.cpp
Labels: style

#2060 kernel/svc: Log out uncaught C++ exceptions from svcBreak
  src/core/hle/kernel/svc.cpp
Labels: hle-new

#2064 service/vi: Remove stubbed notifier from SetLayerVisibility
  src/core/hle/service/vi/vi.cpp
Labels: hle-issue

#2065 service/pm: Implement SetMaintenanceBoot
  src/core/hle/service/pm/pm.cpp
  src/core/hle/service/pm/pm.h
Labels: hle-new

#2063 video_core/shader: Minor changes
  src/video_core/shader/decode.cpp
  src/video_core/shader/shader_ir.h
Labels: style

#1908 video_core/GPU Implemented the GPU PFIFO puller semaphore operations.
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: gpu-new

#1960 video_core: Implement LDG through heuristics based on IR
  src/video_core/CMakeLists.txt
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_global_cache.cpp
  src/video_core/renderer_opengl/gl_global_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/shader/track.cpp
Labels: gpu-new

#1485 Add more info into textures' object labels
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu

#2076 video_core/dma_pusher: Silence C4828 warnings
  src/video_core/dma_pusher.h
Labels: style

#1818 Add missing environment variables to travis-ci.env
  .travis/common/travis-ci.env
Labels: build-system

#2075 service/nvflinger: Minor renaming changes
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/vi/vi.cpp
Labels: style

#2077 kernel/wait_object: Devirtualize functions related to manipulating the thread list directly
  src/core/hle/kernel/readable_event.cpp
  src/core/hle/kernel/readable_event.h
  src/core/hle/kernel/timer.cpp
  src/core/hle/kernel/timer.h
  src/core/hle/kernel/wait_object.h
Labels: style

#2072 service: Update function tables
  src/core/hle/service/am/applet_ae.cpp
  src/core/hle/service/audio/audin_u.cpp
  src/core/hle/service/audio/audrec_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/audren_u.h
  src/core/hle/service/btdrv/btdrv.cpp
  src/core/hle/service/btm/btm.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
  src/core/hle/service/ncm/ncm.cpp
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/psc/psc.cpp
Labels: hle-new
