Repository yuzu-emu/yuzu, pull requests merged in 2019-02, with the labels that each got.

#2078 kernel: Remove the Timer class
  src/core/CMakeLists.txt
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/object.cpp
  src/core/hle/kernel/object.h
  src/core/hle/kernel/timer.cpp
  src/core/hle/kernel/timer.h
  src/yuzu/debugger/wait_tree.cpp
  src/yuzu/debugger/wait_tree.h
Labels: kernel-issue

#2067 gl_rasterizer: Workaround invalid zeta clears
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: gpu-fix

#2073 hwopus: Implement DecodeInterleaved (the newest variant)
  src/core/hle/service/audio/hwopus.cpp
Labels: hle-new

#2081 shader_ir/memory: Add LD_L 64 bits loads
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/memory.cpp
Labels: gpu-new

#2085 video_core/texture: Fix BitField size for depth_minus_one
  src/video_core/textures/texture.h
Labels: gpu-fix

#2057 Port citra-emu/citra#4586: "Use QPixmap/QIcon for background color selection button"
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
Labels: frontend-fix

#2071 gl_rasterizer: Use DSA for textures and move swizzling to texture state
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_resource_manager.cpp
  src/video_core/renderer_opengl/gl_resource_manager.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: canary-merge, gpu-fix

#2042 maxwell_3d: Allow texture handles with TIC id zero
  src/video_core/dma_pusher.cpp
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/memory_manager.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_primitive_assembler.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/textures/texture.h
Labels: gpu-fix

#2021 gl_shader_cache: Disk based shader cache
  CMakeLists.txt
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/common/common_paths.h
  src/common/file_util.cpp
  src/common/file_util.h
  src/common/scm_rev.cpp.in
  src/common/scm_rev.h
  src/core/core.cpp
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/video_core/CMakeLists.txt
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_resource_manager.cpp
  src/video_core/renderer_opengl/gl_resource_manager.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_opengl/gl_shader_util.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/shader/shader_ir.h
  src/video_core/video_core.cpp
  src/video_core/video_core.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu/loading_screen.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
  src/yuzu_cmd/yuzu.cpp
Labels: gpu, gpu-new, performance

#1904 gl_rasterizer: Implement a more accurate fermi 2D copy.
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-fix, gpu-new

#2068 shader_ir: Clean texture management code
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/shader_ir.h
Labels: canary-merge, gpu-fix, style

#2110 core_timing: Rename CoreTiming namespace to Core::Timing
  src/audio_core/stream.cpp
  src/audio_core/stream.h
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/core.cpp
  src/core/core_cpu.cpp
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/core_timing_util.cpp
  src/core/core_timing_util.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/service/hid/controllers/debug_pad.cpp
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/mouse.cpp
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/stubbed.cpp
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/xpad.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
  src/core/hle/service/hid/irs.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/time/time.cpp
  src/tests/core/core_timing.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/gpu.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: style

#2114 renderer_opengl: Remove reference to global system instance
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: style

#2099 Implement BGRA8 framebuffer format
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/surface.cpp
Labels: gpu-new, needs-hardware-test

#2116 threadsafe_queue: Remove NeedSize template parameter
  src/common/threadsafe_queue.h
  src/core/core_timing.cpp
Labels: style

#2115 core_timing: Make EmptyTimedCallback a local variable
  src/core/core_timing.cpp
Labels: style

#2111 gl_shader_decompiler: Re-implement TLDS lod
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/decode/memory.cpp
Labels: canary-merge, gpu-fix

#2112 gl_rasterizer_cache: Get rid of variable shadowing
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: style

#2123 core_timing: De-globalize core_timing facilities
  src/audio_core/audio_out.cpp
  src/audio_core/audio_out.h
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/audio_core/stream.cpp
  src/audio_core/stream.h
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/arm/unicorn/arm_unicorn.h
  src/core/core.cpp
  src/core/core.h
  src/core/core_cpu.cpp
  src/core/core_cpu.h
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/cpu_core_manager.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/hid/controllers/controller_base.h
  src/core/hle/service/hid/controllers/debug_pad.cpp
  src/core/hle/service/hid/controllers/debug_pad.h
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/gesture.h
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/keyboard.h
  src/core/hle/service/hid/controllers/mouse.cpp
  src/core/hle/service/hid/controllers/mouse.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/controllers/stubbed.cpp
  src/core/hle/service/hid/controllers/stubbed.h
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
  src/core/hle/service/hid/controllers/xpad.cpp
  src/core/hle/service/hid/controllers/xpad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/irs.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/hle/service/time/time.cpp
  src/tests/core/core_timing.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/gpu.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: canary-merge, style

#2133 address_arbiter: Use nested namespaces where applicable
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/address_arbiter.h
Labels: style

#2134 audio_core/buffer: Make const and non-const getter for samples consistent
  src/audio_core/buffer.h
  src/audio_core/stream.cpp
Labels: style

#2122 vk_resource_manager: Implement fence and command buffer allocator
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/vk_resource_manager.cpp
  src/video_core/renderer_vulkan/vk_resource_manager.h
Labels: canary-merge

#2142 service/nvflinger: Relocate definitions of Layer and Display to the vi service
  src/core/CMakeLists.txt
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/vi/display/vi_display.cpp
  src/core/hle/service/vi/display/vi_display.h
  src/core/hle/service/vi/layer/vi_layer.cpp
  src/core/hle/service/vi/layer/vi_layer.h
Labels: style

#2120 Fixes Unicode Key File Directories
  src/core/crypto/key_manager.cpp
Labels: canary-merge

#2130 video_core: Remove usages of System::GetInstance() within the engines
  src/core/core.cpp
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: style

#2125 gl_state: Synchronize gl_state even when state is disabled
  src/video_core/renderer_opengl/gl_state.cpp
Labels: canary-merge, gpu-fix

#2139 video_core/dma_pusher: The full list of headers at once.
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
Labels: canary-merge, gpu-fix, performance

#2144 service/vi: Convert Display and Layer structs into classes
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/vi/display/vi_display.cpp
  src/core/hle/service/vi/display/vi_display.h
  src/core/hle/service/vi/layer/vi_layer.cpp
  src/core/hle/service/vi/layer/vi_layer.h
  src/core/hle/service/vi/vi.cpp
Labels: style

#2119 rasterizer_cache_gl: Only do fast layered copy on the same format.
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: canary-merge

#2118 shader_decompiler: Improve Accuracy of Attribute Interpolation.
  src/video_core/engines/shader_bytecode.h
  src/video_core/engines/shader_header.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/other.cpp
Labels: canary-merge, gpu-fix

#2159 shader/track: Resolve variable shadowing warnings
  src/video_core/shader/track.cpp
Labels: style

#2160 audio_core: Resolve compilation warnings
  src/audio_core/codec.cpp
  src/audio_core/cubeb_sink.cpp
Labels: audio-issue

#2158 service/vi: Update IManagerDisplayService's function table
  src/core/hle/service/vi/vi.cpp
Labels: hle-issue

#2171 gl_shader_disk_cache: Remove #pragma once from cpp file
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
Labels: style

#2167 common: Move Quaternion, Rectangle, Vec2, Vec3, and Vec4 into the Common namespace
  src/common/color.h
  src/common/math_util.h
  src/common/quaternion.h
  src/common/vector_math.h
  src/core/frontend/framebuffer_layout.cpp
  src/core/frontend/framebuffer_layout.h
  src/core/frontend/input.h
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/vi/vi.cpp
  src/input_common/motion_emu.cpp
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/gpu.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/renderer_opengl.h
  src/yuzu/debugger/graphics/graphics_surface.cpp
Labels: style

#2161 kernel/handle_table: Allow process capabilities to limit the handle table size
  src/core/hle/kernel/errors.h
  src/core/hle/kernel/handle_table.cpp
  src/core/hle/kernel/handle_table.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process_capability.cpp
  src/core/hle/kernel/process_capability.h
Labels: canary-merge, hle-new, kernel-issue

#2170 core/frontend/emu_window: Make ClipToTouchScreen a const member function
  src/core/frontend/emu_window.cpp
  src/core/frontend/emu_window.h
Labels: style

#2169 audio_core/audio_renderer: Provide names for some parameters of AudioRendererParameter
  src/audio_core/audio_renderer.h
  src/core/hle/service/audio/audren_u.cpp
Labels: audio-issue, style

#2176 audio_core/cubeb_sink: Ensure COM is initialized on Windows prior to calling cubeb_init
  src/audio_core/cubeb_sink.cpp
  src/audio_core/cubeb_sink.h
Labels: audio-fix

#2141 speed up memory page mapping
  src/core/memory.cpp
Labels: canary-merge

#2163 maxwell_3d: Use std::bitset to manage dirty flags
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
Labels: style

#2172 gl_rasterizer/vk_memory_manager: Silence -Wreorder warnings
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_memory_manager.cpp
Labels: style

#2121 Improve the Accuracy of the Rasterizer Cache through a Texception Pass
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge, gpu-fix

#2174 service/hid: Amend forward declaration of ServiceManager
  src/core/hle/service/hid/hid.h
Labels: style
