Repository yuzu-emu/yuzu, pull requests merged in 2019-11, with the labels that each got.

#2914 Fermi2D: limit blit area to only available area
  src/video_core/engines/fermi_2d.cpp
Labels: gpu-fix, mainline-merge, vulkan

#2859 hid: Stub SetNpadJoyAssignmentModeSingle and GetNpadHandheldActivationMode
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: hle-new, mainline-merge

#3073 ci: Rename build folder only on non-mainline builds
  .ci/scripts/common/post-upload.sh
  .ci/scripts/linux/upload.sh
  .ci/scripts/windows/upload.ps1
  .ci/scripts/windows/upload.sh
  .ci/templates/build-msvc.yml
Labels: build-system-fix

#3039 shader/node: Unpack bindless texture encoding
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/shader/decode/image.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/node.h
  src/video_core/shader/shader_ir.h
  src/video_core/textures/texture.h
Labels: gpu, mainline-merge

#3062 kernel: Improve events
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/object.h
  src/core/hle/kernel/readable_event.cpp
  src/core/hle/kernel/readable_event.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/writable_event.cpp
  src/core/hle/kernel/writable_event.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/bcat/backend/backend.cpp
  src/core/hle/service/btdrv/btdrv.cpp
  src/core/hle/service/btm/btm.cpp
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/vi/display/vi_display.cpp
  src/yuzu/debugger/wait_tree.cpp
  src/yuzu/debugger/wait_tree.h
Labels: core-fix, mainline-merge

#3076 ci: Populate build repository from Azure environment
  src/common/CMakeLists.txt
Labels: build-system-fix

#3057 gl_rasterizer: Upload constant buffers with glNamedBufferSubData
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: mainline-merge, opengl, performance

#3070 shader_ir: Reduce severity of warnings
  src/video_core/shader/decode/arithmetic.cpp
  src/video_core/shader/decode/arithmetic_half.cpp
  src/video_core/shader/decode/arithmetic_half_immediate.cpp
  src/video_core/shader/decode/ffma.cpp
  src/video_core/shader/decode/half_set.cpp
  src/video_core/shader/decode/half_set_predicate.cpp
  src/video_core/shader/decode/texture.cpp
Labels: general

#3032 shader/control_flow: Abstract repeated code chunks in BRX tracking
  src/video_core/shader/control_flow.cpp
Labels: style

#3080 GLSLDecompiler: Correct Texture Gather Offset.
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: gpu-fix, mainline-merge, opengl

#3082 gl_shader_cache: Fix locker constructors
  src/video_core/renderer_opengl/gl_shader_cache.cpp
Labels: gpu-fix, opengl

#3085 yuzu: configure_web: Use Base64 encoded token
  src/web_service/web_backend.cpp
  src/web_service/web_backend.h
  src/yuzu/configuration/configure_web.cpp
  src/yuzu/configuration/configure_web.ui
Labels: frontend-fix, mainline-merge

#3090 ci: Package source with builds
  .ci/scripts/common/post-upload.sh
  .ci/scripts/windows/upload.ps1
Labels: build-system-new

#3084 video_core: Treat implicit conversions as errors
  externals/microprofile/microprofile.h
  src/video_core/CMakeLists.txt
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/shader/decode.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/textures/astc.cpp
  src/video_core/textures/texture.h
  src/video_core/video_core.cpp
Labels: general

#3103 common_funcs: silence sign-conversion warnings in MakeMagic()
  src/common/common_funcs.h
Labels: general

#3104 xts_archive: Remove redundant std::string constructor
  src/core/file_sys/xts_archive.cpp
Labels: general

#3107 common/hash: Remove unused HashableStruct
  src/common/hash.h
Labels: general

#3081 shader: Implement FSWZADD and reimplement SHFL
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/warp.cpp
  src/video_core/shader/node.h
Labels: gpu-new, opengl

#3092 key_manager: Make use of IOFile in WriteKeyToFile()
  src/core/crypto/key_manager.cpp
Labels: bug

#3093 core: Migrate off deprecated mbedtls functions
  src/core/crypto/key_manager.cpp
  src/core/crypto/partition_data_manager.cpp
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/xts_archive.cpp
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/core/hle/service/bcat/module.cpp
  src/core/hle/service/ldr/ldr.cpp
Labels: general

#3089 Implement stub for IApplicationFunctions::QueryApplicationPlayStatisticsByUid
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: hle-new, mainline-merge

#3110 Complete the implementation of RGBA16UI
  src/video_core/surface.cpp
Labels: gpu-fix, mainline-merge

#3113 common_funcs: Remove semicolons from INSERT_PADDING_* macros
  src/common/common_funcs.h
Labels: general

#3091 core: Make most implicit type conversion warnings errors on MSVC
  externals/httplib/httplib.h
  src/core/CMakeLists.txt
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/arm/unicorn/arm_unicorn.h
  src/core/crypto/key_manager.cpp
  src/core/crypto/partition_data_manager.cpp
  src/core/file_sys/kernel_executable.cpp
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/vfs_libzip.cpp
  src/core/file_sys/xts_archive.cpp
  src/core/gdbstub/gdbstub.cpp
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/result.h
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/web_browser.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/audio/hwopus.cpp
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/mii/mii.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/time/time.cpp
  src/core/hle/service/vi/vi.cpp
  src/core/perf_stats.cpp
Labels: build-system-new, general

#3047 gl_rasterizer: Emulate viewport flipping with ARB_clip_control
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
Labels: gpu-new, mainline-merge, opengl

#3106 common/bit_field: Silence sign-conversion warnings
  src/common/bit_field.h
Labels: general

#3126 Revert "common/bit_field: Silence sign-conversion warnings"
  src/common/bit_field.h
Labels: do-not-merge, mainline-merge

#3123 common/logging: Silence no return value warnings
  src/common/logging/backend.cpp
Labels: general

#3086 texture_cache: Use a flat table instead of switch for texture format lookups
  src/video_core/CMakeLists.txt
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/format_lookup_table.cpp
  src/video_core/texture_cache/format_lookup_table.h
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/surface_params.h
  src/video_core/texture_cache/texture_cache.h
Labels: gpu

#3142 shader/other: Reduce DEPBAR log severity
  src/video_core/shader/decode/other.cpp
Labels: general

#3111 am: Stub QueryApplicationPlayStatistics
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: hle-new

#3112 service/am: Remove unnecessary Skip calls
  src/core/hle/service/am/am.cpp
Labels: general

#3130 Kernel: Correct Cancel Synchronization.
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: kernel-fix, mainline-merge

#3141 gl_shader_gen: Apply default value to gl_Position
  src/video_core/renderer_opengl/gl_shader_gen.cpp
Labels: gpu-fix, mainline-merge

#3114 Kernel: Correct behavior of Condition Variables to be more similar to real hardware.
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
Labels: kernel-fix, mainline-merge

#3145 buffer_cache: Remove brace initialized for objects with default constructor
  src/video_core/buffer_cache/buffer_cache.h
Labels: style

#3153 Port citra-emu/citra#4964: "Unfold UNREACHABLE implementation for dumb compilers"
  src/common/assert.h
Labels: general

#3105 maxwell_3d: Fix stencil_back_func_mask offset
  src/video_core/engines/maxwell_3d.h
Labels: early-access, gpu-fix

#3098 gl_shader_cache: Miscellaneous changes to shaders
  src/video_core/CMakeLists.txt
  src/video_core/engines/const_buffer_engine_interface.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/shader_type.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/utils.cpp
  src/video_core/renderer_opengl/utils.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.h
  src/video_core/shader/const_buffer_locker.cpp
  src/video_core/shader/const_buffer_locker.h
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/node.h
  src/video_core/shader/shader_ir.h
Labels: gpu-new, mainline-merge, opengl

#3155 gpu_thread: Don't spin wait if there are no GPU commands.
  src/video_core/gpu_thread.cpp
Labels: gpu-fix

#3094 service: Update function tables
  src/core/hle/service/acc/acc_su.cpp
  src/core/hle/service/acc/acc_u1.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/idle.cpp
  src/core/hle/service/am/omm.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/audio/audctl.cpp
  src/core/hle/service/bcat/module.cpp
  src/core/hle/service/btdrv/btdrv.cpp
  src/core/hle/service/erpt/erpt.cpp
  src/core/hle/service/es/es.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/mii/mii.cpp
  src/core/hle/service/ncm/ncm.cpp
  src/core/hle/service/nfc/nfc.cpp
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/npns/npns.cpp
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/pm/pm.cpp
  src/core/hle/service/prepo/prepo.cpp
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set_cal.cpp
  src/core/hle/service/set/set_fd.cpp
  src/core/hle/service/set/set_sys.cpp
  src/core/hle/service/sockets/nsd.cpp
  src/core/hle/service/ssl/ssl.cpp
  src/core/hle/service/time/interface.cpp
  src/core/hle/service/time/time.cpp
  src/core/hle/service/vi/vi.cpp
Labels: general

#3158 gl_texture_cache: Apply sRGB on blits
  src/video_core/renderer_opengl/gl_texture_cache.cpp
Labels: opengl

#3160 ci: Continue pipeline on clang format failure
  .ci/yuzu-patreon-step2.yml
Labels: build-system-fix

#3162 kernel: Fix reference management for client/server session.
  src/core/hle/kernel/client_session.cpp
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/session.h
Labels: kernel-fix, mainline-merge

#3164 gl_shader_decompiler: Fix casts from fp32 to fp16
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: gpu-fix, opengl

#3159 core_timing: Use better reference tracking for EventType.
  src/audio_core/stream.cpp
  src/audio_core/stream.h
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/hardware_interrupt_manager.cpp
  src/core/hardware_interrupt_manager.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/memory/cheat_engine.cpp
  src/core/memory/cheat_engine.h
  src/core/tools/freezer.cpp
  src/core/tools/freezer.h
  src/tests/core/core_timing.cpp
Labels: mainline-merge

#3143 gl_device: Deduce indexing bug from device instead of heuristic
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
Labels: gpu-fix, opengl

#3172 video_core/const_buffer_locker: Remove #pragma once from cpp file
  src/video_core/shader/const_buffer_locker.cpp
  src/video_core/shader/const_buffer_locker.h
Labels: general

#3174 video_core/gpu_thread: Tidy up SwapBuffers()
  src/video_core/gpu_thread.cpp
Labels: general

#3170 file_sys/directory: Make EntryType an enum class
  src/core/file_sys/directory.h
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: general

#3171 filesys/romfs: Make ProcessFile and ProcessDirectory internally linked
  src/core/file_sys/romfs.cpp
  src/core/file_sys/romfs.h
Labels: general

#3169 core/memory: Deglobalize memory management code
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/core/CMakeLists.txt
  src/core/arm/arm_interface.cpp
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/arm/unicorn/arm_unicorn.h
  src/core/core.cpp
  src/core/core.h
  src/core/core_cpu.cpp
  src/core/core_cpu.h
  src/core/cpu_core_manager.cpp
  src/core/gdbstub/gdbstub.cpp
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/client_session.cpp
  src/core/hle/kernel/client_session.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/mutex.cpp
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/server_session.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/lm/lm.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/memory.cpp
  src/core/memory.h
  src/core/memory/cheat_engine.cpp
  src/core/memory/cheat_engine.h
  src/core/memory_setup.h
  src/core/reporter.cpp
  src/core/tools/freezer.cpp
  src/core/tools/freezer.h
  src/tests/core/arm/arm_test_common.cpp
  src/video_core/memory_manager.cpp
  src/video_core/rasterizer_accelerated.cpp
  src/video_core/rasterizer_accelerated.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/yuzu/debugger/wait_tree.cpp
Labels: general

#3185 texture_cache/surface_base: Fix out of bounds texture views
  src/video_core/texture_cache/surface_base.h
Labels: gpu-fix

#3184 gl_framebuffer_cache: Optimize framebuffer cache management
  src/video_core/renderer_opengl/gl_framebuffer_cache.cpp
  src/video_core/renderer_opengl/gl_framebuffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: opengl, performance

#3177 kernel: Implement a more accurate IPC dispatch.
  src/core/CMakeLists.txt
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/client_port.cpp
  src/core/hle/kernel/client_session.cpp
  src/core/hle/kernel/client_session.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/object.cpp
  src/core/hle/kernel/object.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/server_session.h
  src/core/hle/kernel/session.cpp
  src/core/hle/kernel/session.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/sm/controller.cpp
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
Labels: kernel-fix, mainline-merge
