Repository yuzu-emu/yuzu, pull requests merged in 2020-07, with the labels that each got.

#4063 Add game version to window title
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#4153 prepo: : Don't read extra buffer from report unless passed
  src/core/hle/service/prepo/prepo.cpp
Labels: early-access-merge, hle-fix

#3967 crypto: Make KeyManager a singleton class
  src/core/crypto/key_manager.h
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
  src/core/file_sys/xts_archive.h
  src/core/hle/service/es/es.cpp
  src/yuzu/main.cpp
Labels: early-access-merge

#4082 maxwell_to_gl: Implement MirrorOnceClampOGL wrap mode using GL_MIRROR_CLAMP_EXT
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: do-not-merge, early-access-merge

#4192 acc: ListOpenContextStoredUsers partial stub
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/acc_su.cpp
  src/core/hle/service/acc/acc_u0.cpp
  src/core/hle/service/acc/acc_u1.cpp
Labels: early-access-merge

#4193 am: Stub GetIndirectLayerConsumerHandle
  src/core/hle/service/am/am.cpp
Labels: early-access-merge

#3924 Implement GetKeyCodeMap & GetKeyCodeMap2
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set.h
Labels: early-access-merge

#4175 gl_buffer_cache: Copy to buffers created as STREAM_READ before downloading
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
Labels: opengl, performance

#4194 shader_cache: Fix use-after-free and orphan invalidation cache entries
  src/video_core/shader_cache.h
Labels: early-access-merge, gpu-fix

#4245 memory: Race-condition in pagetables.
  src/core/memory.cpp
Labels: core-fix, early-access-merge

#4219 audio: Improving audio timing for multicore/single core
  src/audio_core/stream.cpp
  src/audio_core/stream.h
Labels: early-access-merge

#4202 core_timing,scheduler: Use std::scoped_lock when possible
  src/core/core_timing.cpp
  src/core/hle/kernel/scheduler.cpp
Labels: early-access-merge

#4248 AM/ISelfController: Stub CreateManagedDisplaySeparableLayer
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: early-access-merge

#4098 configuration: implement per-game configurations
  src/audio_core/cubeb_sink.cpp
  src/audio_core/stream.cpp
  src/core/core.cpp
  src/core/frontend/framebuffer_layout.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/set/set.cpp
  src/core/hle/service/spl/module.cpp
  src/core/hle/service/vi/vi.cpp
  src/core/perf_stats.cpp
  src/core/settings.cpp
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/gpu.cpp
  src/video_core/query_cache.h
  src/video_core/renderer_base.cpp
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/textures/texture.cpp
  src/video_core/video_core.cpp
  src/yuzu/CMakeLists.txt
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configuration_shared.cpp
  src/yuzu/configuration/configuration_shared.h
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_audio.h
  src/yuzu/configuration/configure_audio.ui
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.h
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_per_game.h
  src/yuzu/configuration/configure_per_game.ui
  src/yuzu/configuration/configure_per_game_addons.cpp
  src/yuzu/configuration/configure_per_game_addons.h
  src/yuzu/configuration/configure_per_game_addons.ui
  src/yuzu/configuration/configure_per_general.ui
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
  src/yuzu_cmd/yuzu.cpp
  src/yuzu_tester/config.cpp
Labels: early-access-merge

#4203 service: Update function tables
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/npns/npns.cpp
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/ns.h
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/nvdrv/interface.cpp
  src/core/hle/service/nvdrv/interface.h
  src/core/hle/service/nvdrv/nvmemp.cpp
  src/core/hle/service/nvdrv/nvmemp.h
  src/core/hle/service/pcie/pcie.cpp
  src/core/hle/service/pcv/pcv.cpp
  src/core/hle/service/pm/pm.cpp
  src/core/hle/service/prepo/prepo.cpp
  src/core/hle/service/psc/psc.cpp
  src/core/hle/service/ptm/psm.cpp
  src/core/hle/service/sm/controller.cpp
  src/core/hle/service/sm/controller.h
  src/core/hle/service/sockets/nsd.cpp
  src/core/hle/service/sockets/sfdnsres.cpp
  src/core/hle/service/sockets/sfdnsres.h
  src/core/hle/service/spl/spl.cpp
  src/core/hle/service/time/time.cpp
  src/core/hle/service/usb/usb.cpp
  src/core/hle/service/vi/vi.cpp
  src/core/hle/service/vi/vi_u.cpp
  src/core/hle/service/wlan/wlan.cpp
Labels: early-access-merge

#4289 vk_rasterizer: Pass <pSizes> to CmdBindVertexBuffers2EXT
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: vulkan

#4275 AM: fix GetDesiredLanguage:
  src/core/hle/service/am/am.cpp
Labels: early-access-merge

#3385 frontend: Add support to batch install files to NAND
  src/yuzu/CMakeLists.txt
  src/yuzu/install_dialog.cpp
  src/yuzu/install_dialog.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: early-access-merge

#4290 CMakeLists: Make use of /std:c++latest on MSVC
  CMakeLists.txt
  src/yuzu/game_list.cpp
Labels: build-system-new

#4265 vfs_real: Fix MoveFile
  src/core/file_sys/vfs_real.cpp
Labels: early-access-merge

#4318 CMakeLists: Enable usage of C++20 on Linux
  CMakeLists.txt
Labels: build-system-new

#4315 udp: Silence a C++20 deprecation warning
  src/input_common/udp/client.cpp
Labels: input

#4314 gcadapter: Tidy up compiler warnings
  src/input_common/gcadapter/gc_adapter.cpp
  src/input_common/gcadapter/gc_adapter.h
  src/input_common/gcadapter/gc_poller.cpp
  src/input_common/gcadapter/gc_poller.h
Labels: input

#4282 filesystem: Set various NAND partition sizes to their defaults
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/sdmc_factory.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_filesystem.cpp
  src/yuzu/configuration/configure_filesystem.ui
  src/yuzu_cmd/config.cpp
Labels: early-access-merge

#4242 maxwell_dma: Match official doc and support pitch->voxel copies
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/surface_params.h
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
Labels: early-access-merge, gpu-new, style

#4342 common/swap: Make use of std::endian
  src/common/swap.h
Labels: general

#4328 memory_layout: Remove unused data member
  src/core/hle/kernel/memory/memory_layout.h
Labels: general

#4249 registered_cache: Remove previous update/dlc if it exists on install
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/yuzu/main.cpp
Labels: early-access-merge

#4346 kernel/handle_table: Remove usages of the global system instance
  src/core/hle/kernel/handle_table.cpp
  src/core/hle/kernel/handle_table.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
Labels: general

#4297 main/profile_select: Don't prompt for profile selection when only one is available
  src/yuzu/main.cpp
Labels: early-access-merge

#4321 vk_blit_screen: Make use of designated initializers where applicable
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
Labels: vulkan

#4332 vk_device: Make use of designated initializers where applicable
  src/video_core/renderer_vulkan/vk_device.cpp
Labels: vulkan

#4333 vk_graphics_pipeline: Make use of designated initializers where applicable
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: vulkan

#4327 address_space_info: Make use of designated initializers
  src/core/hle/kernel/memory/address_space_info.cpp
  src/core/hle/kernel/memory/address_space_info.h
Labels: general

#4362 vk_graphics_pipeline: Resolve narrowing warnings
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: general

#4292 hle: service: mii: Rewrite service to properly support creation of random and default miis.
  src/core/CMakeLists.txt
  src/core/hle/service/mii/manager.cpp
  src/core/hle/service/mii/manager.h
  src/core/hle/service/mii/mii.cpp
  src/core/hle/service/mii/mii_manager.cpp
  src/core/hle/service/mii/mii_manager.h
  src/core/hle/service/mii/raw_data.cpp
  src/core/hle/service/mii/raw_data.h
  src/core/hle/service/mii/types.h
Labels: early-access-merge

#4363 vk_texture_cache: Amend mismatched access masks and indices in UploadBuffer
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: vulkan

#4370 macro_hle: Simplify shift expression in HLE_771BB18C62444DA0()
  src/video_core/macro/macro_hle.cpp
Labels: general

#4368 macro: Resolve missing parameter in doxygen comment
  src/video_core/macro/macro.h
Labels: general

#4367 constants: Add missing <array> include
  src/core/constants.h
Labels: general

#4358 kernel/thread: Remove unimplemented function prototype
  src/core/hle/kernel/thread.h
Labels: general

#4357 kernel: Remove unused variables
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/synchronization.cpp
Labels: general

#4371 core/CMakeLists: Add missing physical_memory.h header file
  src/core/CMakeLists.txt
Labels: build-system-new

#4347 settings: Make use of std::string_view over std::string for logging
  src/core/settings.cpp
Labels: general

#4340 shader_cache: Make use of std::erase_if
  src/video_core/shader_cache.h
Labels: general

#4322 vk_state_tracker: Fix dirty flags for stencil_enable on VK_EXT_extended_dynamic_state
  src/video_core/renderer_vulkan/vk_state_tracker.cpp
Labels: early-access-merge, vulkan

#4309 fs: Fix RomFS building when zero byte files are present
  src/core/file_sys/fsmitm_romfsbuild.cpp
  src/core/file_sys/fsmitm_romfsbuild.h
  src/core/file_sys/vfs_concat.cpp
  src/core/file_sys/vfs_concat.h
Labels: early-access-merge

#4344 dmnt_cheat_vm: Implement opcode 0xC3 (ReadWriteStaticRegister)
  src/core/memory/dmnt_cheat_vm.cpp
  src/core/memory/dmnt_cheat_vm.h
Labels: early-access-merge

#4366 mii/manager: Resolve sign mismatch warnings
  src/core/hle/service/mii/manager.cpp
Labels: general

#4365 mii/manager: Make use of designated initializers
  src/core/hle/service/mii/manager.cpp
Labels: general

#4364 vulkan: Make use of designated initializers where applicable
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/renderer_vulkan/vk_image.cpp
  src/video_core/renderer_vulkan/vk_memory_manager.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_renderpass_cache.cpp
  src/video_core/renderer_vulkan/vk_resource_manager.cpp
  src/video_core/renderer_vulkan/vk_sampler_cache.cpp
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_shader_util.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/wrapper.cpp
Labels: vulkan

#4345 filesystem: Create subdirectories prior to creating a file
  src/core/hle/service/filesystem/filesystem.cpp
Labels: early-access-merge

#4373 alignment: Simplify AlignmentAllocator implementation
  src/common/alignment.h
Labels: general

#4348 core_timing: Make usage of nanoseconds more consistent in the interface
  src/audio_core/stream.cpp
  src/audio_core/stream.h
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/hardware_interrupt_manager.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/time_manager.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/memory/cheat_engine.cpp
  src/core/memory/cheat_engine.h
  src/core/tools/freezer.cpp
  src/core/tools/freezer.h
  src/tests/core/core_timing.cpp
Labels: general

#3349 [WIP] yuzu: Port translation support from Citra v2
  .ci/scripts/linux/docker.sh
  .ci/scripts/windows/docker.sh
  CMakeLists.txt
  README.md
  dist/languages/.gitignore
  dist/languages/.tx/config
  dist/languages/README.md
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_dialog.h
  src/yuzu/configuration/configure_ui.cpp
  src/yuzu/configuration/configure_ui.h
  src/yuzu/configuration/configure_ui.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/uisettings.h
Labels: frontend-new

#4168 gl_arb_decompiler: Use NV_shader_buffer_{load,store} on assembly shaders
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/renderer_opengl/gl_stream_buffer.cpp
Labels: early-access-merge, opengl

#4324 video_core: Fix, add and rename pixel formats
  src/video_core/compatible_formats.cpp
  src/video_core/gpu.h
  src/video_core/morton.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/shader/decode/image.cpp
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/format_lookup_table.cpp
  src/video_core/texture_cache/surface_base.cpp
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/textures/convert.cpp
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
  src/video_core/textures/texture.h
Labels: gpu-fix

#4306 core/network: Add network abstraction
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/network/network.cpp
  src/core/network/network.h
  src/core/network/sockets.h
Labels: early-access-merge

#4361 decode/other: Implement S2R.LaneId
  src/video_core/shader/decode/other.cpp
Labels: early-access-merge, gpu-new

#4360 gl_arb_decompiler: Execute BAR even when inside control flow
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
Labels: early-access-merge, opengl

#4359 renderer_{opengl,vulkan}: Clamp shared memory to host's limit
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Labels: early-access-merge, gpu

#4353 gc_adapter: Refactor code
  src/input_common/gcadapter/gc_adapter.cpp
  src/input_common/gcadapter/gc_adapter.h
Labels: early-access-merge

#4394 video_core: Remove unused variables
  src/video_core/gpu_thread.cpp
  src/video_core/macro/macro_jit_x64.cpp
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/texture_cache/format_lookup_table.cpp
Labels: general

#4391 video_core: Allow copy elision to take place where applicable
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/decode/arithmetic_integer.cpp
  src/video_core/shader/decode/video.cpp
  src/video_core/shader/decode/xmad.cpp
  src/video_core/shader/shader_ir.cpp
Labels: general

#4388 buffer_cache: Eliminate redundant map lookup in MarkRegionAsWritten()
  src/video_core/buffer_cache/buffer_cache.h
Labels: general

#4334 configure_per_game: Clearer per-game settings
  src/yuzu/configuration/configuration_shared.cpp
  src/yuzu/configuration/configuration_shared.h
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_audio.h
  src/yuzu/configuration/configure_audio.ui
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.h
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_system.ui
Labels: early-access-merge

#4393 vk_rasterizer: Remove unused variable in Clear()
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: vulkan

#4383 frontend: Match indeterminate checkbox state with light theme
  dist/qt_themes/qdarkstyle/rc/checkbox_checked.png
  dist/qt_themes/qdarkstyle/rc/checkbox_checked_disabled.png
  dist/qt_themes/qdarkstyle/rc/checkbox_checked_focus.png
  dist/qt_themes/qdarkstyle/rc/checkbox_indeterminate.png
  dist/qt_themes/qdarkstyle/rc/checkbox_indeterminate_disabled.png
  dist/qt_themes/qdarkstyle/rc/checkbox_indeterminate_focus.png
Labels: early-access-merge

#4380 swkbd: Return result for Calc request for inlined swkbd
  src/core/hle/service/am/applets/software_keyboard.cpp
  src/core/hle/service/am/applets/software_keyboard.h
Labels: early-access-merge

#4414 common/string_util: Remove unimplemented function prototype
  src/common/string_util.h
Labels: general

#4350 hid: Only update keyboard & debug pad inputs if enabled
  src/core/hle/service/hid/controllers/debug_pad.cpp
  src/core/hle/service/hid/controllers/keyboard.cpp
Labels: early-access-merge

#4417 gc_adapter/gc_poller: Resolve compiler warnings
  src/input_common/gcadapter/gc_adapter.cpp
  src/input_common/gcadapter/gc_poller.cpp
Labels: general

#4418 udp/client: Remove unused boost include
  src/input_common/udp/client.cpp
Labels: general

#4419 vulkan: Resolve -Wmissing-field-initializer warnings
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: vulkan

#4437 core_timing: Make use of uintptr_t to represent user_data
  src/audio_core/stream.cpp
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/hardware_interrupt_manager.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/time_manager.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/memory/cheat_engine.cpp
  src/core/memory/cheat_engine.h
  src/core/tools/freezer.cpp
  src/core/tools/freezer.h
  src/tests/core/core_timing.cpp
Labels: general

#4442 device_memory: Remove unused system member
  src/core/core.cpp
  src/core/device_memory.cpp
  src/core/device_memory.h
Labels: general

#4372 game_list: Add "Remove" context menu
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/xts_archive.cpp
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#4396 surface_params: Replace questionable usages of the comma operator with semicolons
  src/video_core/texture_cache/surface_params.cpp
Labels: general

#4392 compatible_formats: Add missing header guard
  src/video_core/compatible_formats.h
Labels: general
