Repository yuzu-emu/yuzu, pull requests merged in 2020-08, with the labels that each got.

#4438 yuzu/main: Remove redundant usages of QStringLiteral("")
  src/yuzu/main.cpp
Labels: general

#4439 cpu_manager: Remove redundant std::function declarations
  src/core/cpu_manager.cpp
Labels: general

#4263 screenshots: Option to save screenshots immediately in a specified directory + Linux workaround
  src/common/common_paths.h
  src/common/file_util.cpp
  src/common/file_util.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_ui.cpp
  src/yuzu/configuration/configure_ui.ui
  src/yuzu/main.cpp
  src/yuzu/uisettings.h
Labels: early-access-merge

#4467 file_sys/mode: Make use of DECLARE_ENUM_FLAG_OPERATORS with Mode
  src/core/file_sys/mode.h
  src/core/file_sys/vfs_real.cpp
Labels: general

#4471 sm: Make use of IsBaseOf for GetService
  src/core/hle/service/sm/sm.h
Labels: general

#4468 registered_cache: Resolve -Wmaybe_uninitialized warnings
  src/core/file_sys/registered_cache.cpp
Labels: general

#4482 service/ldr: Resolve sign mismatch warnings
  src/core/hle/service/ldr/ldr.cpp
Labels: general

#4480 tests/core_timing: Remove pragma optimize(off)
  src/tests/core/core_timing.cpp
Labels: general

#4456 fsp-srv: Stub Read/WriteSaveDataFileSystemExtraDataWithMaskBySaveDataAttribute
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
Labels: early-access-merge

#4473 dmnt_cheat_vm: Make use of designated initializers
  src/core/memory/dmnt_cheat_vm.cpp
Labels: general

#4474 profile_manager: Make use of designated initializers
  src/core/hle/service/acc/profile_manager.cpp
Labels: general

#4481 yuzu: Resolve C++20 deprecation warnings related to lambda captures
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/nvdrv/interface.cpp
  src/core/hle/service/vi/vi.cpp
  src/video_core/gpu.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_mouse_advanced.cpp
  src/yuzu/configuration/configure_ui.cpp
  src/yuzu/main.cpp
Labels: general

#4470 patch_manager: Resolve -Wignored-qualifier warnings
  src/core/file_sys/patch_manager.cpp
Labels: general

#4469 vk_texture_cache: Silence -Wmissing-field-initializer warnings
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_sampler_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: general

#4472 perf_stats: Mark GetMeanFrametime() as const
  src/core/perf_stats.cpp
  src/core/perf_stats.h
Labels: general

#4450 game_list_worker: Fix game list subdirectory scanning
  src/yuzu/game_list_worker.cpp
Labels: early-access-merge

#4445 renderer_opengl: Use 1/4 of all threads for async shader compilation
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge

#4440 CMakeLists: Update several libraries
  CMakeLists.txt
Labels: early-access-merge, externals

#4430 hle: nvdrv: Rewrite of GPU memory management.
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
  src/core/hle/service/nvdrv/devices/nvmap.cpp
  src/core/hle/service/nvdrv/devices/nvmap.h
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: early-access-merge

#4401 vi: IApplicationDisplayService:GetIndirectLayerImageRequiredMemoryInfo
  src/core/hle/service/vi/vi.cpp
Labels: early-access-merge

#4476 time_zone_binary: Make use of designated initializers
  src/core/file_sys/system_archive/time_zone_binary.cpp
Labels: general

#4466 loader: Make IdentifyFile typesafe
  src/core/loader/loader.cpp
Labels: general

#4444 common/atomic_ops: Don't cast away volatile from pointers
  src/common/atomic_ops.cpp
  src/common/atomic_ops.h
  src/core/memory.cpp
Labels: general

#4479 CMakeLists: Resolve #4478
  src/CMakeLists.txt
Labels: build-system-new

#4475 buffer_queue: Make use of designated initializers/std::nullopt where applicable
  src/core/hle/service/nvflinger/buffer_queue.cpp
Labels: general

#4477 logging/backend: Make use of designated initializers
  src/common/logging/backend.cpp
  src/common/logging/backend.h
Labels: general

#4484 aes_util: Allow SetIV() to be non-allocating
  src/core/crypto/aes_util.cpp
  src/core/crypto/aes_util.h
  src/core/crypto/ctr_encryption_layer.cpp
  src/core/crypto/ctr_encryption_layer.h
  src/core/crypto/partition_data_manager.cpp
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/nca_patch.cpp
Labels: general

#4489 ipc_helpers: Only allow trivially copyable objects with PushRaw() and PopRaw()
  src/core/hle/ipc_helpers.h
Labels: general

#4490 address_arbiter/scheduler: Resolve sign conversion warnings
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/scheduler.cpp
Labels: general

#4483 partition_data_manager: Make data arrays constexpr
  src/common/hex_util.cpp
  src/common/hex_util.h
  src/core/crypto/key_manager.cpp
  src/core/crypto/partition_data_manager.cpp
Labels: early-access-merge, general

#4501 common/concepts: Rename IsBaseOf to DerivedFrom
  src/common/concepts.h
  src/core/hle/service/sm/sm.h
  src/core/loader/loader.cpp
Labels: general

#4464 ci: Make use of clang-format 10.0
  .ci/scripts/format/script.sh
  .travis/clang-format/script.sh
Labels: general

#4389 video_core: Remove redundant pixel format type
  src/video_core/texture_cache/surface_params.cpp
Labels: early-access-merge

#4448 game_list_worker: Do not clear entries when > 1 gamedir is present
  src/yuzu/game_list_worker.cpp
Labels: early-access-merge

#4488 vfs_vector: Make creation of array vfs files less verbose
  src/core/file_sys/system_archive/mii_model.cpp
  src/core/file_sys/system_archive/ng_word.cpp
  src/core/file_sys/system_archive/time_zone_binary.cpp
  src/core/file_sys/vfs_vector.h
Labels: general

#4491 kernel: Remove unused variables
  src/core/hle/kernel/memory/page_table.cpp
  src/core/hle/kernel/scheduler.cpp
Labels: general

#4496 cheat_engine: Make use of designated initializers
  src/core/memory/cheat_engine.cpp
Labels: general

#4502 General: Tidy up clang-format warnings
  .ci/scripts/format/script.sh
  CMakeLists.txt
  src/common/bit_field.h
Labels: general

#4497 freezer: Make use of std::erase_if
  src/core/tools/freezer.cpp
  src/core/tools/freezer.h
Labels: general

#4511 General: Tidy up clang-format warnings part 2
  .ci/scripts/format/script.sh
  src/audio_core/cubeb_sink.cpp
  src/common/bit_field.h
  src/common/detached_tasks.cpp
  src/common/math_util.h
  src/core/file_sys/registered_cache.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/memory/page_table.cpp
  src/core/hle/service/am/applets/web_browser.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/input_common/udp/client.cpp
  src/video_core/renderer_vulkan/wrapper.h
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/decode/memory.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_mouse_advanced.cpp
Labels: general

#4495 cheat_engine: Resolve implicit bool->u64 conversion
  src/core/memory/cheat_engine.cpp
Labels: general

#4529 time_zone_content_manager: Collapse auto and default case
  src/core/hle/service/time/time_zone_content_manager.cpp
Labels: general

#4453 textures/decoders: Fix block linear to pitch copies
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
Labels: early-access-merge, gpu-fix

#4518 CMakeLists: Update fmt to 7.0.3
  CMakeLists.txt
Labels: externals

#4416 lz4_compression/zstd_compression: Make use of std::span in interfaces
  src/common/lz4_compression.cpp
  src/common/lz4_compression.h
  src/common/zstd_compression.cpp
  src/common/zstd_compression.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
Labels: general

#4463 kernel/scheduler: Mark SchedulerLock constructor as nodiscard
  src/core/frontend/emu_window.h
  src/core/hle/kernel/scheduler.h
Labels: general

#4492 system_control: Make functions internally linked where applicable
  src/core/hle/kernel/memory/system_control.cpp
  src/core/hle/kernel/memory/system_control.h
Labels: general

#4527 software_keyboard: Resolve a pessimizing move warning
  src/core/hle/service/am/applets/software_keyboard.cpp
Labels: general

#4526 core: Resolve several -Wextra-semi warnings
  src/core/hle/result.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/nvdrv/devices/nvdevice.h
Labels: general

#4519 maxwell_3d: Resolve -Wextra-semi warning
  src/video_core/engines/maxwell_3d.h
Labels: general

#4528 common: Make use of [[nodiscard]] where applicable
  src/common/algorithm.h
  src/common/alignment.h
  src/common/atomic_ops.h
  src/common/bit_field.h
  src/common/bit_util.h
  src/common/cityhash.h
  src/common/color.h
  src/common/common_funcs.h
  src/common/dynamic_library.h
  src/common/fiber.h
  src/common/file_util.h
  src/common/hash.h
  src/common/hex_util.h
  src/common/lz4_compression.cpp
  src/common/lz4_compression.h
  src/common/math_util.h
  src/common/memory_detect.h
  src/common/multi_level_queue.h
  src/common/page_table.h
  src/common/param_package.h
  src/common/quaternion.h
  src/common/ring_buffer.h
  src/common/spin_lock.h
  src/common/string_util.h
  src/common/telemetry.h
  src/common/thread_queue_list.h
  src/common/threadsafe_queue.h
  src/common/time_zone.h
  src/common/timer.h
  src/common/uint128.h
  src/common/uuid.h
  src/common/vector_math.h
  src/common/virtual_buffer.h
  src/common/wall_clock.h
  src/common/zstd_compression.cpp
  src/common/zstd_compression.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
Labels: general

#4536 yuzu: Resolve -Wextra-semi warnings
  src/yuzu/game_list.cpp
  src/yuzu/game_list_worker.cpp
  src/yuzu/uisettings.h
Labels: general

#4520 async_shaders: Resolve -Wpessimizing-move warning
  src/video_core/shader/async_shaders.cpp
Labels: general

#4443 vulkan_renderer: Async shader/graphics pipeline compilation
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
  src/video_core/shader/async_shaders.cpp
  src/video_core/shader/async_shaders.h
  src/yuzu/configuration/configure_graphics_advanced.ui
Labels: early-access-merge

#4531 yuzu: Make use of qOverload where applicable
  src/yuzu/debugger/profiler.cpp
Labels: general

#4494 aes_util: Make use of non-template variant of Transcode
  src/core/crypto/aes_util.cpp
  src/core/crypto/partition_data_manager.cpp
Labels: general

#4540 configure_hotkeys: Don't translate empty strings
  src/yuzu/configuration/configure_hotkeys.cpp
Labels: general

#4537 common/time_zone: Simplify GetOsTimeZoneOffset()
  src/common/time_zone.cpp
Labels: general

#4535 common/fileutil: Convert namespace to Common::FS
  src/common/file_util.cpp
  src/common/file_util.h
  src/common/logging/backend.h
  src/core/core.cpp
  src/core/crypto/key_manager.cpp
  src/core/crypto/key_manager.h
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/vfs.cpp
  src/core/file_sys/vfs_libzip.cpp
  src/core/file_sys/vfs_real.cpp
  src/core/file_sys/vfs_real.h
  src/core/file_sys/xts_archive.cpp
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/am/applets/web_browser.cpp
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/loader/loader.cpp
  src/core/perf_stats.cpp
  src/core/reporter.cpp
  src/core/settings.cpp
  src/core/telemetry_session.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_vulkan/nsight_aftermath_tracker.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/yuzu/applets/profile_select.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_filesystem.cpp
  src/yuzu/configuration/configure_per_game_addons.cpp
  src/yuzu/configuration/configure_profile_manager.cpp
  src/yuzu/configuration/configure_ui.cpp
  src/yuzu/game_list_worker.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/yuzu.cpp
  src/yuzu_tester/config.cpp
  src/yuzu_tester/yuzu.cpp
Labels: general

#4532 configuration_shared: Simplify name lookup in highlighting functions
  src/yuzu/configuration/configuration_shared.cpp
  src/yuzu/configuration/configuration_shared.h
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_system.cpp
Labels: general

#4381 main: Fix Open Save/Mod Locations for installed titles
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#4522 vulkan/wrapper: Avoid unnecessary copy in EnumerateInstanceExtensionProperties()
  src/video_core/renderer_vulkan/wrapper.cpp
Labels: general

#4539 common: Silence two discarded result warnings
  src/common/dynamic_library.cpp
  src/common/file_util.cpp
Labels: general

#4547 common/concepts: Move <type_traits> include out of the Common namespace
  src/common/concepts.h
Labels: general

#4546 common/telemetry: Migrate namespace into the Common namespace
  src/common/telemetry.cpp
  src/common/telemetry.h
  src/core/core.cpp
  src/core/telemetry_session.cpp
  src/core/telemetry_session.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/web_service/telemetry_json.cpp
  src/web_service/telemetry_json.h
  src/yuzu/compatdb.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
  src/yuzu_tester/yuzu.cpp
Labels: general

#4559 web_service: Move web_result.h into web_service
  src/common/CMakeLists.txt
  src/web_service/CMakeLists.txt
  src/web_service/telemetry_json.cpp
  src/web_service/verify_login.cpp
  src/web_service/web_backend.cpp
  src/web_service/web_backend.h
  src/web_service/web_result.h
Labels: general

#4549 vfs_real: Avoid redundant map lookups
  src/core/file_sys/vfs_real.cpp
Labels: general

#4561 key_manager: Make data arrays constexpr
  src/core/crypto/key_manager.cpp
  src/core/crypto/key_manager.h
Labels: general

#4571 video_core/fence_manager: Remove unnecessary includes
  src/video_core/fence_manager.h
  src/video_core/renderer_opengl/gl_fence_manager.cpp
  src/video_core/renderer_opengl/gl_fence_manager.h
Labels: general

#4573 gl_texture_cache: Take std::string by reference in DecorateViewName()
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
Labels: general

#4562 cpu_manager: Make use of ranged for where applicable
  src/core/cpu_manager.cpp
Labels: general

#4548 common/color: Migrate code over to the Common namespace
  src/common/color.h
Labels: general

#4563 registered_cache: Make use of designated initializers
  src/core/file_sys/registered_cache.cpp
Labels: general

#4565 microprofile: Don't memset through std::atomic types
  externals/microprofile/microprofile.h
  externals/microprofile/microprofileui.h
Labels: general

#4574 memory_manager: Mark IsGranularRange() as a const member function
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: general

#4593 memory_manager: Make operator+ const qualified
  src/video_core/memory_manager.h
Labels: general

#4555 vk_state_tracker: Fix primitive topology
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_state_tracker.cpp
  src/video_core/renderer_vulkan/vk_state_tracker.h
Labels: gpu-fix, vulkan

#4569 video_core/host_shaders: Add CMake integration for string shaders
  src/video_core/CMakeLists.txt
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/StringShaderHeader.cmake
  src/video_core/host_shaders/opengl_present.frag
  src/video_core/host_shaders/opengl_present.vert
  src/video_core/host_shaders/source_shader.h.in
  src/video_core/renderer_opengl/gl_resource_manager.cpp
  src/video_core/renderer_opengl/gl_resource_manager.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_util.cpp
  src/video_core/renderer_opengl/gl_shader_util.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: build-system-new, gpu

#4524 shader/memory: Amend UNIMPLEMENTED_IF_MSG without a message
  src/video_core/shader/decode/memory.cpp
Labels: general

#4577 common/assert: Make use of C++ attribute syntax
  src/common/assert.h
Labels: general

#4586 cpu_interrupt_handler: Make is_interrupted an atomic
  src/core/arm/cpu_interrupt_handler.cpp
  src/core/arm/cpu_interrupt_handler.h
Labels: bug

#4544 input_common: Eliminate most global state
  src/input_common/main.cpp
  src/input_common/main.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/configure_debug_controller.cpp
  src/yuzu/configuration/configure_debug_controller.h
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_dialog.h
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input.h
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_mouse_advanced.cpp
  src/yuzu/configuration/configure_mouse_advanced.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.h
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h
  src/yuzu_cmd/yuzu.cpp
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.cpp
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
Labels: general

#4599 vk_device: Blacklist AMD proprietary from VK_EXT_extended_dynamic_state
  src/video_core/renderer_vulkan/vk_device.cpp
Labels: vulkan

#4600 input_common/main: Remove unimplemented prototype
  src/input_common/main.h
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/settings.h
Labels: general

#4604 yuzu/main: Amend lifetime issues with InputSubsystem
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: bug

#4605 bootmanager: Prevent unnecessary copies in TouchUpdateEvent()
  src/yuzu/bootmanager.cpp
Labels: general

#4601 sdl_impl: Minor cleanup
  src/input_common/sdl/sdl_impl.cpp
Labels: general

#4614 vk_device: Fix driver id check on AMD for VK_EXT_extended_dynamic_state
  src/video_core/renderer_vulkan/vk_device.cpp
Labels: vulkan
