Repository yuzu-emu/yuzu, pull requests merged in 2020-01, with the labels that each got.

#3239 shader/p2r: Implement P2R Pr
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/register_set_predicate.cpp
Labels: early-access-merge, gpu-new

#3243 maxwell_to_gl: Implement missing primitive topologies
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: early-access-merge, gpu-new, opengl

#3267 yuzu: Remove Maxwell debugger
  src/core/core.cpp
  src/core/core.h
  src/video_core/CMakeLists.txt
  src/video_core/debug_utils/debug_utils.cpp
  src/video_core/debug_utils/debug_utils.h
  src/video_core/engines/maxwell_3d.cpp
  src/yuzu/CMakeLists.txt
  src/yuzu/debugger/graphics/graphics_breakpoint_observer.cpp
  src/yuzu/debugger/graphics/graphics_breakpoint_observer.h
  src/yuzu/debugger/graphics/graphics_breakpoints.cpp
  src/yuzu/debugger/graphics/graphics_breakpoints.h
  src/yuzu/debugger/graphics/graphics_breakpoints_p.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: gpu

#3247 NvServices: Correct Ioctl Remap.
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
Labels: early-access-merge, hle-fix

#3258 Shader_IR: add the ability to amend code in the shader ir.
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/node.h
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: gpu

#2945 nifm: Only return that there's an internet connection when there's a BCATServer
  src/core/hle/service/nifm/nifm.cpp
Labels: hle-fix, mainline-merge

#3264 vk_descriptor_pool: Initial implementation
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.h
Labels: vulkan

#3257 video_core: Block in WaitFence.
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: early-access-merge, general, performance

#3277 yuzu/bootmanager: Remove {glx,wgl}MakeCurrent on SwapBuffers
  src/yuzu/bootmanager.cpp
Labels: opengl

#3278 renderer_vulkan: Buffer cache, stream buffer and memory manager changes
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_memory_manager.cpp
  src/video_core/renderer_vulkan/vk_memory_manager.h
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.h
Labels: vulkan

#3276 vk_update_descriptor/vk_renderpass_cache: Add pipeline cache dependencies
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/vk_renderpass_cache.cpp
  src/video_core/renderer_vulkan/vk_renderpass_cache.h
  src/video_core/renderer_vulkan/vk_update_descriptor.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.h
Labels: vulkan

#3272 service: vi: Implement CloseLayer.
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/vi/display/vi_display.cpp
  src/core/hle/service/vi/display/vi_display.h
  src/core/hle/service/vi/vi.cpp
Labels: early-access-merge

#3279 vk_pipeline_cache: Initial implementation
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_compute_pipeline.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: vulkan

#3283 vk_compute_pass: Add compute passes to emulate missing Vulkan features
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_shader_util.cpp
  src/video_core/renderer_vulkan/vk_shader_util.h
Labels: vulkan

#3292 core/kernel: Fix GetTotalPhysicalMemoryUsed.
  src/core/hle/kernel/process.cpp
Labels: early-access-merge

#3290 maxwell_to_vk: Implement GL_CLAMP hacking Nvidia's driver
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/vk_sampler_cache.cpp
Labels: early-access-merge, vulkan

#3288 shader_ir/texture: Simplify AOFFI code
  src/video_core/shader/decode/texture.cpp
Labels: early-access-merge, style

#3287 shader_ir/memory: Implement u16 and u8 for STG and LDG
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/shader_ir.h
Labels: gpu-new

#3302 gl_shader_cache: Remove unused variables
  src/video_core/renderer_opengl/gl_shader_cache.cpp
Labels: general

#3303 control_flow: Silence -Wreorder warning for CFGRebuildState
  src/video_core/shader/control_flow.cpp
Labels: general

#3308 maxwell_3d: Make dirty_pointers private
  src/video_core/engines/maxwell_3d.h
Labels: general

#3300 vk_texture_cache: Implement generic texture cache on Vulkan
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/surface_params.h
Labels: vulkan

#3311 format_lookup_table: Fix ZF32_X24S8 component types
  src/video_core/texture_cache/format_lookup_table.cpp
Labels: gpu-fix

#3306 gl_texture_cache: Minor fixes and style changes
  src/video_core/renderer_opengl/gl_texture_cache.cpp
Labels: early-access-merge, gpu-fix, opengl

#3312 shader/memory: Implement ATOMS.ADD.U32
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/node.h
Labels: early-access-merge, gpu-new

#3305 gl_state: Implement PROGRAM_POINT_SIZE
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: early-access-merge, opengl

#3314 core/hle/kernel: Simplify PhysicalMemory usages.
  src/core/hle/kernel/physical_memory.h
  src/core/hle/kernel/vm_manager.cpp
  src/core/loader/elf.cpp
  src/core/loader/kip.cpp
  src/core/loader/nso.cpp
  src/core/memory.cpp
  src/core/memory.h
Labels: early-access-merge

#3323 gl_state: Use bool instead of GLboolean
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: opengl

#3317 gl_shader_decompiler: Fix decompilation of condition codes
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: gpu-fix, opengl

#3313 vk_rasterizer: Implement Vulkan's rasterizer
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: vulkan

#3271 service: time: Rewrite implementation of glue services.
  src/core/CMakeLists.txt
  src/core/file_sys/system_archive/system_archive.cpp
  src/core/file_sys/system_archive/time_zone_binary.cpp
  src/core/file_sys/system_archive/time_zone_binary.h
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/mii/mii_manager.h
  src/core/hle/service/time/clock_types.h
  src/core/hle/service/time/ephemeral_network_system_clock_context_writer.h
  src/core/hle/service/time/ephemeral_network_system_clock_core.h
  src/core/hle/service/time/errors.h
  src/core/hle/service/time/interface.cpp
  src/core/hle/service/time/interface.h
  src/core/hle/service/time/local_system_clock_context_writer.h
  src/core/hle/service/time/network_system_clock_context_writer.h
  src/core/hle/service/time/standard_local_system_clock_core.h
  src/core/hle/service/time/standard_network_system_clock_core.h
  src/core/hle/service/time/standard_steady_clock_core.cpp
  src/core/hle/service/time/standard_steady_clock_core.h
  src/core/hle/service/time/standard_user_system_clock_core.cpp
  src/core/hle/service/time/standard_user_system_clock_core.h
  src/core/hle/service/time/steady_clock_core.h
  src/core/hle/service/time/system_clock_context_update_callback.cpp
  src/core/hle/service/time/system_clock_context_update_callback.h
  src/core/hle/service/time/system_clock_core.cpp
  src/core/hle/service/time/system_clock_core.h
  src/core/hle/service/time/tick_based_steady_clock_core.cpp
  src/core/hle/service/time/tick_based_steady_clock_core.h
  src/core/hle/service/time/time.cpp
  src/core/hle/service/time/time.h
  src/core/hle/service/time/time_manager.cpp
  src/core/hle/service/time/time_manager.h
  src/core/hle/service/time/time_sharedmemory.cpp
  src/core/hle/service/time/time_sharedmemory.h
  src/core/hle/service/time/time_zone_content_manager.cpp
  src/core/hle/service/time/time_zone_content_manager.h
  src/core/hle/service/time/time_zone_manager.cpp
  src/core/hle/service/time/time_zone_manager.h
  src/core/hle/service/time/time_zone_service.cpp
  src/core/hle/service/time/time_zone_service.h
  src/core/hle/service/time/time_zone_types.h
Labels: early-access-merge

#3322 vk_graphics_pipeline: Set front facing properly
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: gpu-fix, vulkan

#3330 vk_blit_screen: Initial implementation
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
Labels: vulkan

#3338 gl_shader_cache: Disable fastmath on Nvidia
  src/video_core/renderer_opengl/gl_shader_cache.cpp
Labels: early-access-merge

#3341 service: time: Implement ToPosixTimeWithMyRule.
  src/core/hle/service/time/time_zone_manager.cpp
  src/core/hle/service/time/time_zone_manager.h
  src/core/hle/service/time/time_zone_service.cpp
  src/core/hle/service/time/time_zone_service.h
Labels: early-access-merge, hle-new

#2800 Port citra-emu/citra#4049: "Input: UDP Client to provide motion and touch controls"
  CMakeLists.txt
  src/common/thread.h
  src/core/settings.h
  src/input_common/CMakeLists.txt
  src/input_common/main.cpp
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
  src/input_common/udp/protocol.cpp
  src/input_common/udp/protocol.h
  src/input_common/udp/udp.cpp
  src/input_common/udp/udp.h
  src/yuzu/configuration/config.cpp
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: frontend-new

#3340 loader: provide default arguments (zero byte) to NSOs
  src/core/loader/nso.cpp
  src/core/loader/nso.h
Labels: core-fix, early-access-merge

#3273 Shader_IR: Implement TXD Array.
  src/video_core/shader/decode/texture.cpp
Labels: early-access-merge, gpu-new

#3344 vk_shader_decompiler: Disable default values on unwritten render targets
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.h
Labels: vulkan

#3326 Port citra-emu/citra#5039: "common/logging: don't use regex for path trimming"
  src/common/logging/backend.cpp
  src/common/logging/backend.h
  src/common/logging/log.h
  src/common/string_util.cpp
Labels: early-access-merge

#3346 bsd: Stub several more functions.
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/sockets/bsd.h
Labels: early-access-merge

#3354 gl_texture_cache: Properly implement depth/stencil sampling
  src/video_core/renderer_opengl/gl_texture_cache.cpp
Labels: early-access-merge, opengl

#3359 gl_shader_decompiler: Remove UNIMPLEMENTED for gl_PointSize
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: opengl

#3358 gl_texture_cache: Silence implicit sign cast warnings
  src/video_core/renderer_opengl/gl_texture_cache.cpp
Labels: style

#3355 texture_cache/surface_base: Fix layered break down
  src/video_core/texture_cache/surface_base.cpp
Labels: early-access-merge, gpu-fix

#3350 shader/memory: Implement ATOM.ADD
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/node.h
Labels: early-access-merge, gpu-new

#3347 shader/memory: Implement LDL.S16, LDS.S16, STL.S16 and STS.S16
  src/video_core/shader/decode/memory.cpp
Labels: early-access-merge, gpu-new

#3363 kernel/physical_core: Make use of std::unique_ptr instead of std::shared_ptr
  src/core/cpu_manager.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/physical_core.cpp
  src/core/hle/kernel/physical_core.h
Labels: general

#3364 core/arm: Remove usage of global GetCurrentThread()
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/unicorn/arm_unicorn.cpp
Labels: general
