Repository yuzu-emu/yuzu, pull requests merged in 2020-12, with the labels that each got.

#4937 InputCommon: Add multiple udp server support
  src/core/settings.h
  src/input_common/main.cpp
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
  src/input_common/udp/udp.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_motion_touch.cpp
  src/yuzu/configuration/configure_motion_touch.h
  src/yuzu/configuration/configure_motion_touch.ui
  src/yuzu_cmd/config.cpp
Labels: early-access-merge, input

#5002 nvdec: Queue and display all decoded frames, cleanup decoders
  src/video_core/command_classes/codecs/codec.cpp
  src/video_core/command_classes/codecs/codec.h
  src/video_core/command_classes/codecs/h264.cpp
  src/video_core/command_classes/codecs/h264.h
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/codecs/vp9.h
  src/video_core/command_classes/codecs/vp9_types.h
  src/video_core/command_classes/nvdec.cpp
  src/video_core/command_classes/nvdec.h
  src/video_core/command_classes/vic.cpp
Labels: early-access-merge, gpu-fix

#5000 audio_core: Make shadowing and unused parameters errors
  src/audio_core/CMakeLists.txt
  src/audio_core/algorithm/filter.cpp
  src/audio_core/algorithm/filter.h
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/audio_core/buffer.h
  src/audio_core/command_generator.cpp
  src/audio_core/command_generator.h
  src/audio_core/cubeb_sink.cpp
  src/audio_core/effect_context.cpp
  src/audio_core/effect_context.h
  src/audio_core/info_updater.cpp
  src/audio_core/info_updater.h
  src/audio_core/memory_pool.cpp
  src/audio_core/memory_pool.h
  src/audio_core/sink_context.cpp
  src/audio_core/sink_context.h
  src/audio_core/splitter_context.cpp
  src/audio_core/splitter_context.h
  src/audio_core/stream.cpp
  src/audio_core/stream.h
  src/audio_core/voice_context.cpp
  src/audio_core/voice_context.h
  src/common/wall_clock.cpp
  src/common/wall_clock.h
  src/common/x64/native_clock.cpp
  src/common/x64/native_clock.h
  src/core/core_timing.h
  src/core/hle/result.h
Labels: build-system-new

#5059 mouse_input/mouse_poller: Minor cleanup
  src/input_common/mouse/mouse_input.cpp
  src/input_common/mouse/mouse_input.h
  src/input_common/mouse/mouse_poller.cpp
Labels: general

#4996 Kernel: Refactor to use 4-instances of Dynarmic & various cleanups and improvements
  src/common/fiber.cpp
  src/common/fiber.h
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.h
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.h
  src/core/core.cpp
  src/core/core.h
  src/core/cpu_manager.cpp
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/address_arbiter.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/memory/page_table.cpp
  src/core/hle/kernel/physical_core.cpp
  src/core/hle/kernel/physical_core.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/synchronization_object.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/time_manager.cpp
  src/core/hle/kernel/time_manager.h
  src/core/hle/service/ldr/ldr.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: early-access-merge

#5061 vp9/vic: Resolve pessimizing moves
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/vic.cpp
Labels: general

#5064 node: Eliminate variable shadowing
  src/video_core/shader/node.h
Labels: general

#5126 codec: Remove deprecated usage of AVCodecContext::refcounted_frames
  src/video_core/command_classes/codecs/codec.cpp
Labels: general

#5124 video_core: Resolve more variable shadowing scenarios
  src/video_core/cdma_pusher.cpp
  src/video_core/cdma_pusher.h
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/codecs/vp9.h
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
  src/video_core/engines/engine_upload.cpp
  src/video_core/engines/engine_upload.h
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/fence_manager.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_asynch.h
  src/video_core/gpu_synch.cpp
  src/video_core/gpu_synch.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/guest_driver.h
  src/video_core/macro/macro_hle.cpp
  src/video_core/macro/macro_hle.h
  src/video_core/macro/macro_interpreter.cpp
  src/video_core/macro/macro_interpreter.h
  src/video_core/macro/macro_jit_x64.cpp
  src/video_core/macro/macro_jit_x64.h
  src/video_core/memory_manager.h
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_fence_manager.cpp
  src/video_core/renderer_opengl/gl_fence_manager.h
  src/video_core/renderer_opengl/gl_query_cache.cpp
  src/video_core/renderer_opengl/gl_query_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_command_pool.cpp
  src/video_core/renderer_vulkan/vk_command_pool.h
Labels: general

#5139 game_list_p: Resolve deprecated usage of QVariant operator<
  src/yuzu/game_list_p.h
Labels: general

#5136 video_core: Resolve more variable shadowing scenarios pt.3
  src/common/scope_exit.h
  src/common/telemetry.h
  src/core/file_sys/vfs_vector.h
  src/core/hle/kernel/memory/memory_block.h
  src/video_core/CMakeLists.txt
  src/video_core/query_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_query_cache.cpp
  src/video_core/renderer_opengl/gl_query_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_command_pool.cpp
  src/video_core/renderer_vulkan/vk_command_pool.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/shader/ast.cpp
  src/video_core/shader/ast.h
  src/video_core/shader/async_shaders.cpp
  src/video_core/shader/async_shaders.h
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/control_flow.h
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/arithmetic_integer.cpp
  src/video_core/shader/expr.h
  src/video_core/shader/node.h
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/texture_cache/copy_params.h
  src/video_core/texture_cache/format_lookup_table.cpp
  src/video_core/texture_cache/surface_base.cpp
  src/video_core/texture_cache/surface_base.h
  src/video_core/texture_cache/surface_view.h
  src/video_core/textures/texture.h
Labels: general

#5158 video_core: Remove unnecessary enum class casting in logging messages
  src/video_core/command_classes/codecs/codec.cpp
  src/video_core/command_classes/vic.cpp
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/shader_bytecode.h
  src/video_core/gpu.cpp
  src/video_core/macro/macro_interpreter.cpp
  src/video_core/macro/macro_jit_x64.cpp
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/shader/decode/arithmetic.cpp
  src/video_core/shader/decode/arithmetic_integer.cpp
  src/video_core/shader/decode/arithmetic_integer_immediate.cpp
  src/video_core/shader/decode/conversion.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/decode/shift.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/decode/warp.cpp
  src/video_core/shader/node_helper.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/surface.cpp
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/textures/convert.cpp
Labels: general

#5160 buffer_block: Remove unnecessary includes
  src/video_core/buffer_cache/buffer_block.h
Labels: general

#5159 shader_ir: std::move node within DeclareAmend()
  src/video_core/shader/shader_ir.cpp
Labels: general

#5163 ast: Improve string concat readability in operator()
  src/video_core/shader/ast.cpp
Labels: general

#5164 video_core: Make use of ordered container contains() where applicable
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/decode.cpp
Labels: general

#5020 Disable analog joystick from buttons by default
  src/core/settings.h
  src/input_common/analog_from_button.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_input_advanced.cpp
  src/yuzu/configuration/configure_input_advanced.ui
Labels: early-access-merge, input

#5165 controller: Avoid unnecessary copies in ConfigurationComplete()
  src/core/hle/service/am/applets/controller.cpp
Labels: general

#5167 memory: Resolve -Wdocumentation warning for Write()
  src/core/memory.cpp
Labels: general

#5166 core: Remove unnecessary enum casts in log calls
  src/core/core.cpp
  src/core/file_sys/content_archive.cpp
  src/core/frontend/applets/error.cpp
  src/core/hle/kernel/process_capability.cpp
  src/core/hle/kernel/resource_limit.cpp
  src/core/hle/kernel/server_session.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/error.cpp
  src/core/hle/service/am/applets/general_backend.cpp
  src/core/hle/service/apm/controller.cpp
  src/core/hle/service/apm/interface.cpp
  src/core/hle/service/fatal/fatal.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/lm/lm.cpp
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/prepo/prepo.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/set/set_sys.cpp
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/sockets/sockets_translate.cpp
  src/core/hle/service/vi/vi.cpp
  src/core/network/network.cpp
Labels: general

#5173 common/file_util: Make use of std::filesystem
  src/common/file_util.cpp
  src/common/file_util.h
Labels: early-access-merge, general

#5174 common/file_util: Fix and deprecate CreateFullPath, add CreateDirs
  src/common/file_util.cpp
  src/common/file_util.h
Labels: early-access-merge

#5176 vfs_real: Fix CreateFile for files without a file extension
  src/core/file_sys/vfs_real.cpp
Labels: early-access-merge

#5162 gl_shader_decompiler: Elide unnecessary copies within DeclareConstantBuffers()
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: general

#5123 nim: Stub IsLargeResourceAvailable
  src/core/hle/service/nim/nim.cpp
Labels: early-access-merge

#5172 svc: Remove unnecessary casts
  src/core/hle/kernel/svc.cpp
Labels: general

#5183 vfs: Use existing type aliases consistently
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/nca_patch.cpp
  src/core/file_sys/nca_patch.h
  src/core/file_sys/vfs.cpp
  src/core/file_sys/vfs.h
  src/core/file_sys/vfs_concat.cpp
  src/core/file_sys/vfs_concat.h
  src/core/file_sys/vfs_layered.cpp
  src/core/file_sys/vfs_layered.h
  src/core/file_sys/vfs_offset.cpp
  src/core/file_sys/vfs_offset.h
  src/core/file_sys/vfs_real.cpp
  src/core/file_sys/vfs_real.h
  src/core/file_sys/vfs_static.h
  src/core/file_sys/vfs_vector.cpp
  src/core/file_sys/vfs_vector.h
  src/core/file_sys/xts_archive.cpp
  src/core/file_sys/xts_archive.h
  src/core/loader/deconstructed_rom_directory.h
  src/core/loader/elf.h
  src/core/loader/kip.h
  src/core/loader/nax.h
  src/core/loader/nca.h
  src/core/loader/nro.h
  src/core/loader/nso.h
  src/core/loader/nsp.h
  src/core/loader/xci.h
Labels: general

#5168 aoc_u: Stub IPurchaseEventManager and its service commands
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/aoc/aoc_u.h
Labels: early-access-merge

#5157 maxwell_3d: Remove unused dirty_pointer array
  src/video_core/engines/maxwell_3d.h
Labels: general

#5119 fsp_srv: Implement OpenDataStorageWithProgramIndex
  src/core/CMakeLists.txt
  src/core/file_sys/common_funcs.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/romfs_factory.h
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
  src/yuzu/main.cpp
Labels: early-access-merge, hle-fix

#5200 system_archive: Update Nintendo Extended OSS font
  src/core/file_sys/system_archive/data/font_nintendo_extended.cpp
  src/core/file_sys/system_archive/data/font_nintendo_extended.h
Labels: early-access-merge

#5201 vi/buffer_queue: Buffer queue management refactor
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/vi/vi.cpp
Labels: early-access-merge, hle-fix

#5131 Rewrite Kernel scheduler based on Atmosphere
  src/common/CMakeLists.txt
  src/common/bit_set.h
  src/common/multi_level_queue.h
  src/core/CMakeLists.txt
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/core.cpp
  src/core/core.h
  src/core/cpu_manager.cpp
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/global_scheduler_context.cpp
  src/core/hle/kernel/global_scheduler_context.h
  src/core/hle/kernel/handle_table.cpp
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/k_affinity_mask.h
  src/core/hle/kernel/k_priority_queue.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_scheduler.h
  src/core/hle/kernel/k_scheduler_lock.h
  src/core/hle/kernel/k_scoped_lock.h
  src/core/hle/kernel/k_scoped_scheduler_lock_and_sleep.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/mutex.cpp
  src/core/hle/kernel/physical_core.cpp
  src/core/hle/kernel/physical_core.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/readable_event.cpp
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/synchronization.cpp
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/time_manager.cpp
  src/core/hle/service/time/time.cpp
  src/tests/CMakeLists.txt
  src/tests/common/multi_level_queue.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: early-access-merge

#5042 Project Aether: Reimplementation of the Web Browser Applet
  src/core/CMakeLists.txt
  src/core/frontend/applets/general_frontend.cpp
  src/core/frontend/applets/general_frontend.h
  src/core/frontend/applets/web_browser.cpp
  src/core/frontend/applets/web_browser.h
  src/core/frontend/input_interpreter.cpp
  src/core/frontend/input_interpreter.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/am/applets/web_browser.cpp
  src/core/hle/service/am/applets/web_browser.h
  src/core/hle/service/am/applets/web_types.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/ns/pl_u.h
  src/yuzu/CMakeLists.txt
  src/yuzu/applets/web_browser.cpp
  src/yuzu/applets/web_browser.h
  src/yuzu/applets/web_browser_scripts.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/util/url_request_interceptor.cpp
  src/yuzu/util/url_request_interceptor.h
Labels: early-access-merge, hle-fix

#5178 Add option to reset window size to 1080p
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: early-access-merge

#5217 yuzu/main: Save settings when starting guest
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#5206 core: memory: Ensure thread safe access when pages are rasterizer cached
  src/core/memory.cpp
Labels: early-access-merge

#5233 InputCommon: Allow to invert analog axis with right click
  src/input_common/gcadapter/gc_poller.cpp
  src/input_common/mouse/mouse_poller.cpp
  src/input_common/sdl/sdl_impl.cpp
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge

#5260 maxwell_to_vk: Initialize usage variable in SurfaceFormat()
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: general

#5263 half_set: Resolve -Wmaybe-uninitialized warnings
  src/video_core/shader/decode/half_set.cpp
Labels: general
