Repository yuzu-emu/yuzu, pull requests merged in 2020-06, with the labels that each got.

#3996 fixed_pipeline_state,gl_rasterizer: Swap negative viewport checks for front faces
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
Labels: early-access-merge, gpu-fix

#4005 format_lookup_table: Implement G24S8 format as S8Z24
  src/video_core/texture_cache/format_lookup_table.cpp
Labels: early-access-merge, gpu-new

#3998 maxwell_3d: Initialize more registers to their expected value
  src/video_core/engines/maxwell_3d.cpp
Labels: early-access-merge, gpu-fix

#4001 buffer_cache: Avoid copying twice on certain cases
  src/video_core/buffer_cache/buffer_cache.h
Labels: early-access-merge, performance

#4033 maxwell_to_vk: Add R16UI image format
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
Labels: early-access-merge, vulkan

#4016 shader/other: Fix hardcoded value in S2R INVOCATION_INFO
  src/video_core/shader/decode/other.cpp
Labels: early-access-merge

#4006 glsl: Squash constant buffers into a single SSBO when we hit the limit
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
Labels: early-access-merge, gpu-fix, opengl

#4032 hid: Stub GetXpadIDs
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge

#4014 gl_device: Avoid devices with CAVEAT_SUPPORT on ASTC
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
Labels: early-access-merge, opengl

#4012 texture_cache: Handle overlaps with multiple subresources
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, gpu-fix

#4009 video_core: Implement Macro JIT
  src/core/settings.h
  src/video_core/CMakeLists.txt
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/macro/macro.cpp
  src/video_core/macro/macro.h
  src/video_core/macro/macro_interpreter.cpp
  src/video_core/macro/macro_interpreter.h
  src/video_core/macro/macro_jit_x64.cpp
  src/video_core/macro/macro_jit_x64.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge, gpu-new

#4031 gl_shader_decompiler: Fix geometry shader outputs on Intel drivers
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: early-access-merge

#4055 gl_device: Black list NVIDIA 443.24 for fast buffer uploads
  src/video_core/renderer_opengl/gl_device.cpp
Labels: opengl

#4052 renderer_opengl: Only enable DEBUG_OUTPUT when graphics debugging is enabled
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: early-access-merge, opengl

#4040 gl_rasterizer: Use NV_transform_feedback for XFB on assembly shaders
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: early-access-merge, opengl

#4027 texture_cache: Implement rendering to 3D textures
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/surface_base.cpp
  src/video_core/texture_cache/surface_base.h
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, gpu-new

#4010 kernel: ResourceLimit::Reserve remove useless while loop
  src/core/hle/kernel/resource_limit.cpp
Labels: early-access-merge

#3986 shader_cache: Implement a generic runtime shader cache
  src/video_core/CMakeLists.txt
  src/video_core/rasterizer_cache.cpp
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/shader_cache.h
Labels: early-access-merge, gpu, performance

#4049 shader/texture: Join separate image and sampler pairs offline
  src/video_core/engines/const_buffer_engine_interface.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/node.h
  src/video_core/shader/node_helper.h
  src/video_core/shader/registry.cpp
  src/video_core/shader/registry.h
  src/video_core/shader/shader_ir.h
  src/video_core/shader/track.cpp
Labels: early-access-merge, gpu-new

#4064 gl_rasterizer: Mark vertex buffers as dirty after buffer cache invalidation
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge, opengl

#4069 kernel: Account for system resource size for memory usage
  src/core/hle/kernel/process.cpp
Labels: early-access-merge

#4070 nvdrv: Fix GetTPCMasks for ioctl3
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
Labels: early-access-merge

#4066 buffer_cache: Avoid passing references of shared pointers and misc style changes
  src/video_core/buffer_cache/buffer_block.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_stream_buffer.cpp
  src/video_core/renderer_opengl/gl_stream_buffer.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_stream_buffer.h
Labels: early-access-merge, gpu

#4041 gl_arb_decompiler: Implement an assembly shader decompiler
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_arb_decompiler.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
Labels: early-access-merge, opengl

#4089 macro_jit_x64: Cleanup
  src/video_core/macro/macro_jit_x64.cpp
  src/video_core/macro/macro_jit_x64.h
Labels: early-access-merge

#4086 xbyak_abi: Cleanup
  src/common/x64/xbyak_abi.h
  src/video_core/macro/macro_jit_x64.cpp
Labels: early-access-merge

#4092 gl_device: Reserve 4 image bindings for fragment stage
  src/video_core/renderer_opengl/gl_device.cpp
Labels: early-access-merge, opengl

#4081 maxwell_to_gl/vk: Miscellaneous changes
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_sampler_cache.cpp
Labels: early-access-merge

#4090 macro_jit_x64: Optimization correctness
  src/video_core/macro/macro_jit_x64.cpp
Labels: early-access-merge

#4080 audren: Implement RendererInfo
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
Labels: early-access-merge

#4087 macro_jit_x64: Inline Engines::Maxwell3D::GetRegisterValue
  src/video_core/macro/macro_jit_x64.cpp
  src/video_core/macro/macro_jit_x64.h
Labels: early-access-merge

#4099 Fix compilation on macOS
  src/core/file_sys/system_archive/shared_font.cpp
  src/core/hle/kernel/memory/memory_manager.cpp
  src/video_core/query_cache.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/shader/memory_util.cpp
  src/video_core/shader_cache.h
  src/yuzu/CMakeLists.txt
  src/yuzu/bootmanager.cpp
Labels: early-access-merge

#4125 macro_jit_x64: Amend readability of Compile_ExtractShiftLeftRegister()
  src/video_core/macro/macro_jit_x64.cpp
Labels: general

#4133 macro_jit_x64: Use ecx for shift register
  src/video_core/macro/macro_jit_x64.cpp
Labels: bug

#4120 gl_arb_decompiler: Avoid several string copies
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
Labels: general

#4126 vulkan/wrapper: Remove noexcept from GetSurfaceCapabilitiesKHR()
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
Labels: general

#4122 video_core: Eliminate some variable shadowing
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/macro/macro_jit_x64.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: general

#4110 vk_update_descriptor: Upload descriptor sets data directly
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.h
Labels: early-access-merge, vulkan

#4127 texture_cache: Fix incorrect address used in a DeduceSurface() call
  src/video_core/texture_cache/texture_cache.h
Labels: bug

#4128 software_keyboard: Eliminate trivial redundant copies
  src/core/hle/service/am/applets/software_keyboard.cpp
Labels: general

#4138 hid: Implement Get/ResetGyroscopeZeroDriftMode
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge

#4129 gl_shader_decompiler: Workaround textureLod when GL_EXT_texture_shadow_lod is not available
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: opengl

#4046 Add support for HLEing Macros
  src/video_core/CMakeLists.txt
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/macro/macro.cpp
  src/video_core/macro/macro.h
  src/video_core/macro/macro_hle.cpp
  src/video_core/macro/macro_hle.h
  src/video_core/macro/macro_interpreter.cpp
  src/video_core/macro/macro_jit_x64.cpp
Labels: early-access-merge

#4083 decode/image: Implement B10G11R11F
  src/video_core/shader/decode/image.cpp
Labels: early-access-merge

#4105 gl_rasterizer: Use NV_vertex_buffer_unified_memory for vertex buffer robustness
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_stream_buffer.cpp
  src/video_core/renderer_opengl/gl_stream_buffer.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.h
Labels: early-access-merge, gpu-fix, opengl

#4141 hid: Stub a series of "SevenSixAxisSensor" service commands
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge

#4136 Add a "Open Mods Page" button to the GUI
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: early-access-merge

#4151 gl_shader_cache: Avoid use after move for program size
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
Labels: bug, early-access-merge, opengl

#4111 vk_rasterizer: Don't preserve contents on full screen clears
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: early-access-merge, performance, vulkan

#4144 TextureCache: Fix case where layer goes off bound.
  src/video_core/texture_cache/surface_base.cpp
Labels: early-access-merge, gpu-fix

#4147 shader/half_set: Implement HSET2_IMM
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/half_set.cpp
Labels: early-access-merge, gpu-new

#4154 Prevent nullptr dereference on swkbd error case
  src/core/hle/service/am/applets/software_keyboard.cpp
Labels: early-access-merge, hle-fix

#4152 Mark invalid IPC buffers as ASSERT_OR_EXECUTE_MSG
  src/core/hle/kernel/hle_ipc.cpp
Labels: early-access-merge, hle-fix

#4158 caps: Use enum classes and check struct sizes on compile time
  src/core/hle/service/caps/caps.cpp
  src/core/hle/service/caps/caps.h
  src/core/hle/service/caps/caps_a.cpp
  src/core/hle/service/caps/caps_a.h
  src/core/hle/service/caps/caps_c.cpp
  src/core/hle/service/caps/caps_c.h
  src/core/hle/service/caps/caps_sc.cpp
  src/core/hle/service/caps/caps_sc.h
  src/core/hle/service/caps/caps_ss.cpp
  src/core/hle/service/caps/caps_ss.h
  src/core/hle/service/caps/caps_su.cpp
  src/core/hle/service/caps/caps_su.h
  src/core/hle/service/caps/caps_u.cpp
  src/core/hle/service/caps/caps_u.h
Labels: early-access-merge

#3396 Implement SpinLocks, Fibers and a Host Timer
  src/common/CMakeLists.txt
  src/common/fiber.cpp
  src/common/fiber.h
  src/common/spin_lock.cpp
  src/common/spin_lock.h
  src/common/thread.h
  src/common/uint128.cpp
  src/common/uint128.h
  src/common/wall_clock.cpp
  src/common/wall_clock.h
  src/common/x64/cpu_detect.cpp
  src/common/x64/cpu_detect.h
  src/common/x64/native_clock.cpp
  src/common/x64/native_clock.h
  src/core/CMakeLists.txt
  src/core/core_timing_util.cpp
  src/core/core_timing_util.h
  src/core/host_timing.cpp
  src/core/host_timing.h
  src/tests/CMakeLists.txt
  src/tests/common/fibers.cpp
  src/tests/core/host_timing.cpp
Labels: kernel-new

#4026 ldr: Update NRR/NRO structs
  src/core/hle/service/ldr/ldr.cpp
Labels: early-access-merge

#4140 renderer_vulkan: Update validation layer name and test before enabling
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
Labels: early-access-merge, vulkan

#4112 macro: Add support for "middle methods" on the code cache
  src/video_core/macro/macro.cpp
Labels: early-access-merge, gpu-fix

#4191 maxwell_to_gl/vk: Reorder vertex formats
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: gpu-fix

#4157 gl_device: Enable NV_vertex_buffer_unified_memory on Turing devices
  src/video_core/renderer_opengl/gl_device.cpp
Labels: early-access-merge, opengl

#4176 texture_cache: Check format compatibility before copying
  src/video_core/CMakeLists.txt
  src/video_core/compatible_formats.cpp
  src/video_core/compatible_formats.h
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, gpu-fix

#4166 Add "Open Quickstart Guide" and "FAQ" buttons to the Help menu
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: mainline-merge
