Repository yuzu-emu/yuzu, pull requests merged in 2020-10, with the labels that each got.

#4742 HID: Only use inputs corresponding to controller type
  src/core/hle/service/hid/controllers/npad.cpp
Labels: early-access-merge

#4727 Reduce the "shake" requirements when configuring UDP.
  src/input_common/udp/client.cpp
Labels: early-access-merge

#4737 capsrv: Stub 3 variants of SetShimLibraryVersion
  src/core/hle/service/caps/caps_c.cpp
  src/core/hle/service/caps/caps_c.h
  src/core/hle/service/caps/caps_su.cpp
  src/core/hle/service/caps/caps_u.cpp
  src/core/hle/service/caps/caps_u.h
Labels: early-access-merge

#4710 submission_package: Fix updates integrated into cartridge images.
  src/core/file_sys/submission_package.cpp
Labels: early-access-merge

#4736 hid: Stub HomeButtonInputProtection service commands
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge

#4765 renderer_vulkan/wrapper: Fix physical device sorting
  src/video_core/renderer_vulkan/wrapper.cpp
Labels: vulkan

#4677 InputCommon: Add random motion input for buttons
  src/input_common/CMakeLists.txt
  src/input_common/main.cpp
  src/input_common/motion_from_button.cpp
  src/input_common/motion_from_button.h
  src/input_common/motion_input.cpp
  src/input_common/motion_input.h
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/sdl/sdl_impl.h
  src/input_common/udp/client.cpp
Labels: early-access-merge

#4757 InputCommon: Add compatibility with only accelerometer and auto calibrate for drift
  src/input_common/motion_input.cpp
  src/input_common/motion_input.h
Labels: early-access-merge

#4766 shader/texture: Implement CUBE texture type for TMML and fix arrays
  src/video_core/shader/decode/texture.cpp
Labels: early-access-merge, gpu-fix

#3929 file_sys/nsp: Make SetTicketKeys actually do something
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
Labels: early-access-merge

#4786 core/CMakeLists: Make some warnings errors
  externals/CMakeLists.txt
  externals/httplib/httplib.h
  src/common/hex_util.h
  src/core/CMakeLists.txt
  src/core/crypto/key_manager.cpp
  src/core/file_sys/fsmitm_romfsbuild.cpp
  src/core/file_sys/ips_layer.cpp
  src/core/file_sys/nca_metadata.cpp
  src/core/file_sys/patch_manager.cpp
  src/core/frontend/emu_window.cpp
  src/core/frontend/framebuffer_layout.cpp
  src/core/gdbstub/gdbstub.cpp
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/handle_table.cpp
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/mii/manager.cpp
  src/core/hle/service/sockets/sockets_translate.cpp
  src/core/hle/service/sockets/sockets_translate.h
  src/core/hle/service/time/time_zone_manager.cpp
  src/core/hle/service/vi/vi.cpp
  src/core/loader/kip.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
  src/core/loader/nso.h
  src/core/memory.cpp
  src/core/memory/cheat_engine.cpp
  src/core/network/network.cpp
  src/web_service/web_backend.cpp
Labels: build-system-new

#4787 audio_core/CMakeLists: Make warnings consistent with core
  src/audio_core/CMakeLists.txt
  src/audio_core/algorithm/filter.cpp
  src/audio_core/algorithm/interpolate.cpp
  src/audio_core/command_generator.cpp
  src/audio_core/cubeb_sink.cpp
  src/audio_core/voice_context.cpp
Labels: build-system-new

#4772 vk_device: Block VK_EXT_extended_dynamic_state for RDNA devices
  src/video_core/renderer_vulkan/vk_device.cpp
Labels: early-access-merge

#4793 service: acc: Stub IManagerForApplication::StoreOpenContext.
  src/core/hle/service/acc/acc.cpp
Labels: early-access-merge

#4784 hle: service: vi: Implement BufferQueue::CancelBuffer.
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/vi/vi.cpp
Labels: early-access-merge

#4790 input_common/CMakeLists: Make some warnings errors
  src/common/math_util.h
  src/common/vector_math.h
  src/input_common/CMakeLists.txt
  src/input_common/analog_from_button.cpp
  src/input_common/gcadapter/gc_adapter.cpp
  src/input_common/gcadapter/gc_adapter.h
  src/input_common/gcadapter/gc_poller.cpp
  src/input_common/keyboard.cpp
  src/input_common/main.cpp
  src/input_common/motion_emu.cpp
  src/input_common/motion_from_button.cpp
  src/input_common/motion_input.cpp
  src/input_common/motion_input.h
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/touch_from_button.cpp
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
  src/input_common/udp/udp.cpp
  src/yuzu/configuration/configure_motion_touch.cpp
Labels: build-system-new

#4798 udp/client: Take std::function by const reference with TestCommunication()
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
Labels: general

#4797 service: bcat: Check client connection before interacting with socket.
  src/core/hle/service/bcat/backend/boxcat.cpp
Labels: early-access-merge

#4782 vk_graphics_pipeline: Manage primitive topology as fixed state
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: early-access-merge, vulkan

#4801 mii/manager: Make use of unused lower bound in GetRandomValue()
  src/core/hle/service/mii/manager.cpp
Labels: bug

#4783 hle: service: nvdrv: Implement nvhost_as_gpu::FreeSpace.
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
Labels: early-access-merge

#4802 core: Add boxcat sources with target_sources
  src/core/CMakeLists.txt
Labels: general

#4204 renderer_vulkan: Create and properly use Vulkan 1.0 instances when 1.1 is not available
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
Labels: early-access-merge, vulkan

#4785 filesystem: Fix CreateDirectory and DeleteFile
  src/core/hle/service/filesystem/filesystem.cpp
Labels: early-access-merge

#4788 kernel: Implement host thread register methods without locking
  src/core/hle/kernel/kernel.cpp
Labels: early-access-merge

#4627 sdl_impl: Erase the SDLJoystick entry after removing a controller
  src/input_common/sdl/sdl_impl.cpp
Labels: early-access-merge

#4809 configure_input_player: Fix modifier buttons
  src/input_common/settings.h
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
Labels: early-access-merge

#4390 nifm: GetAppletInfo stub
  src/core/hle/service/nifm/nifm.cpp
Labels: early-access-merge

#4807 gl_arb_decompiler: Implement robust buffer operations
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: early-access-merge, opengl

#4811 video_core: Conditially activate relevant compiler warnings
  src/video_core/CMakeLists.txt
Labels: build-system-new

#4792 service: time: Update current time with changes to RTC setting.
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/time/time.cpp
  src/core/hle/service/time/time.h
  src/core/hle/service/time/time_manager.cpp
  src/core/hle/service/time/time_manager.h
  src/core/hle/service/time/time_zone_content_manager.cpp
  src/core/hle/service/time/time_zone_content_manager.h
  src/yuzu/configuration/configure_system.cpp
Labels: early-access-merge

#4706 video_core: Fix instances where msbuild always regenerated host shaders
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/StringShaderHeader.cmake
Labels: build-system-fix

#4816 sdl_impl: Fix controller reconnection issues
  src/input_common/sdl/sdl_impl.cpp
Labels: early-access-merge

#4817 main/profile_select: Don't ask for profile when there's only one.
  src/yuzu/applets/profile_select.cpp
  src/yuzu/applets/profile_select.h
  src/yuzu/main.cpp
Labels: early-access-merge

#4834 controller: Pass ControllerParameters by reference in ReconfigureControllers()
  src/core/frontend/applets/controller.cpp
  src/core/frontend/applets/controller.h
  src/yuzu/applets/controller.cpp
  src/yuzu/applets/controller.h
Labels: general

#4832 core: cpu_manager: Add missing call to MicroProfileOnThreadExit().
  src/core/cpu_manager.cpp
Labels: early-access-merge

#4729 video_core: NVDEC Implementation
  CMakeLists.txt
  CMakeModules/CopyYuzuFFmpegDeps.cmake
  externals/find-modules/FindFFmpeg.cmake
  src/common/CMakeLists.txt
  src/common/stream.cpp
  src/common/stream.h
  src/core/CMakeLists.txt
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/core/hle/service/nvdrv/devices/nvhost_vic.h
  src/core/hle/service/nvdrv/devices/nvmap.h
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/core/settings.cpp
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/video_core/CMakeLists.txt
  src/video_core/cdma_pusher.cpp
  src/video_core/cdma_pusher.h
  src/video_core/command_classes/codecs/codec.cpp
  src/video_core/command_classes/codecs/codec.h
  src/video_core/command_classes/codecs/h264.cpp
  src/video_core/command_classes/codecs/h264.h
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/codecs/vp9.h
  src/video_core/command_classes/codecs/vp9_types.h
  src/video_core/command_classes/host1x.cpp
  src/video_core/command_classes/host1x.h
  src/video_core/command_classes/nvdec.cpp
  src/video_core/command_classes/nvdec.h
  src/video_core/command_classes/nvdec_common.h
  src/video_core/command_classes/sync_manager.cpp
  src/video_core/command_classes/sync_manager.h
  src/video_core/command_classes/vic.cpp
  src/video_core/command_classes/vic.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_asynch.h
  src/video_core/gpu_synch.cpp
  src/video_core/gpu_synch.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/video_core.cpp
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_graphics.ui
Labels: early-access-merge

#4846 service: Update function tables
  src/core/hle/service/am/am.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/mii/mii.cpp
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set_sys.cpp
Labels: general

#4838 sync_manager: Amend parameter order of calls to SyncptIncr constructor
  src/video_core/command_classes/sync_manager.cpp
  src/video_core/command_classes/sync_manager.h
Labels: bug

#4857 web_service: follow-up fix to #4842
  externals/httplib/README.md
  externals/httplib/httplib.h
  src/web_service/web_backend.cpp
Labels: early-access-merge

#4781 Add hotplug, rumble and fix 3rd party adapters for the GC adapter
  src/input_common/gcadapter/gc_adapter.cpp
  src/input_common/gcadapter/gc_adapter.h
  src/input_common/gcadapter/gc_poller.cpp
Labels: early-access-merge

#4837 nvdec: Minor tidying up
  src/video_core/command_classes/codecs/codec.cpp
  src/video_core/command_classes/codecs/codec.h
  src/video_core/command_classes/codecs/h264.cpp
  src/video_core/command_classes/codecs/h264.h
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/codecs/vp9.h
  src/video_core/command_classes/codecs/vp9_types.h
  src/video_core/command_classes/host1x.cpp
  src/video_core/command_classes/host1x.h
  src/video_core/command_classes/nvdec.cpp
  src/video_core/command_classes/nvdec.h
  src/video_core/command_classes/vic.cpp
  src/video_core/command_classes/vic.h
Labels: general

#4867 VP9: Minor interface changes and safety improvements
  src/common/stream.h
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/codecs/vp9.h
Labels: general

#4868 General: Make ignoring a discarded return value an error
  src/CMakeLists.txt
  src/common/file_util.h
  src/common/misc.cpp
Labels: build-system-new

#4853 shader/arithmetic: Implement FCMP immediate + register variant
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/arithmetic.cpp
Labels: early-access-merge
