Repository yuzu-emu/yuzu, pull requests merged in 2020-02, with the labels that each got.

#3284 hid: Fix analog sticks directional states
  src/core/frontend/input.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/input_common/sdl/sdl_impl.cpp
Labels: early-access-merge

#3268 GUI: Deadzone controls for sdl engine at configuration input
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_input_player.ui
Labels: early-access-merge

#3282 Partially implement Indexed samplers in general and specific code in GLSL
  src/video_core/CMakeLists.txt
  src/video_core/engines/const_buffer_engine_interface.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/guest_driver.cpp
  src/video_core/guest_driver.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/const_buffer_locker.cpp
  src/video_core/shader/const_buffer_locker.h
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/node.h
  src/video_core/shader/node_helper.h
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/shader/track.cpp
Labels: early-access-merge, gpu-new

#3370 shader: Remove curly braces initializers on shared pointers
  src/video_core/shader/ast.h
  src/video_core/shader/decode/arithmetic_integer.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/node.h
  src/video_core/shader/track.cpp
Labels: style

#3374 input_common/udp: Minor changes
  src/input_common/main.cpp
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
  src/input_common/udp/protocol.h
  src/input_common/udp/udp.cpp
  src/input_common/udp/udp.h
Labels: general

#3360 GUI: Togglable graphics settings buttons in status bar
  dist/qt_themes/colorful/style.qrc
  dist/qt_themes/colorful/style.qss
  dist/qt_themes/default/default.qrc
  dist/qt_themes/default/style.qss
  dist/qt_themes/qdarkstyle/style.qss
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#3356 shader/arithmetic: Implement FCMP
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/arithmetic.cpp
Labels: early-access-merge, gpu-new

#3357 shader/bfi: Implement register-constant buffer variant
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/bfi.cpp
Labels: early-access-merge, gpu-new

#3377 vk_rasterizer: Use noexcept methods of std::bitset
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: vulkan

#3366 applets: Fixes for software keyboard and transfer memory.
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/transfer_memory.cpp
  src/core/hle/kernel/transfer_memory.h
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/kernel/vm_manager.h
  src/core/hle/kernel/wait_object.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/error.cpp
  src/core/hle/service/am/applets/general_backend.cpp
  src/core/hle/service/am/applets/profile_select.cpp
  src/core/hle/service/am/applets/software_keyboard.cpp
  src/core/hle/service/am/applets/web_browser.cpp
Labels: hle-fix, mainline-merge

#3362 gl_rasterizer: Fix instanced draw arrays
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: early-access-merge, opengl

#3381 hle: services: Fix prepo IPC, and add better error checking.
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/service/prepo/prepo.cpp
Labels: early-access-merge, hle-fix

#3369 shader/shift: Implement SHF
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/shift.cpp
Labels: early-access-merge, gpu-new

#3378 maxwell_to_gl: Implement R8G8_USCALED
  src/video_core/renderer_opengl/maxwell_to_gl.h
Labels: early-access-merge, opengl

#3386 video_core: memory_manager: Use GPU interface for cache functions.
  src/video_core/gpu.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: early-access-merge

#3387 gpu_thread: Use MPSCQueue for GPU commands.
  src/video_core/gpu_thread.h
Labels: early-access-merge

#3388 hle: services: Use std::shared_ptr instead of copy by value.
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/am/applets/error.cpp
  src/core/hle/service/am/applets/general_backend.cpp
  src/core/hle/service/am/applets/profile_select.cpp
  src/core/hle/service/am/applets/software_keyboard.cpp
  src/core/hle/service/am/applets/web_browser.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: early-access-merge

#3372 maxwell_3d: Fix stencil back mask
  src/video_core/engines/maxwell_3d.h
Labels: early-access-merge, gpu-fix

#3376 gl_rasterizer: Implement GL_POINT_SPRITE
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
Labels: early-access-merge, opengl

#3402 kernel/thread: Remove trivial usages of the global system accessor
  src/core/hle/kernel/thread.cpp
Labels: general

#3403 bcat/backend: Prevent fmt exception in debug log within NullBackend::Clear()
  src/core/hle/service/bcat/backend/backend.cpp
Labels: bug

#3405 address_arbiter: Minor cleanup to list querying
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/address_arbiter.h
Labels: general

#3395 GPU: Refactor queries implementation and correct GPU Clock.
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: early-access-merge, gpu-fix

#3379 shader/decode: Fix constant buffer offsets
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/arithmetic_integer.cpp
  src/video_core/shader/decode/bfi.cpp
Labels: early-access-merge, gpu-fix

#3419 Revert "video_core: memory_manager: Use GPU interface for cache functions."
  src/video_core/gpu.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: early-access-merge

#3420 nvhost_gpu: implement ChannelSetTimeslice
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.h
Labels: early-access-merge

#3412 GUI: Add aspect ratio dropdown
  src/core/frontend/framebuffer_layout.cpp
  src/core/frontend/framebuffer_layout.h
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
  src/yuzu_tester/config.cpp
  src/yuzu_tester/default_ini.h
Labels: early-access-merge

#3409 query_cache: Implement a query cache and query 21 (samples passed)
  src/video_core/CMakeLists.txt
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/query_cache.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_query_cache.cpp
  src/video_core/renderer_opengl/gl_query_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_resource_manager.cpp
  src/video_core/renderer_opengl/gl_resource_manager.h
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
Labels: early-access-merge, gpu-new

#3410 vk_shader_decompiler: Fix vertex id and instance id
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Labels: early-access-merge, gpu-fix, vulkan

#3437 shader_conversion: add conversion I2F for Short
  src/video_core/shader/decode/conversion.cpp
Labels: early-access-merge, gpu-new

#3411 gl_rasterizer: Use the least generic OpenGL draw function possible
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge, opengl

#3414 maxwell_3d: Unify draw methods
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: early-access-merge, gpu

#3415 shader/texture: Allow 2D shadow arrays and simplify code
  src/video_core/shader/decode/texture.cpp
Labels: early-access-merge, gpu-fix

#3432 Update httplib to 0.5.5
  externals/httplib/README.md
  externals/httplib/httplib.h
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/web_service/web_backend.cpp
Labels: early-access-merge, externals

#3438 video_core: memory_manager: Flush/invalidate asynchronously when possible.
  src/video_core/memory_manager.cpp
Labels: gpu

#3423 texture_cache: Avoid matches in 3D textures
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, gpu-fix

#3435 vulkan: add DXT23_SRGB
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
Labels: early-access-merge, gpu-new, vulkan

#3434 vk_shader: Implement ImageLoad
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Labels: early-access-merge, gpu-new, vulkan

#3433 renderer_vulkan: Add the rest of case for TryConvertBorderColor
  src/video_core/renderer_vulkan/vk_sampler_cache.cpp
Labels: early-access-merge, vulkan

#3442 shader/texture: Fix illegal 3D texture assert
  src/video_core/shader/decode/texture.cpp
Labels: gpu-fix

#3310 audio_core: Switch to a faster interpolation technique
  src/audio_core/algorithm/interpolate.cpp
  src/audio_core/algorithm/interpolate.h
Labels: audio-fix, early-access-merge, performance

#3416 Kernel: Refactors and Implement a TimeManager and SchedulerLocks
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.h
  src/core/hardware_properties.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/time_manager.cpp
  src/core/hle/kernel/time_manager.h
Labels: early-access-merge

#3422 surface_base: Implement texture buffer flushes
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/texture_cache/surface_base.cpp
Labels: early-access-merge, gpu-new, opengl

#3424 vk_shader_decompiler: Implement Layer output attribute
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Labels: early-access-merge, vulkan

#3425 texture_cache: Implement layered framebuffer attachments
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/surface_params.h
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, gpu-new

#3417 texture: Implement R32I
  src/video_core/morton.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/format_lookup_table.cpp
Labels: early-access-merge, gpu-new

#3460 video_core/gpu: Remove unused functions
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: general

#3461 video_core/surface: Add R32_SINT render target format
  src/video_core/gpu.h
  src/video_core/surface.cpp
Labels: gpu-new

#3431 InputCommon: analog_from_button get direction implementation
  src/core/hle/service/hid/controllers/npad.cpp
  src/input_common/analog_from_button.cpp
Labels: early-access-merge, hle-fix

#3440 shader: implement LOP3 fast replace for old function
  src/video_core/shader/decode/arithmetic_integer.cpp
Labels: early-access-merge, gpu-fix

#3441 shader: FMUL switch to using LUT
  src/video_core/shader/decode/arithmetic.cpp
Labels: early-access-merge

#3430 Port citra-emu/citra#4940: "Split Presentation thread from Render thread"
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/frontend/emu_window.h
  src/core/frontend/framebuffer_layout.h
  src/core/frontend/scope_acquire_context.cpp
  src/core/frontend/scope_acquire_context.h
  src/core/frontend/scope_acquire_window_context.cpp
  src/core/settings.cpp
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/video_core/gpu_thread.cpp
  src/video_core/renderer_base.h
  src/video_core/renderer_opengl/gl_resource_manager.cpp
  src/video_core/renderer_opengl/gl_resource_manager.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.h
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h
  src/yuzu_cmd/yuzu.cpp
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.cpp
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
Labels: early-access-merge, frontend-new

#3448 audio_core: interpolate: Improvements to fix audio crackling.
  src/audio_core/algorithm/interpolate.cpp
  src/audio_core/algorithm/interpolate.h
Labels: audio-fix, early-access-merge
