Repository yuzu-emu/yuzu, pull requests merged in 2020-04, with the labels that each got.

#3591 renderer_vulkan/wrapper: Add a Vulkan wrapper (part 2 of 2)
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
Labels: vulkan

#3552 Refactor Context management (Fixes renderdoc on opengl issues)
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/frontend/emu_window.h
  src/core/frontend/scope_acquire_context.cpp
  src/core/frontend/scope_acquire_context.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_asynch.h
  src/video_core/gpu_synch.cpp
  src/video_core/gpu_synch.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/renderer_base.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/video_core.cpp
  src/video_core/video_core.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h
  src/yuzu_cmd/yuzu.cpp
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.cpp
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
  src/yuzu_tester/yuzu.cpp
Labels: core-fix, early-access-merge, gpu-fix

#3595 shader/memory: Silence no return value warning
  src/video_core/shader/decode/memory.cpp
Labels: style

#3563 services: ldr: Fix MemoryState for read/write regions of NROs.
  src/core/hle/service/ldr/ldr.cpp
Labels: early-access-merge, hle-fix

#3589 gl_rasterizer: Mark cleared textures as dirty
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge, gpu-fix, opengl

#3592 shader_decompiler: Remove FragCoord.w hack and change IPA implementation
  src/video_core/engines/shader_header.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/other.cpp
Labels: early-access-merge, gpu-fix

#3513 video_core: Use native ASTC when available
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/surface_base.cpp
  src/video_core/texture_cache/surface_base.h
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/surface_params.h
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, opengl, vulkan

#3489 shader: implement SULD.D bits32/64
  src/video_core/shader/decode/image.cpp
  src/video_core/shader/shader_ir.h
Labels: do-not-merge, early-access-merge, gpu-new

#3599 Revert "Merge pull request #3499 from ReinUsesLisp/depth-2d-array"
  src/video_core/texture_cache/surface_params.cpp
Labels: early-access-merge, gpu-fix

#3621 Log version and about section version fix
  src/yuzu/about_dialog.cpp
  src/yuzu/main.cpp
Labels: frontend-fix

#3572 Port citra-emu/citra#5127: "common: Port some changes from dolphin"
  src/common/file_util.cpp
  src/common/thread.cpp
Labels: general

#3601 video_core/shader: Add some instruction and S2R encodings
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/shader_ir.cpp
Labels: gpu

#3610 Refactor all the GPU Caches to use VAddr for cache addressing
  src/core/memory.cpp
  src/core/memory.h
  src/video_core/buffer_cache/buffer_block.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/map_interval.h
  src/video_core/gpu.h
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_asynch.h
  src/video_core/gpu_synch.cpp
  src/video_core/gpu_synch.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/query_cache.h
  src/video_core/rasterizer_cache.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/texture_cache/surface_base.cpp
  src/video_core/texture_cache/surface_base.h
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, gpu-fix

#3622 video_core/texture: Use a LUT to convert sRGB texture borders
  src/video_core/CMakeLists.txt
  src/video_core/textures/texture.cpp
  src/video_core/textures/texture.h
Labels: early-access-merge, gpu-fix

#3623 qt/bootmanager: Remove unnecessary glBindFramebuffer
  src/yuzu/bootmanager.cpp
Labels: early-access-merge, gpu

#3607 yuzu/configuration: Fix input profiles and a wrong assert
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_simple.cpp
  src/yuzu/configuration/configure_mouse_advanced.cpp
Labels: early-access-merge, general

#3594 yuzu: Drop SDL2 and Qt frontend Vulkan requirements
  src/common/CMakeLists.txt
  src/common/dynamic_library.cpp
  src/common/dynamic_library.h
  src/core/frontend/emu_window.h
  src/video_core/renderer_vulkan/declarations.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/yuzu/CMakeLists.txt
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.cpp
  src/yuzu_tester/emu_window/emu_window_sdl2_hide.h
Labels: early-access-merge, vulkan

#3611 Port citra-emu/citra#4956: "Fixes to game list sorting"
  src/yuzu/game_list.cpp
  src/yuzu/game_list_p.h
Labels: early-access-merge, frontend-fix

#3635 Buffer queue: Correct behavior of free buffer.
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
Labels: early-access-merge

#3644 video_core: Add MSAA registers in 3D engine and TIC
  src/video_core/engines/maxwell_3d.h
  src/video_core/textures/texture.h
Labels: gpu

#3578 shader/video: Partially implement VMNMX
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/video.cpp
  src/video_core/shader/shader_ir.h
Labels: early-access-merge, gpu-new

#3606 service/vi: Partially implement BufferQueue disconnect
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/vi/vi.cpp
Labels: early-access-merge, hle-fix

#3633 shader/texture: Remove type mismatches management from shader decoder
  src/video_core/shader/decode/texture.cpp
Labels: early-access-merge, gpu

#3646 gl_shader_decompiler: Improve generated code in HMergeH*
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: early-access-merge, gpu-fix, opengl

#3627 gl_texture_cache: Attach view instead of base texture for layered attchments
  src/video_core/renderer_opengl/gl_texture_cache.cpp
Labels: early-access-merge, opengl

#3631 texture/astc: More small ASTC optimizations
  src/video_core/textures/astc.cpp
Labels: early-access-merge, performance

#3638 texture_cache: Remove preserve_contents
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: gpu

#3651 gl_rasterizer: Implement line widths and smooth lines
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state_tracker.cpp
  src/video_core/renderer_opengl/gl_state_tracker.h
Labels: gpu-new, opengl

#3634 Texture Cache: Only do buffer copies on accurate GPU.
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge

#3657 vk_rasterizer: Default to 1 viewports with a size of 0
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge, vulkan

#3667 vk_blit_screen: Initialize all members in VkPipelineViewportStateCreateInfo
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
Labels: mainline-merge, vulkan

#3664 Revert "gl_shader_decompiler: Implement merges with bitfieldInsert"
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: early-access-merge, gpu-fix, opengl

#3663 shader/arithmetic: Add FCMP_CR variant
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/arithmetic.cpp
Labels: early-access-merge, gpu-new

#3654 gl_texture_cache: Fix layered texture attachment base level
  src/video_core/renderer_opengl/gl_texture_cache.cpp
Labels: early-access-merge, opengl

#3656 gl_shader_cache: Use CompileDepth::FullDecompile on GLSL
  src/video_core/renderer_opengl/gl_shader_cache.cpp
Labels: early-access-merge, opengl

#3668 maxwell_to_vk: Add uint16 vertex formats
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: early-access-merge, vulkan

#3662 gl_rasterizer: Implement constant vertex attributes
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge, opengl

#3670 CMakeLists: Make -Wreorder a compile-time error
  src/CMakeLists.txt
  src/core/hle/kernel/kernel.cpp
  src/video_core/gpu_asynch.cpp
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: build-system-new

#3612 shader/memory: Implement RED.E.ADD and minor changes to ATOM
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/node.h
Labels: early-access-merge, gpu-fix, gpu-new

#3649 Texture Cache: Read current data when flushing a 3D segment.
  src/video_core/texture_cache/surface_base.cpp
Labels: early-access-merge, gpu-fix

#3683 video_core: Amend doxygen comment references
  src/video_core/renderer_vulkan/vk_memory_manager.h
  src/video_core/texture_cache/texture_cache.h
Labels: general

#3685 control_flow: Make use of std::move in TryInspectAddress()
  src/video_core/shader/control_flow.cpp
Labels: general

#3687 surface_base: Make IsInside() a const member function
  src/video_core/texture_cache/surface_base.h
Labels: general

#3680 gl_device: Mark stage_swizzle as constexpr
  src/video_core/renderer_opengl/gl_device.cpp
Labels: general

#3688 surface_view: Add missing operator!= to ViewParams
  src/video_core/texture_cache/surface_view.cpp
  src/video_core/texture_cache/surface_view.h
Labels: general

#3689 decode/shift: Remove unused variable within Shift()
  src/video_core/shader/decode/shift.cpp
Labels: general

#3659 service: time: Implement CalculateStandardUserSystemClockDifferenceByUser.
  src/core/hle/service/time/interface.cpp
  src/core/hle/service/time/time.cpp
  src/core/hle/service/time/time.h
Labels: early-access-merge

#3600 buffer_cache: Return handles instead of pointer to handles
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/utils.cpp
  src/video_core/renderer_opengl/utils.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.h
Labels: early-access-merge, gpu

#3673 CMakeLists: Specify -Wextra on linux builds
  src/CMakeLists.txt
  src/core/arm/arm_interface.cpp
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/vfs_libzip.cpp
  src/core/frontend/framebuffer_layout.cpp
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/time/time_zone_manager.cpp
  src/core/hle/service/vi/vi.cpp
  src/core/memory/dmnt_cheat_vm.cpp
  src/core/telemetry_session.cpp
  src/input_common/sdl/sdl_impl.cpp
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/decode/image.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/track.cpp
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/texture_cache.h
  src/web_service/web_backend.cpp
  src/yuzu/debugger/profiler.cpp
  src/yuzu/game_list_worker.cpp
  src/yuzu/main.cpp
Labels: build-system-new, early-access-merge

#3671 kernel/thread: Resolve -Wswitch warnings
  src/core/hle/kernel/thread.cpp
Labels: general

#3682 gl_query_cache: Resolve use-after-move in CachedQuery move assignment operator
  src/video_core/renderer_opengl/gl_query_cache.cpp
Labels: bug

#3672 file_util: Early-exit in WriteArray and ReadArray if specified lengths are zero
  src/common/file_util.cpp
  src/common/file_util.h
Labels: bug, early-access-merge

#3703 Revert "gl_shader_cache: Use CompileDepth::FullDecompile on GLSL"
  src/video_core/renderer_opengl/gl_shader_cache.cpp
Labels: mainline-merge

#3630 common/file_util: Allow access to files on network shares
  src/common/file_util.cpp
Labels: early-access-merge, general

#3711 memory/slab_heap: Make use of static_cast over reinterpret_cast
  src/core/hle/kernel/memory/slab_heap.h
Labels: general

#3713 service/time: Minor changes
  src/core/hle/service/time/standard_network_system_clock_core.h
  src/core/hle/service/time/steady_clock_core.h
  src/core/hle/service/time/system_clock_context_update_callback.h
  src/core/hle/service/time/system_clock_core.cpp
  src/core/hle/service/time/system_clock_core.h
Labels: general

#3710 loader/nso: Resolve moves not occurring in DecompressSegment
  src/core/loader/nso.cpp
Labels: general

#3679 track: Eliminate redundant copies
  src/video_core/shader/track.cpp
Labels: general

#3696 hle_ipc: Remove std::size_t casts where applicable
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
Labels: general

#3686 texture_cache/format_lookup_table: Fix incorrect green, blue, and alpha indices
  src/video_core/texture_cache/format_lookup_table.cpp
Labels: bug, early-access-merge

#3694 vk_compute_pass: Implement indexed quads
  src/video_core/renderer_vulkan/shaders/quad_indexed.comp
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: early-access-merge, vulkan

#3729 dma_pusher: Remove reliance on the global system instance
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
  src/video_core/gpu.cpp
Labels: general

#3709 am: Resolve ineffective moves
  src/core/hle/service/am/am.cpp
Labels: general

#3712 service: Remove unused RequestParser instances
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/es/es.cpp
Labels: general

#3700 vk_stream_buffer: Fix out of memory on boot on recent Nvidia drivers
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.h
Labels: early-access-merge, vulkan

#3733 Initialize quad_indexed_pass before uint8_pass
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: general

#3695 maxwell_3d: Initialize format attributes constant as one
  src/video_core/engines/maxwell_3d.cpp
Labels: early-access-merge, gpu-fix

#3736 audio_renderer: Preliminary BehaviorInfo
  src/audio_core/CMakeLists.txt
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/audio_core/behavior_info.cpp
  src/audio_core/behavior_info.h
  src/audio_core/common.h
  src/core/hle/service/audio/audren_u.cpp
Labels: audio-new, early-access-merge

#3724 core: arm_unicorn: Fix interpret fallback by temporarily mapping instruction page.
  src/core/arm/unicorn/arm_unicorn.cpp
Labels: early-access-merge

#3698 General: Resolve minor assorted warnings
  src/core/crypto/key_manager.cpp
  src/core/hle/service/time/time_zone_manager.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/texture.cpp
Labels: general

#3718 fixed_pipeline_state: Pack structure, use memcmp and CityHash on it
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge, performance, vulkan

#3714 gl_shader_decompiler: Avoid copies where applicable
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: general

#3653 renderer_vulkan: Integrate Nvidia Nsight Aftermath on Windows
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/nsight_aftermath_tracker.cpp
  src/video_core/renderer_vulkan/nsight_aftermath_tracker.h
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
Labels: early-access-merge, vulkan

#3758 Introduce dummy context for yuzu-cmd VK support
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h
Labels: frontend-fix

#3725 thread: FPCR.FZ is likely not 1 (and FPCR.RMode = TieAway and FPCR.DN = 0)
  src/core/hle/kernel/thread.cpp
Labels: create-testing-build, early-access-merge

#3767 vk_pipeline_cache: Fix unintentional memcpy into optional
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: vulkan

#3677 Introduce Predictive Flushing and Improve ASYNC GPU
  src/core/settings.cpp
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/map_interval.h
  src/video_core/dma_pusher.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/fence_manager.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/gpu_asynch.cpp
  src/video_core/gpu_asynch.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/query_cache.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_fence_manager.cpp
  src/video_core/renderer_opengl/gl_fence_manager.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_vulkan/vk_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
  src/video_core/texture_cache/surface_base.h
  src/video_core/texture_cache/texture_cache.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
  src/yuzu_tester/config.cpp
Labels: early-access-merge, gpu-fix, gpu-new

#3697 CMakeLists: Enable -Wmissing-declarations on Linux builds
  externals/microprofile/microprofile.h
  externals/microprofile/microprofileui.h
  src/CMakeLists.txt
  src/core/crypto/partition_data_manager.cpp
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/core/hle/service/es/es.cpp
  src/tests/core/core_timing.cpp
  src/video_core/engines/fermi_2d.cpp
  src/video_core/shader/control_flow.cpp
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
  src/yuzu/applets/profile_select.cpp
Labels: build-system-new, early-access-merge

#3730 service/time: Remove reliance on the global system accessor
  src/core/hle/service/time/time.cpp
Labels: general

#3707 kernel: memory: Improve implementation of device shared memory.
  src/core/hle/kernel/memory/memory_block.h
  src/core/hle/kernel/memory/memory_block_manager.cpp
  src/core/hle/kernel/memory/memory_block_manager.h
  src/core/hle/kernel/memory/page_table.cpp
  src/core/hle/kernel/memory/page_table.h
  src/video_core/memory_manager.cpp
Labels: early-access-merge, kernel-new

#3781 shared_memory: Amend doxygen reference
  src/core/hle/kernel/shared_memory.cpp
  src/core/hle/kernel/shared_memory.h
Labels: general

#3778 svc: Remove unused variable
  src/core/hle/kernel/svc.cpp
Labels: general

#3777 page_table: Remove unused captures
  src/core/hle/kernel/memory/page_table.cpp
Labels: general

#3749 shader/arithmetic_integer: Fix LEA_IMM encoding
  src/video_core/shader/decode/arithmetic_integer.cpp
Labels: early-access-merge, gpu-fix

#3780 svc: Re-add MapProcessCodeMemory/UnmapProcessCodeMemory
  src/core/hle/kernel/svc.cpp
Labels: early-access-merge, kernel-new

#3734 decode/arithmetic_half: Fix HADD2 and HMUL2 absolute and negation bits
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/arithmetic_half.cpp
Labels: early-access-merge, gpu-fix

#3721 vulkan/wrapper: Sort physical devices
  src/video_core/renderer_vulkan/wrapper.cpp
Labels: early-access-merge, vulkan

#3761 configure_input_player: Use slider to edit modifier scale
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_input_player.ui
Labels: early-access-merge, frontend-fix

#3791 configuration: Add Restore Default and Clear options to hotkeys
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_hotkeys.cpp
  src/yuzu/configuration/configure_hotkeys.h
  src/yuzu/configuration/configure_hotkeys.ui
Labels: frontend-new

#3753 {gl,vk}_rasterizer: Add lazy default buffer maker and use it for empty buffers
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
Labels: early-access-merge, opengl, vulkan

#3744 service: Update function tables
  src/core/hle/service/acc/acc_su.cpp
  src/core/hle/service/acc/acc_u1.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/audio/audctl.cpp
  src/core/hle/service/bcat/module.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/ncm/ncm.cpp
  src/core/hle/service/npns/npns.cpp
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/pctl/module.cpp
  src/core/hle/service/prepo/prepo.cpp
  src/core/hle/service/set/set_cal.cpp
  src/core/hle/service/set/set_sys.cpp
  src/core/hle/service/sockets/bsd.cpp
  src/core/reporter.h
Labels: hle-new

#3742 Optimize GPU Command Lists and Introduce Fast GPU Time Option
  src/core/settings.h
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_tester/config.cpp
Labels: early-access-merge, gpu-new, performance

#3797 services: hid: Stub StopSevenSixAxisSensor.
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge, hle-new

#3756 vk_memory_manager: Remove unified memory model flag
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_memory_manager.cpp
  src/video_core/renderer_vulkan/vk_memory_manager.h
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
Labels: early-access-merge, vulkan

#3766 vk_renderpass_cache: Pack renderpass cache key and unify keys
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_renderpass_cache.cpp
  src/video_core/renderer_vulkan/vk_renderpass_cache.h
Labels: early-access-merge, vulkan

#3785 vi: Don't let uninitialized data pass as a response for SetBufferCount
  src/core/hle/service/vi/vi.cpp
Labels: early-access-merge, hle-fix

#3784 shader/memory_util: Deduplicate code
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/decode.cpp
  src/video_core/shader/memory_util.cpp
  src/video_core/shader/memory_util.h
  src/video_core/shader/shader_ir.h
Labels: gpu-fix

#3783 physical_core: Make use of std::make_unique instead of std::make_shared in ctor
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/arm/unicorn/arm_unicorn.h
  src/core/hle/kernel/physical_core.cpp
Labels: general

#3771 Dump RomFS command to include Updates
  src/yuzu/main.cpp
Labels: general

#3788 Revert: shader_decode: Fix LD, LDG when track constant buffer.
  src/video_core/shader/track.cpp
Labels: early-access-merge, gpu-fix

#3805 texture_cache: Reintroduce preserve_contents accurately
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, performance

#3807 maxwell_3d: Fix depth clamping register
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: early-access-merge, gpu-fix

#3831 caps: Add missing service names to caps:su
  src/core/hle/service/caps/caps_su.cpp
Labels: general

#3832 nim: CreateServerInterface, CreateAccessorInterface, CreateAsyncInterface
  src/core/hle/service/nim/nim.cpp
Labels: hle-new

#3835 fs-srv: GetFreeSpaceSize & GetTotalSpaceSize
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: hle-new

#3830 am: GetFriendInvitationStorageChannelEvent
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: hle-new

#3823 am: IsVrModeEnabled & SetVrModeEnabled fixes
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: early-access-merge, hle-fix
