Repository yuzu-emu/yuzu, pull requests merged in 2020-09, with the labels that each got.

#4587 externals/microprofile: Fix data race in g_bUseLock
  externals/microprofile/microprofile.h
Labels: bug

#4589 hle/kernel: Fix data race in GetCurrentHostThreadID
  src/core/hle/kernel/kernel.cpp
Labels: bug

#4588 common/thread: Fix data race in is_set
  src/common/thread.h
Labels: bug

#4625 externals: Work around libusb duplicate GUID errors
  externals/libusb/CMakeLists.txt
Labels: externals

#4564 file_sys: Replace inclusions with forward declarations where applicable
  src/core/crypto/partition_data_manager.cpp
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/bis_factory.h
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/content_archive.h
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/file_sys/kernel_executable.cpp
  src/core/file_sys/kernel_executable.h
  src/core/file_sys/nca_metadata.cpp
  src/core/file_sys/nca_metadata.h
  src/core/file_sys/partition_filesystem.cpp
  src/core/file_sys/partition_filesystem.h
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
  src/core/file_sys/romfs.h
  src/core/file_sys/sdmc_factory.cpp
  src/core/file_sys/sdmc_factory.h
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
  src/core/file_sys/xts_archive.cpp
  src/core/file_sys/xts_archive.h
  src/core/hle/service/ns/ns.cpp
Labels: general

#4568 fsp_srv: Resolve -Wmaybe_uninitialized warning in OpenSaveDataFileSystem()
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: general

#4626 file_sys/patch_manager: Add missing include
  src/core/file_sys/patch_manager.h
Labels: general

#4575 async_shaders: Mark getters as const member functions
  src/video_core/shader/async_shaders.cpp
  src/video_core/shader/async_shaders.h
Labels: general

#4590 hle/scheduler: Fix data race in is_context_switch_pending
  src/core/hle/kernel/scheduler.cpp
Labels: bug

#4578 common_funcs: Add missing XOR operators to DECLARE_ENUM_FLAG_OPERATORS
  src/common/common_funcs.h
Labels: general

#4583 gc_poller: Resolve compilation warnings on MSVC
  src/input_common/gcadapter/gc_poller.cpp
Labels: general

#4397 services: Implement most of bsd:s and GetCurrentIpAddress from nifm
  src/core/CMakeLists.txt
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/sockets/blocking_worker.h
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/sockets/bsd.h
  src/core/hle/service/sockets/sockets.cpp
  src/core/hle/service/sockets/sockets.h
  src/core/hle/service/sockets/sockets_translate.cpp
  src/core/hle/service/sockets/sockets_translate.h
Labels: early-access-merge, hle-new

#4606 game_list_p: Mark some constants as constexpr
  src/yuzu/game_list_p.h
Labels: general

#4635 gc_adapter: Make DeviceConnected() a const member function
  src/input_common/gcadapter/gc_adapter.cpp
  src/input_common/gcadapter/gc_adapter.h
  src/input_common/gcadapter/gc_poller.cpp
Labels: general

#4633 video_core: Remove all Core::System references in renderer
  src/core/core.cpp
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/fence_manager.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/query_cache.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_fence_manager.cpp
  src/video_core/renderer_opengl/gl_fence_manager.h
  src/video_core/renderer_opengl/gl_query_cache.cpp
  src/video_core/renderer_opengl/gl_query_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_opengl/gl_state_tracker.cpp
  src/video_core/renderer_opengl/gl_state_tracker.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_state_tracker.cpp
  src/video_core/renderer_vulkan/vk_state_tracker.h
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/shader/memory_util.cpp
  src/video_core/shader/memory_util.h
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/surface_params.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/video_core.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu_cmd/yuzu.cpp
  src/yuzu_tester/yuzu.cpp
Labels: gpu

#4608 configure_input_player: Resolve sign conversion warnings in UpdateMappingWithDefaults()
  src/yuzu/configuration/configure_input_player.cpp
Labels: general

#4597 Project Mjölnir: Part 2 - Controller Applet
  dist/icons/controller/applet_dual_joycon.png
  dist/icons/controller/applet_dual_joycon_dark.png
  dist/icons/controller/applet_dual_joycon_dark_disabled.png
  dist/icons/controller/applet_dual_joycon_disabled.png
  dist/icons/controller/applet_dual_joycon_midnight.png
  dist/icons/controller/applet_dual_joycon_midnight_disabled.png
  dist/icons/controller/applet_handheld.png
  dist/icons/controller/applet_handheld_dark.png
  dist/icons/controller/applet_handheld_dark_disabled.png
  dist/icons/controller/applet_handheld_disabled.png
  dist/icons/controller/applet_handheld_midnight.png
  dist/icons/controller/applet_handheld_midnight_disabled.png
  dist/icons/controller/applet_pro_controller.png
  dist/icons/controller/applet_pro_controller_dark.png
  dist/icons/controller/applet_pro_controller_dark_disabled.png
  dist/icons/controller/applet_pro_controller_disabled.png
  dist/icons/controller/applet_pro_controller_midnight.png
  dist/icons/controller/applet_pro_controller_midnight_disabled.png
  dist/icons/controller/applet_single_joycon_left.png
  dist/icons/controller/applet_single_joycon_left_dark.png
  dist/icons/controller/applet_single_joycon_left_dark_disabled.png
  dist/icons/controller/applet_single_joycon_left_disabled.png
  dist/icons/controller/applet_single_joycon_left_midnight.png
  dist/icons/controller/applet_single_joycon_left_midnight_disabled.png
  dist/icons/controller/applet_single_joycon_right.png
  dist/icons/controller/applet_single_joycon_right_dark.png
  dist/icons/controller/applet_single_joycon_right_dark_disabled.png
  dist/icons/controller/applet_single_joycon_right_disabled.png
  dist/icons/controller/applet_single_joycon_right_midnight.png
  dist/icons/controller/applet_single_joycon_right_midnight_disabled.png
  dist/icons/controller/controller.qrc
  dist/qt_themes/default/style.qss
  dist/qt_themes/qdarkstyle/style.qrc
  dist/qt_themes/qdarkstyle/style.qss
  dist/qt_themes/qdarkstyle_midnight_blue/style.qrc
  dist/qt_themes/qdarkstyle_midnight_blue/style.qss
  src/core/CMakeLists.txt
  src/core/frontend/applets/controller.cpp
  src/core/frontend/applets/controller.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/am/applets/controller.cpp
  src/core/hle/service/am/applets/controller.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/yuzu/CMakeLists.txt
  src/yuzu/applets/controller.cpp
  src/yuzu/applets/controller.h
  src/yuzu/applets/controller.ui
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input.h
  src/yuzu/configuration/configure_input_dialog.cpp
  src/yuzu/configuration/configure_input_dialog.h
  src/yuzu/configuration/configure_input_dialog.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#4310 audio_core: Apollo Part 1, AudioRenderer refactor
  src/audio_core/CMakeLists.txt
  src/audio_core/algorithm/interpolate.cpp
  src/audio_core/algorithm/interpolate.h
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/audio_core/behavior_info.cpp
  src/audio_core/behavior_info.h
  src/audio_core/command_generator.cpp
  src/audio_core/command_generator.h
  src/audio_core/common.h
  src/audio_core/cubeb_sink.cpp
  src/audio_core/effect_context.cpp
  src/audio_core/effect_context.h
  src/audio_core/info_updater.cpp
  src/audio_core/info_updater.h
  src/audio_core/memory_pool.cpp
  src/audio_core/memory_pool.h
  src/audio_core/mix_context.cpp
  src/audio_core/mix_context.h
  src/audio_core/sink_context.cpp
  src/audio_core/sink_context.h
  src/audio_core/splitter_context.cpp
  src/audio_core/splitter_context.h
  src/audio_core/stream.cpp
  src/audio_core/voice_context.cpp
  src/audio_core/voice_context.h
  src/core/hle/service/audio/audren_u.cpp
Labels: early-access-merge

#4323 kernel/scheduler: Use std::mutex instead of spin lock
  src/core/hle/kernel/scheduler.h
Labels: early-access-merge

#4636 service: Remove two usages of the global system accessor
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/hle/service/sm/sm.cpp
Labels: general

#4651 kernel: Remove all dependencies on the global system instance
  src/core/hle/kernel/client_session.cpp
  src/core/hle/kernel/client_session.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/server_session.h
  src/core/hle/kernel/svc.cpp
Labels: general

#4652 crypto/key_manager: Remove dependency on the global system accessor
  src/core/crypto/key_manager.cpp
  src/core/crypto/key_manager.h
  src/yuzu/main.cpp
Labels: general

#4655 patch_manager: Minor cleanup
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
Labels: general

#4657 cheat_engine: Remove unnecessary system argument to CheatParser's Parse function
  src/core/file_sys/patch_manager.cpp
  src/core/memory/cheat_engine.cpp
  src/core/memory/cheat_engine.h
Labels: general

#4658 nca_patch: Reduce stack usage size within SearchBucketEntry()
  src/core/file_sys/nca_patch.cpp
  src/core/file_sys/nca_patch.h
Labels: general

#4661 core/loader: Remove dependencies on the global system instance
  src/core/core.cpp
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/deconstructed_rom_directory.h
  src/core/loader/elf.cpp
  src/core/loader/elf.h
  src/core/loader/kip.cpp
  src/core/loader/kip.h
  src/core/loader/loader.h
  src/core/loader/nax.cpp
  src/core/loader/nax.h
  src/core/loader/nca.cpp
  src/core/loader/nca.h
  src/core/loader/nro.cpp
  src/core/loader/nro.h
  src/core/loader/nso.cpp
  src/core/loader/nso.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
Labels: general

#4662 bis_factory/romfs_factory: Eliminate dependencies on the global system instance
  src/core/core.cpp
  src/core/core.h
  src/core/file_sys/bis_factory.cpp
  src/core/file_sys/bis_factory.h
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/romfs_factory.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/nca.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
Labels: general

#4663 video_core: Enforce -Werror=switch
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/shader/decode/arithmetic_half.cpp
  src/video_core/shader/decode/image.cpp
Labels: general

#4653 gc_adapter: Disable MSVC nonstandard extension warning on libusb.h
  src/input_common/gcadapter/gc_adapter.cpp
Labels: general

#4668 control_metadata: Resolve typo in Portuguese language name
  src/core/file_sys/control_metadata.h
Labels: general

#4594 hid/configuration: Implement motion controls to HID
  src/core/frontend/input.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
  src/core/settings.h
  src/input_common/main.cpp
  src/input_common/main.h
  src/input_common/motion_emu.cpp
  src/input_common/settings.cpp
  src/input_common/settings.h
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
  src/input_common/udp/udp.cpp
  src/input_common/udp/udp.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_input_player.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_tester/config.cpp
Labels: early-access-merge

#4673 decode/image: Eliminate switch fallthrough in DecodeImage()
  src/video_core/shader/decode/image.cpp
Labels: general

#4672 decoder/texture: Eliminate narrowing conversion in GetTldCode()
  src/video_core/shader/decode/texture.cpp
Labels: general

#4671 command_generator/nfp: Eliminate unnecessary copies
  src/audio_core/command_generator.cpp
  src/core/hle/service/nfp/nfp.cpp
Labels: general

#4666 service: Remove unused funcation
  src/core/hle/service/service.cpp
Labels: general

#4665 service/sm: Eliminate dependency on the global system instance
  src/core/core.cpp
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
Labels: general

#4670 arm_dynarmic_cp15: Initialize member variables
  src/core/arm/dynarmic/arm_dynarmic_cp15.h
Labels: general

#4676 am: Stub GetPreviousProgramIndex
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: early-access-merge

#4684 fermi_2d: Make use of designated initializers
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
Labels: general

#4643 Test: Decrease pad_update_ns
  src/core/hle/service/hid/hid.cpp
Labels: early-access-merge

#4692 renderer_opengl: Remove emulated mailbox presentation
  src/video_core/renderer_base.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/yuzu/bootmanager.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.h
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_vk.h
  src/yuzu_cmd/yuzu.cpp
Labels: early-access-merge, opengl

#4675 submission_package: Account for multi-content NSPs
  src/core/file_sys/submission_package.cpp
Labels: early-access-merge

#4697 ips_layer: Eliminate a redundant copy in Parse()
  src/core/file_sys/ips_layer.cpp
Labels: general

#4698 General: Make use of std::nullopt where applicable
  src/core/arm/dynarmic/arm_dynarmic_cp15.cpp
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/vfs.cpp
  src/core/file_sys/vfs_offset.cpp
  src/core/file_sys/vfs_static.h
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/nvdrv.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/sockets/bsd.cpp
  src/core/loader/nso.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/macro/macro.cpp
  src/video_core/memory_manager.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/ast.h
  src/video_core/shader/track.cpp
  src/video_core/texture_cache/surface_base.cpp
Labels: general

#4699 control_flow: Make use of std::move in InsertBranch()
  src/video_core/shader/control_flow.cpp
Labels: general

#4700 game_list: Eliminate redundant argument copies
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
Labels: general

#4701 install_dialog: Remove unused function prototype
  src/yuzu/install_dialog.h
Labels: general

#4702 memory: Resolve a -Wdocumentation warning
  src/core/memory.cpp
Labels: general

#4618 Add automap feature for GC adapter
  src/input_common/gcadapter/gc_adapter.cpp
  src/input_common/gcadapter/gc_adapter.h
  src/input_common/main.cpp
Labels: early-access-merge

#4674 renderer_vulkan: Make unconditional use of VK_KHR_timeline_semaphore
  src/video_core/CMakeLists.txt
  src/video_core/query_cache.h
  src/video_core/renderer_opengl/gl_query_cache.cpp
  src/video_core/renderer_opengl/gl_query_cache.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/video_core/renderer_vulkan/vk_command_pool.cpp
  src/video_core/renderer_vulkan/vk_command_pool.h
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.h
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_resource_manager.cpp
  src/video_core/renderer_vulkan/vk_resource_manager.h
  src/video_core/renderer_vulkan/vk_resource_pool.cpp
  src/video_core/renderer_vulkan/vk_resource_pool.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.h
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
  src/video_core/shader/async_shaders.h
Labels: early-access-merge, vulkan

#4678 acc: Partially implement LoadOpenContext
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/acc_u0.cpp
Labels: early-access-merge

#4711 arithmetic_integer_immediate: Make use of std::move where applicable
  src/video_core/shader/decode/arithmetic_integer_immediate.cpp
Labels: general

#4717 service: Restore "unused" function
  src/core/hle/service/service.cpp
Labels: general

#4723 behavior_info: Fix typo Renerer -> Renderer
  src/audio_core/behavior_info.cpp
  src/audio_core/behavior_info.h
Labels: general

#4720 audio_core: Remove unnecessary inclusions
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/audio_core/command_generator.h
  src/audio_core/common.h
  src/audio_core/stream.cpp
Labels: general

#4718 vk_command_pool: Add missing header guard
  src/video_core/renderer_vulkan/vk_command_pool.cpp
  src/video_core/renderer_vulkan/vk_command_pool.h
Labels: general

#4703 shader/registry: Make use of designated initializers where applicable
  src/video_core/shader/registry.cpp
  src/video_core/shader/registry.h
Labels: general

#4724 vk_stream_buffer: Fix initializing Vulkan with NVIDIA on Linux
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
Labels: early-access-merge

#4719 audio_core: Resolve sign conversion warnings
  src/audio_core/CMakeLists.txt
  src/audio_core/command_generator.cpp
  src/audio_core/effect_context.cpp
  src/audio_core/effect_context.h
  src/audio_core/info_updater.cpp
  src/audio_core/mix_context.cpp
  src/audio_core/splitter_context.cpp
  src/audio_core/voice_context.cpp
Labels: general

#1703 nvdrv: Stub nvdec/vic ioctls to bypass nvdec movies
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/core/hle/service/nvdrv/devices/nvhost_vic.h
Labels: gpu-fix

#4722 cubeb_sink: Use static_cast instead of reinterpret_cast in DataCallback()
  src/audio_core/cubeb_sink.cpp
Labels: general

#4721 codec: Make lookup table static constexpr
  src/audio_core/codec.cpp
  src/audio_core/codec.h
  src/audio_core/command_generator.cpp
Labels: general

#4728 main: Allow applets to display on top while fullscreen
  src/yuzu/main.cpp
Labels: early-access-merge

#4705 HID: Use different timing for motion
  src/core/hle/service/hid/controllers/controller_base.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge

#4735 Remove ext_extended_dynamic_state blacklist
  src/video_core/renderer_vulkan/vk_device.cpp
Labels: early-access-merge

#4726 frontend/controller: Eliminate dependency on the global system instance
  src/core/core.h
  src/core/frontend/applets/controller.cpp
  src/core/frontend/applets/controller.h
  src/core/hle/service/am/applets/applets.cpp
Labels: general

#4291 input_common: First implementation of controller rumble
  src/core/frontend/input.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
  src/input_common/sdl/sdl_impl.cpp
Labels: early-access-merge
