Repository yuzu-emu/yuzu, pull requests merged in 2020-03, with the labels that each got.

#3464 ARM_Interface: Cache the JITs instead of deleting/recreating.
  src/core/arm/dynarmic/arm_dynarmic.cpp
  src/core/arm/dynarmic/arm_dynarmic.h
Labels: early-access-merge

#3455 video_core: Implement more scaled attribute formats
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Labels: early-access-merge, gpu-new

#3478 Refactoring to boot A32 games
  src/core/CMakeLists.txt
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.h
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.h
  src/core/arm/dynarmic/arm_dynarmic_cp15.cpp
  src/core/arm/dynarmic/arm_dynarmic_cp15.h
  src/core/arm/exclusive_monitor.cpp
  src/core/arm/unicorn/arm_unicorn.cpp
  src/core/arm/unicorn/arm_unicorn.h
  src/core/core_manager.cpp
  src/core/gdbstub/gdbstub.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/physical_core.cpp
  src/core/hle/kernel/physical_core.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/scheduler.cpp
  src/core/hle/kernel/scheduler.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/reporter.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: early-access-merge

#3469 shader_decode: Fix LD, LDG when track constant buffer
  src/video_core/shader/track.cpp
Labels: early-access-merge

#3451 vk_shader_decompiler: Implement indexed textures
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/node.h
Labels: early-access-merge, vulkan

#3463 vk_swapchain: Silence TOCTOU race condition
  src/video_core/renderer_vulkan/vk_swapchain.cpp
Labels: early-access-merge, vulkan

#3481 maxwell_to_vk: Remove Storage capability for A1B5G5R5U
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: vulkan

#3452 frontend/Graphics: Add "Advanced" graphics tab and experimental Anisotropic Filtering support
  src/core/settings.h
  src/video_core/renderer_opengl/gl_sampler_cache.cpp
  src/video_core/textures/texture.h
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure.ui
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
  src/yuzu_tester/config.cpp
  src/yuzu_tester/default_ini.h
Labels: early-access-merge

#3301 video_core: Remove gl_state and use a state tracker based on dirty flags
  src/common/math_util.h
  src/core/core.cpp
  src/video_core/CMakeLists.txt
  src/video_core/dirty_flags.cpp
  src/video_core/dirty_flags.h
  src/video_core/dma_pusher.cpp
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_framebuffer_cache.cpp
  src/video_core/renderer_opengl/gl_framebuffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_resource_manager.cpp
  src/video_core/renderer_opengl/gl_resource_manager.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/gl_state_tracker.cpp
  src/video_core/renderer_opengl/gl_state_tracker.h
  src/video_core/renderer_opengl/gl_stream_buffer.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_opengl/utils.cpp
  src/video_core/renderer_opengl/utils.h
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_state_tracker.cpp
  src/video_core/renderer_vulkan/vk_state_tracker.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, opengl, vulkan

#3458 cubeb_sink: Don't discard other channels when performing downmixing
  src/audio_core/cubeb_sink.cpp
Labels: audio-fix, early-access-merge

#3494 gl_shader_manager: Fix interaction between graphics and compute
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: early-access-merge, opengl

#3480 vk_rasterizer: Support disabled uniform buffers
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
Labels: early-access-merge, vulkan

#3483 vk_rasterizer: fix mistype on SetupGraphicsImages
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge

#3491 gl_rasterizer: Implement polygon modes and fill rectangles
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state_tracker.cpp
  src/video_core/renderer_opengl/gl_state_tracker.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: early-access-merge, gpu-new, opengl

#3473 gl_shader_cache: Rework shader cache and store texture arrays
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/engines/const_buffer_engine_interface.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/guest_driver.cpp
  src/video_core/guest_driver.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/shader/const_buffer_locker.cpp
  src/video_core/shader/const_buffer_locker.h
  src/video_core/shader/control_flow.cpp
  src/video_core/shader/control_flow.h
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/registry.cpp
  src/video_core/shader/registry.h
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
  src/video_core/shader/track.cpp
  src/yuzu/loading_screen.cpp
Labels: opengl

#3490 video_core: Initial implementation of transform feedbacks
  CMakeModules/GenerateSCMRev.cmake
  src/common/CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.h
  src/video_core/shader/transform_feedback.cpp
  src/video_core/shader/transform_feedback.h
Labels: early-access-merge, gpu-new

#3499 texture_cache/surface_params: Force depth=1 on 2D textures
  src/video_core/texture_cache/surface_params.cpp
Labels: early-access-merge, gpu-fix

#3500 texture_cache: Report incompatible textures as black
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, gpu-fix

#3508 PageTable: move backing addresses to a children class as the CPU page table does not need them.
  src/common/page_table.cpp
  src/common/page_table.h
  src/video_core/memory_manager.h
Labels: early-access-merge

#3512 renderer_opengl: Keep frames synchronized when using a GPU debugger.
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: early-access-merge

#3503 maxwell_to_vk: add vertex format eA2B10G10R10UnormPack32
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: early-access-merge

#3502 shader_decode: Reimplement BFE instructions
  src/video_core/engines/shader_bytecode.h
  src/video_core/shader/decode/bfe.cpp
  src/video_core/shader/node_helper.cpp
Labels: early-access-merge

#3501 video_core: Implement RGBA16_SNORM
  src/video_core/gpu.h
  src/video_core/morton.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/format_lookup_table.cpp
Labels: early-access-merge, gpu-new

#3521 renderer_opengl: Detect Nvidia Nsight as a debugging tool
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
Labels: opengl

#3498 gl_shader_decompiler: Add layer component to texelFetch
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: early-access-merge, opengl

#3519 maxwell_to_vk: Implement RG32 and RGB32 integer vertex formats
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: mainline-merge, vulkan

#3518 vk_rasterizer: Implement scissor clears and layered clears
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: vulkan

#3509 astc: General changes and optimizations
  src/video_core/textures/astc.cpp
Labels: early-access-merge, gpu

#3510 DirtyFlags: relax need to set render_targets as dirty
  src/video_core/dirty_flags.cpp
  src/video_core/dirty_flags.h
  src/video_core/renderer_opengl/gl_state_tracker.cpp
  src/video_core/renderer_vulkan/vk_state_tracker.cpp
Labels: early-access-merge, performance

#3535 video_core: Silence misc warnings
  externals/microprofile/microprofile.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: general

#3527 yuzu: Save sound output mode and set it to Stereo by default
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_system.cpp
Labels: frontend-fix

#3505 shader_decode: implement XMAD mode CSfu
  src/video_core/shader/decode/xmad.cpp
Labels: early-access-merge, gpu-new

#3526 bcat: Disable Boxcat backend by default
  src/yuzu/configuration/config.cpp
  src/yuzu_cmd/config.cpp
Labels: general

#3525 input_common/udp: Fix Linux build by using a backwards compatible way of error checking
  src/input_common/udp/client.cpp
Labels: general

#3531 set: implement GetRegionCode
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set.h
  src/core/settings.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_system.ui
Labels: early-access-merge, hle-new

#3477 core/web_browser: Allow WebApplet to exit gracefully when an error occurs
  src/core/hle/service/am/applets/web_browser.cpp
Labels: core-fix, early-access-merge

#3542 Implement MME shadow RAM
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
Labels: early-access-merge, gpu-new

#3543 gl_rasterizer: Use transformed viewport for depth ranges
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge, opengl

#3524 Port citra-emu/citra#5106: "gdbstub: Ensure gdbstub doesn't drop packets crucial to initialization"
  src/core/core.cpp
  src/core/gdbstub/gdbstub.cpp
  src/core/gdbstub/gdbstub.h
Labels: core-fix

#3520 gl_shader_decompiler: Implement legacy varyings
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: early-access-merge, gpu-new, opengl

#3544 xmad: fix clang build error
  src/video_core/shader/decode/xmad.cpp
Labels: gpu-fix

#3548 Use the correct directory for Qt Plugins
  CMakeModules/CopyYuzuQt5Deps.cmake
Labels: build-system-fix, early-access-merge

#3550 Minor Readme Changes
  README.md
Labels: general

#3453 yuzu: Remove exit lock for game pausing
  src/yuzu/main.cpp
Labels: hle-fix

#3564 maxwell_to_vk: implement signedscaled vertex formats
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: early-access-merge, vulkan

#3565 engines/const_buffer_engine_interface: Store image format and types
  src/video_core/engines/const_buffer_engine_interface.h
Labels: early-access-merge, gpu

#3573 Port citra-emu/citra#5089: "Set render window's focus policy to Qt::StrongFocus"
  src/yuzu/main.cpp
Labels: frontend-fix

#3569 services: hid: Stub InitializeSevenSixAxisSensor.
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge, hle-new

#3562 am: Implement VR related APIs
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
Labels: early-access-merge, hle-new

#3545 audio_core: Accept Audren REV8
  src/audio_core/audio_renderer.h
Labels: audio-new, early-access-merge

#3568 services: time: Implement CalculateSpanBetween.
  src/core/hle/service/time/interface.cpp
  src/core/hle/service/time/time.cpp
  src/core/hle/service/time/time.h
Labels: early-access-merge, hle-new

#3560 gl_rasterizer: Synchronize stencil testing on clears
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge, gpu-fix, opengl

#3566 renderer_vulkan/wrapper: Add a Vulkan wrapper (part 1 of 2)
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
Labels: vulkan

#3506 shader_decode: Implement partial ATOM/ATOMS instr
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/node.h
  src/video_core/shader/node_helper.cpp
Labels: gpu-new

#3577 shader/lea: Fix LEA implementation
  src/video_core/shader/decode/arithmetic_integer.cpp
Labels: early-access-merge, gpu-fix

#3561 shader/conversion: Fix F2F rounding operations with different sizes
  src/video_core/shader/decode/conversion.cpp
Labels: early-access-merge, gpu-fix

#3571 capsrv: Split Capture services into individual files and stub GetAlbumContentsFileListForApplication
  src/core/CMakeLists.txt
  src/core/hle/service/caps/caps.cpp
  src/core/hle/service/caps/caps.h
  src/core/hle/service/caps/caps_a.cpp
  src/core/hle/service/caps/caps_a.h
  src/core/hle/service/caps/caps_c.cpp
  src/core/hle/service/caps/caps_c.h
  src/core/hle/service/caps/caps_sc.cpp
  src/core/hle/service/caps/caps_sc.h
  src/core/hle/service/caps/caps_ss.cpp
  src/core/hle/service/caps/caps_ss.h
  src/core/hle/service/caps/caps_su.cpp
  src/core/hle/service/caps/caps_su.h
  src/core/hle/service/caps/caps_u.cpp
  src/core/hle/service/caps/caps_u.h
Labels: early-access-merge, hle-new
