Repository yuzu-emu/yuzu, pull requests merged in 2020-05, with the labels that each got.

#3812 account: ListQualifiedUsers
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/acc_su.cpp
  src/core/hle/service/acc/acc_u0.cpp
  src/core/hle/service/acc/acc_u1.cpp
Labels: early-access-merge, hle-new

#3821 acc: Fix InitializeApplicationInfo
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
Labels: early-access-merge, hle-fix

#3833 Add stub for caps:su SetShimLibraryVersion
  src/core/hle/service/caps/caps_su.cpp
  src/core/hle/service/caps/caps_su.h
Labels: hle-new

#3693 shader/texture: Support multiple unknown sampler properties
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/image.cpp
  src/video_core/shader/decode/texture.cpp
  src/video_core/shader/node.h
  src/video_core/shader/shader_ir.h
  src/video_core/texture_cache/surface_params.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, gpu-fix

#3809 vk_rasterizer: Skip index buffer setup when vertices are zero
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge, vulkan

#3775 Fixed packaging on some systems with different QT5 path
  .ci/scripts/windows/docker.sh
Labels: build-system-fix

#3732 vulkan: Remove unnecessary includes
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_compute_pipeline.h
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.h
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_sampler_cache.cpp
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.h
  src/video_core/renderer_vulkan/vk_shader_util.cpp
  src/video_core/renderer_vulkan/vk_shader_util.h
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/renderer_vulkan/vk_update_descriptor.h
Labels: general

#3819 kernel: Don't fail silently
  src/core/hle/kernel/handle_table.cpp
  src/core/hle/kernel/mutex.cpp
  src/core/hle/kernel/process_capability.cpp
  src/core/hle/kernel/readable_event.cpp
  src/core/hle/kernel/resource_limit.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/thread.cpp
Labels: general

#3811 audin:u: ListAudioIns, OpenAudioIn, ListAudioInsAuto, OpenAudioInAuto, ListAudioInsAutoFiltered, OpenAudioInProtocolSpecified
  src/core/hle/service/audio/audin_u.cpp
  src/core/hle/service/audio/audin_u.h
Labels: early-access-merge, hle-new

#3824 am: Properly implement GetDisplayVersion
  src/core/hle/service/am/am.cpp
Labels: early-access-merge, hle-new

#3871 readable_event: Remove unnecessary semicolon in Signal()
  src/core/hle/kernel/readable_event.cpp
Labels: general

#3872 input_common: fix build when SDL2 is disabled
  src/input_common/main.cpp
Labels: input

#3808 {maxwell_3d,buffer_cache}: Implement memory barriers using 3D registers
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/wrapper.cpp
  src/video_core/renderer_vulkan/wrapper.h
Labels: early-access-merge, gpu-fix

#3875 settings: Add anisotropic filtering level to the yuzu configuration log
  src/core/settings.cpp
Labels: general

#3822 acc: Return a unique value per account for GetAccountId
  src/common/uuid.h
  src/core/hle/service/acc/acc.cpp
Labels: early-access-merge, hle-fix

#3637 Port citra-emu/citra#5094: "yuzu: Option to hide mouse on inactivity"
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/uisettings.h
Labels: frontend-new

#3843 am: IHomeMenuFunctions:GetPopFromGeneralChannelEvent
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/applet_ae.cpp
Labels: early-access-merge, hle-new

#3880 kernel/memory: Amend potential encoding warnings
  src/core/hle/kernel/memory/address_space_info.cpp
  src/core/hle/kernel/memory/address_space_info.h
  src/core/hle/kernel/memory/memory_block.h
  src/core/hle/kernel/memory/page_heap.cpp
  src/core/hle/kernel/memory/page_heap.h
  src/core/hle/kernel/memory/slab_heap.h
Labels: general

#3881 kernel/memory: Resolve several compiler warnings
  src/core/hle/kernel/memory/address_space_info.cpp
  src/core/hle/kernel/memory/address_space_info.h
  src/core/hle/kernel/memory/memory_block_manager.cpp
  src/core/hle/kernel/memory/memory_block_manager.h
  src/core/hle/kernel/memory/memory_manager.cpp
  src/core/hle/kernel/memory/memory_manager.h
  src/core/hle/kernel/memory/page_linked_list.h
  src/core/hle/kernel/memory/page_table.cpp
  src/core/hle/kernel/memory/page_table.h
  src/core/hle/kernel/memory/slab_heap.h
  src/core/hle/kernel/memory/system_control.cpp
Labels: general

#3815 GPU: More optimizations to GPU Command List Processing and DMA Copy Optimizations
  src/video_core/CMakeLists.txt
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
  src/video_core/engines/engine_interface.h
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/gpu.cpp
  src/video_core/macro_interpreter.cpp
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
Labels: early-access-merge, gpu-new

#3879 hle_ipc: Eliminate core memory globals
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/server_session.cpp
Labels: general

#3885 video_core: Implement viewport swizzles with NV_viewport_swizzle
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: early-access-merge, gpu-new

#3842 maxwell_to_vk: implement missing signed int formats
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: early-access-merge, vulkan

#3839 texture: Implement R8G8UI
  src/video_core/gpu.h
  src/video_core/morton.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/format_lookup_table.cpp
Labels: early-access-merge, gpu-new

#3896 CI: Don't check clang format on early access builds
  .ci/yuzu-patreon-step2.yml
Labels: early-access-merge

#3816 vk_graphics_pipeline: Implement rasterizer_enable on Vulkan
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: early-access-merge, vulkan

#3899 shader_ir: Add separate instructions for ordered and unordered comparisons and fix NE on GLSL
  src/video_core/engines/shader_bytecode.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode.cpp
  src/video_core/shader/decode/xmad.cpp
  src/video_core/shader/node.h
  src/video_core/shader/shader_ir.cpp
Labels: early-access-merge, gpu-fix, opengl

#3909 Improve time zone support
  src/common/CMakeLists.txt
  src/common/time_zone.cpp
  src/common/time_zone.h
  src/core/hle/service/time/time_manager.cpp
  src/core/hle/service/time/time_zone_content_manager.cpp
  src/core/settings.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_system.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge, hle-new

#3757 audio_renderer: Better voice mixing and 6 channel downmixing
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/audio_core/common.h
Labels: audio-new, mainline-merge

#3927 Frontend: Remove tracking for context wrapper
  src/yuzu/bootmanager.cpp
Labels: early-access-merge

#3413 frontend: Set minimum window size to 640x360 instead of 1280x720
  src/core/frontend/emu_window.cpp
  src/core/frontend/framebuffer_layout.h
  src/yuzu/loading_screen.cpp
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: frontend-new

#3942 vk_rasterizer: Match OpenGL's FlushAndInvalidate behavior
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge, vulkan

#3665 FS: Improve emulation of device saves
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/file_sys/savedata_factory.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: mainline-merge

#3926 hid: Clear keyboard states & fix logic issue
  src/core/hle/service/hid/controllers/keyboard.cpp
Labels: early-access-merge

#3946 file_sys: Update SystemVersion archive to version 10.0.2
  src/core/file_sys/system_archive/system_version.cpp
Labels: early-access-merge

#3977 yuzu/discord_impl: Update the applicationID
  src/yuzu/discord_impl.cpp
Labels: early-access-merge

#3975 buffer_cache: Replace boost::icl::interval_map with boost::intrusive::set
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/map_interval.cpp
  src/video_core/buffer_cache/map_interval.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.h
Labels: early-access-merge, gpu, performance

#3979 shader/other: Implement thread comparisons (NV_shader_thread_group)
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/node.h
Labels: early-access-merge

#3964 renderer_opengl: Add assembly program code paths
  src/core/settings.cpp
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_resource_manager.cpp
  src/video_core/renderer_opengl/gl_resource_manager.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge, opengl

#3905 Correct a series of crashes and intructions on Async GPU and Vulkan Pipeline
  src/video_core/rasterizer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge, gpu-fix, vulkan

#3978 shader_decompiler: Visit source nodes even when they assign to RZ
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Labels: early-access-merge

#3980 shader/memory: Implement non-addition operations in RED
  src/video_core/shader/decode/memory.cpp
Labels: early-access-merge

#3954 main: Log host system memory parameters
  src/common/CMakeLists.txt
  src/common/memory_detect.cpp
  src/common/memory_detect.h
  src/yuzu/main.cpp
Labels: mainline-merge

#3993 gl_shader_manager: Unbind GLSL program when binding a host pipeline
  src/video_core/renderer_opengl/gl_shader_manager.cpp
Labels: early-access-merge, opengl

#3991 texture_cache: Implement depth stencil texture swizzles
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, gpu-new

#4007 maxwell_3d: Reduce severity of logs that can be spammed
  src/video_core/engines/maxwell_3d.cpp
Labels: early-access-merge

#3982 shader/other: Implement MEMBAR.CTS
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/other.cpp
  src/video_core/shader/node.h
Labels: early-access-merge

#3999 texture_cache: Optimize GetSurfacesInRegion
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge, performance

#3958 OpenGL: Enable Debug Context and Synchronous debugging when graphics debugging is enabled
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
Labels: mainline-merge, opengl

#3930 vk_rasterizer: Implement constant attributes
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.h
Labels: early-access-merge, vulkan
