Repository yuzu-emu/yuzu, pull requests merged in 2020-11, with the labels that each got.

#4714 Rename to align with switchbrew and remove gpu function
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
Labels: early-access-merge

#4865 async_shaders: Increase Async worker thread count for >8 thread cpus
  src/video_core/shader/async_shaders.cpp
Labels: early-access-merge

#4878 hle: service: ldr: Implement UnloadNrr.
  src/core/hle/service/ldr/ldr.cpp
Labels: early-access-merge

#4873 common: Enable warnings as errors
  externals/microprofile/microprofile.h
  src/common/CMakeLists.txt
  src/common/fiber.cpp
  src/common/fiber.h
  src/common/file_util.cpp
  src/common/logging/backend.cpp
  src/common/string_util.cpp
  src/common/timer.cpp
  src/common/wall_clock.cpp
  src/common/x64/native_clock.h
Labels: build-system-new

#4887 microprofile: Silence warning in headers
  externals/microprofile/microprofile.h
Labels: general

#4874 nvdec: Make use of [[nodiscard]] where applicable
  src/video_core/command_classes/codecs/codec.h
  src/video_core/command_classes/codecs/h264.cpp
  src/video_core/command_classes/codecs/h264.h
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/codecs/vp9.h
  src/video_core/command_classes/codecs/vp9_types.h
  src/video_core/command_classes/nvdec.h
Labels: general

#4869 Improvements to GPU synchronization & various refactoring
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.h
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/core/hle/service/nvdrv/nvdrv.h
  src/core/hle/service/nvdrv/syncpoint_manager.cpp
  src/core/hle/service/nvdrv/syncpoint_manager.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: early-access-merge

#4858 General: Resolve a few missing initializer warnings
  src/core/arm/arm_interface.cpp
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/texture_cache/surface_params.cpp
Labels: general

#4889 core/settings: Move configuring_global behind an API
  src/core/settings.cpp
  src/core/settings.h
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_system.cpp
Labels: general

#4854 shader: Partially implement texture cube array shadow
  src/video_core/renderer_opengl/gl_arb_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/shader/decode/texture.cpp
Labels: early-access-merge

#4894 settings: Simplify initializer of resolution factor
  src/core/settings.h
Labels: general

#4891 General: Fix clang build
  src/common/fiber.h
  src/common/spin_lock.h
  src/video_core/dma_pusher.h
  src/video_core/gpu.h
Labels: general

#4899 common/fiber: Move all member variables into impl class
  src/common/fiber.cpp
  src/common/fiber.h
Labels: general

#4908 externals: Update fmt to 7.1.2
  CMakeLists.txt
Labels: externals

#4903 video_core: dma_pusher: Remove integrity check on command lists.
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
Labels: do-not-merge, early-access-merge

#4910 ipc_helpers: Remove usage of the global system instance
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/am/applet_ae.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/apm/apm.cpp
  src/core/hle/service/bcat/module.cpp
  src/core/hle/service/btdrv/btdrv.cpp
  src/core/hle/service/btm/btm.cpp
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/glue/arp.cpp
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/lm/lm.cpp
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/core/hle/service/pm/pm.cpp
  src/core/hle/service/prepo/prepo.cpp
Labels: general

#4909 cpu_interrupt_handler: Mark move contructor/assignment as deleted
  src/core/arm/cpu_interrupt_handler.h
Labels: general

#4901 hle: service: caps_u: Stub GetAlbumFileList3AaeAruid.
  src/core/hle/service/caps/caps_u.cpp
  src/core/hle/service/caps/caps_u.h
Labels: early-access-merge

#4895 applets/controller: Introduce additional checks for mode and caller
  src/core/hle/service/am/applets/controller.cpp
  src/core/hle/service/am/applets/controller.h
Labels: early-access-merge

#4929 motion_input: Mark member functions as [[nodiscard]] where applicable
  src/input_common/motion_input.h
Labels: general

#4933 [gpu, render_base, rasterizer_interface]: Make use of [[nodiscard]] where applicable
  src/video_core/gpu.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_base.h
Labels: general

#4936 page_table: Allow page tables to be moved
  src/common/page_table.cpp
  src/common/page_table.h
  src/common/virtual_buffer.cpp
  src/common/virtual_buffer.h
Labels: general

#4948 virtual_buffer: Do nothing on resize() calls with same sizes
  src/common/virtual_buffer.h
Labels: general

#4308 maxwell_3d: Move code to separate functions and insert instead of push_back
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
Labels: early-access-merge, style

#4950 Modify rumble amplification
  src/input_common/gcadapter/gc_poller.cpp
  src/input_common/sdl/sdl_impl.cpp
Labels: early-access-merge

#4941 configure_input_player: Use static qualifier for IsProfileNameValid()
  src/yuzu/configuration/configure_input_player.cpp
Labels: general

#4951 hle: service: Stub OLSC Initialize and SetSaveDataBackupSettingEnabled functions.
  src/common/logging/backend.cpp
  src/common/logging/log.h
  src/core/CMakeLists.txt
  src/core/hle/service/olsc/olsc.cpp
  src/core/hle/service/olsc/olsc.h
  src/core/hle/service/service.cpp
Labels: early-access-merge, hle-new

#4953 shader_bytecode: Eliminate variable shadowing
  src/video_core/engines/shader_bytecode.h
Labels: general

#4907 core: Make nvservices more standardized
  src/core/hle/service/nvdrv/devices/nvdevice.h
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.h
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/core/hle/service/nvdrv/devices/nvhost_vic.h
  src/core/hle/service/nvdrv/devices/nvmap.cpp
  src/core/hle/service/nvdrv/devices/nvmap.h
  src/core/hle/service/nvdrv/interface.cpp
  src/core/hle/service/nvdrv/interface.h
  src/core/hle/service/nvdrv/nvdata.h
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/core/hle/service/nvdrv/nvdrv.h
Labels: early-access-merge

#4955 async_shaders: std::move data within QueueVulkanShader()
  src/video_core/shader/async_shaders.cpp
Labels: general

#4954 gl_rasterizer: Make floating-point literal a float
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: general

#4944 patch_manager: Remove usages of the global system instance
  src/core/core.cpp
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/romfs_factory.cpp
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/ns.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nso.cpp
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
  src/core/telemetry_session.cpp
  src/core/telemetry_session.h
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_per_game_addons.cpp
  src/yuzu/game_list_worker.cpp
  src/yuzu/main.cpp
Labels: general

#4451 logging/settings: Increase maximum log size to 100 MB and add extended logging option
  src/common/logging/backend.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
Labels: early-access-merge

#4927 input_common: Treat warnings as errors
  src/core/frontend/input.h
  src/input_common/CMakeLists.txt
  src/input_common/gcadapter/gc_poller.cpp
  src/input_common/sdl/sdl.h
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/touch_from_button.cpp
  src/input_common/udp/client.cpp
  src/input_common/udp/protocol.h
Labels: build-system-new

#4972 svc: Remove unnecessary [[maybe_unused]] tag
  src/core/hle/kernel/svc.cpp
Labels: general

#4942 core: Make use of [[nodiscard]] with the System class
  src/core/core.cpp
  src/core/core.h
  src/yuzu_cmd/yuzu.cpp
  src/yuzu_tester/yuzu.cpp
Labels: general

#3681 decoder/image: Fix incorrect G24R8 component sizes in GetComponentSize()
  src/video_core/shader/decode/image.cpp
Labels: bug

#4977 hle: services: Fix a crash with improper NVFlinger lifetime management.
  src/core/core.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/applet_ae.cpp
  src/core/hle/service/am/applet_ae.h
  src/core/hle/service/am/applet_oe.cpp
  src/core/hle/service/am/applet_oe.h
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/hle/service/vi/vi.cpp
  src/core/hle/service/vi/vi.h
  src/core/hle/service/vi/vi_m.cpp
  src/core/hle/service/vi/vi_m.h
  src/core/hle/service/vi/vi_s.cpp
  src/core/hle/service/vi/vi_s.h
  src/core/hle/service/vi/vi_u.cpp
  src/core/hle/service/vi/vi_u.h
Labels: early-access-merge

#4799 core: Refactor loader and implement ExecuteProgram
  src/core/core.cpp
  src/core/core.h
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#4905 Allow to dial any angle with digital joystick
  src/input_common/analog_from_button.cpp
Labels: early-access-merge, input

#4978 core: cpu_manager: Fix shutdown crash when closing before emulation starts.
  src/core/cpu_manager.cpp
Labels: early-access-merge

#4932 audren: Make use of nodiscard, rework downmixing, release all buffers
  src/audio_core/audio_out.cpp
  src/audio_core/audio_out.h
  src/audio_core/audio_renderer.cpp
  src/audio_core/audio_renderer.h
  src/audio_core/behavior_info.h
  src/audio_core/command_generator.h
  src/audio_core/common.h
  src/audio_core/effect_context.h
  src/audio_core/mix_context.h
  src/audio_core/sink_context.cpp
  src/audio_core/sink_context.h
  src/audio_core/stream.cpp
  src/audio_core/stream.h
Labels: audio-fix, early-access-merge

#4959 configure_input_player: Use the NpadStyleSet to limit the available controllers shown
  src/yuzu/applets/controller.cpp
  src/yuzu/applets/controller.h
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
Labels: early-access-merge

#4946 vulkan_renderer: Alpha Test Culling Implementation
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.h
Labels: gpu-fix

#5023 savedata_factory: Eliminate usage of the global system instance
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/yuzu/main.cpp
Labels: general

#5028 core: Eliminate remaining usages of the global system instance
  src/core/CMakeLists.txt
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/core.cpp
  src/core/cpu_manager.cpp
  src/core/gdbstub/gdbstub.cpp
  src/core/gdbstub/gdbstub.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/kip.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
  src/core/settings.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_profile_manager.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_ui.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
  src/yuzu_tester/yuzu.cpp
Labels: general

#5011 core: Reduce string copies in GetGameFileFromPath()
  src/core/core.cpp
Labels: general

#4998 hid: Check if applet_resource exists in InitializeVibrationDevice
  src/core/hle/service/hid/hid.cpp
Labels: early-access-merge

#4939 InputCommon: Implement full mouse support
  src/core/frontend/input.h
  src/input_common/CMakeLists.txt
  src/input_common/main.cpp
  src/input_common/main.h
  src/input_common/motion_emu.cpp
  src/input_common/motion_emu.h
  src/input_common/mouse/mouse_input.cpp
  src/input_common/mouse/mouse_input.h
  src/input_common/mouse/mouse_poller.cpp
  src/input_common/mouse/mouse_poller.h
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
Labels: early-access-merge, input

#5013 vk_shader_decompiler: Implement force early fragment tests
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.h
Labels: early-access-merge, gpu-new, vulkan
