Repository yuzu-emu/yuzu, pull requests merged in 2021-10, with the labels that each got.

#7114 ci: Use latest ubuntu image for mainline/patreon step 1
  .ci/yuzu-mainline-step1.yml
  .ci/yuzu-patreon-step1.yml
Labels: build-system-fix

#7093 core: Properly shutdown and exit the running application when ISelfController::Exit is called
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/am/am.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: core-fix, early-access-merge

#6979 input_common: Add alternative string for joycons
  src/input_common/sdl/sdl_impl.cpp
Labels: early-access-merge

#7113 network: Do not log IP address
  src/core/network/network.cpp
Labels: general, early-access-merge

#7111 main: Don't add an extra separator when the title version is absent
  src/yuzu/main.cpp
Labels: general, early-access-merge

#7122 Qt: Update to Qt 5.15.2
  CMakeLists.txt
  CMakeModules/CopyYuzuQt5Deps.cmake
Labels: early-access-merge

#7091 core: Fix memory leak
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_shared_memory_info.h
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc.cpp
Labels: core-fix, kernel-fix, early-access-merge

#7107 prevent access violation from iob in Memory::IsValidVirtualAddress
  src/core/memory.cpp
Labels: early-access-merge

#7101 vk_graphics_pipeline: Force patch list topology when tessellation is used
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: gpu-fix, vulkan, early-access-merge

#7103 service: Replace all service event creation with ServiceContext::CreateEvent
  src/core/hle/service/acc/async_context.cpp
  src/core/hle/service/acc/async_context.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/aoc/aoc_u.h
  src/core/hle/service/audio/audin_u.cpp
  src/core/hle/service/audio/audin_u.h
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/audren_u.h
  src/core/hle/service/bcat/backend/backend.cpp
  src/core/hle/service/bcat/backend/backend.h
  src/core/hle/service/bcat/bcat_module.cpp
  src/core/hle/service/btdrv/btdrv.cpp
  src/core/hle/service/btm/btm.cpp
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nfp/nfp.h
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/ptm/psm.cpp
  src/core/hle/service/time/standard_user_system_clock_core.cpp
  src/core/hle/service/time/standard_user_system_clock_core.h
Labels: hle-fix, early-access-merge

#7115 common/logging: Reduce dependent header include overhead
  src/audio_core/command_generator.cpp
  src/audio_core/mix_context.cpp
  src/audio_core/voice_context.cpp
  src/common/CMakeLists.txt
  src/common/logging/backend.cpp
  src/common/logging/log.h
  src/common/logging/log_entry.h
  src/common/logging/text_formatter.cpp
  src/common/logging/types.h
  src/common/param_package.cpp
  src/core/hle/kernel/k_auto_object_container.cpp
  src/core/hle/service/lbl/lbl.cpp
  src/core/hle/service/time/system_clock_context_update_callback.h
  src/core/hle/service/time/system_clock_core.h
  src/video_core/engines/maxwell_3d.h
Labels: general, early-access-merge

#7090 (Minor Change) Hint (?) Button Removal and Spacing Change to the TAS Window
  src/yuzu/configuration/configure_tas.cpp
  src/yuzu/configuration/configure_tas.ui
Labels: early-access-merge

#7240 hle/result: Remove cv-qualifiers from Arg in MakeResult
  src/core/hle/result.h
Labels: general

#7244 file_sys/ns: Add Brazilian Portuguese to the list of ApplicationLanguage
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/hle/service/ns/language.cpp
  src/core/hle/service/ns/language.h
Labels: hle-fix, early-access-merge

#6702 yuzu_cmd, yuzu qt: Use SDL to disable the screen saver
  src/yuzu/CMakeLists.txt
  src/yuzu/main.cpp
Labels: early-access-merge

#7201 emit_spirv_image: Fix depth image implicit lod sample in non-fragment stages
  src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
Labels: gpu, vulkan, early-access-merge
