Repository yuzu-emu/yuzu, pull requests merged in 2021-01, with the labels that each got.

#5239 .ci/templates: Enable QT translation for MSVC CI
  .ci/templates/build-msvc.yml
Labels: early-access-merge

#5249 core/memory: Read and write page table atomically
  src/common/page_table.cpp
  src/common/page_table.h
  src/common/virtual_buffer.h
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/hle/kernel/memory/page_table.cpp
  src/core/memory.cpp
Labels: early-access-merge

#5279 hle: service: nvflinger: buffer_queue: Do not reset id/layer_id on Connect.
  src/core/hle/service/nvflinger/buffer_queue.cpp
Labels: early-access-merge

#5230 vulkan_common: Move reusable Vulkan abstractions to a separate directory
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/blit_image.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_command_pool.cpp
  src/video_core/renderer_vulkan/vk_command_pool.h
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_compute_pipeline.h
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.h
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.h
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.h
  src/video_core/renderer_vulkan/vk_memory_manager.cpp
  src/video_core/renderer_vulkan/vk_memory_manager.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_util.cpp
  src/video_core/renderer_vulkan/vk_shader_util.h
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.h
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/renderer_vulkan/vk_update_descriptor.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.h
  src/video_core/vulkan_common/vulkan_debug_callback.cpp
  src/video_core/vulkan_common/vulkan_debug_callback.h
  src/video_core/vulkan_common/vulkan_instance.cpp
  src/video_core/vulkan_common/vulkan_instance.h
  src/video_core/vulkan_common/vulkan_library.cpp
  src/video_core/vulkan_common/vulkan_library.h
  src/video_core/vulkan_common/vulkan_surface.cpp
  src/video_core/vulkan_common/vulkan_surface.h
  src/video_core/vulkan_common/vulkan_wrapper.cpp
  src/video_core/vulkan_common/vulkan_wrapper.h
Labels: vulkan

#5285 main: Resolve error string not displaying
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/yuzu/main.cpp
Labels: general

#5286 renderer_vulkan: Rename VKDevice to Device
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/blit_image.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_command_pool.cpp
  src/video_core/renderer_vulkan/vk_command_pool.h
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_compute_pipeline.h
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.h
  src/video_core/renderer_vulkan/vk_device.cpp
  src/video_core/renderer_vulkan/vk_device.h
  src/video_core/renderer_vulkan/vk_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.h
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.h
  src/video_core/renderer_vulkan/vk_memory_manager.cpp
  src/video_core/renderer_vulkan/vk_memory_manager.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.h
  src/video_core/renderer_vulkan/vk_shader_util.cpp
  src/video_core/renderer_vulkan/vk_shader_util.h
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.h
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/renderer_vulkan/vk_update_descriptor.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.h
  src/video_core/shader/async_shaders.cpp
  src/video_core/shader/async_shaders.h
Labels: vulkan

#5292 vk_rasterizer: Skip binding empty descriptor sets on compute
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: vulkan

#5289 vulkan_common: Move device abstraction to the common directory and allow surfaceless devices
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_command_pool.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_memory_manager.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/renderer_vulkan/vk_shader_util.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_stream_buffer.cpp
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.cpp
  src/video_core/shader/async_shaders.h
  src/video_core/vulkan_common/nsight_aftermath_tracker.cpp
  src/video_core/vulkan_common/nsight_aftermath_tracker.h
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: early-access-merge, vulkan

#5288 gl_texture_cache: Avoid format views on Intel and AMD
  src/video_core/compatible_formats.cpp
  src/video_core/compatible_formats.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/image_base.cpp
  src/video_core/texture_cache/image_view_base.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/util.cpp
  src/video_core/texture_cache/util.h
Labels: early-access-merge, opengl

#5237 nvdec: Incorporate syncpoint manager
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/core/hle/service/nvdrv/devices/nvhost_vic.h
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/video_core/cdma_pusher.cpp
  src/video_core/cdma_pusher.h
  src/video_core/command_classes/host1x.cpp
  src/video_core/command_classes/host1x.h
Labels: early-access-merge

#5231 renderer_vulkan/fixed_pipeline_state: Move enabled bindings to static state
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: early-access-merge, vulkan

#5229 yuzu/main: Add basic command line arguments
  src/yuzu/main.cpp
Labels: early-access-merge

#5266 Rewrite KSynchronizationObject, KConditonVariable, and KAddressArbiter
  src/common/CMakeLists.txt
  src/common/common_funcs.h
  src/common/intrusive_red_black_tree.h
  src/common/parent_of_member.h
  src/common/tree.h
  src/core/CMakeLists.txt
  src/core/arm/arm_interface.h
  src/core/core_timing.cpp
  src/core/hle/kernel/address_arbiter.cpp
  src/core/hle/kernel/address_arbiter.h
  src/core/hle/kernel/client_port.cpp
  src/core/hle/kernel/client_session.cpp
  src/core/hle/kernel/client_session.h
  src/core/hle/kernel/errors.h
  src/core/hle/kernel/k_address_arbiter.cpp
  src/core/hle/kernel/k_address_arbiter.h
  src/core/hle/kernel/k_condition_variable.cpp
  src/core/hle/kernel/k_condition_variable.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_scheduler.h
  src/core/hle/kernel/k_scheduler_lock.h
  src/core/hle/kernel/k_synchronization_object.cpp
  src/core/hle/kernel/k_synchronization_object.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/memory/memory_layout.h
  src/core/hle/kernel/mutex.cpp
  src/core/hle/kernel/mutex.h
  src/core/hle/kernel/object.h
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/readable_event.cpp
  src/core/hle/kernel/readable_event.h
  src/core/hle/kernel/server_port.cpp
  src/core/hle/kernel/server_port.h
  src/core/hle/kernel/server_session.cpp
  src/core/hle/kernel/server_session.h
  src/core/hle/kernel/session.cpp
  src/core/hle/kernel/session.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_common.h
  src/core/hle/kernel/svc_results.h
  src/core/hle/kernel/svc_types.h
  src/core/hle/kernel/svc_wrap.h
  src/core/hle/kernel/synchronization.cpp
  src/core/hle/kernel/synchronization.h
  src/core/hle/kernel/synchronization_object.cpp
  src/core/hle/kernel/synchronization_object.h
  src/core/hle/kernel/thread.cpp
  src/core/hle/kernel/thread.h
  src/core/hle/kernel/time_manager.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/sm/sm.cpp
  src/yuzu/debugger/wait_tree.cpp
  src/yuzu/debugger/wait_tree.h
Labels: early-access-merge

#5333 common/parent_of_member: Replace TYPED_STORAGE define with template alias
  src/common/intrusive_red_black_tree.h
  src/common/parent_of_member.h
Labels: general

#5311 vk_fence_manager: Use timeline semaphores instead of spin waits
  src/video_core/renderer_vulkan/vk_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge, vulkan

#5280 Port citra-emu/citra#5666: "Rotate previous log file to "citra_log.txt.old""
  src/common/logging/backend.cpp
Labels: early-access-merge, general

#5341 vulkan_device: Remove requirement on shaderStorageImageMultisample
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: vulkan

#5342 yuzu: Migrate off of setMargin() to setContentsMargins()
  src/yuzu/bootmanager.cpp
  src/yuzu/game_list.cpp
Labels: general

#5330 Fix IP validator error
  src/yuzu/configuration/configure_motion_touch.cpp
Labels: early-access-merge

#5344 configure_motion_touch: Prevent use after move in ApplyConfiguration()
  src/yuzu/configuration/configure_motion_touch.cpp
Labels: bug

#5343 configure_motion_touch: Migrate off QRegExp to QRegularExpression
  src/yuzu/configuration/configure_motion_touch.cpp
Labels: general

#5345 yuzu: Remove unused variables in Qt code
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_motion_touch.cpp
Labels: general

#5348 astc: Make the decoder more robust to invalid data
  src/video_core/textures/astc.cpp
Labels: gpu-fix

#5349 vulkan_device: Enable shaderStorageImageMultisample conditionally
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: vulkan

#5356 common/bit_util: Replace CLZ/CTZ operations with standardized ones
  src/common/bit_util.h
  src/core/hle/kernel/k_priority_queue.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/memory/page_heap.h
  src/core/hle/kernel/process_capability.cpp
  src/tests/CMakeLists.txt
  src/tests/common/bit_utils.cpp
  src/video_core/cdma_pusher.cpp
  src/video_core/cdma_pusher.h
  src/video_core/command_classes/codecs/h264.cpp
Labels: general

#5355 common/timer: Remove
  src/common/CMakeLists.txt
  src/common/timer.cpp
  src/common/timer.h
Labels: general

#5297 vulkan_memory_allocator: Improvements to the memory allocator
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_memory_manager.cpp
  src/video_core/renderer_vulkan/vk_memory_manager.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/vulkan_common/vulkan_memory_allocator.cpp
  src/video_core/vulkan_common/vulkan_memory_allocator.h
Labels: early-access-merge, vulkan

#5336 common/tree: Convert defines over to templates
  src/common/intrusive_red_black_tree.h
  src/common/tree.h
Labels: early-access-merge, general

#5275 X86/NativeClock: Improve performance of clock calculations on hot path.
  src/common/CMakeLists.txt
  src/common/atomic_ops.cpp
  src/common/atomic_ops.h
  src/common/x64/native_clock.cpp
  src/common/x64/native_clock.h
Labels: early-access-merge, performance

#5262 buffer_cache/buffer_base: Add a range tracking buffer container and tests
  src/tests/CMakeLists.txt
  src/tests/video_core/buffer_base.cpp
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_base.h
Labels: early-access-merge, gpu

#5740 input_interpreter: Mark two member functions as const
  src/core/frontend/input_interpreter.h
Labels: general

#5744 vulkan_debug_callback: Add missing header guard
  src/video_core/vulkan_common/vulkan_debug_callback.h
Labels: general

#5745 video_core: Resolve -Wdocumentation warnings
  src/video_core/buffer_cache/buffer_base.h
  src/video_core/vulkan_common/vulkan_memory_allocator.h
Labels: general

#5746 texture_cache/util: Resolve -Wsign-compare warning
  src/video_core/texture_cache/util.cpp
Labels: general

#5743 Fix player 1 turning on handheld and not updating handheld settings
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge

#5361 vk_shader_decompiler: Show comments as OpUndef with a type
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
Labels: vulkan

#5270 HID: Add multitouch support
  src/core/frontend/emu_window.cpp
  src/core/frontend/emu_window.h
  src/core/frontend/input.h
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
  src/input_common/touch_from_button.cpp
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
  src/input_common/udp/protocol.h
  src/input_common/udp/udp.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_motion_touch.cpp
  src/yuzu/configuration/configure_motion_touch.ui
  src/yuzu/configuration/configure_touchscreen_advanced.cpp
  src/yuzu/configuration/configure_touchscreen_advanced.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: early-access-merge, input

#5781 bit_util: Unify implementations of MostSignificantBit32/MostSignificantBit64
  src/common/bit_util.h
Labels: general

#5765 acc: Stub StoreSaveDataThumbnail
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/acc_su.cpp
  src/core/hle/service/acc/acc_u0.cpp
  src/core/hle/service/acc/acc_u1.cpp
Labels: early-access-merge

#5776 lbl: Implement most of lbl
  src/core/hle/service/lbl/lbl.cpp
Labels: early-access-merge

#5796 vk_pipeline_cache: Properly bypass VertexA shaders
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: early-access-merge, vulkan

#5814 vulkan_device: Lift VK_EXT_extended_dynamic_state blacklist on RDNA
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: vulkan

#5363 vk_texture_cache: Support image store on sRGB images with VkImageViewUsageCreateInfo
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: vulkan

#5823 Revert "Start of Integer flags implementation"
  src/video_core/shader/node.h
  src/video_core/shader/shader_ir.cpp
  src/video_core/shader/shader_ir.h
Labels: gpu

#5785 video_core/memory_manager: Flush destination buffer on CopyBlock
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: early-access-merge, gpu-fix

#5799 nvdrv: Unregister already registered events
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
Labels: early-access-merge

#5771 lm: Recode LM service
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/lm/lm.cpp
  src/core/hle/service/lm/manager.cpp
  src/core/hle/service/lm/manager.h
  src/core/reporter.cpp
  src/core/reporter.h
Labels: early-access-merge

#5774 mii: Fix BuildRandomStoreData & Cleanup raw_data
  src/core/hle/service/mii/manager.cpp
  src/core/hle/service/mii/manager.h
  src/core/hle/service/mii/raw_data.cpp
  src/core/hle/service/mii/raw_data.h
Labels: early-access-merge

#5824 psm: IPsmSession
  src/core/hle/service/ptm/psm.cpp
Labels: early-access-merge

#5810 hle: Implement remaining services for Stereo Vision
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/pctl/module.cpp
Labels: early-access-merge, hle-new

#5812 HID: Stub Set/Get/Reset SixaxisSensorFusionParameters
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge, input

#5778 renderer_opengl: Avoid precompiled cache and force NV GL cache directory
  src/common/CMakeLists.txt
  src/common/nvidia_flags.cpp
  src/common/nvidia_flags.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: early-access-merge, opengl

#5798 vulkan_device: Blacklist Intel from float16 math
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: early-access-merge, vulkan

#5786 gl_shader_decompiler: Fix constant buffer size calculation
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: early-access-merge, gpu-fix, opengl

#5836 vk_scheduler: Fix unaligned placement new expressions
  src/video_core/renderer_vulkan/vk_scheduler.h
Labels: vulkan

#5809 audout: FlushAudioOutBuffers
  src/audio_core/stream.cpp
  src/audio_core/stream.h
  src/core/hle/service/audio/audout_u.cpp
Labels: audio-fix, early-access-merge

#5805 Fix connect and disconnect controller events
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge, input

#5795 video_core/memory_manager: Add BytesToMapEnd
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: early-access-merge, gpu

#5846 analog_from_button: Fix update_thread.join exception
  src/input_common/analog_from_button.cpp
Labels: bug
