Repository yuzu-emu/yuzu, pull requests merged in 2021-02, with the labels that each got.

#5841 Avoid overwriting username
  src/yuzu/configuration/configure_profile_manager.cpp
Labels: bug

#5842 acc: Fix error when second user is selected
  src/core/hle/service/acc/profile_manager.cpp
Labels: early-access-merge

#5848 kernel: Rewrite resource limit to be more accurate
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_light_condition_variable.h
  src/core/hle/kernel/k_resource_limit.cpp
  src/core/hle/kernel/k_resource_limit.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/memory/page_table.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/process.h
  src/core/hle/kernel/resource_limit.cpp
  src/core/hle/kernel/resource_limit.h
  src/core/hle/kernel/svc.cpp
Labels: early-access-merge

#5863 audren: Disable reverb for the time being
  src/audio_core/command_generator.cpp
Labels: audio-issue, early-access-merge

#5870 config: Always update handheld config
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge

#5876 k_affinity_mask: Avoid implicit truncation to bool
  src/core/hle/kernel/k_affinity_mask.h
Labels: general

#5875 k_priority_queue: Minor cleanup
  src/core/hle/kernel/k_priority_queue.h
Labels: general

#5326 HID: Update the HID service to match more closely to switchbrew part 1
  src/core/hle/service/am/applets/controller.cpp
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/keyboard.h
  src/core/hle/service/hid/controllers/mouse.cpp
  src/core/hle/service/hid/controllers/mouse.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/controllers/xpad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge

#5871 k_address_arbiter: Minor cleanup
  src/core/hle/kernel/k_address_arbiter.cpp
Labels: general

#5887 lm: Fix ReadLeb128
  src/core/hle/service/lm/lm.cpp
Labels: early-access-merge

#5872 svc: Provide more detailed error logs for svc functions
  src/core/hle/kernel/svc.cpp
Labels: general

#5339 Settings: Make settings controller image change with controller input
  dist/icons/controller/controller.qrc
  dist/icons/controller/dual_joycon.png
  dist/icons/controller/dual_joycon_dark.png
  dist/icons/controller/dual_joycon_midnight.png
  dist/icons/controller/handheld.png
  dist/icons/controller/handheld_dark.png
  dist/icons/controller/handheld_midnight.png
  dist/icons/controller/pro_controller.png
  dist/icons/controller/pro_controller_dark.png
  dist/icons/controller/pro_controller_midnight.png
  dist/icons/controller/single_joycon_left.png
  dist/icons/controller/single_joycon_left_dark.png
  dist/icons/controller/single_joycon_left_midnight.png
  dist/icons/controller/single_joycon_left_vertical.png
  dist/icons/controller/single_joycon_left_vertical_dark.png
  dist/icons/controller/single_joycon_left_vertical_midnight.png
  dist/icons/controller/single_joycon_right.png
  dist/icons/controller/single_joycon_right_dark.png
  dist/icons/controller/single_joycon_right_midnight.png
  dist/icons/controller/single_joycon_right_vertical.png
  dist/icons/controller/single_joycon_right_vertical_dark.png
  dist/icons/controller/single_joycon_right_vertical_midnight.png
  src/core/frontend/input.h
  src/input_common/analog_from_button.cpp
  src/input_common/gcadapter/gc_poller.cpp
  src/input_common/mouse/mouse_poller.cpp
  src/input_common/sdl/sdl_impl.cpp
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_input_player.ui
  src/yuzu/configuration/configure_input_player_widget.cpp
  src/yuzu/configuration/configure_input_player_widget.h
  src/yuzu/debugger/controller.cpp
  src/yuzu/debugger/controller.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#5868 Prevent over scheduling audio events and add motion update unschedule event
  src/audio_core/stream.cpp
  src/core/hle/service/hid/hid.cpp
Labels: early-access-merge

#5892 olsc: Stub GetSaveDataBackupSetting
  src/core/hle/service/olsc/olsc.cpp
Labels: early-access-merge

#5900 video_core: Remove unused functions and variables
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/texture_cache/util.cpp
Labels: general

#5901 udp: Silence warnings on Clang 12
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
  src/input_common/udp/udp.cpp
Labels: general

#5893 configure_input_player_widget: Minor cleanup
  src/yuzu/configuration/configure_input_player_widget.cpp
  src/yuzu/configuration/configure_input_player_widget.h
Labels: general

#5869 input_common: Add mouse panning
  src/core/settings.h
  src/input_common/mouse/mouse_input.cpp
  src/input_common/mouse/mouse_input.h
  src/input_common/mouse/mouse_poller.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_input_advanced.cpp
  src/yuzu/configuration/configure_input_advanced.ui
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: early-access-merge, input

#5902 core: Silence various warnings on Clang 12
  src/core/hle/service/am/applets/controller.cpp
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/sockets/bsd.cpp
Labels: bug, general

#5877 kernel: More accurately utilize resource_limit
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_scoped_resource_reservation.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/memory/page_table.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/session.cpp
  src/core/hle/kernel/shared_memory.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/transfer_memory.cpp
Labels: early-access-merge

#5917 vulkan_device: Require VK_EXT_robustness2
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: vulkan

#5925 vk_resource_pool: Load GPU tick once and compare with it
  src/video_core/renderer_vulkan/vk_resource_pool.cpp
  src/video_core/renderer_vulkan/vk_resource_pool.h
Labels: vulkan

#5920 Fix LDN Initialization return code & resulting AM overflow
  src/core/CMakeLists.txt
  src/core/hle/service/am/am.cpp
  src/core/hle/service/ldn/errors.h
  src/core/hle/service/ldn/ldn.cpp
Labels: early-access-merge

#5909 audren: Implement I3dl2Reverb
  src/audio_core/CMakeLists.txt
  src/audio_core/command_generator.cpp
  src/audio_core/command_generator.h
  src/audio_core/common.h
  src/audio_core/delay_line.cpp
  src/audio_core/delay_line.h
  src/audio_core/effect_context.cpp
  src/audio_core/effect_context.h
Labels: early-access-merge

#4940 HID: Implement GC controller in game
  src/core/frontend/applets/controller.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/input_common/settings.h
  src/yuzu/applets/controller.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_input_player_widget.cpp
Labels: early-access-merge, input

#5923 fixed_pipeline_cache: Use dirty flags to lazily update key
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_state_tracker.cpp
  src/video_core/renderer_vulkan/vk_state_tracker.h
Labels: early-access-merge, performance, vulkan

#3603 Port citra-emu/citra#5123: "SDL: Disable hidapi drivers due to compatibility problems with certain controllers"
  src/input_common/sdl/sdl_impl.cpp
Labels: frontend-fix

#5929 Improve mouse panning
  src/input_common/mouse/mouse_input.cpp
Labels: early-access-merge, input

#5121 core: Optimize core timing utility functions to avoid unnecessary math
  src/common/CMakeLists.txt
  src/common/uint128.cpp
  src/common/uint128.h
  src/common/wall_clock.cpp
  src/common/x64/native_clock.cpp
  src/core/CMakeLists.txt
  src/core/core_timing_util.cpp
  src/core/core_timing_util.h
Labels: early-access-merge

#4973 nvdec: Reuse allocated buffers and general cleanup
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/video_core/cdma_pusher.cpp
  src/video_core/cdma_pusher.h
  src/video_core/command_classes/codecs/codec.cpp
  src/video_core/command_classes/nvdec.cpp
  src/video_core/command_classes/nvdec.h
  src/video_core/command_classes/vic.cpp
  src/video_core/command_classes/vic.h
  src/video_core/gpu.cpp
  src/video_core/gpu_thread.cpp
Labels: early-access-merge

#5924 vk_update_descriptor: Inline and improve code for binding buffers
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_update_descriptor.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.h
Labels: early-access-merge, vulkan

#5936 Offsets for TexelFetch and TextureGather in Vulkan
  src/video_core/renderer_vulkan/vk_shader_decompiler.cpp
  src/video_core/shader/decode/memory.cpp
  src/video_core/shader/decode/texture.cpp
Labels: early-access-merge, gpu-new

#5997 [OpenGL] Implement glDepthRangeIndexeddNV
  externals/glad/include/glad/glad.h
  externals/glad/src/glad.c
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge, opengl

#5944 hid: Implement GameCube Controller Vibrations
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge

#5276 HID: Implement gestures
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/gesture.h
Labels: early-access-merge, hle-new

#6007 core: hle: ldn: Error out on call to Initialization.
  src/core/hle/service/ldn/ldn.cpp
Labels: early-access-merge
