Repository yuzu-emu/yuzu, pull requests merged in 2021-03, with the labels that each got.

#6020 core: Shutdown: Move kernel cleanup to later in shutdown.
  src/core/core.cpp
Labels: early-access-merge

#5815 Network error handling reform
  src/common/common_funcs.h
  src/common/misc.cpp
  src/core/network/network.cpp
  src/core/network/network.h
  src/tests/CMakeLists.txt
  src/tests/core/network/network.cpp
Labels: early-access-merge

#6004 InputCommon: Use an unique client id for each udp socket instance
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
  src/yuzu/configuration/configure_motion_touch.cpp
  src/yuzu/configuration/configure_motion_touch.h
Labels: early-access-merge, input

#5989 vk_command_pool: Reduce the command pool size from 4096 to 4
  src/video_core/renderer_vulkan/vk_command_pool.cpp
Labels: early-access-merge, vulkan

#6006 core: Switch to unique_ptr for usage of Common::Fiber.
  src/common/fiber.cpp
  src/common/fiber.h
  src/core/cpu_manager.cpp
  src/core/cpu_manager.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_scheduler.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/svc.cpp
  src/tests/common/fibers.cpp
Labels: early-access-merge

#6029 CMakeLists: Add /utf-8 compile option for MSVC
  src/CMakeLists.txt
Labels: early-access-merge

#6036 hle: kernel: KThread: Rework dummy threads & fix memory leak.
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/process.cpp
  src/core/hle/kernel/svc.cpp
Labels: early-access-merge

#6041 common: fiber: Use weak_ptr when yielding.
  src/common/fiber.cpp
  src/common/fiber.h
  src/core/cpu_manager.cpp
  src/core/hle/kernel/k_scheduler.cpp
  src/tests/common/fibers.cpp
Labels: early-access-merge

#5990 InputCommon: Mouse fixes
  src/input_common/mouse/mouse_input.cpp
  src/input_common/mouse/mouse_input.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.h
Labels: early-access-merge, input

#6021 buffer_cache: Heuristically decide to skip cache on uniform buffers
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
Labels: early-access-merge, performance

#5891 renderer_opengl: Use compute shaders to swizzle BGR textures on copy
  src/video_core/compatible_formats.cpp
  src/video_core/compatible_formats.h
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/opengl_copy_bgra.comp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/util_shaders.cpp
  src/video_core/renderer_opengl/util_shaders.h
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/image_base.cpp
  src/video_core/texture_cache/image_view_base.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/util.cpp
  src/video_core/texture_cache/util.h
Labels: early-access-merge, gpu-fix

#6040 Enable toggle buttons for keyboard and mouse
  src/input_common/keyboard.cpp
  src/input_common/mouse/mouse_input.cpp
  src/input_common/mouse/mouse_input.h
  src/input_common/mouse/mouse_poller.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge

#6028 video_core: rasterizer_accelerated: Use a flat array instead of interval_map for cached pages.
  src/video_core/rasterizer_accelerated.cpp
  src/video_core/rasterizer_accelerated.h
Labels: early-access-merge

#6053 time: Fix CalculateSpanBetween implementation
  src/core/hle/service/time/time.cpp
Labels: early-access-merge

#6054 time: Assign the current time point to the ClockSnapshot
  src/core/hle/service/time/time.cpp
Labels: early-access-merge

#6055 [testing] fiber: Double default stack size
  src/common/fiber.cpp
Labels: early-access-merge

#6056 service: Refactor spl
  src/core/hle/service/spl/module.cpp
  src/core/hle/service/spl/spl.cpp
  src/core/hle/service/spl/spl.h
Labels: early-access-merge

#6078 externals/libusb/CMakeLists: Add /utf-8 compile option for MSVC
  externals/libusb/CMakeLists.txt
Labels: early-access-merge

#6092 Fix cancelation of getExistingDirectory dialog
  src/yuzu/configuration/configure_filesystem.cpp
Labels: early-access-merge

#6100 core: arm_dynarmic: Ensure JIT state is saved/restored on page table changes.
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
Labels: early-access-merge

#6101 nvdrv: Change InitializeEx to AllocAsEx
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
Labels: early-access-merge

#6102 nvdrv: Pass device fd and handle device create methods for device opening and closing
  src/core/hle/service/nvdrv/devices/nvdevice.h
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.h
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/core/hle/service/nvdrv/devices/nvhost_vic.h
  src/core/hle/service/nvdrv/devices/nvmap.cpp
  src/core/hle/service/nvdrv/devices/nvmap.h
  src/core/hle/service/nvdrv/nvdrv.cpp
Labels: early-access-merge

#6109 HID: Initialize correctly the gesture finger_id and filter invalid inputs
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/touchscreen.cpp
Labels: early-access-merge, hle-fix

#5927 video_core: Accelerate ASTC texture decoding using compute shaders
  src/video_core/CMakeLists.txt
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/StringShaderHeader.cmake
  src/video_core/host_shaders/astc_decoder.comp
  src/video_core/host_shaders/source_shader.h.in
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/util_shaders.cpp
  src/video_core/renderer_opengl/util_shaders.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/accelerated_swizzle.h
  src/video_core/texture_cache/util.cpp
  src/video_core/textures/astc.cpp
  src/video_core/textures/astc.h
  src/video_core/textures/decoders.cpp
  src/video_core/textures/decoders.h
Labels: early-access-merge, gpu, performance
