Repository yuzu-emu/yuzu, pull requests merged in 2021-05, with the labels that each got.

#6265 service: filesystem: Return proper error codes for CreateFile
  src/core/file_sys/errors.h
  src/core/hle/service/filesystem/filesystem.cpp
Labels: early-access-merge

#6263 game_list: Fix dir move up/down expand state
  src/yuzu/game_list.cpp
Labels: early-access-merge

#6269 file_sys: Resolve cases of variable shadowing
  src/core/file_sys/card_image.cpp
  src/core/file_sys/content_archive.cpp
  src/core/file_sys/fsmitm_romfsbuild.cpp
  src/core/file_sys/fsmitm_romfsbuild.h
  src/core/file_sys/nca_patch.cpp
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/romfs_factory.h
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/vfs_concat.cpp
  src/core/file_sys/vfs_concat.h
  src/core/file_sys/vfs_layered.cpp
  src/core/file_sys/vfs_layered.h
  src/core/file_sys/vfs_offset.cpp
  src/core/file_sys/vfs_offset.h
  src/core/file_sys/vfs_real.cpp
  src/core/file_sys/vfs_real.h
  src/core/file_sys/vfs_vector.cpp
  src/core/file_sys/vfs_vector.h
Labels: general

#6277 hid: Fix touch not initializing properly if disabled
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/touchscreen.cpp
Labels: bug

#6278 core: Resolve misc straggler cases of variable shadowing
  src/core/arm/dynarmic/arm_dynarmic_cp15.cpp
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/cpu_manager.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/deconstructed_rom_directory.h
  src/core/memory/cheat_engine.cpp
  src/core/memory/cheat_engine.h
  src/core/tools/freezer.cpp
  src/core/tools/freezer.h
Labels: general

#6281 service: Resolve cases of member field shadowing
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.h
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.h
  src/core/hle/service/acc/acc_aa.cpp
  src/core/hle/service/acc/acc_aa.h
  src/core/hle/service/acc/acc_su.cpp
  src/core/hle/service/acc/acc_su.h
  src/core/hle/service/acc/acc_u0.cpp
  src/core/hle/service/acc/acc_u0.h
  src/core/hle/service/acc/acc_u1.cpp
  src/core/hle/service/acc/acc_u1.h
  src/core/hle/service/am/applets/software_keyboard.cpp
  src/core/hle/service/am/applets/software_keyboard.h
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/bcat/bcat.cpp
  src/core/hle/service/bcat/bcat.h
  src/core/hle/service/grc/grc.cpp
  src/core/hle/service/hid/controllers/console_sixaxis.cpp
  src/core/hle/service/hid/controllers/console_sixaxis.h
  src/core/hle/service/hid/controllers/debug_pad.cpp
  src/core/hle/service/hid/controllers/debug_pad.h
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/gesture.h
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/keyboard.h
  src/core/hle/service/hid/controllers/mouse.cpp
  src/core/hle/service/hid/controllers/mouse.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/controllers/stubbed.cpp
  src/core/hle/service/hid/controllers/stubbed.h
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
  src/core/hle/service/hid/controllers/xpad.cpp
  src/core/hle/service/hid/controllers/xpad.h
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.h
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.h
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/core/hle/service/nvdrv/devices/nvhost_vic.h
  src/core/hle/service/nvdrv/devices/nvmap.cpp
  src/core/hle/service/nvdrv/devices/nvmap.h
  src/core/hle/service/pctl/module.cpp
  src/core/hle/service/pctl/module.h
  src/core/hle/service/time/interface.cpp
  src/core/hle/service/time/interface.h
Labels: general

#6283 service: Remove unused class variables
  src/core/hle/service/am/applets/web_browser.h
  src/core/hle/service/lbl/lbl.cpp
  src/core/hle/service/pctl/module.cpp
Labels: general

#6279 nvdrv: /dev/nvhost-prof-gpu for production
  src/core/hle/service/nvdrv/interface.cpp
Labels: early-access-merge

#6291 kernel: Eliminate variable shadowing
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/k_auto_object.h
  src/core/hle/kernel/k_client_port.cpp
  src/core/hle/kernel/k_client_port.h
  src/core/hle/kernel/k_client_session.cpp
  src/core/hle/kernel/k_client_session.h
  src/core/hle/kernel/k_condition_variable.cpp
  src/core/hle/kernel/k_event.cpp
  src/core/hle/kernel/k_event.h
  src/core/hle/kernel/k_linked_list.h
  src/core/hle/kernel/k_memory_block_manager.cpp
  src/core/hle/kernel/k_memory_region.h
  src/core/hle/kernel/k_port.cpp
  src/core/hle/kernel/k_port.h
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_readable_event.cpp
  src/core/hle/kernel/k_readable_event.h
  src/core/hle/kernel/k_resource_limit.cpp
  src/core/hle/kernel/k_resource_limit.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_scheduler.h
  src/core/hle/kernel/k_server_port.cpp
  src/core/hle/kernel/k_server_port.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_server_session.h
  src/core/hle/kernel/k_session.cpp
  src/core/hle/kernel/k_session.h
  src/core/hle/kernel/k_shared_memory.cpp
  src/core/hle/kernel/k_shared_memory.h
  src/core/hle/kernel/k_synchronization_object.cpp
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/k_transfer_memory.cpp
  src/core/hle/kernel/k_transfer_memory.h
  src/core/hle/kernel/k_writable_event.cpp
  src/core/hle/kernel/k_writable_event.h
  src/core/hle/kernel/kernel.cpp
Labels: general

#6267 hid: Improve hardware accuracy of gestures
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/gesture.h
Labels: early-access-merge

#6298 configure_ui: Call RequestGameListUpdate when toggling "Show Add-Ons Column"
  src/yuzu/configuration/configure_ui.cpp
Labels: early-access-merge

#6301 ssl: Stub Import(Client/Server)Pki
  src/core/hle/service/ssl/ssl.cpp
Labels: early-access-merge

#6244 input_common: Implement SDL motion
  src/input_common/main.cpp
  src/input_common/sdl/sdl.h
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/sdl/sdl_impl.h
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge

#6289 texture_cache: Handle out of bound texture blits
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/blit_image.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/types.h
Labels: early-access-merge

#6299 Various improvements to IPC and session management
  src/common/tree.h
  src/core/hle/ipc.h
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/k_client_port.cpp
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_session.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/slab_helpers.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/audren_u.h
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/hle/service/sm/controller.cpp
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
Labels: mainline-merge

#6316 main: Add running title's version to window name on EA/mainline
  src/yuzu/main.cpp
Labels: early-access-merge

#6293 On Linux, build SDL2 from externals with HIDAPI support
  CMakeLists.txt
  externals/CMakeLists.txt
Labels: early-access-merge

#6284 nvflinger: Create layers when they are queried but not found
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
Labels: early-access-merge

#6319 main: Prevent installing base titles into NAND
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#6322 buffer_cache: Ensure null buffers cannot take the fast uniform bind path
  src/video_core/buffer_cache/buffer_cache.h
Labels: early-access-merge

#6317 perf_stats: Rework FPS counter to be more accurate
  src/core/core.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/perf_stats.cpp
  src/core/perf_stats.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: early-access-merge

#6310 input_common: Sanitize motion data
  src/input_common/udp/client.cpp
Labels: early-access-merge

#6297 parent_of_member: Make sign conversion explicit in OffsetOfImpl()
  src/common/parent_of_member.h
Labels: general

#6321 configuration: Add CPU tab to game properties and slight per-game settings rework
  src/common/settings.cpp
  src/common/settings.h
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/core.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configuration_shared.cpp
  src/yuzu/configuration/configuration_shared.h
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_cpu.cpp
  src/yuzu/configuration/configure_cpu.h
  src/yuzu/configuration/configure_cpu.ui
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_per_game.ui
  src/yuzu/configuration/configure_system.cpp
  src/yuzu_cmd/config.cpp
Labels: early-access-merge

#6333 applets/swkbd: Send the correct text string on TextCheck::Confirm
  src/yuzu/applets/software_keyboard.cpp
Labels: early-access-merge

#6347 Various improvements to IPC and session management (Part 2)
  src/common/tree.h
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/init/init_slab_setup.cpp
  src/core/hle/kernel/k_client_port.cpp
  src/core/hle/kernel/k_client_port.h
  src/core/hle/kernel/k_port.cpp
  src/core/hle/kernel/k_server_port.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_server_session.h
  src/core/hle/kernel/k_session.cpp
  src/core/hle/kernel/k_session.h
  src/core/hle/kernel/k_slab_heap.h
  src/core/hle/kernel/service_thread.cpp
  src/core/hle/kernel/slab_helpers.h
  src/core/hle/service/service.cpp
  src/core/hle/service/sm/controller.cpp
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
  src/core/memory.cpp
  src/core/memory.h
Labels: early-access-merge

#6312 input_common: Rewrite sdl analog mapping and fix controller disconnection crash
  src/input_common/sdl/sdl_impl.cpp
Labels: early-access-merge

#6357 common/compression: Make use of std::span
  src/common/lz4_compression.cpp
  src/common/lz4_compression.h
  src/common/zstd_compression.cpp
  src/common/zstd_compression.h
Labels: general

#6348 CMakeLists: Update zstd to 1.5.0
  CMakeLists.txt
Labels: build-system-new

#6331 hid/gesture: Simplify point related code
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/gesture.h
Labels: general

#6346 yuzu qt: Add an Apply button to configuration dialogs
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_dialog.h
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_per_game.h
  src/yuzu/main.cpp
  src/yuzu/uisettings.h
Labels: early-access-merge

#6372 video_core: rasterizer_cache: Use u16 for cached page count.
  src/video_core/rasterizer_accelerated.cpp
  src/video_core/rasterizer_accelerated.h
Labels: early-access-merge

#6375 common/fs/file: Default initialize IOFile members
  src/common/fs/file.h
Labels: general

#6371 core/arm_interface: Call SVC after end of dynarmic block.
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.h
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.h
  src/core/hle/kernel/k_scheduler.cpp
Labels: early-access-merge

#6373 hle: kernel: KSlabHeap: Allow host or guest allocations.
  src/core/hle/kernel/k_slab_heap.h
  src/core/hle/kernel/kernel.cpp
Labels: early-access-merge

#6382 k_thread: Move dereference after null check in Initialize()
  src/core/hle/kernel/k_thread.cpp
Labels: kernel-fix

#6384 kernel: Add missing override specifiers
  src/core/hle/kernel/k_client_port.h
  src/core/hle/kernel/k_client_session.h
  src/core/hle/kernel/k_event.h
  src/core/hle/kernel/k_port.h
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_readable_event.h
  src/core/hle/kernel/k_resource_limit.h
  src/core/hle/kernel/k_server_port.h
  src/core/hle/kernel/k_server_session.h
  src/core/hle/kernel/k_session.h
  src/core/hle/kernel/k_shared_memory.h
  src/core/hle/kernel/k_synchronization_object.h
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/k_transfer_memory.h
  src/core/hle/kernel/k_writable_event.h
Labels: general

#6386 video_core: gpu: WaitFence: Do not block threads during shutdown.
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: early-access-merge

#6387 k_class_token: Use variable templates where applicable
  src/core/hle/kernel/k_class_token.cpp
Labels: general

#6377 common: Extract Point struct into common
  src/common/CMakeLists.txt
  src/common/point.h
  src/core/hle/service/hid/controllers/gesture.h
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
Labels: general

#6385 core/memory: Check our memory fallbacks for out-of-bound behavior.
  src/common/page_table.cpp
  src/common/page_table.h
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/memory.cpp
Labels: early-access-merge
