Repository yuzu-emu/yuzu, pull requests merged in 2021-06, with the labels that each got.

#6367 vulkan_memory_allocator: Allow textures to be allocated in host memory
  src/video_core/vulkan_common/vulkan_memory_allocator.cpp
  src/video_core/vulkan_common/vulkan_memory_allocator.h
Labels: early-access-merge, vulkan

#6318 input_common: Add dual joycon support
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/sdl/sdl_impl.h
Labels: early-access-merge

#6395 common_funcs: Move R_ macros to result.h
  src/common/common_funcs.h
  src/core/hle/result.h
Labels: general

#6389 input_common: Analog button, use time based position
  src/core/frontend/input.h
  src/input_common/analog_from_button.cpp
  src/input_common/keyboard.cpp
Labels: early-access-merge

#6392 settings: Disable controller preview if controller is not active
  src/yuzu/configuration/configure_input_player_widget.cpp
  src/yuzu/configuration/configure_input_player_widget.h
  src/yuzu/debugger/controller.cpp
Labels: early-access-merge

#6362 yuzu qt: Add settings reset button to general configuration
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.h
  src/yuzu/configuration/configure_general.ui
  src/yuzu/main.cpp
  src/yuzu/uisettings.h
Labels: early-access-merge

#6415 result: Add [[nodiscard]] specifiers where applicable
  src/core/hle/result.h
Labels: general

#6400 buffer_cache: Simplify uniform disabling logic
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/memory_manager.cpp
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: early-access-merge

#6414 hle: kernel: Refactor to allocate a ServiceThread per service handler.
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/k_auto_object.h
  src/core/hle/kernel/k_auto_object_container.cpp
  src/core/hle/kernel/k_auto_object_container.h
  src/core/hle/kernel/k_client_port.cpp
  src/core/hle/kernel/k_client_port.h
  src/core/hle/kernel/k_client_session.h
  src/core/hle/kernel/k_readable_event.h
  src/core/hle/kernel/k_server_port.cpp
  src/core/hle/kernel/k_server_port.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_server_session.h
  src/core/hle/kernel/k_session.cpp
  src/core/hle/kernel/k_session.h
  src/core/hle/kernel/k_writable_event.cpp
  src/core/hle/service/ns/pl_u.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/hle/service/sm/controller.cpp
  src/core/hle/service/sm/sm.cpp
Labels: early-access-merge

#6410 decoders: Avoid out-of-bounds access
  src/video_core/textures/decoders.cpp
Labels: early-access-merge

#6412 yuzu-cmd: Fix OpenGL rendering
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.h
Labels: early-access-merge

#6428 hle: kernel: Remove service thread manager and use weak_ptr.
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/kernel.cpp
Labels: bug, kernel-fix, mainline-merge, regression

#6434 configure_ui: Add translation context for file-scope strings
  src/yuzu/configuration/configure_ui.cpp
Labels: frontend-fix

#6435 common/fs/path_util: Remove [[nodiscard]] from function with void return
  src/common/fs/path_util.h
Labels: general

#6443 kernel: KLightConditionVariable: Update implementation to 12.x
  src/core/hle/kernel/k_light_condition_variable.h
  src/core/hle/kernel/k_light_lock.cpp
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_resource_limit.cpp
Labels: early-access-merge

#6452 hid: Stub IsFirmwareUpdateAvailableForSixAxisSensor
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge

#6448 common: fs: Use the normal directory iterator in *Recursively functions
  src/common/fs/fs.cpp
Labels: early-access-merge

#6460 fsp_srv: Fix filesystem access logging
  src/common/fs/file.cpp
  src/common/fs/file.h
  src/common/settings.h
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
  src/core/reporter.cpp
  src/core/reporter.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge, hle-fix

#6464 textures: Add a toggle for GPU Accelerated ASTC decoder
  src/common/settings.cpp
  src/common/settings.h
  src/core/telemetry_session.cpp
  src/video_core/CMakeLists.txt
  src/video_core/host_shaders/astc_decoder.comp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/texture_cache/util.cpp
  src/video_core/textures/astc.cpp
  src/video_core/textures/astc.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge

#6469 texture_cache/util: Avoid relaxed image views on different bytes per block
  src/video_core/texture_cache/util.cpp
Labels: early-access-merge, gpu-fix

#6418 Audio: SDL2 audio backend
  externals/CMakeLists.txt
  src/audio_core/CMakeLists.txt
  src/audio_core/sdl2_sink.cpp
  src/audio_core/sdl2_sink.h
  src/audio_core/sink_details.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge

#6475 nvflinger: Add experimental toggle to disable buffer swap interval limits
  src/common/settings.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu/main.cpp
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge

#6506 vk_master_semaphore: Use jthread for debug thread
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.h
Labels: early-access-merge

#6514 Simple resizing of Per-Game configuration window and removal of useless Help question mark button in the title bar
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_per_game.ui
Labels: frontend-fix

#6465 GPU: Implement a garbage collector for GPU Caches (project Reaper+)
  src/common/common_sizes.h
  src/common/settings.cpp
  src/common/settings.h
  src/video_core/buffer_cache/buffer_base.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/image_base.cpp
  src/video_core/texture_cache/image_base.h
  src/video_core/texture_cache/slot_vector.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/util.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
  src/video_core/vulkan_common/vulkan_memory_allocator.cpp
  src/video_core/vulkan_common/vulkan_memory_allocator.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge, gpu-new

#6518 maxwell3d: Add missing return in default SizeInBytes() case
  src/video_core/engines/maxwell_3d.h
Labels: general

#6504 [audout] Implement GetAudioOutPlayedSampleCount
  src/audio_core/stream.cpp
  src/audio_core/stream.h
  src/core/hle/service/audio/audout_u.cpp
Labels: early-access-merge

#6522 general: Add missing #pragma once directives
  src/common/logging/types.h
  src/core/hle/api_version.h
  src/core/hle/service/spl/spl_results.h
  src/core/hle/service/spl/spl_types.h
Labels: general

#6496 astc: Various robustness enhancements for the gpu decoder
  src/video_core/host_shaders/astc_decoder.comp
  src/video_core/renderer_opengl/util_shaders.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/textures/astc.cpp
  src/video_core/textures/astc.h
Labels: early-access-merge, gpu-fix

#6526 services: Misc. minor changes for latest SDK update.
  src/audio_core/common.h
  src/core/hle/ipc_helpers.h
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/aoc/aoc_u.h
  src/core/hle/service/audio/hwopus.cpp
  src/core/hle/service/audio/hwopus.h
Labels: early-access-merge

#6529 buffer_cache,texture_cache: Misc fixups from the memory reaper
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/command_classes/codecs/codec.h
  src/video_core/command_classes/vic.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge

#6502 main: Add GPU Vendor name to running title bar
  src/video_core/renderer_base.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#6471 yuzu qt, core: Support LayeredFS mods from SDMC directory
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/patch_manager.h
  src/core/file_sys/sdmc_factory.cpp
  src/core/file_sys/sdmc_factory.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge
