Repository yuzu-emu/yuzu, pull requests merged in 2021-04, with the labels that each got.

#6106 [test] arm_dynarmic: Always have a 'valid' jit instance
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.h
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.h
Labels: early-access-merge

#6131 HID: Fix SL and SR buttons for right joycon
  src/core/hle/service/hid/controllers/npad.cpp
Labels: hle-fix

#6127 InputCommon: Improve UDP communications
  src/input_common/udp/client.cpp
  src/input_common/udp/client.h
  src/yuzu/configuration/configure_motion_touch.cpp
  src/yuzu/configuration/configure_motion_touch.h
Labels: early-access-merge

#6062 service: Add a toggle for auto stub fallback
  src/core/hle/service/service.cpp
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
Labels: early-access-merge

#6162 video_core: Avoid spin loops.
  src/common/threadsafe_queue.h
  src/core/core.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
Labels: early-access-merge

#6113 Friend: Stub GetPlayHistoryRegistrationKey
  src/core/hle/service/friend/friend.cpp
Labels: early-access-merge

#6099 Kernel Rework: Derive memory regions from board layout.
  src/common/CMakeLists.txt
  src/common/common_sizes.h
  src/core/CMakeLists.txt
  src/core/hle/kernel/arch/arm64/k_memory_region_device_types.inc
  src/core/hle/kernel/board/nintendo/nx/k_memory_region_device_types.inc
  src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
  src/core/hle/kernel/board/nintendo/nx/k_system_control.h
  src/core/hle/kernel/board/nintendo/nx/secure_monitor.h
  src/core/hle/kernel/k_address_space_info.cpp
  src/core/hle/kernel/k_memory_layout.board.nintendo_nx.cpp
  src/core/hle/kernel/k_memory_layout.cpp
  src/core/hle/kernel/k_memory_layout.h
  src/core/hle/kernel/k_memory_manager.cpp
  src/core/hle/kernel/k_memory_manager.h
  src/core/hle/kernel/k_memory_region.h
  src/core/hle/kernel/k_memory_region_type.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_scheduler.h
  src/core/hle/kernel/k_scheduler_lock.h
  src/core/hle/kernel/k_spin_lock.h
  src/core/hle/kernel/k_system_control.cpp
  src/core/hle/kernel/k_system_control.h
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/k_trace.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
Labels: early-access-merge

#6112 pctl: Rework how pctl works to be more accurate
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/hle/service/pctl/module.cpp
  src/core/hle/service/pctl/module.h
  src/core/hle/service/pctl/pctl.cpp
  src/core/hle/service/pctl/pctl.h
Labels: early-access-merge

#6167 service: time: Fix CalculateStandardUserSystemClockDifferenceByUser
  src/core/hle/service/time/time.cpp
Labels: early-access-merge

#6170 service: time: Setup the network clock with the local clock context
  src/core/hle/service/time/clock_types.h
  src/core/hle/service/time/time.cpp
  src/core/hle/service/time/time.h
  src/core/hle/service/time/time_manager.cpp
  src/core/hle/service/time/time_zone_manager.cpp
  src/core/hle/service/time/time_zone_types.h
Labels: early-access-merge

#6135 configure_graphics: Add Borderless Windowed fullscreen mode
  src/core/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu/main.cpp
Labels: early-access-merge, frontend-new

#6192 k_thread: Remove [[nodiscard]] attribute from ClearWaitCancelled()
  src/core/hle/kernel/k_thread.h
Labels: general

#6193 nvidia_flags: Add missing header guard
  src/common/nvidia_flags.h
Labels: general

#6187 texure_cache/util: Resolve implicit sign conversions with std::reduce
  src/video_core/texture_cache/util.cpp
  src/video_core/texture_cache/util.h
Labels: general

#6188 vk_texture_cache: Make use of bit_cast where applicable
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: general

#6191 engine_interface: Add missing virtual destructor
  src/video_core/engines/engine_interface.h
  src/video_core/engines/fermi_2d.h
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_dma.h
Labels: general

#6185 kernel/process: Replace process resource limit instance with the kernel's resource limit
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/process.cpp
Labels: early-access-merge

#6119 InputCommon: Address mapping and naming issues with SDL2
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/sdl/sdl_impl.h
Labels: early-access-merge

#6201 cmake: Remove use of bintray for externals.
  .ci/templates/build-msvc.yml
  CMakeLists.txt
Labels: early-access-merge

#6216 arp: Prevent potential uninitialized read of launch member variable
  src/core/hle/service/glue/arp.cpp
Labels: general

#6215 npad: Remove duplicated class member variable
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
Labels: general

#6218 texture_cache/util: Fix src being used instead of dst within DeduceBlitImages case
  src/video_core/texture_cache/util.cpp
Labels: bug

#6219 log/backend: Make use of erase_if
  src/common/logging/backend.cpp
  src/common/logging/backend.h
Labels: general

#6214 time: Fix GetClockSnapshotFromSystemClockContext
  src/core/hle/service/time/time.cpp
Labels: early-access-merge

#6232 emu_window: unsigned -> u32
  src/core/frontend/emu_window.cpp
  src/core/frontend/emu_window.h
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.h
Labels: general

#6231 aes_util: Make use of std::span
  src/core/crypto/aes_util.cpp
  src/core/crypto/aes_util.h
Labels: general

#6229 acc/lbl: Remove unused variables
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/lbl/lbl.cpp
Labels: general

#6228 lm: Resolve -Wextra-semi warning
  src/core/hle/service/lm/lm.cpp
Labels: general

#6227 program_metadata: Explicitly specify copy/move operators/functions
  src/core/file_sys/program_metadata.h
Labels: general

#6230 program_metadata: Set a default resource size when a NPDM is not present
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
  src/core/loader/kip.cpp
Labels: bug

#6198 game_list: Mark games as favorite to make them appear at the top.
  dist/license.md
  dist/qt_themes/colorful/icons/48x48/star.png
  dist/qt_themes/colorful/style.qrc
  dist/qt_themes/default/default.qrc
  dist/qt_themes/default/icons/48x48/star.png
  dist/qt_themes/qdarkstyle/icons/48x48/star.png
  dist/qt_themes/qdarkstyle/style.qrc
  dist/qt_themes/qdarkstyle_midnight_blue/icons/48x48/star.png
  dist/qt_themes/qdarkstyle_midnight_blue/style.qrc
  license.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/game_list_p.h
  src/yuzu/uisettings.h
Labels: early-access-merge

#6246 service: Eliminate cases of member variable shadowing
  src/core/hle/service/am/applets/error.cpp
  src/core/hle/service/am/applets/general_backend.cpp
  src/core/hle/service/bcat/backend/boxcat.cpp
  src/core/hle/service/bcat/module.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/time/standard_user_system_clock_core.cpp
  src/core/hle/service/time/standard_user_system_clock_core.h
  src/core/hle/service/time/system_clock_core.cpp
  src/core/hle/service/time/system_clock_core.h
  src/core/hle/service/time/time_manager.cpp
  src/core/hle/service/time/time_sharedmemory.cpp
  src/core/hle/service/time/time_sharedmemory.h
  src/core/hle/service/vi/display/vi_display.cpp
  src/core/hle/service/vi/display/vi_display.h
Labels: general

#6250 loader: Resolve instances of variable shadowing
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/deconstructed_rom_directory.h
  src/core/loader/elf.cpp
  src/core/loader/elf.h
  src/core/loader/kip.cpp
  src/core/loader/kip.h
  src/core/loader/loader.h
  src/core/loader/nax.cpp
  src/core/loader/nax.h
  src/core/loader/nca.cpp
  src/core/loader/nca.h
  src/core/loader/nro.cpp
  src/core/loader/nro.h
  src/core/loader/nso.cpp
  src/core/loader/nso.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
Labels: general

#6226 hid: Implement SevenSixAxis and ConsoleSixAxisSensor
  src/core/CMakeLists.txt
  src/core/frontend/input.h
  src/core/hle/kernel/transfer_memory.cpp
  src/core/hle/kernel/transfer_memory.h
  src/core/hle/service/hid/controllers/console_sixaxis.cpp
  src/core/hle/service/hid/controllers/console_sixaxis.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
  src/input_common/motion_input.cpp
Labels: early-access-merge

#6257 applets/web: Fix a use-after-free when passing in the URL string
  src/core/frontend/applets/web_browser.cpp
  src/core/frontend/applets/web_browser.h
  src/yuzu/applets/web_browser.cpp
  src/yuzu/applets/web_browser.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge
