Repository yuzu-emu/yuzu, pull requests merged in 2021-08, with the labels that each got.

#6765 vk_rasterizer: Flip viewport on Y_NEGATE
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge, vulkan

#6720 renderer_vulkan: Implement screenshots
  src/video_core/renderer_base.cpp
  src/video_core/renderer_base.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/yuzu/bootmanager.cpp
Labels: early-access-merge, gpu-new, vulkan

#6762 ui: make game list dir icons smaller
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_ui.cpp
  src/yuzu/configuration/configure_ui.ui
  src/yuzu/game_list.cpp
  src/yuzu/game_list_p.h
  src/yuzu/uisettings.h
Labels: early-access-merge

#6790 decoders: Double the performance
  src/video_core/textures/decoders.cpp
Labels: early-access-merge, performance

#6713 nvdec: Implement VA-API hardware video acceleration
  CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/command_classes/codecs/codec.cpp
  src/video_core/command_classes/codecs/codec.h
  src/video_core/command_classes/vic.cpp
  src/video_core/command_classes/vic.h
Labels: early-access-merge

#6818 hex_util: Fix incorrect array size in AsArray
  src/common/hex_util.h
Labels: bug

#6819 applet_swkbd: Include the null terminator in the buffer size calculation
  src/core/hle/service/am/applets/applet_software_keyboard.cpp
Labels: bug

#6799 nvdec: Fix VP9 reference frame refreshes
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/codecs/vp9.h
  src/video_core/command_classes/codecs/vp9_types.h
Labels: gpu-fix, mainline-merge

#6791 astc_decoder: Various performance and memory optimizations
  src/video_core/host_shaders/astc_decoder.comp
  src/video_core/renderer_opengl/util_shaders.cpp
  src/video_core/renderer_opengl/util_shaders.h
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/textures/astc.cpp
  src/video_core/textures/astc.h
Labels: performance, early-access-merge

#6830 nvdec: Better logging for unimplemented codecs
  src/video_core/command_classes/nvdec.cpp
Labels: general

#6698 input_common: Improve SDL joystick and hide toggle option
  src/input_common/main.cpp
  src/input_common/mouse/mouse_poller.cpp
  src/input_common/sdl/sdl_impl.cpp
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge, input

#6834 Respect Vulkan bufferImageGranularity
  src/video_core/vulkan_common/vulkan_memory_allocator.cpp
  src/video_core/vulkan_common/vulkan_memory_allocator.h
Labels: early-access-merge

#6823 memory: Clean up code
  src/core/memory.cpp
  src/core/memory.h
Labels: early-access-merge

#6820 texture_cache: Split out template definitions
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/gl_texture_cache_base.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/renderer_vulkan/vk_texture_cache_base.cpp
  src/video_core/texture_cache/image_view_info.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
Labels: general, early-access-merge

#6862 input_common: Disable sdl raw input mode
  src/input_common/sdl/sdl_impl.cpp
Labels: early-access-merge

#6861 decoders: Optimize memcpy for the other functions
  src/video_core/textures/decoders.cpp
Labels: performance, early-access-merge

#6863 Fix LAN Play
  CMakeLists.txt
  src/common/settings.h
  src/core/CMakeLists.txt
  src/core/hle/service/nifm/nifm.cpp
  src/core/network/network.cpp
  src/core/network/network.h
  src/core/network/network_interface.cpp
  src/core/network/network_interface.h
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure.ui
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_network.cpp
  src/yuzu/configuration/configure_network.h
  src/yuzu/configuration/configure_network.ui
Labels: hle-new, hle-fix, early-access-merge

#6832 kernel: Various improvements to scheduler
  src/core/core.cpp
  src/core/core.h
  src/core/cpu_manager.cpp
  src/core/cpu_manager.h
  src/core/hle/kernel/k_address_arbiter.cpp
  src/core/hle/kernel/k_auto_object.h
  src/core/hle/kernel/k_condition_variable.cpp
  src/core/hle/kernel/k_handle_table.cpp
  src/core/hle/kernel/k_handle_table.h
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_scheduler.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/vi/display/vi_display.cpp
  src/core/hle/service/vi/display/vi_display.h
Labels: early-access-merge

#6904 settings: Amend language_index maximum setting range
  src/common/settings.h
Labels: frontend-fix

#6869 logging: Simplify and make thread-safe
  src/common/logging/backend.cpp
  src/common/logging/backend.h
  src/core/core.cpp
  src/core/core.h
  src/tests/common/param_package.cpp
  src/yuzu/debugger/console.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: frontend-fix, early-access-merge

#6912 CMakeLists: Ensure proper numerusform tags are generated for pluralized translations
  src/yuzu/CMakeLists.txt
Labels: build-system-fix

#6878 kernel: Optimize GetHostThreadID
  src/core/hle/kernel/kernel.cpp
Labels: performance, early-access-merge

#6921 vp9_types: Remove unusued VP9 info struct members
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/codecs/vp9_types.h
Labels: early-access-merge

#6905 nifm/network_interface: Cleanup and populate fields in GetCurrentNetworkProfile
  src/core/hle/service/nifm/nifm.cpp
  src/core/network/network_interface.cpp
Labels: hle-fix, early-access-merge

#6879 vk_blit_screen: Fix non-accelerated texture size calculation
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/textures/decoders.cpp
Labels: early-access-merge

#6928 emit_spirv_context_get_set: Fix Get FrontFace return value
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
Labels: gpu-fix, vulkan, early-access-merge

#6897 Project <tentative title>: Rework Garbage Collection.
  src/common/lru_cache.h
  src/common/settings.cpp
  src/common/settings.h
  src/video_core/buffer_cache/buffer_base.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/texture_cache/image_base.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/config.cpp
Labels: gpu-fix, early-access-merge
