Repository yuzu-emu/yuzu, pull requests merged in 2021-09, with the labels that each got.

#6900 structured_control_flow: Add DemoteCombinationPass
  src/shader_recompiler/frontend/maxwell/structured_control_flow.cpp
  src/shader_recompiler/frontend/maxwell/structured_control_flow.h
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/host_translate_info.h
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: gpu-fix, early-access-merge

#6968 core: hle: service: nvflinger/vi: Improve management of KEvent.
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/vi/display/vi_display.cpp
  src/core/hle/service/vi/display/vi_display.h
Labels: early-access-merge

#6965 core: cpu_manager: Use jthread.
  src/core/cpu_manager.cpp
  src/core/cpu_manager.h
Labels: early-access-merge

#6971 core: hle: service: buffer_queue: Improve management of KEvent.
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/nvflinger/nvflinger.cpp
Labels: early-access-merge

#6980 Fix blend equation enum error
  src/video_core/engines/maxwell_3d.h
Labels: early-access-merge

#6962 renderer_vulkan: Spirv support glsl legacy attribute
  src/shader_recompiler/backend/spirv/emit_context.cpp
  src/shader_recompiler/backend/spirv/emit_context.h
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
Labels: early-access-merge

#6981 nvflinger: Use external surface format for framebuffer creation
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/nvflinger/nvflinger.cpp
Labels: gpu-fix, early-access-merge

#6953 renderer_vulkan: Wait on present semaphore at queue submit
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
Labels: gpu-fix, vulkan, early-access-merge

#6941 vk_swapchain: Prefer linear swapchain format when presenting sRGB images
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-fix, vulkan, early-access-merge

#6901 vk_rasterizer: Only clear depth/stencil buffers when specified in attachment aspect mask
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
Labels: gpu-fix, early-access-merge

#6846 nvdec: Add GPU video decoding for all capable drivers and platforms
  CMakeLists.txt
  src/common/settings.cpp
  src/common/settings.h
  src/core/telemetry_session.cpp
  src/video_core/CMakeLists.txt
  src/video_core/command_classes/codecs/codec.cpp
  src/video_core/command_classes/codecs/codec.h
  src/video_core/command_classes/codecs/h264.cpp
  src/video_core/video_core.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: gpu-new, early-access-merge

#6997 main: Apply confirm exit setting in exit locked scenarios
  src/yuzu/main.cpp
Labels: general

#6974 FS: Recursively create directories for CreateDirectory
  src/core/hle/service/filesystem/filesystem.cpp
Labels: early-access-merge

#6975 account: EnsureTokenIdCacheAsync
  src/core/CMakeLists.txt
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/async_context.cpp
  src/core/hle/service/acc/async_context.h
Labels: hle-new, hle-fix, early-access-merge

#6948 shaders: Fix warp instructions on 64-thread warp devices
  src/shader_recompiler/backend/glsl/emit_glsl_warp.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_warp.cpp
Labels: gpu-fix, opengl, vulkan, early-access-merge

#7002 vk_state_tracker: Remove unused function
  src/video_core/renderer_vulkan/vk_state_tracker.h
Labels: general

#7000 FS: Mark recursive CreateDirectory as inaccurate and temporary
  src/core/hle/service/filesystem/filesystem.cpp
Labels: general

#7001 vk_rasterizer: Fix dynamic StencilOp updating when two faces are enabled
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: gpu-fix, vulkan, early-access-merge

#6944 Vulkan/Descriptors: Increase sets per pool on AMD propietary driver.
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-fix, early-access-merge

#7006 Vulkan: Blacklist Int8Float16 Extension on AMD on driver 21.9.1
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, early-access-merge

#6943 Vulkan: Disable VK_EXT_SAMPLER_FILTER_MINMAX in GCN AMD
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, early-access-merge

#7009 core: Destroy main_process during shutdown
  src/core/core.cpp
Labels: core-fix, early-access-merge

#7014 renderers: Log total pipeline count
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: general, early-access-merge

#7010 vfs: Partially implement GetFileTimeStampRaw
  src/core/file_sys/vfs.cpp
  src/core/file_sys/vfs.h
  src/core/file_sys/vfs_real.cpp
  src/core/file_sys/vfs_real.h
  src/core/file_sys/vfs_types.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: early-access-merge, filesystem-fix, service-implementation

#7027 vulkan_device: Reorder Float16Int8 declaration
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, vulkan, early-access-merge

#7011 vulkan_debug_callback: Ignore InvalidCommandBuffer-VkDescriptorSet errors
  src/video_core/vulkan_common/vulkan_debug_callback.cpp
Labels: vulkan

#7015 ngct: Stub Match
  src/core/hle/service/ngct/ngct.cpp
Labels: early-access-merge, service-stub

#6950 input_common: Add advanced setting for 8 player support
  src/common/settings.cpp
  src/common/settings.h
  src/input_common/sdl/sdl_impl.cpp
  src/input_common/udp/client.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_input_advanced.cpp
  src/yuzu/configuration/configure_input_advanced.ui
  src/yuzu/main.cpp
Labels: early-access-merge

#6485 input_common: TAS with script playback & recording
  src/common/fs/fs_paths.h
  src/common/fs/path_util.cpp
  src/common/fs/path_util.h
  src/common/settings.h
  src/input_common/CMakeLists.txt
  src/input_common/main.cpp
  src/input_common/main.h
  src/input_common/tas/tas_input.cpp
  src/input_common/tas/tas_input.h
  src/input_common/tas/tas_poller.cpp
  src/input_common/tas/tas_poller.h
  src/yuzu/CMakeLists.txt
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player_widget.cpp
  src/yuzu/configuration/configure_input_player_widget.h
  src/yuzu/configuration/configure_tas.cpp
  src/yuzu/configuration/configure_tas.h
  src/yuzu/configuration/configure_tas.ui
  src/yuzu/configuration/configure_vibration.cpp
  src/yuzu/debugger/controller.cpp
  src/yuzu/debugger/controller.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: early-access-merge

#7019 videocore: Use std::jthread for worker threads
  src/common/threadsafe_queue.h
  src/core/core.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
Labels: gpu, early-access-merge

#7017 Spir-V: Rescale the frag depth to 0,1 mode when -1,1 mode is used in Vulkan.
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
Labels: gpu-fix, vulkan, early-access-merge

#7003 vk_swapchain: Use immediate present mode when mailbox is unavailable and FPS is unlocked
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
Labels: gpu, vulkan, early-access-merge

#7069 common/uuid: Add validity checking functions to interface
  src/common/uuid.h
  src/core/frontend/applets/profile_select.cpp
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/am/applets/applet_profile_select.cpp
Labels: general

#7084 general: Update style to clang-format-12
  .ci/scripts/format/script.sh
  CMakeLists.txt
  src/common/alignment.h
  src/common/div_ceil.h
  src/common/intrusive_red_black_tree.h
  src/common/vector_math.h
  src/core/hle/kernel/k_priority_queue.h
  src/core/hle/kernel/k_scheduler.h
  src/core/hle/kernel/k_scoped_lock.h
  src/core/hle/kernel/k_scoped_scheduler_lock_and_sleep.h
  src/input_common/main.cpp
  src/shader_recompiler/object_pool.h
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/texture_cache/slot_vector.h
Labels: general

#7082 service: bsd: Implement Read
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/sockets/bsd.h
Labels: hle-fix, do-not-merge, service-implementation

#7085 service: bsd: Stub Read
  src/core/hle/service/sockets/bsd.cpp
Labels: hle-fix, service-stub

#7078 video_core: Fix jthread related hangs when stopping emulation
  src/core/core.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
Labels: gpu-fix, early-access-merge

#7076 vk_texture_cache: Disable cube compatibility flag on non-mesa AMD GCN4 and earlier
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu, vulkan, early-access-merge

#7018 audin_u: stub Start, RegisterBufferEvent, AppendAudioInBufferAuto
  src/core/hle/service/audio/audin_u.cpp
  src/core/hle/service/audio/audin_u.h
Labels: early-access-merge, service-stub

#7036 gl_texture_cache: Unify BGR copy passes using PBOs
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/opengl_copy_bgra.comp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_opengl/util_shaders.cpp
  src/video_core/renderer_opengl/util_shaders.h
Labels: gpu-fix, opengl, early-access-merge

#7104 style: Remove extra space preceding the :: operator
  src/core/file_sys/program_metadata.cpp
  src/core/hle/kernel/k_handle_table.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/time/system_clock_core.cpp
  src/core/hle/service/time/time_zone_service.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_context_get_set.cpp
  src/yuzu/configuration/configure_profile_manager.cpp
Labels: style, general

#7061 buffer_cache, maxwell_dma: Minor refactoring and code fixes
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
Labels: early-access-merge

#7075 applets: Use subdirectory of main data directory for QtWebEngine storage
  src/yuzu/applets/qt_web_browser.cpp
Labels: early-access-merge
