Repository yuzu-emu/yuzu, pull requests merged in 2021-11, with the labels that each got.

#7227 Fix memory leak v2
  src/core/core.cpp
  src/core/hle/kernel/k_handle_table.cpp
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc.cpp
Labels: early-access-merge

#7268 common, result: Implement a subset of std::expected and use it in ResultVal
  src/common/CMakeLists.txt
  src/common/expected.h
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/sdmc_factory.cpp
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/result.h
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/glue/glue_manager.cpp
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/mii/mii_manager.cpp
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/spl/spl_module.cpp
  src/core/hle/service/vi/vi.cpp
Labels: general

#7265 gl_rasterizer: Remove unused includes
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: general

#7262 ShaderCache: Order Phi Arguments from farthest away to nearest.
  src/shader_recompiler/backend/glasm/emit_glasm_not_implemented.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_special.cpp
  src/shader_recompiler/frontend/ir/basic_block.h
  src/shader_recompiler/frontend/ir/microinstruction.cpp
  src/shader_recompiler/frontend/ir/value.h
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/ir_opt/ssa_rewrite_pass.cpp
Labels: gpu-fix, early-access-merge

#7283 service: acc: Stub acc:u0 '160'
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/acc_u0.cpp
Labels: early-access-merge, service-stub

#7287 service: aoc: Stub more 13.x functions used by Animal Crossing
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/aoc/aoc_u.h
Labels: early-access-merge

#7289 core: Reorder perf_stats destruction order on Shutdown
  src/core/core.cpp
Labels: bug

#7279 general: Get the current process program id directly from the system
  src/core/core.cpp
  src/core/core.h
  src/core/file_sys/savedata_factory.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applet_error.cpp
  src/core/hle/service/am/applets/applet_general_backend.cpp
  src/core/hle/service/am/applets/applet_web_browser.cpp
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/bcat/bcat_module.cpp
  src/core/hle/service/fatal/fatal.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/glue/arp.cpp
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/pctl/pctl_module.cpp
  src/core/hle/service/pm/pm.cpp
  src/core/hle/service/prepo/prepo.cpp
  src/core/memory/cheat_engine.cpp
  src/core/reporter.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: general

#7303 applets/swkbd: Skip text checking if the text has been confirmed
  src/core/frontend/applets/software_keyboard.cpp
  src/core/frontend/applets/software_keyboard.h
  src/core/hle/service/am/applets/applet_software_keyboard.cpp
  src/core/hle/service/am/applets/applet_software_keyboard.h
  src/yuzu/applets/qt_software_keyboard.cpp
  src/yuzu/applets/qt_software_keyboard.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: hle-fix, early-access-merge

#7272 Logging: Impl refactor
  src/common/logging/backend.cpp
  src/common/logging/backend.h
  src/common/logging/log_entry.h
  src/yuzu/main.cpp
Labels: early-access-merge

#7305 ci: Print traceback on patch merge failure
  .ci/scripts/merge/apply-patches-by-label.py
Labels: early-access-merge

#7260 shader: Spirv support legacy attribute v2
  src/shader_recompiler/backend/spirv/emit_context.cpp
  src/shader_recompiler/backend/spirv/emit_context.h
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
Labels: gpu-new, early-access-merge

#7326 codecs: Implement VP8 video decoding support
  CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/video_core/command_classes/codecs/codec.cpp
  src/video_core/command_classes/codecs/codec.h
  src/video_core/command_classes/codecs/h264.cpp
  src/video_core/command_classes/codecs/h264.h
  src/video_core/command_classes/codecs/vp8.cpp
  src/video_core/command_classes/codecs/vp8.h
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/command_classes/codecs/vp9.h
  src/video_core/command_classes/nvdec.cpp
  src/video_core/command_classes/nvdec_common.h
Labels: gpu-new, early-access-merge

#7349 gl_texture_cache: Implement pixel format conversions for copies
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
Labels: gpu-fix, opengl, early-access-merge

#7357 video_core: Implement S8_UINT format
  src/video_core/gpu.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/formatter.h
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, opengl, vulkan, early-access-merge

#7294 Fix image update/download error when width too small
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
Labels: gpu-fix

#7368 Fix ART Blit detection regression and add D24S8 <-> RGBA8 conv to Vulkan
  src/common/bit_util.h
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/convert_abgr8_to_d24s8.frag
  src/video_core/host_shaders/convert_b10g11r11_to_d24s8.frag
  src/video_core/host_shaders/convert_d24s8_to_abgr8.frag
  src/video_core/host_shaders/convert_d24s8_to_b10g11r11.frag
  src/video_core/host_shaders/convert_d24s8_to_r16g16.frag
  src/video_core/host_shaders/convert_r16g16_to_d24s8.frag
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/blit_image.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
  src/video_core/texture_cache/types.h
  src/video_core/texture_cache/util.cpp
Labels: gpu-new, gpu-fix, mainline-merge

#7359 Fix crash on exit due to static scoped dummy threads
  src/core/hle/kernel/kernel.cpp
Labels: early-access-merge

#7389 Fix screenshot dimensions when at 1x scale
  src/core/frontend/framebuffer_layout.cpp
  src/core/frontend/framebuffer_layout.h
  src/video_core/video_core.cpp
  src/video_core/video_core.h
  src/yuzu/bootmanager.cpp
Labels: gpu-fix

#7440 CMakeLists: Update fmt to 8.0.1
  CMakeLists.txt
Labels: externals

#7396 TextureCache: Eliminate format deduction as full depth conversion has been supported.
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/convert_abgr8_to_d24s8.frag
  src/video_core/host_shaders/convert_b10g11r11_to_d24s8.frag
  src/video_core/host_shaders/convert_d24s8_to_abgr8.frag
  src/video_core/host_shaders/convert_d24s8_to_b10g11r11.frag
  src/video_core/host_shaders/convert_d24s8_to_r16g16.frag
  src/video_core/host_shaders/convert_r16g16_to_d24s8.frag
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/blit_image.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
  src/video_core/texture_cache/util.cpp
Labels: gpu-fix, mainline-merge
