Repository yuzu-emu/yuzu, pull requests merged in 2022-07, with the labels that each got.

#8523 cpu_manager: properly check idle on return from preemption
  src/core/cpu_manager.cpp
  src/core/hle/kernel/k_scheduler.h
Labels: core-fix, mainline-merge

#8477 tweak API usage in qt_web_browser.cpp
  src/yuzu/applets/qt_web_browser.cpp
Labels: early-access-merge

#8532 common/fiber: make fibers easier to use
  src/common/fiber.cpp
  src/common/fiber.h
  src/core/cpu_manager.cpp
  src/core/cpu_manager.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_scheduler.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/tests/common/fibers.cpp
Labels: core-new, early-access-merge

#8486 CI: Use GitHub Actions to validate pull requests
  .ci/scripts/clang/docker.sh
  .ci/scripts/clang/exec.sh
  .ci/scripts/clang/upload.sh
  .ci/scripts/common/post-upload.sh
  .ci/scripts/format/exec.sh
  .ci/scripts/linux/docker.sh
  .ci/scripts/linux/exec.sh
  .ci/scripts/linux/upload.sh
  .ci/scripts/windows/docker.sh
  .ci/scripts/windows/exec.sh
  .ci/scripts/windows/upload.sh
  .github/workflows/verify.yml
  CMakeLists.txt
  CMakeModules/CopyYuzuFFmpegDeps.cmake
  CMakeModules/MSVCCache.cmake
  src/CMakeLists.txt
Labels: build-system-new, early-access-merge

#8522 settings: Consolidate RangedSetting's with regular ones
  src/common/settings.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configuration_shared.cpp
  src/yuzu/configuration/configuration_shared.h
  src/yuzu/uisettings.h
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/config.h
Labels: general, early-access-merge

#8492 service: hid: Correct some mistakes and add more validations
  src/core/hid/hid_types.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/errors.h
  src/core/hle/service/hid/hid.cpp
Labels: early-access-merge

#8502 kernel: clean up waiting implementation
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_thread.cpp
Labels: kernel-fix, early-access-merge

#8501 core/arm: better support for backtrace generation
  src/core/arm/arm_interface.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.h
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.h
Labels: core-fix

#8531 Core timing: use only one thread.
  src/core/core_timing.cpp
  src/core/core_timing.h
Labels: mainline-merge

#8528 renderer_(gl/vk): Implement ASTC_10x6_UNORM
  src/video_core/compatible_formats.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/format_lookup_table.cpp
  src/video_core/texture_cache/formatter.h
Labels: opengl, vulkan, early-access-merge

#8559 kernel: fix usage of waiter_list in Finalize
  src/core/hle/kernel/k_thread.cpp
Labels: kernel-fix, early-access-merge

#8510 input_common: sdl: lower vibration frequency and use it's own unique thread
  src/core/hle/service/hid/controllers/npad.cpp
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/drivers/sdl_driver.h
Labels: early-access-merge

#8536 qt_web_browser: Fix button inputs with QtWebEngine
  src/yuzu/applets/qt_web_browser.cpp
Labels: frontend-fix, early-access-merge

#8560 common: fix bitfield aliasing on GCC/Clang
  src/common/bit_field.h
Labels: input

#8511 service: ptm: Add TS, nifm: Stub GetInternetConnectionStatus
  src/common/logging/filter.cpp
  src/common/logging/types.h
  src/core/CMakeLists.txt
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/ptm/psm.cpp
  src/core/hle/service/ptm/psm.h
  src/core/hle/service/ptm/ptm.cpp
  src/core/hle/service/ptm/ptm.h
  src/core/hle/service/ptm/ts.cpp
  src/core/hle/service/ptm/ts.h
  src/core/hle/service/service.cpp
Labels: early-access-merge

#8594 core/arm: skip watchpoint checks when reading instructions
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
Labels: core-fix

#8543 common/x64: Use TSC clock rate from CPUID when available
  src/common/wall_clock.cpp
  src/common/x64/cpu_detect.cpp
  src/common/x64/cpu_detect.h
Labels: early-access-merge

#8544 service: Update some services to 14.0.0+
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/bcat/bcat_module.cpp
  src/core/hle/service/btdrv/btdrv.cpp
  src/core/hle/service/btm/btm.cpp
  src/core/hle/service/fatal/fatal_p.cpp
Labels: early-access-merge

#8508 hle: service: nvflinger: Factor speed limit into frame time calculation.
  src/common/settings.cpp
  src/common/settings.h
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.ui
  src/yuzu/main.cpp
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge

#8598 Enable the use of MSG_DONTWAIT flag on RecvImpl
  src/core/hle/service/sockets/bsd.cpp
Labels: early-access-merge

#8611 video_core: use correct byte size for framebuffer
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
Labels: gpu-fix, mainline-merge

#8627 ci/windows: Cleanup unused data in submodules before packaging
  .ci/scripts/windows/upload.ps1
Labels: build-system-fix

#8484 service: irs: Add camera support, split processors and implement ImageTransferProcessor
  CMakeLists.txt
  CMakeModules/CopyYuzuQt5Deps.cmake
  src/common/input.h
  src/common/settings.h
  src/core/CMakeLists.txt
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hid/input_converter.cpp
  src/core/hid/input_converter.h
  src/core/hid/irs_types.h
  src/core/hle/service/hid/errors.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/irs.cpp
  src/core/hle/service/hid/irs.h
  src/core/hle/service/hid/irsensor/clustering_processor.cpp
  src/core/hle/service/hid/irsensor/clustering_processor.h
  src/core/hle/service/hid/irsensor/image_transfer_processor.cpp
  src/core/hle/service/hid/irsensor/image_transfer_processor.h
  src/core/hle/service/hid/irsensor/ir_led_processor.cpp
  src/core/hle/service/hid/irsensor/ir_led_processor.h
  src/core/hle/service/hid/irsensor/moment_processor.cpp
  src/core/hle/service/hid/irsensor/moment_processor.h
  src/core/hle/service/hid/irsensor/pointing_processor.cpp
  src/core/hle/service/hid/irsensor/pointing_processor.h
  src/core/hle/service/hid/irsensor/processor_base.cpp
  src/core/hle/service/hid/irsensor/processor_base.h
  src/core/hle/service/hid/irsensor/tera_plugin_processor.cpp
  src/core/hle/service/hid/irsensor/tera_plugin_processor.h
  src/input_common/CMakeLists.txt
  src/input_common/drivers/camera.cpp
  src/input_common/drivers/camera.h
  src/input_common/input_engine.cpp
  src/input_common/input_engine.h
  src/input_common/input_poller.cpp
  src/input_common/input_poller.h
  src/input_common/main.cpp
  src/input_common/main.h
  src/yuzu/CMakeLists.txt
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_camera.cpp
  src/yuzu/configuration/configure_camera.h
  src/yuzu/configuration/configure_camera.ui
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input_advanced.cpp
  src/yuzu/configuration/configure_input_advanced.h
  src/yuzu/configuration/configure_input_advanced.ui
  src/yuzu/main.cpp
Labels: hle-new

#8564 yuzu: Streamline broken Vulkan handling
  src/yuzu/CMakeLists.txt
  src/yuzu/check_vulkan.cpp
  src/yuzu/check_vulkan.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/startup_checks.cpp
  src/yuzu/startup_checks.h
  src/yuzu/uisettings.h
Labels: mainline-merge

#8592 exit gracefully on sigint/sigterm
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: mainline-merge

#8633 applet/swkbd: Implement optional symbol keys
  src/core/frontend/applets/software_keyboard.h
  src/core/hle/service/am/applets/applet_software_keyboard.cpp
  src/yuzu/applets/qt_software_keyboard.cpp
  src/yuzu/applets/qt_software_keyboard.h
  src/yuzu/applets/qt_software_keyboard.ui
Labels: hle-fix, early-access-merge

#8636 service: irs: Implement clustering processor
  src/core/CMakeLists.txt
  src/core/hle/service/hid/irs.cpp
  src/core/hle/service/hid/irs_ring_lifo.h
  src/core/hle/service/hid/irsensor/clustering_processor.cpp
  src/core/hle/service/hid/irsensor/clustering_processor.h
  src/yuzu/bootmanager.cpp
Labels: early-access-merge

#8542 gpu_thread: Use the previous MPSCQueue implementation
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
Labels: mainline-merge

#8585 implement pause on system suspend
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: mainline-merge

#8591 Revert Coretiming PRs 8531 and 7454
  src/common/uint128.h
  src/common/x64/native_clock.cpp
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/tests/core/core_timing.cpp
Labels: mainline-merge

#8642 ci/linux: Exclude libwayland-client from AppImage
  .ci/scripts/linux/docker.sh
Labels: mainline-merge

#8657 [Audio] Avoid an out-of-bounds span write in depop prepare
  src/audio_core/renderer/command/command_buffer.cpp
  src/audio_core/renderer/command/mix/depop_prepare.cpp
Labels: mainline-merge

#8349 Revert "ci: Enable building with Visual Studio 2022"
  .ci/templates/build-msvc.yml
  .ci/yuzu-mainline-step2.yml
  .ci/yuzu-patreon-step2.yml
Labels: mainline-merge

#8656 yuzu: Add incremental steps to volume hotkeys
  src/yuzu/main.cpp
Labels: early-access-merge

#8677 audio_core: fix -Wuninitialized when compiling with ASan
  src/audio_core/renderer/effect/effect_info_base.h
Labels: build-system-fix

#8664 common: move forwarded value into SPSCQueue
  src/common/threadsafe_queue.h
Labels: build-system-fix

#8640 cmake,ci: vcpkg leftovers
  .ci/templates/build-msvc.yml
  .github/workflows/verify.yml
  CMakeLists.txt
  vcpkg.json
Labels: early-access-merge

#8684 renderer_opengl: delete shader source after linking
  src/video_core/renderer_opengl/gl_shader_util.cpp
Labels: gpu-fix, early-access-merge

#8692 Properly write out the command buffer when serving close request
  src/core/hle/service/service.cpp
Labels: kernel-fix

#8622 qt: reset progress bar after shader compilation
  src/yuzu/loading_screen.cpp
Labels: early-access-merge

#8678 video_core: stop waiting for shader compilation on user cancel
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: early-access-merge
