Repository yuzu-emu/yuzu, pull requests merged in 2022-11, with the labels that each got.

#9143 vk_scheduler: Remove recorded_counts
  src/video_core/renderer_vulkan/vk_scheduler.h
Labels: gpu-fix, early-access-merge

#9157 core: hle: service: acc: Fix ListOpenContextStoredUsers/StoreOpenContext.
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc.h
  src/core/hle/service/acc/acc_u0.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
Labels: hle-new, hle-fix, mainline-merge

#9097 video_core: don't build ASTC decoder shader unless requested
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
Labels: mainline-merge, intel

#9154 vk_blit_screen: recreate swapchain images on guest format change
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
Labels: gpu-fix, vulkan, early-access-merge

#9135 kernel: invert session request handling flow
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/k_client_port.cpp
  src/core/hle/kernel/k_client_port.h
  src/core/hle/kernel/k_port.cpp
  src/core/hle/kernel/k_server_port.cpp
  src/core/hle/kernel/k_server_port.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_server_session.h
  src/core/hle/kernel/k_session.cpp
  src/core/hle/kernel/k_session.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/service_thread.cpp
  src/core/hle/kernel/service_thread.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
  src/core/hle/service/sm/sm_controller.cpp
Labels: hle-fix, kernel-fix, mainline-merge

#9189 video_core: Fix scaling graphical regressions for multiple games
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: early-access-merge

#9173 Kernel: Various updates for FW 15.0.x
  src/core/CMakeLists.txt
  src/core/hle/kernel/board/nintendo/nx/k_system_control.h
  src/core/hle/kernel/init/init_slab_setup.cpp
  src/core/hle/kernel/init/init_slab_setup.h
  src/core/hle/kernel/k_class_token.cpp
  src/core/hle/kernel/k_class_token.h
  src/core/hle/kernel/k_debug.h
  src/core/hle/kernel/k_dynamic_page_manager.h
  src/core/hle/kernel/k_dynamic_resource_manager.h
  src/core/hle/kernel/k_event_info.h
  src/core/hle/kernel/k_handle_table.cpp
  src/core/hle/kernel/k_handle_table.h
  src/core/hle/kernel/k_memory_block.h
  src/core/hle/kernel/k_memory_layout.cpp
  src/core/hle/kernel/k_memory_layout.h
  src/core/hle/kernel/k_memory_manager.cpp
  src/core/hle/kernel/k_memory_manager.h
  src/core/hle/kernel/k_memory_region_type.h
  src/core/hle/kernel/k_page_bitmap.h
  src/core/hle/kernel/k_page_buffer.h
  src/core/hle/kernel/k_page_group.h
  src/core/hle/kernel/k_page_heap.cpp
  src/core/hle/kernel/k_page_heap.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/k_page_table_manager.h
  src/core/hle/kernel/k_page_table_slab_heap.h
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_system_resource.cpp
  src/core/hle/kernel/k_system_resource.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/slab_helpers.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_results.h
  src/core/hle/kernel/svc_types.h
  src/core/hle/result.h
  src/core/hle/service/nvdrv/devices/nvmap.cpp
Labels: kernel-new, early-access-merge

#9163 video_core: Fix drawing trigger mechanism regression
  src/video_core/engines/maxwell_3d.cpp
Labels: early-access-merge

#9199 service_thread: fix deletion
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
Labels: kernel-fix, early-access-merge

#9215 Ensure correctness of atomic store ordering
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_scheduler_lock.h
Labels: kernel-fix

#9182 kernel: assign KProcess to service threads
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/service_thread.cpp
Labels: kernel-fix, early-access-merge

#9183 kernel/svc_types: refresh
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/init/init_slab_setup.cpp
  src/core/hle/kernel/k_client_port.cpp
  src/core/hle/kernel/k_event.cpp
  src/core/hle/kernel/k_memory_block.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_resource_limit.cpp
  src/core/hle/kernel/k_resource_limit.h
  src/core/hle/kernel/k_session.cpp
  src/core/hle/kernel/k_shared_memory.cpp
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_transfer_memory.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/service_thread.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_types.h
  src/core/hle/service/kernel_helpers.cpp
  src/core/hle/service/sm/sm_controller.cpp
Labels: kernel-new, early-access-merge

#9192 yuzu: Change QtKeyToSwitchKey switch case to array
  src/yuzu/bootmanager.cpp
Labels: early-access-merge

#9176 ir/texture_pass: Use host_info instead of querying Settings::values
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/host_translate_info.h
  src/shader_recompiler/ir_opt/passes.h
  src/shader_recompiler/ir_opt/texture_pass.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_state_tracker.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_state_tracker.cpp
  src/video_core/shader_environment.cpp
Labels: general, early-access-merge

#9167 video_core: Fix few issues in Tess stage
  src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp
  src/shader_recompiler/backend/glasm/emit_glasm_instructions.h
  src/shader_recompiler/backend/glasm/glasm_emit_context.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_context_get_set.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_instructions.h
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.h
  src/shader_recompiler/frontend/ir/ir_emitter.cpp
  src/shader_recompiler/frontend/ir/ir_emitter.h
  src/shader_recompiler/frontend/ir/opcodes.inc
  src/shader_recompiler/frontend/ir/patch.h
  src/shader_recompiler/frontend/maxwell/translate/impl/move_special_register.cpp
  src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
  src/shader_recompiler/shader_info.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: early-access-merge

#9133 yuzu/compatdb: Improve compatibility submission system
  src/yuzu/compatdb.cpp
  src/yuzu/compatdb.h
  src/yuzu/compatdb.ui
  src/yuzu/game_list_p.h
  src/yuzu/main.cpp
Labels: early-access-merge

#9204 video_core: Fix dma copy 1D random crash
  src/video_core/engines/maxwell_dma.cpp
Labels: gpu-fix, early-access-merge

#9224 service_thread: remove explicit KProcess
  src/core/hle/kernel/k_event.cpp
  src/core/hle/kernel/service_thread.cpp
Labels: kernel-fix, early-access-merge

#9226 [video_core] Fix a couple regs regressions
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: bug, early-access-merge

#9234 kernel: implement data cache management operations
  src/common/CMakeLists.txt
  src/common/cache_management.cpp
  src/common/cache_management.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
  src/core/memory.cpp
  src/core/memory.h
Labels: kernel-new, early-access-merge

#9253 shader: Implement miss attribute layer
  src/shader_recompiler/backend/glasm/emit_glasm.cpp
  src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_context_get_set.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
Labels: gpu-fix, mainline-merge

#9252 maxwell3d: HLE multi-layer clear macro
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/macro/macro_hle.cpp
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: gpu-fix, mainline-merge

#9260 spirv_emit_context: add missing flat decoration
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
Labels: gpu-fix, mainline-merge

#9191 core: hid: Implement true multitouch support
  src/core/hid/emulated_console.cpp
  src/core/hid/emulated_console.h
  src/core/hid/input_converter.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
  src/input_common/helpers/touch_from_buttons.cpp
  src/input_common/input_poller.cpp
Labels: early-access-merge

#9254 Dynarmic: Remove inaccurate NaN from Auto CPU settings.
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
Labels: cpu-fix, mainline-merge

#9238 service: am: Implement cabinet applet
  src/core/CMakeLists.txt
  src/core/frontend/applets/cabinet.cpp
  src/core/frontend/applets/cabinet.h
  src/core/hle/service/am/applets/applet_cabinet.cpp
  src/core/hle/service/am/applets/applet_cabinet.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nfp/nfp_device.h
  src/core/hle/service/nfp/nfp_types.h
  src/core/hle/service/nfp/nfp_user.cpp
  src/input_common/drivers/virtual_amiibo.cpp
  src/input_common/drivers/virtual_amiibo.h
  src/input_common/input_engine.h
  src/yuzu/CMakeLists.txt
  src/yuzu/applets/qt_amiibo_settings.cpp
  src/yuzu/applets/qt_amiibo_settings.h
  src/yuzu/applets/qt_amiibo_settings.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#9216 video_core: Reimplement inline index buffer binding
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: gpu-fix, mainline-merge

#9279 dmnt:cht: fix copy-paste error
  src/core/memory/dmnt_cheat_vm.cpp
Labels: early-access-merge

#9219 service: nfc: Implement NFC IUser service
  src/core/CMakeLists.txt
  src/core/hle/service/nfc/nfc.cpp
  src/core/hle/service/nfc/nfc_device.cpp
  src/core/hle/service/nfc/nfc_device.h
  src/core/hle/service/nfc/nfc_result.h
  src/core/hle/service/nfc/nfc_user.cpp
  src/core/hle/service/nfc/nfc_user.h
  src/core/hle/service/nfp/amiibo_crypto.cpp
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nfp/nfp_device.h
  src/core/hle/service/nfp/nfp_user.cpp
  src/core/hle/service/nfp/nfp_user.h
Labels: early-access-merge

#9312 GPU: Fix buffer cache issue, engine upload not inlining memory in multiple lines, etc
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/engine_upload.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/puller.cpp
Labels: gpu-fix, mainline-merge

#9194 YFC - Fermi2D: Rework blit engine and add a software blitter.
  src/video_core/CMakeLists.txt
  src/video_core/control/channel_state.cpp
  src/video_core/engines/fermi_2d.cpp
  src/video_core/engines/fermi_2d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/engines/sw_blitter/blitter.cpp
  src/video_core/engines/sw_blitter/blitter.h
  src/video_core/engines/sw_blitter/converter.cpp
  src/video_core/engines/sw_blitter/converter.h
  src/video_core/engines/sw_blitter/generate_converters.py
  src/video_core/gpu.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/formatter.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
Labels: gpu-new, gpu-fix, early-access-merge

#9302 externals: always use LibreSSL on Windows
  externals/CMakeLists.txt
Labels: mainline-merge

#9297 [audio_core] Fix an OoB with sample sinking
  src/audio_core/renderer/command/command_buffer.cpp
Labels: audio-fix, early-access-merge

#9307 maxwell_to_vk: Fix format usage bits and add R16_SINT
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: vulkan, early-access-merge

#9288 video_core: Fine tune maxwell drawing trigger mechanism
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
Labels: gpu-fix, early-access-merge

#9276 FSR Sharpening Slider
  src/common/settings.cpp
  src/common/settings.h
  src/video_core/renderer_vulkan/vk_fsr.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu_cmd/config.cpp
Labels: gpu, early-access-merge

#9317 yuzu-cmd: Fix input callback crash on close
  src/core/hid/emulated_devices.cpp
  src/input_common/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: early-access-merge

#8829 CMake: rework for Qt6 support
  CMakeLists.txt
  CMakeModules/CopyYuzuQt5Deps.cmake
  src/yuzu/CMakeLists.txt
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/configure_camera.cpp
  src/yuzu/configuration/configure_camera.h
  src/yuzu/configuration/configure_input_advanced.cpp
  src/yuzu/main.cpp
  src/yuzu/multiplayer/direct_connect.cpp
  src/yuzu/multiplayer/validation.h
Labels: mainline-merge

#9322 input_common: Pump SDL events from main thread
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/drivers/sdl_driver.h
  src/input_common/main.cpp
  src/input_common/main.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: mainline-merge

#9308 startup_checks: Use Windows flow for *nix
  src/yuzu/startup_checks.cpp
  src/yuzu/startup_checks.h
Labels: mainline-merge

#9349 CMakeLists: Bump minimum required CMake version to 3.22
  CMakeLists.txt
  externals/CMakeLists.txt
  src/audio_core/CMakeLists.txt
  src/input_common/CMakeLists.txt
  src/yuzu/CMakeLists.txt
Labels: build-system-new

#9320 AudioCore: Take suspend lock when stalling the running process.
  src/audio_core/sink/sink_stream.cpp
  src/audio_core/sink/sink_stream.h
  src/core/core.cpp
Labels: audio-fix, early-access-merge
