Repository yuzu-emu/yuzu, pull requests merged in 2022-12, with the labels that each got.

#9348 service: nifm: Update stubs for Submit/GetRequestState/GetResult
  src/core/hle/service/nifm/nifm.cpp
Labels: early-access-merge, service-stub

#9363 shader_recompiler: add gl_Layer translation GS for older hardware
  src/shader_recompiler/CMakeLists.txt
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/frontend/maxwell/translate_program.h
  src/shader_recompiler/host_translate_info.h
  src/shader_recompiler/ir_opt/layer_pass.cpp
  src/shader_recompiler/ir_opt/passes.h
  src/shader_recompiler/shader_info.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: gpu-fix, early-access-merge

#9353 video_core: Fine tuning the index drawing judgment logic
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
Labels: early-access-merge

#9273 Configuration: Add per-game input profiles
  src/common/settings_input.h
  src/core/hid/emulated_controller.cpp
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_input_per_game.cpp
  src/yuzu/configuration/configure_input_per_game.h
  src/yuzu/configuration/configure_input_per_game.ui
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_per_game.h
  src/yuzu/main.cpp
Labels: early-access-merge

#9232 hle: service: audio: Use default service thread.
  src/core/hle/service/audio/audin_u.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
Labels: hle-fix, mainline-merge

#9381 service_thread: fix uninitialized memory usage
  src/core/hle/kernel/service_thread.cpp
Labels: kernel-fix, early-access-merge

#9383 Vulkan: Implement Alpha coverage
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: gpu-new, early-access-merge

#9388 CMakeLists: Remove version specifier for lz4
  CMakeLists.txt
Labels: build-system-fix

#9360 Respect render mode override
  src/video_core/engines/maxwell_3d.cpp
Labels: early-access-merge

#9369 service: nfc: Implement mifare service
  src/core/CMakeLists.txt
  src/core/hle/service/nfc/mifare_user.cpp
  src/core/hle/service/nfc/mifare_user.h
  src/core/hle/service/nfc/nfc.cpp
  src/core/hle/service/nfc/nfc_device.cpp
  src/core/hle/service/nfc/nfc_device.h
  src/core/hle/service/nfc/nfc_result.h
  src/core/hle/service/nfc/nfc_user.cpp
  src/core/hle/service/nfp/nfp_types.h
  src/input_common/drivers/virtual_amiibo.cpp
  src/input_common/drivers/virtual_amiibo.h
Labels: early-access-merge

#9386 kernel: Ensure relevant class members are always initialized on construction
  src/core/hle/kernel/k_memory_block.h
  src/core/hle/kernel/k_memory_block_manager.h
  src/core/hle/kernel/k_shared_memory.h
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/physical_core.h
Labels: early-access-merge

#9389 emulated_console/emulated_controller: std::move ParamPackage instances where applicable
  src/core/hid/emulated_console.cpp
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge

#9392 reporter: Eliminate undefined behavior in SaveErrorReport
  src/core/reporter.cpp
  src/core/reporter.h
Labels: early-access-merge

#9370 core: add option to break on unmapped access
  src/common/settings.h
  src/core/arm/arm_interface.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_cpu_debug.cpp
  src/yuzu/configuration/configure_cpu_debug.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge

#9365 vulkan_common: quiet some validation errors
  src/video_core/vulkan_common/vulkan_debug_callback.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: early-access-merge

#9401 video_core: Implement maxwell3d draw manager and split draw logic
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/draw_manager.cpp
  src/video_core/engines/draw_manager.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/macro/macro_hle.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: gpu-fix, early-access-merge

#9409 video_core: Integrate SMAA
  src/common/settings.h
  src/video_core/CMakeLists.txt
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/StringShaderHeader.cmake
  src/video_core/host_shaders/opengl_smaa.glsl
  src/video_core/host_shaders/smaa_blending_weight_calculation.frag
  src/video_core/host_shaders/smaa_blending_weight_calculation.vert
  src/video_core/host_shaders/smaa_edge_detection.frag
  src/video_core/host_shaders/smaa_edge_detection.vert
  src/video_core/host_shaders/smaa_neighborhood_blending.frag
  src/video_core/host_shaders/smaa_neighborhood_blending.vert
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_smaa.cpp
  src/video_core/renderer_vulkan/vk_smaa.h
  src/video_core/smaa_area_tex.h
  src/video_core/smaa_search_tex.h
  src/video_core/vulkan_common/vulkan_wrapper.cpp
  src/video_core/vulkan_common/vulkan_wrapper.h
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu/main.cpp
Labels: early-access-merge

#9415 memory: correct semantics of data cache management operations
  src/common/CMakeLists.txt
  src/common/cache_management.cpp
  src/common/cache_management.h
  src/core/memory.cpp
Labels: core-fix

#9420 video_core: fix off by one in anisotropic filtering amount
  src/video_core/textures/texture.cpp
Labels: early-access-merge

#9404 input_common: Filter SDL GUID
  src/input_common/drivers/sdl_driver.cpp
Labels: input

#9406 video_core: Adjust topology update logic and Adjust Clear Manage
  src/video_core/engines/draw_manager.cpp
  src/video_core/engines/draw_manager.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge

#9398 general: improve handling of system startup failure
  src/common/thread.h
  src/core/core.cpp
  src/core/cpu_manager.cpp
  src/core/cpu_manager.h
  src/core/hle/kernel/kernel.cpp
Labels: mainline-merge

#6688 render_vulkan: Fix validation errors on less compatible Intel GPUs
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: early-access-merge

#7410 Wayland fixes
  src/core/frontend/emu_window.h
  src/video_core/gpu.cpp
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
  src/yuzu/bootmanager.cpp
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2_gl.cpp
Labels: mainline-merge

#9430 spirv_emit_context: declare GroupNonUniform capability for SubgroupLocalInvocationId
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
Labels: early-access-merge

#9431 vulkan_common: declare storageBuffer8BitAccess
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: early-access-merge

#8605 let games gracefully exit
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/main.cpp
Labels: early-access-merge

#9455 [audio_core] Signal buffer event on audio in/out system stop
  src/audio_core/device/audio_buffers.h
  src/audio_core/device/device_session.cpp
  src/audio_core/device/device_session.h
  src/audio_core/in/audio_in_system.cpp
  src/audio_core/out/audio_out_system.cpp
Labels: early-access-merge

#9452 hle_ipc: Refactor ReadBuffer to set buffer size upon initialization
  src/core/hle/kernel/hle_ipc.cpp
Labels: early-access-merge

#9454 qt: handle wayland-egl platform name
  src/yuzu/bootmanager.cpp
  src/yuzu/main.cpp
Labels: mainline-merge

#9461 qt: avoid setting WA_DontCreateNativeAncestors on all platforms
  src/yuzu/bootmanager.cpp
Labels: mainline-merge

#7450 Vulkan: Add support for VK_EXT_depth_clip_control.
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_special.cpp
  src/shader_recompiler/profile.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-new, mainline-merge

#9456 input_common: Add virtual gamepad
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/input_common/CMakeLists.txt
  src/input_common/drivers/virtual_gamepad.cpp
  src/input_common/drivers/virtual_gamepad.h
  src/input_common/main.cpp
  src/input_common/main.h
Labels: early-access-merge

#9442 Enable compiler optimizations and enforce x86-64-v2 on GCC/Clang
  .ci/scripts/clang/docker.sh
  .ci/scripts/linux/docker.sh
  .ci/templates/build-msvc.yml
  src/common/assert.h
Labels: early-access-merge

#9474 kernel: add KHardwareTimer
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_address_arbiter.cpp
  src/core/hle/kernel/k_hardware_timer.cpp
  src/core/hle/kernel/k_hardware_timer.h
  src/core/hle/kernel/k_hardware_timer_base.h
  src/core/hle/kernel/k_scoped_scheduler_lock_and_sleep.h
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/k_thread_queue.cpp
  src/core/hle/kernel/k_timer_task.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/time_manager.cpp
  src/core/hle/kernel/time_manager.h
Labels: early-access-merge

#9482 CMakeLists: bump required Vulkan package version to 1.3.238
  CMakeLists.txt
Labels: mainline-merge

#9463 EmuThread: refactor
  src/core/core.cpp
  src/core/core.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#9486 qt: exit properly on guest-initiated close
  src/yuzu/bootmanager.cpp
  src/yuzu/main.cpp
Labels: mainline-merge

#9476 qt: continue event loop during game close
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/util/overlay_dialog.cpp
  src/yuzu/util/overlay_dialog.h
Labels: mainline-merge

#9497 qt: fix 'Pause' menu item
  src/yuzu/bootmanager.h
Labels: mainline-merge

#9453 common: Add ScratchBuffer Class
  src/common/CMakeLists.txt
  src/common/make_unique_for_overwrite.h
  src/common/scratch_buffer.h
  src/tests/CMakeLists.txt
  src/tests/common/scratch_buffer.cpp
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
  src/video_core/engines/engine_upload.cpp
  src/video_core/engines/engine_upload.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/host1x/vic.cpp
  src/video_core/host1x/vic.h
Labels: early-access-merge

#9487 time: add LockFreeAtomicType
  src/core/hle/service/time/clock_types.h
  src/core/hle/service/time/time_sharedmemory.cpp
  src/core/hle/service/time/time_sharedmemory.h
Labels: mainline-merge

#9496 kernel: workaround static shared memory initialization
  src/core/hle/kernel/k_shared_memory.cpp
  src/core/hle/kernel/k_shared_memory.h
  src/core/hle/kernel/kernel.cpp
Labels: kernel-fix, early-access-merge

#9500 qt: prevent reentrant shutdown
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#9495 yuzu: Automatically refresh device list
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.h
  src/yuzu/configuration/configure_input_player.ui
Labels: early-access-merge

#9490 texture_cache: Use pre-allocated heap buffer for texture swizzles
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
  src/video_core/texture_cache/util.cpp
  src/video_core/texture_cache/util.h
Labels: mainline-merge

#9504 k_page_group: synchronize
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_code_memory.cpp
  src/core/hle/kernel/k_code_memory.h
  src/core/hle/kernel/k_memory_manager.cpp
  src/core/hle/kernel/k_page_group.cpp
  src/core/hle/kernel/k_page_group.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/k_shared_memory.cpp
  src/core/hle/kernel/memory_types.h
  src/core/hle/kernel/svc.cpp
Labels: kernel-fix, mainline-merge

#9423 video_core: Implement all vulkan topology
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/host_shaders/vulkan_quad_indexed.comp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: mainline-merge

#9515 CMake: make more features optional
  CMakeLists.txt
  externals/CMakeLists.txt
  src/CMakeLists.txt
  src/audio_core/CMakeLists.txt
  src/input_common/CMakeLists.txt
  src/input_common/main.cpp
Labels: early-access-merge
