Repository yuzu-emu/yuzu, pull requests merged in 2022-01, with the labels that each got.

#7659 texture_cache/util: Fix s32 overflow when resolving overlaps
  src/video_core/texture_cache/util.cpp
Labels: gpu-fix, early-access-merge

#7629 shaders: Add fixes for NVIDIA drivers 495+
  src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp
  src/shader_recompiler/backend/glasm/emit_glasm_instructions.h
  src/shader_recompiler/backend/glsl/emit_glsl_bitwise_conversion.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_context_get_set.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_floating_point.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_instructions.h
  src/shader_recompiler/backend/glsl/emit_glsl_integer.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_special.cpp
  src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
  src/shader_recompiler/frontend/ir/opcodes.inc
  src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
  src/shader_recompiler/ir_opt/constant_propagation_pass.cpp
  src/shader_recompiler/profile.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
Labels: gpu-fix, early-access-merge

#7624 vk_texture_cache: Use 3D scale helpers for MSAA texture scaling on Intel Windows drivers
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-fix, early-access-merge

#7648 core: hle: kernel: Implement thread pinning.
  src/core/CMakeLists.txt
  src/core/hle/kernel/global_scheduler_context.cpp
  src/core/hle/kernel/k_interrupt_manager.cpp
  src/core/hle/kernel/k_interrupt_manager.h
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/svc.cpp
Labels: kernel-new, early-access-merge

#7668 gpu: Use std::stop_token in WaitFence for VSync thread
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/video_core/gpu.cpp
  src/video_core/gpu.h
Labels: bug

#7251 ShaderDecompiler: Add a debug option to dump the game's shaders.
  src/common/settings.h
  src/shader_recompiler/environment.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/shader_environment.cpp
  src/video_core/shader_environment.h
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
Labels: gpu-new, early-access-merge

#7658 video_core/memory_manager: Fixes for sparse memory management
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/texture_cache/texture_cache.h
Labels: gpu-fix, early-access-merge

#7680 input_common: Allow to only have acceleration motion data
  src/core/hid/motion_input.cpp
  src/input_common/input_engine.cpp
Labels: early-access-merge

#7682 input_common: Fix UDP controller mappings
  src/core/hid/emulated_controller.cpp
  src/input_common/drivers/udp_client.cpp
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge

#7687 input_common: Handle errors on TAS scripts
  src/input_common/drivers/tas_input.cpp
Labels: general

#7683 logging: adapt to changes in fmt 8.1
  CMakeLists.txt
  src/common/CMakeLists.txt
  src/common/logging/formatter.h
  src/common/logging/log.h
  src/shader_recompiler/exception.h
Labels: general, early-access-merge

#7633 yuzu: Add controller hotkeys
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hid/hid_types.h
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/drivers/sdl_driver.h
  src/input_common/drivers/tas_input.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_hotkeys.cpp
  src/yuzu/configuration/configure_hotkeys.h
  src/yuzu/hotkeys.cpp
  src/yuzu/hotkeys.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/uisettings.h
Labels: frontend-new, early-access-merge, input

#7684 Kernel Memory Updates (Part 1): SetMemoryAttribute, and other minor changes.
  src/core/hle/kernel/k_memory_block.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_types.h
Labels: early-access-merge

#7700 core/hid: Reduce gyro threshold even more
  src/core/hid/motion_input.cpp
Labels: hle-fix, early-access-merge

#7690 yuzu: main: Increase the open file limit on Windows to 8192
  src/yuzu/main.cpp
Labels: general, early-access-merge

#7698 Kernel Memory Updates (Part 2): SetProcessMemoryPermission, update permissions, and other minor changes.
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/physical_core.cpp
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/ldr/ldr.cpp
Labels: kernel-fix, early-access-merge

#7699 hle: kernel: Fix service_threads access to be thread safe.
  src/core/hle/kernel/kernel.cpp
Labels: kernel-fix, early-access-merge

#7707 service/hid: Decrease motion update rate
  src/core/hle/service/hid/hid.cpp
Labels: early-access-merge

#7724 astc_decoder: Combine FastReplicate functions to work around new NV driver bug
  src/video_core/host_shaders/astc_decoder.comp
Labels: gpu-fix, early-access-merge

#7712 Accurately implement thread exit
  src/common/fiber.cpp
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/k_worker_task.h
  src/core/hle/kernel/k_worker_task_manager.cpp
  src/core/hle/kernel/k_worker_task_manager.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
Labels: kernel-new, kernel-fix, early-access-merge

#7701 Kernel Memory Updates (Part 3): Clear KMemoryManager pages & other fixes
  src/core/hle/kernel/k_memory_manager.cpp
  src/core/hle/kernel/k_memory_manager.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/kernel.cpp
Labels: kernel-fix, early-access-merge

#7710 core/hid: Increment shake force
  src/core/hid/input_converter.cpp
Labels: early-access-merge

#7695 common: bit_util: Add IsPow2 helper function
  src/common/bit_util.h
Labels: general

#7756 service: Update function tables
  src/core/hle/service/acc/acc_su.cpp
  src/core/hle/service/acc/acc_u1.cpp
  src/core/hle/service/am/omm.cpp
  src/core/hle/service/audio/audctl.cpp
  src/core/hle/service/btm/btm.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/set/set_sys.cpp
  src/core/hle/service/usb/usb.cpp
  src/core/hle/service/wlan/wlan.cpp
Labels: general

#7737 Various fixes to HLE service thread management
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/k_priority_queue.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/service_thread.cpp
  src/yuzu/debugger/wait_tree.cpp
Labels: kernel-fix, early-access-merge

#7735 input_common: Report battery for UDP controllers
  src/input_common/drivers/udp_client.cpp
  src/input_common/drivers/udp_client.h
Labels: early-access-merge

#7716 yuzu: Add volume hotkeys
  src/audio_core/stream.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/main.cpp
Labels: early-access-merge

#7765 hle: kernel: KThread: Improve Increment/Decrement RunningThreadCount.
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_thread.cpp
Labels: kernel-fix, early-access-merge

#7771 kernel/k_affinity_mask: Remove duplicated assert
  src/core/hle/kernel/k_affinity_mask.h
Labels: general

#7773 input_common/udp_client: Replace deprecated from_string()/to_ulong() functions
  src/input_common/drivers/udp_client.cpp
  src/input_common/drivers/udp_client.h
Labels: input

#7774 input_common/main: Pass MappingData by const reference in callbacks
  src/input_common/input_engine.h
  src/input_common/input_mapping.cpp
  src/input_common/input_mapping.h
  src/input_common/main.cpp
  src/input_common/main.h
Labels: input

#7778 vk_fsr: Replace comma operator with semicolon
  src/video_core/renderer_vulkan/vk_fsr.cpp
Labels: general

#7779 gpu: Remove obsoleted CDmaPusher() accessors
  src/video_core/gpu.h
Labels: general

#7777 shader_recompiler: Remove unnecessary [[nodiscard]] specifier
  src/shader_recompiler/frontend/maxwell/translate_program.h
Labels: general

#7768 Update AMD FidelityFX Super Resolution™ to 1.0.2
  externals/FidelityFX-FSR/ffx-fsr/ffx_fsr1.h
  src/yuzu/configuration/configure_graphics.ui
Labels: early-access-merge

#7780 video_core/macro: Move impl classes into their cpp files
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/macro/macro.cpp
  src/video_core/macro/macro.h
  src/video_core/macro/macro_hle.cpp
  src/video_core/macro/macro_hle.h
  src/video_core/macro/macro_interpreter.cpp
  src/video_core/macro/macro_interpreter.h
  src/video_core/macro/macro_jit_x64.cpp
  src/video_core/macro/macro_jit_x64.h
Labels: general

#7762 Kernel Memory Updates (Part 4): Improve Un/MapPages, and more.
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/svc.cpp
Labels: kernel-new, early-access-merge

#7783 common/xbyak_api: Make BuildRegSet() constexpr
  src/common/x64/xbyak_abi.h
  src/video_core/macro/macro_jit_x64.cpp
Labels: general

#7770 input_common: Add option to configure gyro threshold
  src/core/hid/emulated_controller.cpp
  src/core/hid/motion_input.cpp
  src/input_common/input_poller.cpp
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge

#7799 emit_spirv: Add Xfb execution mode when transform feedback is used
  src/shader_recompiler/backend/spirv/emit_spirv.cpp
Labels: gpu-fix, vulkan, early-access-merge

#7786 video_minimum_maximum: Implement src operand selectors
  src/shader_recompiler/frontend/maxwell/translate/impl/video_minimum_maximum.cpp
Labels: gpu-new, early-access-merge

#7788 buffer_cache: Reduce stream buffer allocations when expanding from the left
  src/video_core/buffer_cache/buffer_cache.h
Labels: gpu-fix, early-access-merge

#7787 hle: kernel: KScheduler: Fix deadlock with core waiting for a thread lock that has migrated.
  src/core/hle/kernel/k_priority_queue.h
  src/core/hle/kernel/k_scheduler.cpp
Labels: kernel-fix, early-access-merge

#7784 input_common: Add DS5 to HD rumble list
  src/input_common/drivers/sdl_driver.cpp
Labels: early-access-merge

#7800 spirv_atomic: Define U32x2 storage buffers for 64-bit storage atomics
  src/shader_recompiler/backend/spirv/emit_spirv_atomic.cpp
  src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
Labels: gpu-fix, vulkan, early-access-merge

#7791 wall_clock: Use standard wall clock if rtsc frequency is too low
  src/common/wall_clock.cpp
Labels: early-access-merge
