Repository yuzu-emu/yuzu, pull requests merged in 2022-04, with the labels that each got.

#8128 GPU Garbage Collection: Fix regressions.
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: gpu-fix, early-access-merge

#8123 service: hid: Remove inaccurate behavior on initialization
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
Labels: early-access-merge, input

#8135 applets/web: Keep foreground (websession) web applet open
  src/core/hle/service/am/applets/applet_web_browser.cpp
Labels: early-access-merge

#8105 native_clock: Use AtomicLoad128
  src/common/atomic_ops.h
  src/common/x64/native_clock.cpp
Labels: early-access-merge, thread-race

#8089 configuration: Add Paranoid CPU accuracy level
  src/common/settings.h
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/yuzu/configuration/configure_cpu.ui
Labels: early-access-merge

#8159 dynarmic: Print stack trace on unrecognised instruction or other exception
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
Labels: mainline-merge

#8137 Follow-up fixes for NVFlinger rewrite (Part 2)
  src/core/hle/service/nvflinger/buffer_queue_consumer.cpp
  src/core/hle/service/nvflinger/buffer_queue_consumer.h
  src/core/hle/service/nvflinger/buffer_queue_core.cpp
  src/core/hle/service/nvflinger/buffer_queue_core.h
  src/core/hle/service/nvflinger/buffer_queue_producer.cpp
  src/core/hle/service/nvflinger/buffer_queue_producer.h
  src/core/hle/service/nvflinger/consumer_base.cpp
  src/core/hle/service/nvflinger/consumer_base.h
  src/core/hle/service/nvflinger/nvflinger.cpp
Labels: early-access-merge

#8122 Improve usage of service host threads
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/nvdrv/nvdrv_interface.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/vi/vi.cpp
Labels: hle-fix, early-access-merge

#8133 shader_recompiler: support const buffer indirect addressing on OpenGL
  src/shader_recompiler/backend/glsl/emit_glsl_context_get_set.cpp
  src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
  src/shader_recompiler/backend/glsl/glsl_emit_context.h
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
  src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
  src/shader_recompiler/shader_info.h
Labels: early-access-merge

#8143 native_clock: Use lfence with rdtsc
  src/common/x64/native_clock.cpp
Labels: early-access-merge

#8150 Vulkan: crop to screen dimensions if crop not explicitly requested
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
Labels: early-access-merge

#8173 CMakeLists: Enforce C4505 and C5245
  src/CMakeLists.txt
Labels: general

#8138 core: hid: Reduce the amount of data races
  src/core/hid/emulated_console.cpp
  src/core/hid/emulated_console.h
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hid/emulated_devices.cpp
  src/core/hid/emulated_devices.h
Labels: early-access-merge

#8149 OpenGL: flip front faces if Z scale is inverted
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge

#8171 Improvements for game modding with Skyline, DNS resolution
  src/core/file_sys/patch_manager.cpp
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/sockets/sfdnsres.cpp
  src/core/hle/service/sockets/sfdnsres.h
  src/core/hle/service/sockets/sockets.h
  src/core/network/network.cpp
  src/core/network/sockets.h
Labels: early-access-merge

#8157 kernel: Fix some data races
  src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
  src/core/hle/kernel/k_auto_object.h
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_scheduler_lock.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
Labels: early-access-merge

#8178 hle: kernel: Invalidate entire icache in UnmapProcessMemory and UnmapCodeMemory (fixes #8174)
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/ldr/ldr.cpp
Labels: early-access-merge

#8165 Kernel: Track open references to KServerPort and KServerSession.
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/k_auto_object.h
  src/core/hle/kernel/k_server_port.cpp
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
Labels: kernel-fix, early-access-merge

#8199 service: jit: Implement the JIT service
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_code_memory.cpp
  src/core/hle/service/jit/jit.cpp
  src/core/hle/service/jit/jit_context.cpp
  src/core/hle/service/jit/jit_context.h
Labels: early-access-merge

#8202 dynarmic: Fix single core mode
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
Labels: cpu-fix

#8172 hle: kernel: Use std::mutex instead of spin locks for most kernel locking.
  src/common/fiber.cpp
  src/core/core_timing.h
  src/core/hle/kernel/global_scheduler_context.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_spin_lock.cpp
  src/core/hle/kernel/k_spin_lock.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/physical_core.cpp
  src/core/hle/kernel/physical_core.h
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/service.h
Labels: kernel-fix, early-access-merge

#8205 Fixes for Mario 64
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/format_lookup_table.cpp
  src/video_core/texture_cache/formatter.h
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, mainline-merge

#8188 dynarmic: Fix race when switching page tables
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.h
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.h
Labels: early-access-merge

#6558 hidbus: Implement hidbus and ringcon
  src/common/settings.h
  src/common/settings_input.h
  src/core/CMakeLists.txt
  src/core/hid/emulated_devices.cpp
  src/core/hid/emulated_devices.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hidbus.cpp
  src/core/hle/service/hid/hidbus.h
  src/core/hle/service/hid/hidbus/hidbus_base.cpp
  src/core/hle/service/hid/hidbus/hidbus_base.h
  src/core/hle/service/hid/hidbus/ringcon.cpp
  src/core/hle/service/hid/hidbus/ringcon.h
  src/core/hle/service/hid/hidbus/starlink.cpp
  src/core/hle/service/hid/hidbus/starlink.h
  src/core/hle/service/hid/hidbus/stubbed.cpp
  src/core/hle/service/hid/hidbus/stubbed.h
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_input_advanced.cpp
  src/yuzu/configuration/configure_input_advanced.h
  src/yuzu/configuration/configure_input_advanced.ui
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_ringcon.cpp
  src/yuzu/configuration/configure_ringcon.h
  src/yuzu/configuration/configure_ringcon.ui
Labels: hle-new, early-access-merge, input, service-implementation

#8170 a workaround if the mouse cursor leaves the rendering window in panning mode
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#8192 bootmanager: Don't create another screenshot request if previous one is not done yet
  src/video_core/renderer_base.cpp
  src/video_core/renderer_base.h
  src/yuzu/bootmanager.cpp
Labels: early-access-merge

#8222 service: hid: Improve accuracy of sixaxis functions
  src/core/hid/hid_types.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/errors.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: hle-new, hle-fix, early-access-merge

#7978 input_common: Map sticks correctly when mapped sideways
  src/input_common/drivers/gc_adapter.cpp
  src/input_common/drivers/gc_adapter.h
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/drivers/sdl_driver.h
  src/input_common/drivers/udp_client.cpp
  src/input_common/drivers/udp_client.h
  src/input_common/input_engine.h
  src/input_common/main.cpp
  src/input_common/main.h
  src/yuzu/configuration/configure_input_player.cpp
Labels: early-access-merge, input

#8261 service: jit: document and clean up
  src/core/hle/service/jit/jit.cpp
  src/core/hle/service/jit/jit_context.cpp
  src/core/hle/service/jit/jit_context.h
Labels: hle-issue

#8262 CMakeLists: Update Conan requirement to 1.45.0
  CMakeLists.txt
Labels: build-system-new, early-access-merge

#8229 service: hid: Access shared memory directly
  src/core/hid/hid_types.h
  src/core/hle/service/hid/controllers/console_sixaxis.cpp
  src/core/hle/service/hid/controllers/console_sixaxis.h
  src/core/hle/service/hid/controllers/controller_base.h
  src/core/hle/service/hid/controllers/debug_pad.cpp
  src/core/hle/service/hid/controllers/debug_pad.h
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/gesture.h
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/keyboard.h
  src/core/hle/service/hid/controllers/mouse.cpp
  src/core/hle/service/hid/controllers/mouse.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/controllers/stubbed.cpp
  src/core/hle/service/hid/controllers/stubbed.h
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
  src/core/hle/service/hid/controllers/xpad.cpp
  src/core/hle/service/hid/controllers/xpad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: hle-fix, early-access-merge

#8267 renderer_vulkan: Update screen info if the framebuffer size has changed
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
Labels: gpu-fix, vulkan, early-access-merge
