Repository yuzu-emu/yuzu, pull requests merged in 2022-08, with the labels that each got.

#8702 renderer_vulkan: add format fallbacks for R16G16B16_SFLOAT, R16G16B16_SSCALED, R8G8B8_SSCALED
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, early-access-merge

#8667 [SPIRV] Add missed shader defines
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
Labels: gpu-fix, early-access-merge

#8700 vk_texture_cache: return VK_NULL_HANDLE for views of null images
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: gpu-fix, early-access-merge

#8658 video_core: differentiate between tiled and untiled framebuffer sizes for unaccelerated blits
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
Labels: gpu-fix, mainline-merge

#8240 core/arm: re-enable cycle counting
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
Labels: mainline-merge

#8637 kernel: unlayer CPU interrupt handling
  src/core/CMakeLists.txt
  src/core/arm/arm_interface.h
  src/core/arm/cpu_interrupt_handler.cpp
  src/core/arm/cpu_interrupt_handler.h
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.h
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.h
  src/core/debugger/debugger.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/physical_core.cpp
  src/core/hle/kernel/physical_core.h
Labels: kernel-fix

#8715 Qt5 work around for suzhou numerals
  src/yuzu/main.cpp
Labels: early-access-merge

#8499 Translate english plurals
  .gitignore
  .reuse/dep5
  dist/english_plurals/README.md
  dist/english_plurals/en.ts
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/configure_ui.cpp
  src/yuzu/main.cpp
Labels: early-access-merge

#8729 arm_dynarmic_cp15: Implement CP15DMB/CP15DSB/CP15ISB
  src/core/arm/dynarmic/arm_dynarmic_cp15.cpp
  src/core/arm/dynarmic/arm_dynarmic_cp15.h
Labels: early-access-merge

#8724 hid: core: Properly emulate controller color and battery level
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hid/hid_types.h
  src/core/hle/service/hid/controllers/npad.cpp
Labels: early-access-merge

#8722 hid: core: Delay the stop vibration command when testing
  src/core/hid/emulated_controller.cpp
Labels: early-access-merge

#8735 Make vsync setting work for Vulkan
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/yuzu/configuration/configure_graphics_advanced.ui
Labels: early-access-merge

#8686 ci: Graft source when archiving
  .ci/scripts/common/post-upload.sh
  .ci/scripts/windows/upload.ps1
Labels: early-access-merge

#8745 arm_dynarmic: Fix nullptr fastmem arenas
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
Labels: cpu-fix, mainline-merge

#8755 ips_layer: Delimit parsed hex value string
  src/core/file_sys/ips_layer.cpp
Labels: bug

#8685 core, network: Add ability to proxy socket packets
  src/CMakeLists.txt
  src/common/CMakeLists.txt
  src/common/announce_multiplayer_room.h
  src/common/socket_types.h
  src/core/CMakeLists.txt
  src/core/announce_multiplayer_session.cpp
  src/core/hle/service/nifm/nifm.cpp
  src/core/hle/service/nifm/nifm.h
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/sockets/bsd.h
  src/core/hle/service/sockets/sockets.h
  src/core/hle/service/sockets/sockets_translate.cpp
  src/core/internal_network/network.cpp
  src/core/internal_network/network.h
  src/core/internal_network/socket_proxy.cpp
  src/core/internal_network/socket_proxy.h
  src/core/internal_network/sockets.h
  src/dedicated_room/CMakeLists.txt
  src/dedicated_room/yuzu_room.cpp
  src/dedicated_room/yuzu_room.rc
  src/network/room.cpp
  src/network/room.h
  src/network/room_member.cpp
  src/network/room_member.h
  src/web_service/verify_user_jwt.cpp
  src/yuzu/main.cpp
  src/yuzu/multiplayer/chat_room.cpp
  src/yuzu/multiplayer/client_room.cpp
  src/yuzu/multiplayer/direct_connect.cpp
  src/yuzu/multiplayer/host_room.cpp
  src/yuzu/multiplayer/lobby.cpp
  src/yuzu/multiplayer/message.cpp
  src/yuzu/multiplayer/message.h
  src/yuzu/multiplayer/state.cpp
  src/yuzu/multiplayer/validation.h
  src/yuzu/uisettings.h
  src/yuzu_cmd/yuzu.cpp
Labels: early-access-merge

#8791 video_core: implement R16G16B16X16 texture format
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
Labels: gpu-fix

#8794 core: implement clkrst service
  src/core/hle/service/pcv/pcv.cpp
  src/core/hle/service/pcv/pcv.h
Labels: early-access-merge

#8795 video_core: support framebuffer crop rect top not zero
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
Labels: early-access-merge

#8790 core/file_sys: fix BuildId padding in patch loading
  src/core/file_sys/ips_layer.cpp
  src/core/file_sys/patch_manager.cpp
Labels: filesystem-fix

#8799 core/file_sys: fix alignment of BuildId
  src/core/file_sys/ips_layer.cpp
  src/core/file_sys/patch_manager.cpp
Labels: filesystem-fix

#8805 yuzu: Force camera output to be saved on a buffer
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/configure_camera.cpp
Labels: early-access-merge

#8485 cmake: Use compatibility list in source directory
  CMakeLists.txt
Labels: mainline-merge

#8566 core: hid: Add fallback for dualjoycon and pro controllers
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
Labels: early-access-merge, input

#8809 video_core: vulkan: rasterizer: Workaround on viewport swizzle on AMD
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: early-access-merge

#8752 video_code: support rectangle texture
  src/shader_recompiler/backend/glasm/emit_glasm_image.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_image.cpp
  src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
  src/shader_recompiler/frontend/ir/ir_emitter.cpp
  src/shader_recompiler/frontend/ir/ir_emitter.h
  src/shader_recompiler/ir_opt/rescaling_pass.cpp
  src/shader_recompiler/ir_opt/texture_pass.cpp
  src/shader_recompiler/shader_info.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/shader_environment.cpp
Labels: early-access-merge
