Repository yuzu-emu/yuzu, pull requests merged in 2022-02, with the labels that each got.

#7805 Inline2Memory: Flush before writing buffer.
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/engine_upload.cpp
  src/video_core/engines/engine_upload.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_memory.cpp
  src/video_core/engines/kepler_memory.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/gpu.cpp
  src/video_core/memory_manager.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: gpu-fix, mainline-merge

#7824 video_core/shader_cache: Take std::span in RemoveShadersFromStorage()
  src/video_core/shader_cache.cpp
  src/video_core/shader_cache.h
Labels: general

#7825 common/file: Remove [[nodiscard]] from Open()
  src/common/fs/file.h
Labels: general

#7828 yuzu/game_list: Use non-deprecated version of QString's split() function
  src/yuzu/game_list.cpp
Labels: general

#7830 configure_input_player: Avoid unnecessary ParamPackage copies
  src/yuzu/configuration/configure_input_player.cpp
Labels: general

#7831 configure_motion_touch: Use functor versions of invokeMethod
  src/yuzu/configuration/configure_motion_touch.cpp
Labels: general

#7833 configure_filesystem: Add missing changeEvent() override
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_filesystem.cpp
  src/yuzu/configuration/configure_filesystem.h
Labels: general

#7806 shaders: Implement U32x2 atomic fallbacks when device does not support int64
  src/shader_recompiler/backend/glasm/emit_glasm_instructions.h
  src/shader_recompiler/backend/glasm/emit_glasm_memory.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_atomic.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_instructions.h
  src/shader_recompiler/backend/spirv/emit_spirv_atomic.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
  src/shader_recompiler/frontend/ir/microinstruction.cpp
  src/shader_recompiler/frontend/ir/opcodes.inc
  src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
  src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp
  src/shader_recompiler/ir_opt/lower_int64_to_int32.cpp
Labels: gpu-fix, early-access-merge

#7838 common_types: Remove NonCopyable struct
  src/common/common_types.h
  src/common/telemetry.h
  src/core/arm/arm_interface.h
  src/core/file_sys/vfs.h
  src/core/hid/emulated_console.h
  src/core/hid/emulated_controller.h
  src/core/hid/hid_core.h
  src/core/hle/kernel/k_auto_object.h
  src/core/hle/kernel/k_auto_object_container.h
  src/core/hle/kernel/k_handle_table.h
  src/core/hle/kernel/k_memory_manager.h
  src/core/hle/kernel/k_memory_region.h
  src/core/hle/kernel/k_page_heap.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/k_slab_heap.h
  src/core/hle/service/vi/display/vi_display.h
  src/core/loader/loader.h
  src/video_core/renderer_base.h
  src/video_core/renderer_opengl/gl_resource_manager.h
Labels: general

#7835 hle: kernel: KPageTable: Migrate locks to KScopedLightLock.
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
Labels: kernel-fix, early-access-merge

#7814 Vulkan: Fix Scheduler Chunks when their FuncType is 0.
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
Labels: gpu-fix, mainline-merge

#7839 yuzu: ui: Improve battery symbols
  src/core/hid/input_converter.cpp
  src/input_common/drivers/sdl_driver.cpp
  src/yuzu/configuration/configure_input_player_widget.cpp
  src/yuzu/configuration/configure_input_player_widget.h
Labels: early-access-merge

#7842 yuzu: config: Vibrate the controller while configuring vibration strength
  src/yuzu/applets/qt_controller.cpp
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_vibration.cpp
  src/yuzu/configuration/configure_vibration.h
  src/yuzu/configuration/configure_vibration.ui
Labels: early-access-merge

#7849 main: Always remove the frameless window flag when restoring UI state
  src/yuzu/main.cpp
Labels: frontend-fix, early-access-merge

#7852 common: Revise and fix the UUID implementation
  src/common/uuid.cpp
  src/common/uuid.h
  src/core/frontend/applets/profile_select.cpp
  src/core/hid/emulated_controller.cpp
  src/core/hle/ipc_helpers.h
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/acc/profile_manager.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applet_profile_select.cpp
  src/core/hle/service/am/applets/applet_profile_select.h
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/mii/mii_manager.cpp
  src/core/hle/service/mii/mii_manager.h
  src/core/hle/service/ns/pdm_qry.cpp
  src/core/hle/service/time/clock_types.h
  src/core/hle/service/time/steady_clock_core.h
  src/core/hle/service/time/time_manager.cpp
  src/input_common/drivers/gc_adapter.cpp
  src/input_common/drivers/keyboard.cpp
  src/input_common/drivers/mouse.cpp
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/drivers/touch_screen.cpp
  src/input_common/drivers/udp_client.cpp
  src/input_common/drivers/udp_client.h
  src/input_common/input_engine.cpp
  src/input_common/input_engine.h
  src/input_common/input_mapping.cpp
  src/yuzu/applets/qt_profile_select.cpp
  src/yuzu/configuration/configure_profile_manager.cpp
  src/yuzu/main.cpp
Labels: general, early-access-merge

#7890 debugger: console: Set console output codepage to UTF-8
  src/yuzu/debugger/console.cpp
Labels: general

#7899 file_sys: Dump patched exefs rather than base
  src/core/file_sys/patch_manager.cpp
Labels: hle-new, mainline-merge

#7866 kernel: svc: Add OutputDebugString32, CreateCodeMemory32, ControlCodeMemory32
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
Labels: kernel-new

#7867 nfp: Improve amiibo support
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nfp/nfp.h
  src/yuzu/configuration/config.cpp
  src/yuzu/main.cpp
  src/yuzu/main.ui
Labels: hle-fix, early-access-merge

#7920 core: hle: kernel: KPageTable: Fix UnmapPages.
  src/core/hle/kernel/k_page_table.cpp
Labels: kernel-fix, early-access-merge

#7919 core: hle: kernel: KPageTable: Improve Un/MapPhysicalMemory.
  src/common/page_table.cpp
  src/common/page_table.h
  src/core/hle/kernel/k_page_table.cpp
Labels: kernel-fix, early-access-merge

#7913 vulkan_device: fix missing format in ANV
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-fix, mainline-merge
