Repository yuzu-emu/yuzu, pull requests merged in 2022-10, with the labels that each got.

#8874 Align index buffe size when vertex_buffer_unified_memory enable
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
Labels: gpu-fix, early-access-merge

#8876 ldn: Implement "local wireless" networked multiplayer
  src/core/CMakeLists.txt
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/ldn/lan_discovery.cpp
  src/core/hle/service/ldn/lan_discovery.h
  src/core/hle/service/ldn/ldn.cpp
  src/core/hle/service/ldn/ldn_types.h
  src/core/internal_network/network_interface.cpp
  src/core/internal_network/network_interface.h
  src/core/internal_network/socket_proxy.cpp
  src/dedicated_room/yuzu_room.cpp
  src/network/room.cpp
  src/network/room.h
  src/network/room_member.cpp
  src/network/room_member.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
  src/yuzu/multiplayer/chat_room.cpp
  src/yuzu/multiplayer/client_room.cpp
  src/yuzu/multiplayer/direct_connect.cpp
  src/yuzu/multiplayer/direct_connect.h
  src/yuzu/multiplayer/host_room.cpp
  src/yuzu/multiplayer/host_room.h
  src/yuzu/multiplayer/lobby.cpp
  src/yuzu/multiplayer/lobby.h
  src/yuzu/multiplayer/lobby_p.h
  src/yuzu/multiplayer/message.cpp
  src/yuzu/multiplayer/state.cpp
  src/yuzu/multiplayer/state.h
  src/yuzu/uisettings.h
Labels: mainline-merge

#6598 MacroHLE: Add MultidrawIndirect HLE Macro.
  src/video_core/macro/macro_hle.cpp
Labels: gpu-new, gpu-fix, do-not-merge, mainline-merge

#8992 service: vi: Retrieve vsync event once per display
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/vi/display/vi_display.cpp
  src/core/hle/service/vi/display/vi_display.h
  src/core/hle/service/vi/vi.cpp
  src/core/hle/service/vi/vi_results.h
Labels: core-fix, early-access-merge

#8955 core: nfp: Rewrite implementation to remove direct access from the frontend
  src/common/input.h
  src/core/CMakeLists.txt
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hid/input_converter.cpp
  src/core/hid/input_converter.h
  src/core/hle/service/mii/mii_manager.cpp
  src/core/hle/service/mii/mii_manager.h
  src/core/hle/service/nfc/nfc.cpp
  src/core/hle/service/nfp/amiibo_crypto.cpp
  src/core/hle/service/nfp/amiibo_crypto.h
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nfp/nfp.h
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nfp/nfp_device.h
  src/core/hle/service/nfp/nfp_result.h
  src/core/hle/service/nfp/nfp_types.h
  src/core/hle/service/nfp/nfp_user.cpp
  src/core/hle/service/nfp/nfp_user.h
  src/input_common/CMakeLists.txt
  src/input_common/drivers/virtual_amiibo.cpp
  src/input_common/drivers/virtual_amiibo.h
  src/input_common/input_engine.cpp
  src/input_common/input_engine.h
  src/input_common/input_poller.cpp
  src/input_common/input_poller.h
  src/input_common/main.cpp
  src/input_common/main.h
  src/yuzu/main.cpp
Labels: early-access-merge

#9010 macro_jit_x64: fix miscompilation of bit extraction operations
  src/video_core/macro/macro_jit_x64.cpp
Labels: gpu-fix, early-access-merge

#9005 macro_jit_x64: cancel exit for taken branch
  src/video_core/macro/macro_jit_x64.cpp
Labels: gpu-fix, early-access-merge

#9011 shader_recompiler: add extended LDC to GLASM backend
  src/shader_recompiler/backend/glasm/emit_glasm_context_get_set.cpp
Labels: gpu-fix, early-access-merge, nvidia

#8987 vulkan: automatically use larger staging buffer sizes when possible
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
Labels: gpu, early-access-merge

#8944 build(room): simplify yuzu-room installation
  src/dedicated_room/CMakeLists.txt
Labels: early-access-merge

#6142 program_metadata: Avoid reference binding to misaligned address
  src/core/file_sys/program_metadata.cpp
  src/core/file_sys/program_metadata.h
Labels: early-access-merge

#9030 configure_graphics: Fix graphics API selection when a game is running
  src/yuzu/configuration/configure_graphics.cpp
Labels: bug

#9016 vk_scheduler: wait for command processing to complete
  src/video_core/renderer_vulkan/vk_scheduler.cpp
Labels: gpu-fix, early-access-merge

#8766 [video_core] Update 3D registers
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/dirty_flags.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/gpu.h
  src/video_core/macro/macro_hle.cpp
  src/video_core/query_cache.h
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
  src/video_core/renderer_opengl/gl_graphics_pipeline.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_state_tracker.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_state_tracker.cpp
  src/video_core/shader_cache.cpp
  src/video_core/shader_environment.cpp
  src/video_core/shader_environment.h
  src/video_core/surface.cpp
  src/video_core/texture_cache/image_info.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/transform_feedback.cpp
  src/video_core/transform_feedback.h
Labels: early-access-merge

#9048 [video_core] Fix stencil mask registers
  src/video_core/dirty_flags.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_state_tracker.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_state_tracker.cpp
Labels: mainline-merge

#9049 syncpoint_manager: ensure handle is removable before removing
  src/video_core/host1x/syncpoint_manager.cpp
Labels: gpu-fix, early-access-merge

#9024 video_core: don't block rendering on screenshots
  src/video_core/renderer_base.cpp
Labels: gpu-fix, early-access-merge

#9040 core_timing: use high-precision sleeps on non-Windows targets
  src/core/core_timing.cpp
Labels: mainline-merge

#9027 Revert "vulkan: automatically use larger staging buffer sizes when possible"
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
Labels: mainline-merge

#9066 settings: Update aspect_ratio range
  src/common/settings.h
Labels: bug

#9065 result: enforce reference check specialization
  src/core/hle/result.h
Labels: kernel-fix, mainline-merge

#9032 IFriendService: stub CheckFriendListAvailability
  src/core/hle/service/friend/friend.cpp
Labels: early-access-merge

#9039 Auto select the SDL audio backend when Cubeb latency is too high
  src/audio_core/sink/cubeb_sink.cpp
  src/audio_core/sink/cubeb_sink.h
  src/audio_core/sink/sdl2_sink.cpp
  src/audio_core/sink/sdl2_sink.h
  src/audio_core/sink/sink_details.cpp
  src/audio_core/sink/sink_details.h
  src/yuzu/configuration/configure_audio.cpp
Labels: early-access-merge

#9067 renderer_(opengl/vulkan): Fix tessellation clockwise parameter
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/fixed_pipeline_state.cpp
Labels: gpu-fix, mainline-merge

#9055 Preliminary support for nx-hbloader
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/k_client_session.cpp
  src/core/hle/kernel/k_client_session.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_server_session.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_wrap.h
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/ns.h
  src/core/hle/service/ptm/ts.cpp
  src/core/hle/service/ptm/ts.h
  src/core/hle/service/set/set_sys.cpp
  src/core/hle/service/set/set_sys.h
  src/core/hle/service/sm/sm.cpp
Labels: kernel-new, early-access-merge

#9061 kernel: remove KWritableEvent
  src/audio_core/in/audio_in_system.cpp
  src/audio_core/out/audio_out_system.cpp
  src/audio_core/renderer/system.cpp
  src/core/CMakeLists.txt
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/k_class_token.cpp
  src/core/hle/kernel/k_class_token.h
  src/core/hle/kernel/k_event.cpp
  src/core/hle/kernel/k_event.h
  src/core/hle/kernel/k_readable_event.cpp
  src/core/hle/kernel/k_readable_event.h
  src/core/hle/kernel/k_writable_event.cpp
  src/core/hle/kernel/k_writable_event.h
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/acc/async_context.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/bcat/backend/backend.cpp
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/palma.cpp
  src/core/hle/service/hid/hidbus/ringcon.cpp
  src/core/hle/service/kernel_helpers.cpp
  src/core/hle/service/ldn/ldn.cpp
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nim/nim.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/core/hle/service/nvdrv/nvdrv_interface.h
  src/core/hle/service/nvflinger/buffer_queue_producer.cpp
  src/core/hle/service/nvflinger/buffer_queue_producer.h
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/ptm/psm.cpp
  src/core/hle/service/time/system_clock_context_update_callback.cpp
  src/core/hle/service/time/system_clock_context_update_callback.h
  src/core/hle/service/vi/display/vi_display.cpp
Labels: kernel-fix, early-access-merge

#9087 general: Add missing pragma once
  src/common/fixed_point.h
  src/core/hle/service/vi/vi_results.h
Labels: general

#9084 video_core: implement 1D copies based on VMM 'kind'
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/video_core/CMakeLists.txt
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/pte_kind.h
Labels: gpu-fix, early-access-merge

#9071 Kernel Multiprocess (Part 1) - Persist memory & core timing
  src/core/CMakeLists.txt
  src/core/arm/arm_interface.cpp
  src/core/core.cpp
  src/core/core.h
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/device_memory.h
  src/core/hle/kernel/init/init_slab_setup.cpp
  src/core/hle/kernel/k_code_memory.cpp
  src/core/hle/kernel/k_dynamic_page_manager.h
  src/core/hle/kernel/k_dynamic_resource_manager.h
  src/core/hle/kernel/k_dynamic_slab_heap.h
  src/core/hle/kernel/k_interrupt_manager.cpp
  src/core/hle/kernel/k_interrupt_manager.h
  src/core/hle/kernel/k_memory_block.h
  src/core/hle/kernel/k_memory_block_manager.cpp
  src/core/hle/kernel/k_memory_block_manager.h
  src/core/hle/kernel/k_memory_manager.cpp
  src/core/hle/kernel/k_page_buffer.cpp
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_shared_memory.cpp
  src/core/hle/kernel/k_shared_memory.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc_common.h
  src/core/hle/kernel/svc_types.h
  src/core/hle/result.h
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/nvdrv/devices/nvmap.cpp
  src/core/memory.cpp
  src/tests/core/core_timing.cpp
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: kernel-new, kernel-fix, early-access-merge

#9083 kernel: fix slab heap ABA
  src/core/hle/kernel/k_slab_heap.h
Labels: kernel-fix, early-access-merge

#9082 savedata_factory: Detect future save data paths
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/yuzu/main.cpp
Labels: early-access-merge

#9096 [audio_core] Update for firmware 15.0.0
  src/audio_core/renderer/system.cpp
  src/audio_core/renderer/system.h
  src/audio_core/renderer/voice/voice_context.cpp
  src/core/hle/service/audio/audctl.cpp
  src/core/hle/service/audio/audren_u.cpp
Labels: early-access-merge

#9078 kernel: Session request cleanup
  src/core/CMakeLists.txt
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/init/init_slab_setup.cpp
  src/core/hle/kernel/k_client_session.cpp
  src/core/hle/kernel/k_linked_list.h
  src/core/hle/kernel/k_page_buffer.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_server_session.h
  src/core/hle/kernel/k_session_request.cpp
  src/core/hle/kernel/k_session_request.h
  src/core/hle/kernel/k_shared_memory_info.h
  src/core/hle/kernel/k_thread_local_page.h
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/slab_helpers.h
  src/core/hle/service/sm/sm_controller.cpp
Labels: kernel-new, kernel-fix, early-access-merge

#9095 Maxwell3D/Puller: Fix regressions and syncing issues.
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/puller.cpp
Labels: gpu-fix, early-access-merge

#9105 general: Treat more warnings as errors
  CMakeLists.txt
  src/CMakeLists.txt
  src/audio_core/CMakeLists.txt
  src/audio_core/renderer/behavior/info_updater.cpp
  src/audio_core/renderer/command/effect/biquad_filter.cpp
  src/audio_core/renderer/command/effect/multi_tap_biquad_filter.cpp
  src/common/CMakeLists.txt
  src/common/bit_field.h
  src/common/bounded_threadsafe_queue.h
  src/core/CMakeLists.txt
  src/core/file_sys/card_image.cpp
  src/core/file_sys/program_metadata.cpp
  src/core/hid/emulated_controller.cpp
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/memory.cpp
  src/input_common/CMakeLists.txt
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/input_poller.cpp
  src/shader_recompiler/CMakeLists.txt
  src/shader_recompiler/backend/glasm/emit_glasm_not_implemented.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_not_implemented.cpp
  src/video_core/CMakeLists.txt
  src/video_core/memory_manager.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/textures/astc.cpp
  src/video_core/textures/decoders.cpp
  src/yuzu/multiplayer/state.cpp
  src/yuzu/startup_checks.cpp
Labels: general

#9122 nvdrv: fix container destruction order
  src/core/hle/service/nvdrv/nvdrv.cpp
  src/core/hle/service/nvdrv/nvdrv.h
Labels: bug, early-access-merge

#9119 core: barrier service thread shutdown
  src/core/core.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
Labels: hle-fix, core-fix, early-access-merge

#9107 input_common: cache vibration tests
  src/common/input.h
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/input_common/drivers/gc_adapter.cpp
  src/input_common/drivers/gc_adapter.h
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/drivers/sdl_driver.h
  src/input_common/input_engine.h
  src/input_common/input_poller.cpp
Labels: early-access-merge

#9113 service: nfp: Allow amiibos without keys
  src/core/hid/emulated_controller.cpp
  src/core/hle/service/nfp/amiibo_crypto.cpp
  src/core/hle/service/nfp/amiibo_crypto.h
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nfp/nfp_device.h
  src/core/hle/service/nfp/nfp_types.h
  src/core/hle/service/nfp/nfp_user.cpp
  src/core/hle/service/nfp/nfp_user.h
Labels: early-access-merge

#9125 kernel: refactor dummy thread wakeups
  src/core/hle/kernel/global_scheduler_context.cpp
  src/core/hle/kernel/global_scheduler_context.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
Labels: kernel-fix, early-access-merge

#9126 Revert "shader_recompiler/dead_code_elimination: Add DeadBranchElimination pass"
  src/shader_recompiler/frontend/ir/microinstruction.cpp
  src/shader_recompiler/frontend/ir/value.h
  src/shader_recompiler/ir_opt/dead_code_elimination_pass.cpp
Labels: gpu-fix, early-access-merge

#9115 file_sys: Priority display of game titles in the current language
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
Labels: early-access-merge

#9138 arm_interface: curb infinite recursion in stacktrace generation
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
Labels: core-fix

#9127 video_core: Catch vulkan clear op not all channel need clear
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: gpu-fix, early-access-merge

#9140 video_core: Fix drawing trigger mechanism regression
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
Labels: gpu-fix, mainline-merge

#9137 Improved support for nx-hbmenu
  src/core/hle/service/nvdrv/core/nvmap.cpp
  src/core/hle/service/nvdrv/core/nvmap.h
  src/core/hle/service/nvdrv/devices/nvmap.cpp
  src/core/hle/service/nvflinger/buffer_queue_producer.cpp
  src/core/hle/service/nvflinger/nvflinger.cpp
  src/core/hle/service/nvflinger/nvflinger.h
  src/core/hle/service/vi/display/vi_display.h
  src/core/hle/service/vi/vi.cpp
Labels: hle-fix, early-access-merge

#9148 k_server_session: fix crashes
  src/core/hle/kernel/k_server_session.h
  src/core/hle/service/sm/sm.cpp
Labels: kernel-fix

#9091 UI: Add option to hide the compatibility list
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_ui.cpp
  src/yuzu/configuration/configure_ui.ui
  src/yuzu/game_list.cpp
  src/yuzu/uisettings.h
Labels: early-access-merge

#9151 kernel: reinitialize after dram layout change
  src/core/core.cpp
Labels: kernel-fix

#9158 k_thread: fix single core
  src/core/hle/kernel/k_thread.cpp
Labels: kernel-fix

#9155 Vulkan: Fix regression caused by limiting render area to width/height of render targets.
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: gpu-fix, vulkan, early-access-merge

#9159 kernel: more complete fix for KPort reference counting
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm_controller.cpp
Labels: mainline-merge
