Repository yuzu-emu/yuzu, pull requests merged in 2022-05, with the labels that each got.

#8295 gc_adapter: fix libusb import on GCC11.2
  src/input_common/drivers/gc_adapter.cpp
Labels: general

#8296 hle/result: Implement ResultRange
  src/core/hle/result.h
Labels: hle-new

#8272 yuzu: config: Improve analog stick mapping
  src/core/hid/input_converter.cpp
  src/input_common/input_poller.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.ui
Labels: early-access-merge, input

#8300 hle/result: Add ResultRange overload in ResultVal
  src/core/hle/result.h
Labels: general

#8319 video_core/macro_jit_x64: warn on invalid parameter access
  src/video_core/macro/macro_jit_x64.cpp
Labels: gpu

#8320 video_core/macro: Add option to dump macros
  src/common/settings.h
  src/video_core/macro/macro.cpp
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
Labels: gpu

#8328 video_core/macro: clear code on upload address assignment
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/macro/macro.cpp
  src/video_core/macro/macro.h
Labels: gpu-fix, early-access-merge

#8313 maxwell_dma: fix bytes_per_pixel
  src/video_core/engines/maxwell_dma.cpp
Labels: gpu-fix, early-access-merge

#8314 OpenGL: interpret face flips according to GL NDC
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: gpu-fix, early-access-merge

#8308 service: hid: Disable correctly motion input
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/hid.cpp
Labels: early-access-merge

#8337 general: Avoid ambiguous format_to compilation errors
  src/core/arm/dynarmic/arm_dynarmic_cp15.cpp
  src/shader_recompiler/frontend/ir/opcodes.h
  src/shader_recompiler/frontend/maxwell/opcodes.h
Labels: general

#8311 vk_rasterizer: fix stencil test when two faces are disabled
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: gpu-fix, early-access-merge

#8369 vulkan_device: Workaround extension bug
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, early-access-merge

#8379 vulkan_device: Block AMDVLK's VK_KHR_push_descriptor
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, early-access-merge

#8372 input_common: touch: Rewrite touch driver to support multiple touch points
  src/core/hid/emulated_console.cpp
  src/core/hid/input_converter.cpp
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/input_common/drivers/touch_screen.cpp
  src/input_common/drivers/touch_screen.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: early-access-merge

#8374 input_common: Make vibration request async
  src/common/input.h
  src/core/hid/emulated_controller.cpp
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/drivers/sdl_driver.h
Labels: early-access-merge

#8332 general: Use smaller array types where applicable
  src/audio_core/command_generator.cpp
  src/core/hle/service/time/time_zone_manager.cpp
  src/video_core/command_classes/codecs/vp9.cpp
  src/video_core/surface.h
Labels: general

#8392 CMakeLists: Update boost to 1.79.0
  CMakeLists.txt
Labels: externals

#8368 Service: hid: Several improvements and implementations
  src/core/hid/hid_types.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/errors.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: hle-new, early-access-merge, input
