Repository yuzu-emu/yuzu, pull requests merged in 2022-03, with the labels that each got.

#7963 gl_fence_manager: Minor optimization to signal querying
  src/video_core/renderer_opengl/gl_fence_manager.cpp
Labels: general

#7956 Kernel Memory Updates (Part 4): Revamp KMemoryManager & other fixes
  src/core/CMakeLists.txt
  src/core/hle/kernel/board/nintendo/nx/k_memory_layout.h
  src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
  src/core/hle/kernel/board/nintendo/nx/k_system_control.h
  src/core/hle/kernel/initial_process.h
  src/core/hle/kernel/k_memory_layout.h
  src/core/hle/kernel/k_memory_manager.cpp
  src/core/hle/kernel/k_memory_manager.h
  src/core/hle/kernel/k_memory_region_type.h
  src/core/hle/kernel/k_page_heap.cpp
  src/core/hle/kernel/k_page_heap.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
Labels: kernel-new, kernel-fix, mainline-merge

#7973 host_memory: Fix fastmem crashes in debug builds
  src/common/host_memory.cpp
Labels: core-fix, early-access-merge

#7969 gl_graphics_pipeline: Improve shader builder synchronization using fences
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
  src/video_core/renderer_opengl/gl_graphics_pipeline.h
Labels: gpu-fix, opengl, early-access-merge

#7930 MaxwellDMA: Implement semaphore operations
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
Labels: gpu-fix, early-access-merge

#7974 Kernel Memory Updates (Part 5): Revamp MapCodeMemory and UnmapCodeMemory.
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
Labels: kernel-fix, mainline-merge

#7989 shader_recompiler/LOP3: Use brute force python results within switch/case.
  src/shader_recompiler/frontend/maxwell/translate/impl/logic_operation_three_input.cpp
  src/shader_recompiler/frontend/maxwell/translate/impl/logic_operation_three_input_lut3.py
Labels: performance, gpu, early-access-merge

#7975 hle: service: ldr: Use deterministic addresses when mapping NROs.
  src/core/hle/kernel/k_page_table.h
  src/core/hle/service/ldr/ldr.cpp
Labels: hle-fix, mainline-merge

#8015 Shader decompiler: Fix storage tracking in deko3d.
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp
Labels: gpu-fix, mainline-merge

#8000 Initial support for Wii Hagi emulator
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: gpu-fix, early-access-merge

#8008 rescaling_pass: Fix rescaling Color2DArray ImageFetch offsets
  src/shader_recompiler/ir_opt/rescaling_pass.cpp
Labels: early-access-merge

#8023 maxwell_3d: Implement a safer CB data upload
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
Labels: gpu-fix, early-access-merge

#8013 Kernel Memory Updates (Part 6): Use guest memory for slab heaps & update TLS.
  src/common/intrusive_red_black_tree.h
  src/common/tree.h
  src/core/CMakeLists.txt
  src/core/hle/ipc_helpers.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/init/init_slab_setup.cpp
  src/core/hle/kernel/init/init_slab_setup.h
  src/core/hle/kernel/k_address_arbiter.cpp
  src/core/hle/kernel/k_condition_variable.cpp
  src/core/hle/kernel/k_memory_layout.h
  src/core/hle/kernel/k_page_buffer.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/k_port.cpp
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_server_port.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_slab_heap.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/k_thread_local_page.cpp
  src/core/hle/kernel/k_thread_local_page.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/service_thread.cpp
  src/core/hle/kernel/slab_helpers.h
  src/core/hle/kernel/svc_types.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/kernel_helpers.cpp
  src/core/hle/service/sm/sm.cpp
Labels: kernel-new, kernel-fix, early-access-merge

#7964 applet: mii: Simple implementation of mii applet
  src/core/CMakeLists.txt
  src/core/frontend/applets/mii.cpp
  src/core/frontend/applets/mii.h
  src/core/hle/service/am/applets/applet_mii.cpp
  src/core/hle/service/am/applets/applet_mii.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/yuzu/main.cpp
Labels: early-access-merge

#8030 Vulkan: convert S8D24 <-> ABGR8
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/convert_s8d24_to_abgr8.frag
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/blit_image.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: gpu-fix, early-access-merge

#8024 Add shader support for const buffer indirect addressing
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.h
  src/shader_recompiler/frontend/maxwell/translate/impl/load_constant.cpp
  src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
  src/shader_recompiler/shader_info.h
Labels: gpu-new, early-access-merge

#8039 general: Reduce core.h includes
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_page_buffer.cpp
  src/core/hle/kernel/k_page_buffer.h
  src/core/hle/kernel/k_thread_local_page.cpp
  src/video_core/fence_manager.h
  src/video_core/query_cache.h
  src/video_core/renderer_opengl/gl_state_tracker.h
  src/video_core/renderer_vulkan/vk_state_tracker.h
Labels: general

#8028 bsd: Allow inexact match for address length in AcceptImpl
  src/core/hle/service/sockets/bsd.cpp
Labels: hle-fix, early-access-merge

#8047 .ci/build-msvc: Disable YUZU_TESTS cmake variable
  .ci/templates/build-msvc.yml
Labels: build-system-new

#7840 texture_cache: Amend unintended bitwise OR in SynchronizeAliases
  src/video_core/texture_cache/texture_cache.h
Labels: bug, early-access-merge

#8036 vk_texture_cache: Do not reinterpret DepthStencil source images
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: gpu-fix, vulkan, early-access-merge

#7812 BufferCache: Find direction of the stream buffer increase.
  src/video_core/buffer_cache/buffer_cache.h
Labels: gpu-fix, mainline-merge

#8031 applets: Cleanup MiiEdit applet implementation
  src/core/CMakeLists.txt
  src/core/frontend/applets/mii.cpp
  src/core/frontend/applets/mii.h
  src/core/frontend/applets/mii_edit.cpp
  src/core/frontend/applets/mii_edit.h
  src/core/hle/service/am/applets/applet_mii.cpp
  src/core/hle/service/am/applets/applet_mii.h
  src/core/hle/service/am/applets/applet_mii_edit.cpp
  src/core/hle/service/am/applets/applet_mii_edit.h
  src/core/hle/service/am/applets/applet_mii_edit_types.h
  src/core/hle/service/am/applets/applets.cpp
  src/core/hle/service/am/applets/applets.h
  src/core/hle/service/mii/mii_manager.cpp
  src/core/hle/service/mii/mii_manager.h
  src/core/hle/service/mii/raw_data.h
  src/core/hle/service/mii/types.h
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nfp/nfp.h
  src/yuzu/main.cpp
Labels: general, early-access-merge

#8068 shader_recompiler/dead_code_elimination: Add DeadBranchElimination pass
  src/shader_recompiler/frontend/ir/microinstruction.cpp
  src/shader_recompiler/frontend/ir/value.h
  src/shader_recompiler/ir_opt/dead_code_elimination_pass.cpp
Labels: gpu, early-access-merge

#7720 First Nugget: Reworked Garbage Collection to be smarter [originally from Project YFC]
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/image_base.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
  src/video_core/vulkan_common/vulkan_memory_allocator.cpp
  src/video_core/vulkan_common/vulkan_wrapper.cpp
  src/video_core/vulkan_common/vulkan_wrapper.h
Labels: gpu-new, gpu-fix, early-access-merge

#8080 Memory GPU <-> CPU: reduce infighting in the texture cache by adding CPU Cached memory.
  src/core/memory.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/texture_cache/image_base.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
Labels: gpu-new, performance, early-access-merge

#8041 applets/swkbd: Add support for an updated inline software keyboard
  src/core/hle/service/am/applets/applet_software_keyboard.cpp
  src/core/hle/service/am/applets/applet_software_keyboard.h
  src/core/hle/service/am/applets/applet_software_keyboard_types.h
Labels: hle-fix, early-access-merge

#8088 Follow-up fixes for NVFlinger rewrite
  src/core/hle/service/nvflinger/buffer_item_consumer.cpp
  src/core/hle/service/nvflinger/buffer_queue.cpp
  src/core/hle/service/nvflinger/buffer_queue.h
  src/core/hle/service/nvflinger/buffer_queue_consumer.cpp
  src/core/hle/service/nvflinger/buffer_queue_core.cpp
  src/core/hle/service/nvflinger/buffer_queue_core.h
  src/core/hle/service/nvflinger/buffer_queue_producer.cpp
  src/core/hle/service/nvflinger/buffer_queue_producer.h
  src/core/hle/service/nvflinger/consumer_base.cpp
Labels: hle-fix, mainline-merge

#8106 gl_rasterizer: Avoid scenario locking already owned mutex
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: gpu-fix, opengl

#8090 Kernel Memory Updates (Part 7): Various fixes to code memory (Skyline support)
  src/core/hle/kernel/k_code_memory.cpp
  src/core/hle/kernel/k_page_linked_list.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/svc.cpp
Labels: kernel-new, kernel-fix, early-access-merge

#8120 service: hid: Signal event on AcquireNpadStyleSetUpdateEventHandle
  src/core/hle/service/hid/hid.cpp
Labels: input

#8076 Vulkan: Use 3D helpers for MSAA scaling on NV drivers 510+
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, vulkan, early-access-merge

#8116 nvhost_ctrl: Only mark EventState::Busy as BadParameter
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
Labels: gpu-fix, early-access-merge

#8066 codec: Fix GPU decoder detection on Windows and a memory leak
  src/video_core/command_classes/codecs/codec.cpp
Labels: gpu-fix, early-access-merge
