Repository yuzu-emu/yuzu, pull requests merged in 2023-06, with the labels that each got.

#10482 yuzu: Disable game list while game is running
  src/yuzu/main.cpp
Labels: early-access-merge

#10352 add context menu for status bar settings
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/main.cpp
Labels: early-access-merge

#10474 Remove timeline semaphore wait
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
Labels: early-access-merge

#10530 Fix incorrect syncpt id bounds check and potential out of bounds lookup
  src/core/hle/service/nvdrv/core/syncpoint_manager.cpp
Labels: early-access-merge

#10091 Fix buffer overlap checking skipping a page for stream score right expand
  src/video_core/buffer_cache/buffer_cache.h
Labels: mainline-merge

#10550 host_memory: merge adjacent placeholder mappings on Linux
  src/common/host_memory.cpp
Labels: early-access-merge

#10588 vfs: add vfs_cached for romfs build
  src/core/CMakeLists.txt
  src/core/file_sys/patch_manager.cpp
  src/core/file_sys/romfs.cpp
  src/core/file_sys/vfs_cached.cpp
  src/core/file_sys/vfs_cached.h
  src/core/file_sys/vfs_vector.cpp
  src/core/file_sys/vfs_vector.h
Labels: early-access-merge, filesystem-fix

#10594 fsp-srv: avoid patching romfs multiple times
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: early-access-merge, filesystem-fix

#10611 audio_renderer: resolve adsp thread deadlock shutdown
  src/audio_core/renderer/adsp/audio_renderer.cpp
  src/audio_core/renderer/adsp/audio_renderer.h
  src/audio_core/sink/sink_stream.cpp
  src/audio_core/sink/sink_stream.h
Labels: audio-fix

#10591 Localize game icons
  src/core/file_sys/control_metadata.cpp
  src/core/file_sys/control_metadata.h
  src/core/file_sys/patch_manager.cpp
  src/yuzu/main.cpp
Labels: early-access-merge

#10583 AccelerateDMA: Fix incorrect check in Buffer<->Texture copies
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge

#10476 OpenGL: Make use of persistent buffer maps in buffer cache
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/buffer_cache_base.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_staging_buffer_pool.cpp
  src/video_core/renderer_opengl/gl_staging_buffer_pool.h
  src/video_core/renderer_opengl/gl_stream_buffer.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/util_shaders.cpp
  src/video_core/renderer_opengl/util_shaders.h
  src/video_core/renderer_vulkan/vk_buffer_cache.h
Labels: early-access-merge

#10666 nvnflinger: allow locking framerate during video playback
  src/audio_core/audio_core.cpp
  src/audio_core/audio_core.h
  src/common/settings.cpp
  src/common/settings.h
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvnflinger/nvnflinger.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
Labels: early-access-merge

#10623 service: nfc: Add backup support
  src/common/fs/fs_paths.h
  src/common/fs/path_util.cpp
  src/common/fs/path_util.h
  src/core/hle/service/nfc/common/device.cpp
  src/core/hle/service/nfc/common/device.h
  src/core/hle/service/nfc/common/device_manager.cpp
  src/core/hle/service/nfc/nfc_interface.cpp
  src/core/hle/service/nfc/nfc_result.h
  src/core/hle/service/nfp/nfp_interface.cpp
  src/core/hle/service/nfp/nfp_result.h
Labels: early-access-merge

#10685 qt: persist framerate sync option
  src/yuzu/configuration/config.cpp
Labels: frontend-fix, mainline-merge

#10670 vk_blit_screen: use higher bit depth for fxaa
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
Labels: vulkan, early-access-merge

#10668 Combine vertex/transform feedback buffer binding into a single call
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/buffer_cache_base.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
Labels: early-access-merge

#10718 qt: use larger buffer for update install
  src/yuzu/main.cpp
Labels: frontend-fix, filesystem-fix

#10693 shader_recompiler: translate f64 to f32 when unsupported on host
  src/shader_recompiler/CMakeLists.txt
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/host_translate_info.h
  src/shader_recompiler/ir_opt/lower_fp64_to_fp32.cpp
  src/shader_recompiler/ir_opt/passes.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu, early-access-merge, intel

#10699 shader_recompiler: remove barriers in conditional control flow when device lacks support
  src/shader_recompiler/CMakeLists.txt
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/host_translate_info.h
  src/shader_recompiler/ir_opt/conditional_barrier_pass.cpp
  src/shader_recompiler/ir_opt/passes.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-fix, early-access-merge, intel

#10675 image_info: adjust rescale thresholds and refactor constant use
  src/video_core/texture_cache/image_info.cpp
Labels: gpu, early-access-merge

#10747 core: decouple ARM interface from Dynarmic
  src/core/CMakeLists.txt
  src/core/arm/arm_interface.cpp
  src/core/arm/arm_interface.h
  src/core/arm/dynarmic/arm_dynarmic.h
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.h
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.h
  src/core/arm/dynarmic/dynarmic_cp15.cpp
  src/core/arm/dynarmic/dynarmic_cp15.h
  src/core/arm/dynarmic/dynarmic_exclusive_monitor.cpp
  src/core/arm/dynarmic/dynarmic_exclusive_monitor.h
  src/core/arm/exclusive_monitor.cpp
  src/core/core.cpp
  src/core/core.h
Labels: core-new

#10603 core,common: Implement missing time zone data/computations
  externals/CMakeLists.txt
  externals/nx_tzdb/CMakeLists.txt
  externals/nx_tzdb/ListFilesInDirectory.cmake
  externals/nx_tzdb/NxTzdbCreateHeader.cmake
  externals/nx_tzdb/include/nx_tzdb.h
  externals/nx_tzdb/tzdb_template.h.in
  src/common/settings.cpp
  src/common/time_zone.cpp
  src/common/time_zone.h
  src/core/CMakeLists.txt
  src/core/file_sys/system_archive/time_zone_binary.cpp
  src/core/hle/service/time/time_manager.cpp
  src/core/hle/service/time/time_manager.h
  src/core/hle/service/time/time_zone_content_manager.cpp
  src/core/hle/service/time/time_zone_manager.cpp
  src/core/hle/service/time/time_zone_manager.h
  src/core/hle/service/time/time_zone_service.cpp
  src/core/hle/service/time/time_zone_service.h
  src/yuzu/configuration/configure_system.cpp
Labels: mainline-merge

#10729 vfs_real: add file LRU cache for open file limits
  src/core/file_sys/vfs_real.cpp
  src/core/file_sys/vfs_real.h
Labels: early-access-merge, filesystem-fix

#10775 renderer_vulkan: propagate conditional barrier support
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: gpu-fix, mainline-merge

#10790 vulkan_device: disable extended_dynamic_state2 on ARM drivers
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: vulkan

#10796 android: fs: Fix Exists / IsFile for SAF.
  src/android/app/src/main/java/org/yuzu/yuzu_emu/NativeLibrary.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/DocumentsTree.kt
  src/common/fs/fs.cpp
  src/common/fs/fs_android.h
Labels: android

#10739 Re-enable SDL's `CPUinfo` subsystem
  externals/CMakeLists.txt
Labels: early-access-merge

#10731 service: nfc: Accuracy fixes
  src/core/hle/service/nfc/common/amiibo_crypto.cpp
  src/core/hle/service/nfc/common/amiibo_crypto.h
  src/core/hle/service/nfc/common/device.cpp
  src/core/hle/service/nfc/common/device.h
  src/core/hle/service/nfc/common/device_manager.cpp
  src/core/hle/service/nfc/mifare_result.h
  src/core/hle/service/nfc/nfc_interface.cpp
  src/core/hle/service/nfc/nfc_result.h
  src/core/hle/service/nfc/nfc_types.h
  src/core/hle/service/nfp/nfp_types.h
Labels: early-access-merge

#10783 video_core: preallocate fewer IR blocks
  src/video_core/renderer_opengl/gl_shader_context.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
Labels: gpu, early-access-merge

#10744 video_core: Improved anisotropic filtering heuristics
  src/video_core/renderer_opengl/gl_compute_pipeline.cpp
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/pipeline_helper.h
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/image_view_base.cpp
  src/video_core/texture_cache/image_view_base.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
  src/video_core/textures/texture.cpp
Labels: early-access-merge

#10809 Synchronize vertex buffer even when it doesn't require binding
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
Labels: early-access-merge

#10798 video_core: drawtexture support upscale
  src/video_core/engines/draw_manager.cpp
Labels: early-access-merge

#10486 yuzu-qt: Load Vulkan device info at startup
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_dialog.h
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_per_game.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/vk_device_info.cpp
  src/yuzu/vk_device_info.h
Labels: frontend-fix, mainline-merge, vulkan

#10835 vulkan_device: Restrict compute disable only to affected Intel drivers
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/vk_device_info.cpp
  src/yuzu/vk_device_info.h
Labels: early-access-merge

#10818 video_core: add samples check when find render target
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
Labels: gpu-fix, early-access-merge

#10863 time_zone_manager: Stop on comma
  src/core/hle/service/time/time_zone_manager.cpp
Labels: early-access-merge

#10841 vfs_concat: fix offset calculation when not aligned to file boundary
  src/core/file_sys/vfs_concat.cpp
Labels: early-access-merge, filesystem-fix

#10777 video_core: optionally skip barriers on feedback loops
  src/common/settings.h
  src/video_core/texture_cache/texture_cache.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
Labels: gpu, early-access-merge

#10086 core_timing: Use CNTPCT as the guest CPU tick
  src/audio_core/renderer/adsp/adsp.cpp
  src/audio_core/renderer/adsp/audio_renderer.cpp
  src/audio_core/renderer/adsp/command_list_processor.cpp
  src/audio_core/renderer/command/performance/performance.cpp
  src/audio_core/sink/sink_stream.cpp
  src/common/CMakeLists.txt
  src/common/steady_clock.cpp
  src/common/wall_clock.cpp
  src/common/wall_clock.h
  src/common/x64/cpu_detect.cpp
  src/common/x64/cpu_wait.cpp
  src/common/x64/native_clock.cpp
  src/common/x64/native_clock.h
  src/common/x64/rdtsc.cpp
  src/common/x64/rdtsc.h
  src/core/CMakeLists.txt
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/core_timing_util.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/svc/svc_info.cpp
  src/core/hle/kernel/svc/svc_tick.cpp
  src/core/hle/service/hid/hidbus.cpp
  src/core/hle/service/nvdrv/devices/nvdisp_disp0.cpp
  src/core/hle/service/nvnflinger/nvnflinger.cpp
  src/core/hle/service/time/clock_types.h
  src/core/hle/service/time/standard_steady_clock_core.cpp
  src/core/hle/service/time/tick_based_steady_clock_core.cpp
  src/core/hle/service/time/time.cpp
  src/core/hle/service/time/time_sharedmemory.cpp
  src/video_core/gpu.cpp
Labels: hle-fix, early-access-merge

#10884 vfs_real: lock concurrent accesses
  src/core/file_sys/vfs_real.cpp
  src/core/file_sys/vfs_real.h
Labels: early-access-merge, filesystem-fix

#10842 input_common: Implement native mifare/skylander support for joycons/pro controller
  src/common/input.h
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hid/input_converter.cpp
  src/core/hle/service/am/applets/applet_cabinet.cpp
  src/core/hle/service/nfc/common/device.cpp
  src/core/hle/service/nfc/common/device.h
  src/core/hle/service/nfc/common/device_manager.cpp
  src/core/hle/service/nfc/common/device_manager.h
  src/core/hle/service/nfc/mifare_types.h
  src/core/hle/service/nfc/nfc_interface.cpp
  src/input_common/drivers/joycon.cpp
  src/input_common/drivers/joycon.h
  src/input_common/drivers/virtual_amiibo.cpp
  src/input_common/drivers/virtual_amiibo.h
  src/input_common/helpers/joycon_driver.cpp
  src/input_common/helpers/joycon_driver.h
  src/input_common/helpers/joycon_protocol/joycon_types.h
  src/input_common/helpers/joycon_protocol/nfc.cpp
  src/input_common/helpers/joycon_protocol/nfc.h
  src/input_common/helpers/joycon_protocol/poller.cpp
  src/input_common/helpers/joycon_protocol/poller.h
  src/input_common/input_engine.h
  src/input_common/input_poller.cpp
  src/yuzu/main.cpp
Labels: early-access-merge

#10859 general: remove atomic signal and wait
  src/common/thread.h
  src/core/hle/service/nvnflinger/nvnflinger.cpp
  src/core/hle/service/nvnflinger/nvnflinger.h
  src/core/hle/service/server_manager.cpp
  src/core/hle/service/server_manager.h
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.h
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
Labels: early-access-merge

#10916 OpenGL: Add Local Memory warmup shader for Nvidia
  src/shader_recompiler/backend/glasm/emit_glasm.cpp
  src/shader_recompiler/ir_opt/collect_shader_info_pass.cpp
  src/shader_recompiler/shader_info.h
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/opengl_lmem_warmup.comp
  src/video_core/renderer_opengl/gl_compute_pipeline.cpp
  src/video_core/renderer_opengl/gl_compute_pipeline.h
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
  src/video_core/renderer_opengl/gl_graphics_pipeline.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
Labels: early-access-merge

#10679 Only use SDL wakelock on Linux
  src/input_common/drivers/sdl_driver.cpp
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: mainline-merge

#10495 input_common: Redesign mouse panning
  src/common/settings.h
  src/input_common/drivers/mouse.cpp
  src/input_common/drivers/mouse.h
  src/yuzu/CMakeLists.txt
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_input_advanced.cpp
  src/yuzu/configuration/configure_input_advanced.ui
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.ui
  src/yuzu/configuration/configure_mouse_panning.cpp
  src/yuzu/configuration/configure_mouse_panning.h
  src/yuzu/configuration/configure_mouse_panning.ui
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge

#10867 Use safe reads in DMA engine
  src/video_core/engines/maxwell_dma.cpp
Labels: early-access-merge

#10837 android: Mali support
  externals/CMakeLists.txt
  externals/bc_decoder/bc_decoder.cpp
  externals/bc_decoder/bc_decoder.h
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/decode_bc.cpp
  src/video_core/texture_cache/decode_bc.h
  src/video_core/texture_cache/decode_bc4.cpp
  src/video_core/texture_cache/util.cpp
  src/video_core/textures/bcn.cpp
  src/video_core/textures/bcn.h
  src/video_core/vulkan_common/vulkan_debug_callback.cpp
  src/video_core/vulkan_common/vulkan_debug_callback.h
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
  src/video_core/vulkan_common/vulkan_instance.cpp
  src/video_core/vulkan_common/vulkan_wrapper.cpp
  src/video_core/vulkan_common/vulkan_wrapper.h
Labels: gpu, early-access-merge, android-merge, android

#10937 input_common: Remove duplicated enum and fix ring detection
  src/common/input.h
  src/input_common/drivers/joycon.cpp
  src/input_common/drivers/joycon.h
  src/input_common/helpers/joycon_driver.cpp
  src/input_common/helpers/joycon_driver.h
  src/input_common/helpers/joycon_protocol/calibration.cpp
  src/input_common/helpers/joycon_protocol/calibration.h
  src/input_common/helpers/joycon_protocol/common_protocol.cpp
  src/input_common/helpers/joycon_protocol/common_protocol.h
  src/input_common/helpers/joycon_protocol/generic_functions.cpp
  src/input_common/helpers/joycon_protocol/generic_functions.h
  src/input_common/helpers/joycon_protocol/irs.cpp
  src/input_common/helpers/joycon_protocol/irs.h
  src/input_common/helpers/joycon_protocol/joycon_types.h
  src/input_common/helpers/joycon_protocol/nfc.cpp
  src/input_common/helpers/joycon_protocol/nfc.h
  src/input_common/helpers/joycon_protocol/ringcon.cpp
  src/input_common/helpers/joycon_protocol/ringcon.h
  src/input_common/helpers/joycon_protocol/rumble.cpp
  src/input_common/helpers/joycon_protocol/rumble.h
  src/yuzu/configuration/configure_ringcon.cpp
Labels: mainline-merge

#10935 x64: Make use of monitorx instructions for power efficient sleeps (AMD)
  src/common/telemetry.cpp
  src/common/x64/cpu_detect.cpp
  src/common/x64/cpu_detect.h
  src/common/x64/cpu_wait.cpp
Labels: performance, early-access-merge, amd, os-windows

#10956 AccelerateDMA: Don't accelerate 3D texture DMA operations
  src/video_core/texture_cache/texture_cache.h
Labels: gpu-fix, early-access-merge

#10953 Texture cache: Fix YFC regression due to code testing
  src/video_core/texture_cache/texture_cache.h
Labels: gpu-fix, early-access-merge
