Repository yuzu-emu/yuzu, pull requests merged in 2023-09, with the labels that each got.

#11430 shader_recompiler: fix emulation of 3D textureGrad
  src/shader_recompiler/backend/glsl/emit_glsl_image.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
Labels: gpu-fix, vulkan, early-access-merge

#11379 general: make -fwrapv generic to all architectures
  src/CMakeLists.txt
Labels: build-system-fix

#11412 vfs: ensure key area keys are validated
  src/core/file_sys/content_archive.cpp
Labels: mainline-merge, filesystem-fix

#11393 Maxwell3D: Improve Index buffer size estimation.
  src/video_core/engines/maxwell_3d.cpp
Labels: performance, gpu, early-access-merge

#11384 am: shorten shutdown timeout when lock is not held
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/am/am.cpp
  src/yuzu/main.cpp
Labels: hle-fix, mainline-merge

#11383 Fix regressions that damaged compute indirect & use reinterpret for copies with different byteblocksizes
  src/shader_recompiler/frontend/maxwell/translate/impl/move_special_register.cpp
  src/video_core/dma_pusher.cpp
  src/video_core/dma_pusher.h
  src/video_core/engines/engine_interface.h
  src/video_core/engines/engine_upload.h
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/kepler_compute.h
  src/video_core/engines/puller.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/vulkan_common/vulkan_wrapper.cpp
  src/video_core/vulkan_common/vulkan_wrapper.h
Labels: gpu-fix, early-access-merge

#11381 qt: fix romfs dumping for multiprogram applications
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: mainline-merge, filesystem-fix

#10048 core: Add support for loading NSPs with personalized tickets.
  src/core/crypto/key_manager.cpp
  src/core/crypto/key_manager.h
  src/core/file_sys/submission_package.cpp
  src/core/file_sys/submission_package.h
  src/core/hle/service/es/es.cpp
Labels: mainline-merge

#11437 qt: measure romfs dump completion by bytes read
  src/yuzu/main.cpp
Labels: frontend-fix, early-access-merge

#11467 [audio] Fix data source version 1 command looping
  src/audio_core/renderer/command/data_source/adpcm.cpp
  src/audio_core/renderer/command/data_source/decode.cpp
  src/audio_core/renderer/command/data_source/pcm_float.cpp
  src/audio_core/renderer/command/data_source/pcm_int16.cpp
Labels: audio-fix, mainline-merge

#11465 [Audio] Do not reset the remaining command count each time
  src/audio_core/adsp/apps/audio_renderer/audio_renderer.cpp
  src/audio_core/adsp/apps/audio_renderer/audio_renderer.h
  src/audio_core/adsp/apps/audio_renderer/command_list_processor.cpp
  src/audio_core/adsp/apps/audio_renderer/command_list_processor.h
  src/audio_core/renderer/system.cpp
Labels: audio-fix, mainline-merge

#11456 core: implement basic integrity verification
  src/core/loader/loader.cpp
  src/core/loader/loader.h
  src/core/loader/nca.cpp
  src/core/loader/nca.h
  src/core/loader/nsp.cpp
  src/core/loader/nsp.h
  src/core/loader/xci.cpp
  src/core/loader/xci.h
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge, filesystem-new

#11436 shader_recompiler: always declare image format for image buffers
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
Labels: gpu-fix, mainline-merge

#11450 configure_graphics: Fix handling of broken Vulkan
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/main.cpp
Labels: early-access-merge

#11459 ci: fix msvc when used with LTO
  src/CMakeLists.txt
Labels: build-system-fix, mainline-merge

#11473 am: Implement UserChannel parameters
  src/android/app/src/main/jni/native.cpp
  src/core/core.cpp
  src/core/core.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu_cmd/yuzu.cpp
Labels: hle-fix, early-access-merge

#11486 qt: add verification for installed contents
  src/core/file_sys/nca_metadata.cpp
  src/core/file_sys/nca_metadata.h
  src/core/file_sys/registered_cache.cpp
  src/core/file_sys/registered_cache.h
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: early-access-merge

#11385 internal_network: cancel pending socket operations on application process termination
  src/core/core.cpp
  src/core/internal_network/network.cpp
  src/core/internal_network/network.h
Labels: hle-fix, mainline-merge

#11435 shader_recompiler: skip sampler for buffer textures
  src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.h
Labels: gpu-fix, mainline-merge

#11479 Look for the most recently modified image for present
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge

#11496 ngc: implement service
  src/common/logging/filter.cpp
  src/common/logging/types.h
  src/core/CMakeLists.txt
  src/core/hle/service/ngc/ngc.cpp
  src/core/hle/service/ngc/ngc.h
  src/core/hle/service/ngct/ngct.cpp
  src/core/hle/service/service.cpp
Labels: hle-new, early-access-merge

#11483 am: Stub GetSaveDataSizeMax
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/sockets/bsd.cpp
Labels: early-access-merge

#11492 general: Remove uncaught usages of C++ string number conversions
  src/android/app/src/main/jni/config.cpp
  src/common/settings_common.h
  src/common/settings_setting.h
  src/core/crypto/key_manager.cpp
  src/core/file_sys/ips_layer.cpp
  src/core/memory/cheat_engine.cpp
  src/yuzu/configuration/configure_ui.cpp
  src/yuzu/configuration/shared_widget.cpp
  src/yuzu/configuration/shared_widget.h
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: early-access-merge

#11499 add std::error_code for std::filesystem exceptions
  src/common/fs/fs.cpp
Labels: mainline-merge

#11460 Reimplement HardwareOpus
  src/audio_core/CMakeLists.txt
  src/audio_core/adsp/adsp.cpp
  src/audio_core/adsp/adsp.h
  src/audio_core/adsp/apps/audio_renderer/audio_renderer.cpp
  src/audio_core/adsp/apps/audio_renderer/audio_renderer.h
  src/audio_core/adsp/apps/opus/opus_decode_object.cpp
  src/audio_core/adsp/apps/opus/opus_decode_object.h
  src/audio_core/adsp/apps/opus/opus_decoder.cpp
  src/audio_core/adsp/apps/opus/opus_decoder.h
  src/audio_core/adsp/apps/opus/opus_multistream_decode_object.cpp
  src/audio_core/adsp/apps/opus/opus_multistream_decode_object.h
  src/audio_core/adsp/apps/opus/shared_memory.h
  src/audio_core/adsp/mailbox.h
  src/audio_core/opus/decoder.cpp
  src/audio_core/opus/decoder.h
  src/audio_core/opus/decoder_manager.cpp
  src/audio_core/opus/decoder_manager.h
  src/audio_core/opus/hardware_opus.cpp
  src/audio_core/opus/hardware_opus.h
  src/audio_core/opus/parameters.h
  src/common/CMakeLists.txt
  src/common/bounded_threadsafe_queue.h
  src/core/CMakeLists.txt
  src/core/hle/result.h
  src/core/hle/service/audio/errors.h
  src/core/hle/service/audio/hwopus.cpp
  src/core/hle/service/audio/hwopus.h
Labels: audio-new, mainline-merge

#11522 registered_cache: correct file deletion case
  src/core/file_sys/registered_cache.cpp
Labels: mainline-merge, filesystem-fix

#11520 Do not consider voice commands in time estimation, fix adpcm estimate
  src/audio_core/renderer/command/command_processing_time_estimator.cpp
  src/audio_core/renderer/system.cpp
Labels: early-access-merge

#11540 aoc: stub purchase info calls
  src/core/hle/service/aoc/aoc_u.cpp
Labels: hle-fix

#11563 Fix DMA engine register offsets
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
Labels: gpu-fix, vulkan, early-access-merge

#11557 renderer_vulkan: Correct component order for A4B4G4R4_UNORM
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-fix, vulkan

#11561 am: mii_edit: Implement DB operations
  src/core/hle/service/am/applets/applet_mii_edit.cpp
  src/core/hle/service/am/applets/applet_mii_edit.h
  src/core/hle/service/mii/mii.cpp
  src/core/hle/service/mii/mii.h
  src/core/hle/service/mii/mii_manager.cpp
  src/core/hle/service/mii/types/char_info.cpp
  src/core/hle/service/mii/types/core_data.cpp
  src/core/hle/service/mii/types/raw_data.cpp
Labels: early-access-merge

#11567 emit_spirv: fix incorrect use of descriptor index in image atomics
  src/shader_recompiler/backend/spirv/emit_spirv_image_atomic.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
Labels: gpu-fix, vulkan, early-access-merge

#11165 vulkan_device: Return true if either depth/stencil format supports blit
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: vulkan, early-access-merge

#11562 vk_texture_cache: Limit srgb block to transcoding only
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: gpu-fix, vulkan, early-access-merge

#11569 service: am: Add support for LLE Mii Edit Applet
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/applet_ae.cpp
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/mii/mii_types.h
  src/core/hle/service/ns/iplatform_service_manager.cpp
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/main.ui
Labels: early-access-merge

#11225 Y.F.C: Rework the Query Cache.
  src/common/settings.cpp
  src/common/settings.h
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/buffer_cache_base.h
  src/video_core/control/channel_state_cache.h
  src/video_core/engines/draw_manager.h
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_3d.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/puller.cpp
  src/video_core/fence_manager.h
  src/video_core/gpu.cpp
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/queries_prefix_scan_sum.comp
  src/video_core/host_shaders/queries_prefix_scan_sum_nosubgroups.comp
  src/video_core/host_shaders/resolve_conditional_render.comp
  src/video_core/macro/macro_hle.cpp
  src/video_core/query_cache.h
  src/video_core/query_cache/bank_base.h
  src/video_core/query_cache/query_base.h
  src/video_core/query_cache/query_cache.h
  src/video_core/query_cache/query_cache_base.h
  src/video_core/query_cache/query_stream.h
  src/video_core/query_cache/types.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_null/null_rasterizer.cpp
  src/video_core/renderer_null/null_rasterizer.h
  src/video_core/renderer_opengl/gl_query_cache.cpp
  src/video_core/renderer_opengl/gl_query_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_fence_manager.h
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/vulkan_common/vulkan_device.h
  src/video_core/vulkan_common/vulkan_wrapper.cpp
  src/video_core/vulkan_common/vulkan_wrapper.h
Labels: gpu-new, gpu-fix, early-access-merge

#11556 renderer_vulkan: Implement MSAA image copies
  src/video_core/host_shaders/convert_msaa_to_non_msaa.comp
  src/video_core/host_shaders/convert_non_msaa_to_msaa.comp
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-fix, vulkan, early-access-merge

#11590 fsp-srv: add GetFileSystemAttribute
  src/core/hle/service/filesystem/fsp_srv.cpp
Labels: early-access-merge, filesystem-new

#11402 Vulkan: Implement Depth Bias Control
  src/common/settings.h
  src/core/core.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
  src/video_core/vulkan_common/vulkan_wrapper.cpp
  src/video_core/vulkan_common/vulkan_wrapper.h
Labels: gpu-new, gpu-fix, vulkan, early-access-merge

#11622 renderer_vulkan: fix query cache for homebrew
  src/video_core/renderer_vulkan/vk_query_cache.cpp
Labels: gpu-fix, mainline-merge, vulkan

#11546 Reduce core timing mutex contention
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hle/kernel/k_hardware_timer.cpp
Labels: performance, early-access-merge

#11493 core_timing: Replace queue with a fibonacci heap
  src/core/core_timing.cpp
  src/core/core_timing.h
  vcpkg.json
Labels: early-access-merge
