Repository yuzu-emu/yuzu, pull requests merged in 2023-07, with the labels that each got.

#10950 input_common: Tune mouse controls
  src/common/settings.h
  src/input_common/drivers/mouse.cpp
  src/input_common/drivers/mouse.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_input_player.ui
  src/yuzu/configuration/configure_mouse_panning.cpp
  src/yuzu/configuration/configure_mouse_panning.ui
Labels: early-access-merge

#10966 sink_stream: Resolve heap buffer corruption due to out of bounds write
  src/audio_core/sink/sink_stream.cpp
  src/audio_core/sink/sink_stream.h
Labels: audio-fix, mainline-merge, android-merge

#10970 general: Misc changes that did not deserve their own PRs
  src/common/ring_buffer.h
  src/common/scratch_buffer.h
  src/core/hle/service/audio/audin_u.cpp
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/hwopus.cpp
  src/core/hle/service/nvdrv/nvdrv_interface.cpp
  src/core/hle/service/nvdrv/nvdrv_interface.h
  src/core/hle/service/nvnflinger/parcel.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/host1x/codecs/codec.cpp
  src/video_core/host1x/codecs/h264.cpp
  src/video_core/host1x/codecs/h264.h
  src/video_core/host1x/codecs/vp8.cpp
  src/video_core/host1x/codecs/vp8.h
  src/video_core/host1x/codecs/vp9.cpp
  src/video_core/host1x/codecs/vp9.h
  src/video_core/host1x/codecs/vp9_types.h
Labels: general, early-access-merge

#10710 fsmitm_romfsbuild: avoid full path lookups
  src/core/file_sys/fsmitm_romfsbuild.cpp
Labels: mainline-merge, filesystem-fix

#10942 Memory Tracking: Add mechanism to register small writes when gpu page is contested by GPU
  src/core/core.cpp
  src/core/core.h
  src/core/gpu_dirty_memory_manager.h
  src/core/memory.cpp
  src/core/memory.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/buffer_cache_base.h
  src/video_core/fence_manager.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/gpu_thread.cpp
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_null/null_rasterizer.cpp
  src/video_core/renderer_null/null_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/shader_cache.cpp
  src/video_core/shader_cache.h
Labels: gpu-new, gpu-fix, early-access-merge

#10969 kernel: Synchronize
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/svc/svc_ipc.cpp
  src/core/hle/kernel/svc/svc_synchronization.cpp
Labels: kernel-fix, early-access-merge

#10479 Add support for VK_KHR_image_format_list
  src/video_core/compatible_formats.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/types.h
  src/video_core/texture_cache/util.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: vulkan, early-access-merge

#11012 Fix regression by unreal engine fix pr #11009
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge

#11006 service: nfc: Ensure controller is in the correct mode
  src/android/app/src/main/AndroidManifest.xml
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hle/service/nfc/common/device.cpp
Labels: early-access-merge

#10994 vulkan_common: use device local preferred for image memory
  src/video_core/vulkan_common/vulkan_memory_allocator.cpp
Labels: vulkan, early-access-merge

#11016 vfs_real: use open file size for getting size
  src/core/file_sys/vfs_real.cpp
Labels: mainline-merge, filesystem-fix

#11031 input_common: Avoid potential division by zero
  src/input_common/drivers/mouse.cpp
Labels: early-access-merge

#10999 main: Fix install progress calculation
  src/yuzu/main.cpp
Labels: mainline-merge

#11030 settings: Disable C++20 time zone path on MSVC
  src/common/settings.cpp
Labels: mainline-merge

#11063 arm_interface: correct breakpoint rewind condition
  src/core/arm/arm_interface.cpp
Labels: core-fix, mainline-merge

#11055 settings: Catch runtime error from STL
  src/common/settings.cpp
Labels: mainline-merge

#11050 input_common: set `SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS` to 0
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/drivers/sdl_driver.h
Labels: mainline-merge

#10996 Use spans over guest memory where possible instead of copying data
  src/audio_core/device/device_session.cpp
  src/audio_core/renderer/command/data_source/decode.cpp
  src/audio_core/renderer/command/effect/aux_.cpp
  src/common/page_table.cpp
  src/common/page_table.h
  src/common/scratch_buffer.h
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/hle/service/hle_ipc.cpp
  src/core/memory.cpp
  src/core/memory.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/dma_pusher.cpp
  src/video_core/engines/engine_upload.cpp
  src/video_core/engines/kepler_compute.cpp
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/sw_blitter/blitter.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/util.cpp
  src/video_core/texture_cache/util.h
Labels: gpu-fix, early-access-merge

#10985 k_server_session: translate special header for non-HLE requests
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/message_buffer.h
Labels: kernel-fix, early-access-merge

#11047 file_sys/content_archive: Detect compressed NCAs
  src/core/file_sys/content_archive.cpp
  src/core/loader/loader.h
Labels: early-access-merge

#10912 Implement SSL service
  CMakeLists.txt
  src/common/socket_types.h
  src/core/CMakeLists.txt
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/sockets/bsd.h
  src/core/hle/service/sockets/nsd.cpp
  src/core/hle/service/sockets/nsd.h
  src/core/hle/service/sockets/sfdnsres.cpp
  src/core/hle/service/sockets/sfdnsres.h
  src/core/hle/service/sockets/sockets.h
  src/core/hle/service/sockets/sockets_translate.cpp
  src/core/hle/service/sockets/sockets_translate.h
  src/core/hle/service/ssl/ssl.cpp
  src/core/hle/service/ssl/ssl_backend.h
  src/core/hle/service/ssl/ssl_backend_none.cpp
  src/core/hle/service/ssl/ssl_backend_openssl.cpp
  src/core/hle/service/ssl/ssl_backend_schannel.cpp
  src/core/hle/service/ssl/ssl_backend_securetransport.cpp
  src/core/internal_network/network.cpp
  src/core/internal_network/network.h
  src/core/internal_network/socket_proxy.cpp
  src/core/internal_network/socket_proxy.h
  src/core/internal_network/sockets.h
Labels: mainline-merge

#11096 service: nfc: Update Implementation to match with latest RE
  src/core/hle/service/nfc/common/amiibo_crypto.cpp
  src/core/hle/service/nfc/common/amiibo_crypto.h
  src/core/hle/service/nfc/common/device.cpp
  src/core/hle/service/nfc/common/device_manager.cpp
  src/core/hle/service/nfc/common/device_manager.h
  src/core/hle/service/nfc/nfc_interface.cpp
  src/core/hle/service/nfc/nfc_result.h
Labels: early-access-merge

#11069 common: Use arithmetic instead of string ops to get time zone
  src/common/settings.cpp
  src/common/time_zone.cpp
Labels: early-access-merge

#11113 nsd: add GetApplicationServerEnvironmentType
  src/core/hle/service/sockets/nsd.cpp
  src/core/hle/service/sockets/nsd.h
Labels: hle-new, mainline-merge

#11098 buffer_cache: Increase number of texture buffers
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/buffer_cache_base.h
Labels: mainline-merge

#11094 kernel: misc cleanup of page table accessors
  src/core/debugger/gdbstub.cpp
  src/core/hle/kernel/k_code_memory.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_shared_memory.cpp
  src/core/hle/kernel/k_thread_local_page.cpp
  src/core/hle/kernel/svc/svc_cache.cpp
  src/core/hle/kernel/svc/svc_code_memory.cpp
  src/core/hle/kernel/svc/svc_device_address_space.cpp
  src/core/hle/kernel/svc/svc_info.cpp
  src/core/hle/kernel/svc/svc_memory.cpp
  src/core/hle/kernel/svc/svc_physical_memory.cpp
  src/core/hle/kernel/svc/svc_process.cpp
  src/core/hle/kernel/svc/svc_process_memory.cpp
  src/core/hle/kernel/svc/svc_query_memory.cpp
  src/core/hle/kernel/svc/svc_shared_memory.cpp
  src/core/hle/kernel/svc/svc_thread.cpp
  src/core/hle/kernel/svc/svc_transfer_memory.cpp
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/nvdrv/devices/nvmap.cpp
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/kip.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
  src/core/memory.cpp
  src/core/memory/cheat_engine.cpp
  src/core/reporter.cpp
Labels: mainline-merge

#11042 ci/linux: Target deploy script from appimage path
  .ci/scripts/linux/docker.sh
Labels: early-access-merge

#11136 ssa_rewrite_pass: use proper maps
  src/shader_recompiler/ir_opt/ssa_rewrite_pass.cpp
Labels: performance, early-access-merge

#11135 core: implement GetGaiStringErrorRequest, IContextRegistrar
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/glue/ectx.cpp
  src/core/hle/service/glue/ectx.h
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/sockets/nsd.cpp
  src/core/hle/service/sockets/nsd.h
  src/core/hle/service/sockets/sfdnsres.cpp
  src/core/hle/service/sockets/sfdnsres.h
  src/core/hle/service/sockets/sockets_translate.cpp
  src/core/hle/service/sockets/sockets_translate.h
Labels: hle-new, hle-fix, early-access-merge

#11095 memory: cleanup
  src/core/debugger/gdbstub.cpp
  src/core/hle/kernel/svc/svc_ipc.cpp
  src/core/hle/kernel/svc/svc_synchronization.cpp
  src/core/memory.cpp
  src/core/memory.h
Labels: core-fix, early-access-merge

#11142 yuzu: Avoid reading broken games
  src/yuzu/game_list_worker.cpp
Labels: early-access-merge

#10990 Fixes and workarounds to make UBSan happier on macOS
  src/common/page_table.h
  src/core/arm/arm_interface.cpp
  src/core/arm/arm_interface.h
  src/core/hle/kernel/k_auto_object.cpp
  src/core/hle/kernel/k_auto_object.h
  src/core/hle/kernel/k_scheduler.cpp
  src/core/hle/kernel/k_thread.cpp
  src/core/memory.cpp
  src/video_core/query_cache.h
  src/video_core/rasterizer_accelerated.cpp
  src/video_core/rasterizer_accelerated.h
Labels: mainline-merge

#11128 yuzu: Replace httplib with QtNetworkRequest
  src/yuzu/discord_impl.cpp
  src/yuzu/discord_impl.h
Labels: early-access-merge

#11163 Revert "Blacklist EDS3 blending from new AMD drivers"
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: early-access-merge

#11155 memory: check page against address space size
  src/core/memory.cpp
Labels: early-access-merge

#11182 Revert the Revert! Reverts the Revert of "Blacklist EDS3 blending from new AMD drivers"
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: mainline-merge, vulkan, amd

#11186 tz_content_man: Generate the time zone binary once
  src/core/hle/service/time/time_zone_content_manager.cpp
  src/core/hle/service/time/time_zone_content_manager.h
Labels: early-access-merge

#11169 vk_descriptor_pool: Disallow descriptor set free
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_descriptor_pool.cpp
  src/video_core/renderer_vulkan/vk_fsr.cpp
  src/video_core/renderer_vulkan/vk_turbo_mode.cpp
Labels: early-access-merge
