Repository yuzu-emu/yuzu, pull requests merged in 2023-11, with the labels that each got.

#11936 romfs: fix extraction of single-directory root
  src/core/file_sys/romfs.cpp
  src/core/file_sys/romfs.h
  src/core/hle/service/am/applets/applet_web_browser.cpp
  src/yuzu/main.cpp
Labels: early-access-merge, filesystem-fix

#11943 renderer_vulkan: minimize transform feedback support log
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: mainline-merge, android-merge

#11881 sockets: use safe access helpers
  src/core/hle/service/sockets/bsd.cpp
  src/core/hle/service/sockets/bsd.h
Labels: hle-fix, mainline-merge

#11952 opus: Allow 0 stereo count
  src/audio_core/adsp/apps/opus/opus_decoder.cpp
  src/audio_core/opus/decoder_manager.cpp
Labels: audio-fix, mainline-merge

#11961 yuzu: Only store games in the recently played list
  src/core/hle/service/am/applets/applets.h
  src/yuzu/main.cpp
Labels: frontend-fix, mainline-merge

#11957 renderer_null: fix
  src/video_core/renderer_null/null_rasterizer.cpp
Labels: gpu-fix, mainline-merge

#11894 renderer_vulkan: render on bottom of surface clip when flipped
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: gpu-fix, mainline-merge, vulkan

#11873 nvdrv: add ioctl command serialization wrapper
  src/core/hle/service/nvdrv/devices/ioctl_serialization.h
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl.h
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_ctrl_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.h
  src/core/hle/service/nvdrv/devices/nvhost_nvdec.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.h
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvjpg.h
  src/core/hle/service/nvdrv/devices/nvhost_vic.cpp
  src/core/hle/service/nvdrv/devices/nvmap.cpp
  src/core/hle/service/nvdrv/devices/nvmap.h
  src/core/hle/service/nvnflinger/fb_share_buffer_manager.cpp
Labels: mainline-merge

#11896 renderer_vulkan: fix cropping for presentation
  src/core/hle/service/nvnflinger/buffer_transform_flags.h
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_fsr.cpp
  src/video_core/renderer_vulkan/vk_fsr.h
Labels: gpu-fix, mainline-merge, vulkan

#11914 kernel: add KPageTableBase
  src/common/page_table.cpp
  src/common/page_table.h
  src/core/CMakeLists.txt
  src/core/debugger/gdbstub.cpp
  src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
  src/core/hle/kernel/board/nintendo/nx/k_system_control.h
  src/core/hle/kernel/k_capabilities.cpp
  src/core/hle/kernel/k_capabilities.h
  src/core/hle/kernel/k_device_address_space.cpp
  src/core/hle/kernel/k_device_address_space.h
  src/core/hle/kernel/k_memory_layout.h
  src/core/hle/kernel/k_memory_manager.cpp
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/k_page_table_base.cpp
  src/core/hle/kernel/k_page_table_base.h
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_process_page_table.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_system_resource.cpp
  src/core/hle/kernel/k_thread_local_page.cpp
  src/core/hle/kernel/process_capability.cpp
  src/core/hle/kernel/process_capability.h
  src/core/hle/kernel/svc/svc_memory.cpp
  src/core/hle/kernel/svc/svc_physical_memory.cpp
  src/core/hle/kernel/svc/svc_process_memory.cpp
  src/core/hle/kernel/svc/svc_query_memory.cpp
  src/core/hle/result.h
  src/core/hle/service/ldr/ldr.cpp
  src/core/memory.cpp
Labels: kernel-new, kernel-fix, mainline-merge

#12004 k_capabilities: ignore map region when KTrace is disabled
  src/core/hle/kernel/k_capabilities.cpp
Labels: kernel-fix, mainline-merge

#11980 service: irs: Implement moment image processor
  src/core/hle/service/hid/irs.cpp
  src/core/hle/service/hid/irsensor/clustering_processor.cpp
  src/core/hle/service/hid/irsensor/clustering_processor.h
  src/core/hle/service/hid/irsensor/image_transfer_processor.cpp
  src/core/hle/service/hid/irsensor/moment_processor.cpp
  src/core/hle/service/hid/irsensor/moment_processor.h
Labels: early-access-merge

#11990 yuzu: Save mute when in background setting
  src/common/settings.cpp
  src/common/settings.h
  src/common/settings_common.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/main.cpp
  src/yuzu/uisettings.h
Labels: frontend-fix, early-access-merge

#12019 audio_core: ignore renderer wait when stream is paused
  src/audio_core/sink/cubeb_sink.cpp
  src/audio_core/sink/sdl2_sink.cpp
  src/audio_core/sink/sink_stream.cpp
  src/audio_core/sink/sink_stream.h
Labels: audio-fix, early-access-merge

#12025 core: check for thread dpc before eret
  src/core/arm/arm_interface.cpp
Labels: core-fix

#12028 core_timing: lock event queue access
  src/core/core_timing.cpp
  src/core/core_timing.h
Labels: core-fix

#12007 core: hid: Split SL and SR buttons
  src/common/settings_input.cpp
  src/common/settings_input.h
  src/core/hid/emulated_controller.cpp
  src/core/hle/service/hid/controllers/npad.cpp
  src/input_common/drivers/gc_adapter.cpp
  src/input_common/drivers/joycon.cpp
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/drivers/sdl_driver.h
  src/input_common/drivers/udp_client.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player.ui
  src/yuzu/configuration/configure_input_player_widget.cpp
Labels: mainline-merge

#11995 Revert PR #11806 and do a proper fix to the memory handling.
  src/core/memory.cpp
  src/video_core/fence_manager.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
Labels: gpu-fix, mainline-merge

#11917 nvnflinger: implement consumer abandonment
  src/core/hle/service/nvnflinger/buffer_queue_consumer.cpp
  src/core/hle/service/nvnflinger/buffer_queue_consumer.h
  src/core/hle/service/nvnflinger/buffer_queue_core.cpp
  src/core/hle/service/nvnflinger/buffer_queue_core.h
  src/core/hle/service/nvnflinger/consumer_base.cpp
  src/core/hle/service/nvnflinger/consumer_base.h
  src/core/hle/service/nvnflinger/nvnflinger.cpp
  src/core/hle/service/nvnflinger/nvnflinger.h
Labels: hle-fix, mainline-merge

#11912 nvnflinger: use graphic buffer lifetime for map handle
  src/core/CMakeLists.txt
  src/core/hle/service/nvnflinger/buffer_item.h
  src/core/hle/service/nvnflinger/buffer_queue_consumer.cpp
  src/core/hle/service/nvnflinger/buffer_queue_consumer.h
  src/core/hle/service/nvnflinger/buffer_queue_producer.cpp
  src/core/hle/service/nvnflinger/buffer_queue_producer.h
  src/core/hle/service/nvnflinger/buffer_slot.h
  src/core/hle/service/nvnflinger/fb_share_buffer_manager.cpp
  src/core/hle/service/nvnflinger/status.h
  src/core/hle/service/nvnflinger/ui/graphic_buffer.cpp
  src/core/hle/service/nvnflinger/ui/graphic_buffer.h
  src/core/hle/service/vi/display/vi_display.cpp
Labels: hle-fix, mainline-merge

#12058 opus: fix stereo stream count check in multistream decoder object
  src/audio_core/adsp/apps/opus/opus_multistream_decode_object.cpp
  src/audio_core/opus/decoder.cpp
Labels: audio-fix, mainline-merge

#12072 Buffer Cache: Eliminate clears on Indirect buffers
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/maxwell_3d.cpp
Labels: gpu-fix, mainline-merge

#12068 gl_graphics_pipeline: GLASM: Fix transform feedback attribs buffer mode
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
  src/video_core/renderer_opengl/gl_graphics_pipeline.h
Labels: gpu-fix, early-access-merge

#12066 shader_recompiler: add byteswap pattern workaround for Nvidia
  src/shader_recompiler/CMakeLists.txt
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/ir_opt/passes.h
  src/shader_recompiler/ir_opt/vendor_workaround_pass.cpp
Labels: gpu-fix, mainline-merge, nvidia

#11792 Improved shortcut: add games in applist for Windows, question for sta…
  src/yuzu/game_list.cpp
  src/yuzu/main.cpp
  src/yuzu/main.h
  src/yuzu/util/util.cpp
  src/yuzu/util/util.h
Labels: frontend-new, early-access-merge

#12036 Query Cache: Disable write syncing on Android
  src/video_core/renderer_vulkan/vk_query_cache.cpp
Labels: android-merge

#12081 Vulkan: Be more generous with pipeline workers for Android
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-fix, android-merge

#12085 qt: fix linux build
  src/yuzu/util/util.cpp
Labels: frontend-fix, mainline-merge

#12083 renderer_vulkan: ignore viewport stores on non-supporting drivers
  src/shader_recompiler/backend/spirv/emit_spirv.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
  src/shader_recompiler/profile.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: gpu-fix, android-merge

#12076 service: hid: Create appropriate hid resources
  src/core/CMakeLists.txt
  src/core/hid/emulated_controller.cpp
  src/core/hid/hid_core.cpp
  src/core/hid/hid_types.h
  src/core/hid/input_interpreter.cpp
  src/core/hid/input_interpreter.h
  src/core/hle/service/hid/controllers/console_six_axis.cpp
  src/core/hle/service/hid/controllers/console_six_axis.h
  src/core/hle/service/hid/controllers/debug_pad.cpp
  src/core/hle/service/hid/controllers/debug_pad.h
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/gesture.h
  src/core/hle/service/hid/controllers/keyboard.cpp
  src/core/hle/service/hid/controllers/keyboard.h
  src/core/hle/service/hid/controllers/mouse.cpp
  src/core/hle/service/hid/controllers/mouse.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/controllers/palma.cpp
  src/core/hle/service/hid/controllers/palma.h
  src/core/hle/service/hid/controllers/seven_six_axis.cpp
  src/core/hle/service/hid/controllers/seven_six_axis.h
  src/core/hle/service/hid/controllers/six_axis.cpp
  src/core/hle/service/hid/controllers/six_axis.h
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
  src/core/hle/service/hid/controllers/xpad.cpp
  src/core/hle/service/hid/controllers/xpad.h
  src/core/hle/service/hid/hid_server.cpp
  src/core/hle/service/hid/hid_system_server.cpp
  src/core/hle/service/hid/hid_util.h
  src/core/hle/service/hid/irs.cpp
  src/core/hle/service/hid/resource_manager.cpp
  src/core/hle/service/hid/resource_manager.h
  src/core/hle/service/nfc/common/device_manager.cpp
  src/core/memory/cheat_engine.cpp
Labels: early-access-merge

#12140 query_cache: demote report synced unreachable to assert
  src/video_core/query_cache/query_cache.h
Labels: gpu-fix, android-merge

#12110 vk_texture_cache: add workaround for nullDescriptor on Mali
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
Labels: gpu-fix, android-merge, android

#12153 renderer_vulkan: exclude steam deck oled from force max clock setting
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: vulkan

#12156 yuzu: Display firmware version
  src/core/hle/service/set/set_sys.cpp
  src/core/hle/service/set/set_sys.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#12180 service: am: Create random mii for cabinet applet
  src/core/hle/service/am/applets/applet_cabinet.cpp
Labels: hle-fix, mainline-merge

#11535 renderer_vulkan: Introduce separate cmd buffer for uploads
  src/common/settings.h
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/buffer_cache_base.h
  src/video_core/buffer_cache/usage_tracker.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_smaa.cpp
  src/video_core/renderer_vulkan/vk_staging_buffer_pool.h
  src/video_core/texture_cache/slot_vector.h
  src/video_core/vulkan_common/vulkan_wrapper.h
  src/yuzu/configuration/configure_debug.cpp
  src/yuzu/configuration/configure_debug.ui
Labels: performance, gpu, vulkan, early-access-merge, android-merge

#12183 service: nfc: Validate mii data
  src/core/hle/service/am/applets/applet_cabinet.cpp
  src/core/hle/service/mii/types/ver3_store_data.cpp
  src/core/hle/service/nfc/common/device.cpp
  src/core/hle/service/nfc/common/device.h
Labels: mainline-merge, input

#11902 shader_recompiler: Align SSBO offsets to meet host requirements
  src/shader_recompiler/backend/glasm/emit_glasm_memory.cpp
  src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/host_translate_info.h
  src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp
  src/shader_recompiler/ir_opt/passes.h
  src/shader_recompiler/profile.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: gpu-fix, mainline-merge

#12154 vulkan_device: add names for more driverID enumeration values
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: mainline-merge

#12201 Fixed controller applet crashing when on FW17+
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/hle/service/hid/controllers/touchscreen.h
  src/core/hle/service/hid/hid_server.cpp
  src/core/hle/service/hid/hid_server.h
Labels: mainline-merge, service-implementation

#12203 set: don't load version nca with null romfs
  src/core/hle/service/set/set_sys.cpp
Labels: mainline-merge

#12204 android: Multi directory UI
  src/android/app/src/main/java/org/yuzu/yuzu_emu/adapters/FolderAdapter.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsActivity.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsAdapter.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AddGameFolderDialogFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GameFolderPropertiesDialogFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GameFoldersFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SettingsDialogFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SetupFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/model/GameDir.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/model/GamesViewModel.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/model/HomeViewModel.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/model/SettingsViewModel.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/main/MainActivity.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/FileUtil.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/GameHelper.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/NativeConfig.kt
  src/android/app/src/main/jni/android_config.cpp
  src/android/app/src/main/jni/android_config.h
  src/android/app/src/main/jni/android_settings.h
  src/android/app/src/main/jni/id_cache.cpp
  src/android/app/src/main/jni/id_cache.h
  src/android/app/src/main/jni/native_config.cpp
  src/android/app/src/main/res/layout/card_folder.xml
  src/android/app/src/main/res/layout/dialog_add_folder.xml
  src/android/app/src/main/res/layout/dialog_folder_properties.xml
  src/android/app/src/main/res/layout/fragment_folders.xml
  src/android/app/src/main/res/navigation/home_navigation.xml
  src/android/app/src/main/res/values/dimens.xml
  src/android/app/src/main/res/values/strings.xml
  src/frontend_common/config.cpp
Labels: android-merge

#12229 renderer_vulkan: exclude more qcom drivers from extensions
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: android
