Repository yuzu-emu/yuzu, pull requests merged in 2023-08, with the labels that each got.

#11195 audren_u: Fix parameter alignment
  src/core/hle/service/audio/audren_u.cpp
Labels: mainline-merge

#11204 vulkan_device: disable EDS3 blending on all AMD drivers
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: vulkan, amd

#11208 service: am: Fix wrong interface ILibraryAppletSelfAccessor
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/applet_ae.cpp
Labels: early-access-merge

#11210 service: set: Implement system settings for Qlaunch
  src/core/hle/service/am/am.h
  src/core/hle/service/set/set.cpp
  src/core/hle/service/set/set.h
  src/core/hle/service/set/set_sys.cpp
  src/core/hle/service/set/set_sys.h
Labels: early-access-merge

#11212 Fix various misc pipeline/shader things
  src/shader_recompiler/environment.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/shader_cache.cpp
  src/video_core/shader_cache.h
  src/video_core/shader_environment.cpp
  src/video_core/shader_environment.h
Labels: gpu-fix, early-access-merge

#11224 service: audctl: Stub functions needed by Qlaunch
  src/core/hle/service/audio/audctl.cpp
  src/core/hle/service/audio/audctl.h
Labels: early-access-merge

#11217 service: olsc: Implement IOlscServiceForSystemService ITransferTaskListController interfaces for QLaunch
  src/core/hle/service/olsc/olsc.cpp
Labels: early-access-merge

#11247 service: pctl: Partially revert 11221
  src/core/hle/service/pctl/pctl_module.cpp
Labels: early-access-merge

#11093 core: remove ResultVal type
  src/core/file_sys/romfs_factory.cpp
  src/core/file_sys/romfs_factory.h
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/core/file_sys/sdmc_factory.cpp
  src/core/file_sys/sdmc_factory.h
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/result.h
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/filesystem/filesystem.cpp
  src/core/hle/service/filesystem/filesystem.h
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/glue/arp.cpp
  src/core/hle/service/glue/glue_manager.cpp
  src/core/hle/service/glue/glue_manager.h
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/mii/mii.cpp
  src/core/hle/service/mii/mii_manager.cpp
  src/core/hle/service/mii/mii_manager.h
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/ns.h
  src/core/hle/service/nvnflinger/nvnflinger.cpp
  src/core/hle/service/nvnflinger/nvnflinger.h
  src/core/hle/service/server_manager.cpp
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
  src/core/hle/service/sockets/nsd.cpp
  src/core/hle/service/spl/spl_module.cpp
  src/core/hle/service/spl/spl_module.h
  src/core/hle/service/ssl/ssl.cpp
  src/core/hle/service/ssl/ssl_backend.h
  src/core/hle/service/ssl/ssl_backend_none.cpp
  src/core/hle/service/ssl/ssl_backend_openssl.cpp
  src/core/hle/service/ssl/ssl_backend_schannel.cpp
  src/core/hle/service/ssl/ssl_backend_securetransport.cpp
  src/core/hle/service/vi/display/vi_display.cpp
  src/core/hle/service/vi/display/vi_display.h
  src/core/hle/service/vi/vi.cpp
Labels: early-access-merge

#11253 general: fix apple clang build
  src/common/settings_common.cpp
  src/common/settings_enums.h
  src/common/settings_setting.h
  src/core/memory.h
  src/video_core/engines/maxwell_dma.cpp
Labels: early-access-merge

#11219 Allow searching by a substring of the title ID
  src/yuzu/game_list.cpp
Labels: early-access-merge

#11263 vulkan_device: disable features associated with unloaded extensions
  src/video_core/vulkan_common/vulkan_device.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: vulkan, early-access-merge

#11281 nvnflinger: add missing scale mode
  src/core/hle/service/nvnflinger/buffer_queue_producer.cpp
  src/core/hle/service/nvnflinger/window.h
Labels: hle-fix, early-access-merge

#11283 gl_graphics_pipeline: Fix GLASM storage buffer detection
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
Labels: early-access-merge

#11282 gl_graphics_pipeline: GLASM: Fix transform feedback with multiple buffers
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
  src/video_core/renderer_opengl/gl_graphics_pipeline.h
Labels: early-access-merge

#11287 gdbstub: fixup replaced instruction bytes in memory reads
  src/core/debugger/gdbstub.cpp
Labels: core-fix

#10989 sockets: Improve behavior when sending to closed connection
  src/core/hle/service/sockets/sockets.h
  src/core/hle/service/sockets/sockets_translate.cpp
  src/core/internal_network/network.cpp
  src/core/internal_network/network.h
Labels: early-access-merge

#11310 video_core: Fix vulkan format assert error
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: vulkan

#11288 kernel: remove relative task registration
  src/core/hle/kernel/k_hardware_timer.h
  src/core/hle/kernel/k_resource_limit.cpp
  src/core/hle/kernel/k_resource_limit.h
  src/core/hle/kernel/k_scoped_scheduler_lock_and_sleep.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/svc/svc_address_arbiter.cpp
  src/core/hle/kernel/svc/svc_condition_variable.cpp
  src/core/hle/kernel/svc/svc_ipc.cpp
  src/core/hle/kernel/svc/svc_resource_limit.cpp
  src/core/hle/kernel/svc/svc_synchronization.cpp
  src/core/hle/kernel/svc/svc_thread.cpp
Labels: kernel-fix, early-access-merge

#11278 Mark accelerated DMA destination buffers and images as GPU-modified
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/texture_cache/texture_cache_base.h
Labels: gpu-fix, early-access-merge

#11320 Support masked depthstencil clears
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/vulkan_depthstencil_clear.frag
  src/video_core/renderer_vulkan/blit_image.cpp
  src/video_core/renderer_vulkan/blit_image.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: gpu-fix, mainline-merge, vulkan

#11149 host_shaders: ASTC compute shader optimizations
  src/video_core/host_shaders/astc_decoder.comp
  src/video_core/renderer_opengl/util_shaders.cpp
Labels: performance, gpu, mainline-merge

#11342 patch_manager: apply manual HTML patches when present
  src/core/file_sys/patch_manager.cpp
Labels: filesystem-fix

#11309 file_sys/card_image: support dumps with prepended key area
  src/core/file_sys/card_image.cpp
  src/core/file_sys/card_image.h
Labels: early-access-merge, filesystem-fix, filesystem-new

#11375 nvhost_as_gpu: ensure mappings are aligned to big page size when deallocated
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
Labels: gpu-fix

#11326 kernel: offset code entry point for 39-bit address space type
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/loader/deconstructed_rom_directory.cpp
  src/core/loader/kip.cpp
  src/core/loader/nro.cpp
  src/core/loader/nso.cpp
  src/core/reporter.cpp
Labels: early-access-merge

#11319 registered_cache: create fake CNMT entries for program updates of multiprogram applications
  src/core/file_sys/registered_cache.cpp
Labels: early-access-merge, filesystem-fix, filesystem-new

#11328 ssl: tolerate handshake without hostname set
  src/core/hle/service/ssl/ssl.cpp
  src/core/hle/service/ssl/ssl_backend_openssl.cpp
  src/core/hle/service/ssl/ssl_backend_schannel.cpp
Labels: hle-fix, early-access-merge

#11371 yuzu/main: Ensure NCAs are registered in content provider when launching from CLI
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#11370 filesystem: Return correct error for RenameFile when dest_path already exists
  src/core/hle/service/filesystem/filesystem.cpp
Labels: early-access-merge

#11359 Pre-test for valid audio backends
  src/audio_core/sink/cubeb_sink.cpp
  src/audio_core/sink/cubeb_sink.h
  src/audio_core/sink/sdl2_sink.cpp
  src/audio_core/sink/sdl2_sink.h
  src/audio_core/sink/sink_details.cpp
Labels: early-access-merge

#11356 general,config-qt: Present Console Mode as an enum with separate options in game properties
  src/android/app/src/main/jni/config.cpp
  src/android/app/src/main/jni/native.cpp
  src/common/settings.cpp
  src/common/settings.h
  src/common/settings_common.h
  src/common/settings_enums.h
  src/core/frontend/applets/controller.cpp
  src/core/frontend/framebuffer_layout.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/apm/apm_controller.cpp
  src/core/hle/service/hid/controllers/gesture.cpp
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/vi/vi.cpp
  src/core/telemetry_session.cpp
  src/yuzu/applets/qt_controller.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_input.cpp
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/shared_translation.cpp
  src/yuzu/configuration/shared_widget.cpp
  src/yuzu/configuration/shared_widget.h
  src/yuzu/main.cpp
Labels: early-access-merge

#11389 Buffer Cache: fix discard writes.
  src/video_core/buffer_cache/buffer_cache.h
Labels: gpu-fix

#11399 audio: allow more latency in cubeb initialization
  src/audio_core/sink/cubeb_sink.cpp
  src/audio_core/sink/sink_details.cpp
Labels: audio-fix, mainline-merge

#11390 hwopus: Implement OpenHardwareOpusDecoderForMultiStreamEx and DecodeInterleavedForMultiStream
  src/core/hle/service/audio/hwopus.cpp
  src/core/hle/service/audio/hwopus.h
Labels: audio-fix, early-access-merge

#11112 Use initial_frame to check interlaced flag
  externals/ffmpeg/CMakeLists.txt
  src/video_core/host1x/codecs/codec.cpp
Labels: early-access-merge

#11409 sfdnsres: ensure lp1 is not resolved
  src/core/hle/service/sockets/nsd.cpp
  src/core/hle/service/sockets/sfdnsres.cpp
Labels: hle-fix, early-access-merge
