Repository yuzu-emu/yuzu, pull requests merged in 2023-05, with the labels that each got.

#10116 kernel: remove boost intrusive lists
  src/common/intrusive_list.h
  src/core/hle/kernel/k_event_info.h
  src/core/hle/kernel/k_object_name.h
  src/core/hle/kernel/k_server_port.h
  src/core/hle/kernel/k_server_session.h
  src/core/hle/kernel/k_session_request.h
  src/core/hle/kernel/k_shared_memory_info.h
  src/core/hle/kernel/k_thread.h
Labels: early-access-merge

#10084 Y.F.C Buffer Cache Revamp
  src/tests/CMakeLists.txt
  src/tests/video_core/buffer_base.cpp
  src/tests/video_core/memory_tracker.cpp
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_base.h
  src/video_core/buffer_cache/buffer_cache.cpp
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/buffer_cache_base.h
  src/video_core/buffer_cache/memory_tracker_base.h
  src/video_core/buffer_cache/word_manager.h
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache_base.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_buffer_cache_base.cpp
Labels: gpu-new, gpu-fix, performance, early-access-merge

#10123 Define SampleMask as an array
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
Labels: early-access-merge

#10130 qt: warn on inoperable keys
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#9973 Implement asynchronous presentation
  src/common/settings.cpp
  src/common/settings.h
  src/video_core/CMakeLists.txt
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.h
  src/video_core/renderer_vulkan/vk_blit_screen.cpp
  src/video_core/renderer_vulkan/vk_blit_screen.h
  src/video_core/renderer_vulkan/vk_present_manager.cpp
  src/video_core/renderer_vulkan/vk_present_manager.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
  src/video_core/renderer_vulkan/vk_update_descriptor.cpp
  src/video_core/renderer_vulkan/vk_update_descriptor.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: gpu-fix, mainline-merge

#10124 settings: rename extended memory layout to unsafe, move from general to system
  src/common/settings.cpp
  src/common/settings.h
  src/core/core.cpp
  src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.h
  src/yuzu/configuration/configure_general.ui
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_system.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: mainline-merge

#10151 Fix softlocks when disabling async present
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_present_manager.cpp
  src/video_core/renderer_vulkan/vk_present_manager.h
Labels: mainline-merge

#10117 kernel: match calls to Register and Unregister
  src/core/core.cpp
  src/core/hle/kernel/k_auto_object.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/service/ipc_helpers.h
  src/core/hle/service/kernel_helpers.cpp
  src/core/hle/service/mutex.cpp
  src/core/hle/service/server_manager.cpp
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm_controller.cpp
Labels: kernel-fix, early-access-merge

#10088 Y.F.C Implement Asynchronous Fence manager and Rework Query async downloads
  src/core/memory.cpp
  src/video_core/fence_manager.h
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
  src/video_core/query_cache.h
  src/video_core/renderer_opengl/gl_fence_manager.h
  src/video_core/renderer_opengl/gl_query_cache.cpp
  src/video_core/renderer_opengl/gl_query_cache.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.cpp
  src/video_core/renderer_vulkan/vk_fence_manager.h
  src/video_core/renderer_vulkan/vk_query_cache.cpp
  src/video_core/renderer_vulkan/vk_query_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: performance, gpu, mainline-merge

#10142 GPU: implement missing ASTC
  src/video_core/compatible_formats.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/maxwell_to_gl.h
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/surface.cpp
  src/video_core/surface.h
  src/video_core/texture_cache/format_lookup_table.cpp
  src/video_core/texture_cache/formatter.h
Labels: gpu-new, gpu-fix, early-access-merge

#10153 Memory manager: Fix possible softlock
  src/video_core/memory_manager.cpp
Labels: gpu-fix, mainline-merge

#10145 Fix shader code resize to use word size rather than byte size
  src/video_core/shader_cache.cpp
  src/video_core/shader_environment.cpp
  src/video_core/shader_environment.h
Labels: early-access-merge

#10128 Wait for the terminate event before destroying a system instance
  src/audio_core/renderer/system.cpp
Labels: early-access-merge

#10178 Fix read access violation after 2 hours of gameplay in PMD: RTDX
  src/common/address_space.inc
Labels: early-access-merge

#10125 configuration: Expose separate swap present modes
  src/common/settings.cpp
  src/common/settings.h
  src/core/telemetry_session.cpp
  src/video_core/renderer_vulkan/renderer_vulkan.cpp
  src/video_core/renderer_vulkan/vk_swapchain.cpp
  src/video_core/renderer_vulkan/vk_swapchain.h
  src/video_core/vulkan_common/vulkan_surface.cpp
  src/video_core/vulkan_common/vulkan_surface.h
  src/yuzu/CMakeLists.txt
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_graphics.ui
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/qt_common.cpp
  src/yuzu/qt_common.h
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: frontend-fix, gpu-fix

#10172 Log object names with debug renderer, add a GPU address to ImageViews
  src/video_core/renderer_opengl/gl_device.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/formatter.cpp
  src/video_core/texture_cache/formatter.h
  src/video_core/texture_cache/image_view_base.cpp
  src/video_core/texture_cache/image_view_base.h
  src/video_core/vulkan_common/vulkan_device.h
Labels: early-access-merge

#10081 Sort overlap_ids by modification tick before copy
  src/video_core/texture_cache/texture_cache.h
Labels: early-access-merge

#10155 Y.F.C. bring back Reactive Flushing
  src/common/settings.cpp
  src/common/settings.h
  src/core/core.cpp
  src/core/core.h
  src/core/memory.cpp
  src/tests/video_core/memory_tracker.cpp
  src/video_core/buffer_cache/buffer_base.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/buffer_cache_base.h
  src/video_core/buffer_cache/memory_tracker_base.h
  src/video_core/buffer_cache/word_manager.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/fence_manager.h
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/query_cache.h
  src/video_core/rasterizer_download_area.h
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_null/null_rasterizer.cpp
  src/video_core/renderer_null/null_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/texture_cache/image_info.cpp
  src/video_core/texture_cache/image_info.h
  src/video_core/texture_cache/image_view_base.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: gpu-new, early-access-merge

#10206 Texture Cache: Fix 3D ASTC textures
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/texture_cache/util.cpp
Labels: gpu-fix, early-access-merge

#10203 core: hid: Allow to calibrate gyro sensor
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hid/motion_input.cpp
  src/core/hid/motion_input.h
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player_widget.cpp
Labels: early-access-merge

#10183 vfs_vector: avoid n^2 lookup in layeredfs building
  src/core/file_sys/vfs_layered.cpp
  src/core/file_sys/vfs_vector.cpp
  src/core/file_sys/vfs_vector.h
Labels: early-access-merge, filesystem-fix

#10119 Attempt at improving HD Rumble emulation
  src/input_common/drivers/sdl_driver.cpp
Labels: early-access-merge

#10207 service: nfp: Allow to load with a different amiibo id
  src/common/settings.h
  src/core/hle/service/nfc/common/device.cpp
  src/core/hle/service/nfc/common/device.h
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_input_advanced.cpp
  src/yuzu/configuration/configure_input_advanced.ui
  src/yuzu_cmd/config.cpp
Labels: early-access-merge

#10222 renderer_vulkan: separate guest and host compute descriptor queues
  src/video_core/renderer_vulkan/pipeline_helper.h
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_compute_pass.cpp
  src/video_core/renderer_vulkan/vk_compute_pass.h
  src/video_core/renderer_vulkan/vk_compute_pipeline.cpp
  src/video_core/renderer_vulkan/vk_compute_pipeline.h
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
  src/video_core/renderer_vulkan/vk_graphics_pipeline.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/renderer_vulkan/vk_update_descriptor.h
Labels: gpu-fix, vulkan, early-access-merge

#10216 Swap order of checking/setting region modifications in the buffer_cache
  src/video_core/buffer_cache/buffer_cache.h
Labels: gpu-fix, early-access-merge

#10132 Allow Fermi blit accelerate to work without images in cache
  src/common/scratch_buffer.h
  src/video_core/engines/sw_blitter/blitter.cpp
  src/video_core/texture_cache/texture_cache.h
Labels: mainline-merge

#10236 nvnflinger: fix Parcel serialization
  src/core/hle/service/nvnflinger/buffer_queue_producer.cpp
  src/core/hle/service/nvnflinger/parcel.h
  src/core/hle/service/vi/vi.cpp
Labels: mainline-merge

#10237 fs: stub cache storage
  src/core/file_sys/savedata_factory.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/filesystem/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp_srv.h
Labels: mainline-merge

#10243 Correctly track render target index in the framebuffer for image aspects
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
Labels: mainline-merge

#10244 time: implement ContinuousAdjustmentTimePoint
  src/core/hle/service/time/clock_types.h
  src/core/hle/service/time/time_sharedmemory.cpp
  src/core/hle/service/time/time_sharedmemory.h
Labels: mainline-merge

#10286 vulkan_common: fix incompatible property flags
  src/video_core/vulkan_common/vulkan_memory_allocator.cpp
Labels: gpu-fix, mainline-merge, vulkan

#10288 vulkan_device: reserve extra memory to prevent swaps
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: gpu-fix, vulkan

#10265 input_common: Make amiibo scanning less demanding
  src/input_common/helpers/joycon_protocol/joycon_types.h
  src/input_common/helpers/joycon_protocol/nfc.cpp
  src/input_common/helpers/joycon_protocol/nfc.h
Labels: early-access-merge

#10254 Fix missing pic_order_present_flag in h264 header
  src/video_core/host1x/codecs/h264.cpp
Labels: early-access-merge

#10234 Fix Tears of the Kingdom flickering clouds and depths geometry.
  src/shader_recompiler/backend/spirv/emit_spirv_context_get_set.cpp
  src/shader_recompiler/frontend/maxwell/translate/impl/texture_mipmap_level.cpp
Labels: mainline-merge

#10181 configure_graphics: Add option to enable compute pipelines for Intel proprietary
  src/common/settings.cpp
  src/common/settings.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_dialog.cpp
  src/yuzu/configuration/configure_dialog.h
  src/yuzu/configuration/configure_graphics.cpp
  src/yuzu/configuration/configure_graphics.h
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu/configuration/configure_per_game.cpp
  src/yuzu/configuration/configure_per_game.h
Labels: frontend-new, gpu-fix, mainline-merge

#10107 Allow fully customised controller hotkeys
  src/yuzu/configuration/configure_hotkeys.cpp
  src/yuzu/configuration/configure_hotkeys.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#10262 vulkan_common: disable depth clamp dynamic state for older radv
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: mainline-merge

#10344 input_common: Fix pro controller amiibo support
  src/input_common/drivers/joycon.cpp
  src/input_common/drivers/joycon.h
  src/input_common/helpers/joycon_protocol/common_protocol.cpp
  src/input_common/helpers/joycon_protocol/joycon_types.h
  src/input_common/helpers/joycon_protocol/nfc.cpp
  src/input_common/helpers/joycon_protocol/nfc.h
Labels: early-access-merge

#10411 Limit device access memory for integrated devices to 4 GB
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: early-access-merge

#10388 vk_master_semaphore: Move fence wait on separate thread
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.h
Labels: gpu-new, early-access-merge

#10398 video_core: add ASTC recompression
  externals/CMakeLists.txt
  externals/stb/stb_dxt.cpp
  externals/stb/stb_dxt.h
  src/common/settings.cpp
  src/common/settings.h
  src/video_core/CMakeLists.txt
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/texture_cache/util.cpp
  src/video_core/textures/astc.cpp
  src/video_core/textures/bcn.cpp
  src/video_core/textures/bcn.h
  src/video_core/textures/workers.cpp
  src/video_core/textures/workers.h
  src/video_core/vulkan_common/vulkan_device.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/config.h
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: gpu-new, early-access-merge

#10417 k_memory_block_manager: remove auditing calls
  src/core/hle/kernel/k_memory_block_manager.h
Labels: kernel-fix, early-access-merge

#10422 video_core: tune garbage collection aggressiveness
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/texture_cache/texture_cache.h
Labels: gpu-new, early-access-merge

#10433 Texture Cache Util: Fix block depth adjustment on slices.
  src/video_core/texture_cache/util.cpp
Labels: gpu-fix, early-access-merge

#10435 Texture cache: revert wrong acceleration assumption
  src/video_core/texture_cache/texture_cache.h
Labels: gpu-fix, early-access-merge

#10396 input_common: Implement amiibo writing
  src/core/hid/emulated_controller.cpp
  src/core/hle/service/nfc/common/device.cpp
  src/input_common/drivers/joycon.cpp
  src/input_common/helpers/joycon_driver.cpp
  src/input_common/helpers/joycon_driver.h
  src/input_common/helpers/joycon_protocol/joycon_types.h
  src/input_common/helpers/joycon_protocol/nfc.cpp
  src/input_common/helpers/joycon_protocol/nfc.h
Labels: early-access-merge

#10221 Add a 5ms tiemout to the DSP processing wait
  src/audio_core/renderer/adsp/audio_renderer.cpp
  src/audio_core/renderer/system_manager.cpp
  src/audio_core/renderer/system_manager.h
  src/audio_core/sink/sink_stream.cpp
Labels: mainline-merge

#10459 shader_recompiler: fix copy-paste error
  src/shader_recompiler/frontend/maxwell/translate/impl/integer_funnel_shift.cpp
Labels: gpu-fix, early-access-merge

#10418 texture_cache: process aliases and overlaps in the correct order
  src/video_core/texture_cache/image_base.cpp
  src/video_core/texture_cache/image_base.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
Labels: gpu-fix, mainline-merge

#10414 vulkan_device: Enable VK_KHR_push_descriptor on newer ANV
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: vulkan, early-access-merge

#10471 Wait indefinitely when audio buffer queue is too big
  src/audio_core/sink/sink_stream.cpp
Labels: audio-fix, mainline-merge

#10469 Move buffer bindings to per-channel state
  src/video_core/buffer_cache/buffer_cache.cpp
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/buffer_cache/buffer_cache_base.h
  src/video_core/renderer_opengl/gl_buffer_cache.cpp
Labels: early-access-merge

#10464 qt: add menu item to remove cache storage
  src/yuzu/game_list.cpp
  src/yuzu/game_list.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#10463 vfs_concat: fix time complexity of read
  src/core/core.cpp
  src/core/file_sys/romfs.cpp
  src/core/file_sys/vfs_concat.cpp
  src/core/file_sys/vfs_concat.h
Labels: early-access-merge, filesystem-fix

#10376 cmake: apply defaults to all externals
  externals/CMakeLists.txt
  externals/glad/CMakeLists.txt
  externals/libusb/CMakeLists.txt
  externals/opus/CMakeLists.txt
Labels: early-access-merge

#10283 Add support for deinterlaced video playback
  CMakeLists.txt
  externals/ffmpeg/CMakeLists.txt
  src/video_core/host1x/codecs/codec.cpp
  src/video_core/host1x/codecs/codec.h
Labels: early-access-merge

#10280 Use TARGET_FILE_DIR generator expression
  .ci/scripts/windows/upload.ps1
  CMakeModules/CopyYuzuFFmpegDeps.cmake
  CMakeModules/CopyYuzuQt5Deps.cmake
  CMakeModules/CopyYuzuSDLDeps.cmake
  src/yuzu/CMakeLists.txt
Labels: early-access-merge

#10506 Skip BufferCache tickframe with no channel state set
  src/video_core/buffer_cache/buffer_cache.h
Labels: mainline-merge
