Repository yuzu-emu/yuzu, pull requests merged in 2023-04, with the labels that each got.

#10005 kernel: fix unbounded stack usage in atomics
  src/core/hle/kernel/k_address_arbiter.cpp
  src/core/hle/kernel/k_condition_variable.cpp
Labels: kernel-fix, mainline-merge

#9999 service: hid: Implement SetNpadJoyAssignmentModeSingleWithDestination
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
Labels: early-access-merge

#9997 applet: controller: Implement cancel button
  src/core/frontend/applets/controller.cpp
  src/core/frontend/applets/controller.h
  src/core/hle/service/am/applets/applet_controller.cpp
  src/core/hle/service/am/applets/applet_controller.h
  src/yuzu/applets/qt_controller.cpp
  src/yuzu/applets/qt_controller.h
  src/yuzu/applets/qt_controller.ui
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#10006 service: am: Improve profile select applet
  src/core/frontend/applets/profile_select.cpp
  src/core/frontend/applets/profile_select.h
  src/core/hle/service/am/applets/applet_profile_select.cpp
  src/core/hle/service/am/applets/applet_profile_select.h
  src/yuzu/applets/qt_profile_select.cpp
  src/yuzu/applets/qt_profile_select.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#9969 Audio synchronisation improvements
  src/audio_core/device/device_session.cpp
  src/audio_core/renderer/adsp/audio_renderer.cpp
  src/audio_core/renderer/adsp/audio_renderer.h
  src/audio_core/renderer/system_manager.cpp
  src/audio_core/renderer/system_manager.h
  src/audio_core/sink/cubeb_sink.cpp
  src/audio_core/sink/sdl2_sink.cpp
  src/audio_core/sink/sink_stream.cpp
  src/audio_core/sink/sink_stream.h
Labels: mainline-merge

#10024 service: hid: Fix handle validation
  src/core/hle/service/hid/controllers/npad.cpp
Labels: early-access-merge

#10022 general: fixes for gcc 13
  src/CMakeLists.txt
  src/common/intrusive_red_black_tree.h
  src/common/typed_address.h
  src/core/internal_network/socket_proxy.h
  src/core/internal_network/sockets.h
  src/web_service/verify_login.cpp
Labels: mainline-merge

#10014 Re-enable LTO for GCC
  .ci/scripts/linux/docker.sh
Labels: mainline-merge

#10035 kernel: switch extended memory setting to 8GB arrangement
  src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
  src/yuzu/configuration/configure_general.ui
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge

#10027 Add some explicit latency to sample count reporting
  src/audio_core/sink/sink_stream.cpp
  src/audio_core/sink/sink_stream.h
Labels: mainline-merge

#10008 video_core: update imageinfo implement
  src/video_core/engines/maxwell_3d.h
  src/video_core/texture_cache/image_info.cpp
  src/video_core/texture_cache/image_info.h
  src/video_core/texture_cache/texture_cache.h
Labels: mainline-merge

#10030 shader_recompiler: Fix ImageGather rounding on AMD/Intel
  src/shader_recompiler/backend/glsl/emit_glsl_image.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
  src/shader_recompiler/profile.h
  src/video_core/renderer_opengl/gl_device.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: mainline-merge

#10053 service: nfp: Implement all interfaces
  src/core/CMakeLists.txt
  src/core/hle/service/nfp/nfp.cpp
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nfp/nfp_device.h
  src/core/hle/service/nfp/nfp_interface.cpp
  src/core/hle/service/nfp/nfp_interface.h
  src/core/hle/service/nfp/nfp_types.h
Labels: early-access-merge

#10057 vulkan: use plain fences when timeline semaphores are not available
  src/video_core/renderer_vulkan/vk_master_semaphore.cpp
  src/video_core/renderer_vulkan/vk_master_semaphore.h
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: mainline-merge, vulkan

#10074 Account for a pre-added offset when using Corner sample mode for 2D blits
  src/video_core/engines/fermi_2d.cpp
Labels: early-access-merge

#10069 maxwell_3d: fix out of bounds array access in size estimation
  src/video_core/engines/maxwell_3d.cpp
Labels: vulkan, early-access-merge

#10056 core: audio: return result when audio_out initialize failed
  src/core/hle/service/audio/audout_u.cpp
Labels: audio-fix, early-access-merge

#10051 vulkan: pick alpha composite flags based on available values
  src/video_core/renderer_vulkan/vk_swapchain.cpp
Labels: vulkan, early-access-merge

#10082 Refactor Accelerate DMA and do downloads through TC.
  src/video_core/engines/maxwell_3d.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
Labels: gpu-fix, mainline-merge

#10110 vk_pipeline_cache: Skip compute pipelines on Intel proprietary drivers
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: vulkan, early-access-merge, intel
