Repository yuzu-emu/yuzu, pull requests merged in 2023-03, with the labels that each got.

#9888 vulkan_common: disable vertexInputDynamicState on unsupported driver
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: vulkan

#9887 ci: Actually enable LTO on MSVC
  .ci/templates/build-msvc.yml
Labels: early-access-merge

#9855 kernel: support for 16.0.0
  src/core/hle/kernel/board/nintendo/nx/k_system_control.cpp
  src/core/hle/kernel/init/init_slab_setup.cpp
  src/core/hle/kernel/k_address_arbiter.cpp
  src/core/hle/kernel/k_address_space_info.cpp
  src/core/hle/kernel/k_condition_variable.cpp
  src/core/hle/kernel/k_light_lock.cpp
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_scheduler_lock.h
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc_types.h
Labels: kernel-new, kernel-fix, mainline-merge

#9786 YFC - Engines: Implement Accelerate DMA Texture.
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/engines/maxwell_dma.cpp
  src/video_core/engines/maxwell_dma.h
  src/video_core/renderer_null/null_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/texture_cache/image_info.cpp
  src/video_core/texture_cache/image_info.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
  src/video_core/texture_cache/types.h
  src/video_core/texture_cache/util.cpp
  src/video_core/texture_cache/util.h
Labels: mainline-merge

#9890 Fix a bug with the Reverb command in reading from the pre delay line
  src/audio_core/renderer/command/effect/reverb.cpp
  src/audio_core/renderer/effect/i3dl2.h
  src/audio_core/renderer/effect/reverb.h
Labels: mainline-merge

#9889 core_timing: Reduce CPU usage on Windows
  CMakeLists.txt
  dist/yuzu.manifest
  src/common/CMakeLists.txt
  src/common/steady_clock.cpp
  src/common/steady_clock.h
  src/common/wall_clock.cpp
  src/common/wall_clock.h
  src/common/windows/timer_resolution.cpp
  src/common/windows/timer_resolution.h
  src/common/x64/native_clock.cpp
  src/core/core_timing.cpp
  src/core/core_timing.h
  src/core/hardware_properties.h
  src/video_core/gpu.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/yuzu.cpp
Labels: core-fix, performance, mainline-merge, os-windows

#9896 Check all swizzle components for red, not just [0]
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
Labels: gpu-fix, mainline-merge

#9904 kernel: fix WaitSynchronization
  src/core/hle/kernel/svc/svc_synchronization.cpp
Labels: kernel-fix, mainline-merge

#9912 hle: rename legacy errors to Results
  src/audio_core/audio_in_manager.cpp
  src/audio_core/audio_manager.cpp
  src/audio_core/audio_out_manager.cpp
  src/audio_core/audio_render_manager.cpp
  src/audio_core/in/audio_in.cpp
  src/audio_core/in/audio_in_system.cpp
  src/audio_core/out/audio_out.cpp
  src/audio_core/out/audio_out_system.cpp
  src/audio_core/renderer/audio_renderer.cpp
  src/audio_core/renderer/behavior/info_updater.cpp
  src/audio_core/renderer/memory/pool_mapper.cpp
  src/audio_core/renderer/system.cpp
  src/audio_core/renderer/voice/voice_info.cpp
  src/core/CMakeLists.txt
  src/core/hle/kernel/k_process.h
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/errors.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applet_controller.cpp
  src/core/hle/service/am/applets/applet_profile_select.cpp
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/errors.h
  src/core/hle/service/friend/errors.h
  src/core/hle/service/friend/friend.cpp
  src/core/hle/service/glue/arp.cpp
  src/core/hle/service/glue/errors.h
  src/core/hle/service/glue/glue_manager.cpp
  src/core/hle/service/glue/glue_manager.h
  src/core/hle/service/ipc_helpers.h
  src/core/hle/service/ns/errors.h
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/server_manager.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/set/set.cpp
  src/core/hle/service/sm/sm.cpp
Labels: hle-new, early-access-merge

#9906 input_common: Increase mouse sensitivity range
  src/common/settings.h
  src/input_common/drivers/mouse.cpp
  src/input_common/input_mapping.cpp
Labels: early-access-merge

#9822 buffer_cache: Add logic for non-NVN storage buffer tracking
  src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp
  src/video_core/buffer_cache/buffer_cache.h
Labels: mainline-merge

#9917 native_clock: Re-adjust the RDTSC frequency to its real frequency
  src/audio_core/renderer/adsp/audio_renderer.cpp
  src/common/steady_clock.cpp
  src/common/steady_clock.h
  src/common/x64/native_clock.cpp
  src/common/x64/native_clock.h
  src/core/core_timing.cpp
  src/core/cpu_manager.cpp
  src/core/hle/service/hid/controllers/stubbed.cpp
  src/core/hle/service/hid/controllers/touchscreen.cpp
  src/core/perf_stats.cpp
  src/video_core/gpu_thread.cpp
Labels: core-fix, mainline-merge

#9925 OpenGL: Prefer glClientWaitSync for OGLSync objects
  src/video_core/renderer_opengl/gl_fence_manager.cpp
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
  src/video_core/renderer_opengl/gl_resource_manager.cpp
  src/video_core/renderer_opengl/gl_resource_manager.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
Labels: mainline-merge

#9928 service: nfp: Improve implementation
  src/core/hle/service/am/applets/applet_cabinet.cpp
  src/core/hle/service/nfp/amiibo_crypto.cpp
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nfp/nfp_device.h
  src/core/hle/service/nfp/nfp_types.h
Labels: early-access-merge

#9923 kernel: add timer pointer to KThreadQueue
  src/core/hle/kernel/k_address_arbiter.cpp
  src/core/hle/kernel/k_condition_variable.cpp
  src/core/hle/kernel/k_light_condition_variable.cpp
  src/core/hle/kernel/k_scoped_scheduler_lock_and_sleep.h
  src/core/hle/kernel/k_synchronization_object.cpp
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread_queue.cpp
  src/core/hle/kernel/k_thread_queue.h
Labels: mainline-merge

#9913 AccelerateDMA: Refactor Buffer/Image copy code and implement for OGL
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
Labels: mainline-merge

#9943 video_core: Fix inline_index and draw_texture error
  src/video_core/engines/draw_manager.cpp
  src/video_core/renderer_opengl/blit_image.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
Labels: early-access-merge

#9941 yuzu: Move audio settings to audio section
  src/yuzu/configuration/configure_audio.cpp
  src/yuzu/configuration/configure_audio.ui
  src/yuzu/configuration/configure_general.cpp
  src/yuzu/configuration/configure_general.ui
  src/yuzu/configuration/configure_system.cpp
  src/yuzu/configuration/configure_system.h
  src/yuzu/configuration/configure_system.ui
Labels: early-access-merge

#9939 input_common: sdl: Only send last vibration command
  src/input_common/drivers/sdl_driver.cpp
Labels: early-access-merge

#9933 video_core: Update texture format
  src/video_core/renderer_vulkan/maxwell_to_vk.cpp
  src/video_core/texture_cache/format_lookup_table.cpp
  src/video_core/textures/texture.h
Labels: early-access-merge

#9931 vk_scheduler: split work queue waits and execution waits
  src/video_core/renderer_vulkan/vk_scheduler.cpp
  src/video_core/renderer_vulkan/vk_scheduler.h
Labels: mainline-merge, vulkan

#9955 vulkan: disable extendedDynamicState3ColorBlendEquation on radv
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: mainline-merge, vulkan

#9953 service: nfp: Actually write correct crc
  src/core/hle/service/mii/mii_manager.cpp
  src/core/hle/service/mii/mii_manager.h
  src/core/hle/service/mii/types.h
  src/core/hle/service/nfp/amiibo_crypto.cpp
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nfp/nfp_device.h
  src/core/hle/service/nfp/nfp_types.h
Labels: early-access-merge

#9778 gpu_thread: Use bounded queue
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
Labels: early-access-merge

#9972 kernel: fix LOG_TRACE in ipc
  src/core/hle/kernel/svc/svc_ipc.cpp
Labels: kernel-fix, mainline-merge

#9965 config: Fix controller config from resetting
  src/yuzu/configuration/configure_input.cpp
Labels: mainline-merge

#9962 [video_core] Disable SRGB border color conversion in samplers
  src/video_core/textures/texture.cpp
Labels: early-access-merge

#9975 vulkan: fix more excessive waiting in scheduler
  src/video_core/renderer_vulkan/vk_scheduler.cpp
Labels: vulkan, early-access-merge

#9981 nfc: Initialize device when controller is connected
  src/core/hle/service/nfc/nfc_device.cpp
  src/core/hle/service/nfc/nfc_device.h
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nfp/nfp_device.h
Labels: early-access-merge

#9985 vulkan: fix scheduler chunk reserve
  src/video_core/renderer_vulkan/vk_scheduler.cpp
Labels: vulkan, early-access-merge

#9989 CMakeLists: Use boost 1.79.0 instead
  CMakeLists.txt
  src/common/CMakeLists.txt
  src/common/container_hash.h
  src/tests/CMakeLists.txt
  src/tests/common/container_hash.cpp
  src/video_core/macro/macro.cpp
  vcpkg.json
Labels: mainline-merge

#9995 service: nfp: Add plain amiibo support
  src/core/hle/service/nfp/amiibo_crypto.cpp
  src/core/hle/service/nfp/amiibo_crypto.h
  src/core/hle/service/nfp/nfp_device.cpp
  src/core/hle/service/nfp/nfp_device.h
  src/core/hle/service/nfp/nfp_types.h
Labels: early-access-merge

#9984 memory: rename global memory references to application memory
  src/audio_core/device/device_session.cpp
  src/audio_core/renderer/adsp/adsp.cpp
  src/audio_core/renderer/adsp/command_list_processor.cpp
  src/audio_core/renderer/system.cpp
  src/core/arm/arm_interface.cpp
  src/core/arm/dynarmic/arm_dynarmic_32.cpp
  src/core/arm/dynarmic/arm_dynarmic_64.cpp
  src/core/core.cpp
  src/core/core.h
  src/core/debugger/gdbstub.cpp
  src/core/hle/kernel/k_address_arbiter.cpp
  src/core/hle/kernel/k_condition_variable.cpp
  src/core/hle/kernel/k_page_table.cpp
  src/core/hle/kernel/k_page_table.h
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/k_process.h
  src/core/hle/kernel/k_server_session.cpp
  src/core/hle/kernel/k_thread.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/svc/svc_cache.cpp
  src/core/hle/kernel/svc/svc_debug_string.cpp
  src/core/hle/kernel/svc/svc_exception.cpp
  src/core/hle/kernel/svc/svc_ipc.cpp
  src/core/hle/kernel/svc/svc_port.cpp
  src/core/hle/kernel/svc/svc_process.cpp
  src/core/hle/kernel/svc/svc_query_memory.cpp
  src/core/hle/kernel/svc/svc_synchronization.cpp
  src/core/hle/kernel/svc/svc_thread.cpp
  src/core/hle/service/am/am.cpp
  src/core/hle/service/hid/controllers/console_sixaxis.cpp
  src/core/hle/service/hid/hidbus/ringcon.cpp
  src/core/hle/service/hid/irsensor/image_transfer_processor.cpp
  src/core/hle/service/hle_ipc.cpp
  src/core/hle/service/jit/jit.cpp
  src/core/hle/service/ldr/ldr.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_nvdec_common.cpp
  src/core/memory.cpp
  src/core/memory.h
  src/core/memory/cheat_engine.cpp
  src/core/reporter.cpp
  src/video_core/memory_manager.cpp
  src/video_core/video_core.cpp
Labels: kernel-new, mainline-merge

#9982 x64: Make use of waitpkg instructions for power efficient sleeps
  src/common/CMakeLists.txt
  src/common/telemetry.cpp
  src/common/x64/cpu_detect.cpp
  src/common/x64/cpu_detect.h
  src/common/x64/cpu_wait.cpp
  src/common/x64/cpu_wait.h
  src/common/x64/native_clock.cpp
  src/core/core_timing.cpp
Labels: mainline-merge

#9505 applets: implement RequestExit
  src/core/frontend/applets/applet.h
  src/core/frontend/applets/cabinet.cpp
  src/core/frontend/applets/cabinet.h
  src/core/frontend/applets/controller.cpp
  src/core/frontend/applets/controller.h
  src/core/frontend/applets/error.cpp
  src/core/frontend/applets/error.h
  src/core/frontend/applets/general_frontend.cpp
  src/core/frontend/applets/general_frontend.h
  src/core/frontend/applets/mii_edit.cpp
  src/core/frontend/applets/mii_edit.h
  src/core/frontend/applets/profile_select.cpp
  src/core/frontend/applets/profile_select.h
  src/core/frontend/applets/software_keyboard.cpp
  src/core/frontend/applets/software_keyboard.h
  src/core/frontend/applets/web_browser.cpp
  src/core/frontend/applets/web_browser.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/applets/applet_cabinet.cpp
  src/core/hle/service/am/applets/applet_cabinet.h
  src/core/hle/service/am/applets/applet_controller.cpp
  src/core/hle/service/am/applets/applet_controller.h
  src/core/hle/service/am/applets/applet_error.cpp
  src/core/hle/service/am/applets/applet_error.h
  src/core/hle/service/am/applets/applet_general_backend.cpp
  src/core/hle/service/am/applets/applet_general_backend.h
  src/core/hle/service/am/applets/applet_mii_edit.cpp
  src/core/hle/service/am/applets/applet_mii_edit.h
  src/core/hle/service/am/applets/applet_profile_select.cpp
  src/core/hle/service/am/applets/applet_profile_select.h
  src/core/hle/service/am/applets/applet_software_keyboard.cpp
  src/core/hle/service/am/applets/applet_software_keyboard.h
  src/core/hle/service/am/applets/applet_web_browser.cpp
  src/core/hle/service/am/applets/applet_web_browser.h
  src/core/hle/service/am/applets/applets.h
  src/yuzu/applets/qt_amiibo_settings.cpp
  src/yuzu/applets/qt_amiibo_settings.h
  src/yuzu/applets/qt_controller.cpp
  src/yuzu/applets/qt_controller.h
  src/yuzu/applets/qt_error.cpp
  src/yuzu/applets/qt_error.h
  src/yuzu/applets/qt_profile_select.cpp
  src/yuzu/applets/qt_profile_select.h
  src/yuzu/applets/qt_software_keyboard.h
  src/yuzu/applets/qt_web_browser.cpp
  src/yuzu/applets/qt_web_browser.h
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: mainline-merge
