Repository yuzu-emu/yuzu, pull requests merged in 2023-02, with the labels that each got.

#9696 input_common: Implement turbo buttons
  src/common/input.h
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/input_common/input_poller.cpp
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_input_player_widget.cpp
  src/yuzu/configuration/configure_input_player_widget.h
Labels: early-access-merge

#9703 shaders: Fix TXQ with MSAA textures
  src/shader_recompiler/backend/glasm/emit_glasm_image.cpp
  src/shader_recompiler/backend/glsl/emit_glsl_image.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.cpp
  src/shader_recompiler/backend/spirv/spirv_emit_context.h
Labels: early-access-merge

#9708 gl_shader_cache: Force context flush when loading disk shader cache
  src/video_core/renderer_opengl/gl_compute_pipeline.cpp
  src/video_core/renderer_opengl/gl_compute_pipeline.h
  src/video_core/renderer_opengl/gl_graphics_pipeline.cpp
  src/video_core/renderer_opengl/gl_graphics_pipeline.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_opengl/gl_shader_cache.h
Labels: early-access-merge

#9704 kernel: add KDeviceAddressSpace
  src/core/CMakeLists.txt
  src/core/hle/kernel/init/init_slab_setup.cpp
  src/core/hle/kernel/k_device_address_space.cpp
  src/core/hle/kernel/k_device_address_space.h
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc_types.h
Labels: kernel-new, early-access-merge

#9717 input_common: Simplify stick from button
  src/input_common/helpers/stick_from_buttons.cpp
Labels: early-access-merge

#9720 Game Image with Discord RPC
  src/yuzu/CMakeLists.txt
  src/yuzu/discord_impl.cpp
Labels: early-access-merge

#9731 kernel/svc: Split implementations into separate files
  src/core/CMakeLists.txt
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc.h
  src/core/hle/kernel/svc/svc_activity.cpp
  src/core/hle/kernel/svc/svc_address_arbiter.cpp
  src/core/hle/kernel/svc/svc_address_translation.cpp
  src/core/hle/kernel/svc/svc_cache.cpp
  src/core/hle/kernel/svc/svc_code_memory.cpp
  src/core/hle/kernel/svc/svc_condition_variable.cpp
  src/core/hle/kernel/svc/svc_debug.cpp
  src/core/hle/kernel/svc/svc_debug_string.cpp
  src/core/hle/kernel/svc/svc_device_address_space.cpp
  src/core/hle/kernel/svc/svc_event.cpp
  src/core/hle/kernel/svc/svc_exception.cpp
  src/core/hle/kernel/svc/svc_info.cpp
  src/core/hle/kernel/svc/svc_interrupt_event.cpp
  src/core/hle/kernel/svc/svc_io_pool.cpp
  src/core/hle/kernel/svc/svc_ipc.cpp
  src/core/hle/kernel/svc/svc_kernel_debug.cpp
  src/core/hle/kernel/svc/svc_light_ipc.cpp
  src/core/hle/kernel/svc/svc_lock.cpp
  src/core/hle/kernel/svc/svc_memory.cpp
  src/core/hle/kernel/svc/svc_physical_memory.cpp
  src/core/hle/kernel/svc/svc_port.cpp
  src/core/hle/kernel/svc/svc_power_management.cpp
  src/core/hle/kernel/svc/svc_process.cpp
  src/core/hle/kernel/svc/svc_process_memory.cpp
  src/core/hle/kernel/svc/svc_processor.cpp
  src/core/hle/kernel/svc/svc_query_memory.cpp
  src/core/hle/kernel/svc/svc_register.cpp
  src/core/hle/kernel/svc/svc_resource_limit.cpp
  src/core/hle/kernel/svc/svc_secure_monitor_call.cpp
  src/core/hle/kernel/svc/svc_session.cpp
  src/core/hle/kernel/svc/svc_shared_memory.cpp
  src/core/hle/kernel/svc/svc_synchronization.cpp
  src/core/hle/kernel/svc/svc_thread.cpp
  src/core/hle/kernel/svc/svc_thread_profiler.cpp
  src/core/hle/kernel/svc/svc_tick.cpp
  src/core/hle/kernel/svc/svc_transfer_memory.cpp
  src/core/hle/kernel/svc_wrap.h
Labels: early-access-merge

#9644 add volume quicksetting with volume slider
  src/yuzu/main.cpp
  src/yuzu/main.h
Labels: early-access-merge

#4949 main: Enable High DPI fixes for Qt >= 5.14
  src/yuzu/applets/qt_software_keyboard.cpp
  src/yuzu/main.cpp
  src/yuzu/util/overlay_dialog.cpp
Labels: frontend-fix, mainline-merge

#9739 kernel: fix compilation with older gcc
  src/core/hle/kernel/k_capabilities.cpp
  src/core/hle/kernel/physical_core.h
Labels: kernel-fix

#9749 buffer_base: Partially revert changes from #9559
  src/tests/video_core/buffer_base.cpp
  src/video_core/buffer_cache/buffer_base.h
Labels: early-access-merge

#9750 glsl_emit_context: Remove redeclarations of gl_SampleID and gl_SampleMask
  src/shader_recompiler/backend/glsl/glsl_emit_context.cpp
Labels: early-access-merge

#9736 Remove fake vertex bindings when dynamic state is enabled
  src/video_core/renderer_vulkan/vk_graphics_pipeline.cpp
Labels: early-access-merge

#9761 main: Re-add QtWebEngine zoom factor
  src/yuzu/main.cpp
Labels: mainline-merge

#9759 input_common: Reintroduce custom pro controller support
  src/common/settings.h
  src/input_common/drivers/joycon.cpp
  src/input_common/drivers/joycon.h
  src/input_common/drivers/sdl_driver.cpp
  src/input_common/helpers/joycon_driver.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_input_advanced.cpp
  src/yuzu/configuration/configure_input_advanced.ui
  src/yuzu_cmd/config.cpp
Labels: early-access-merge

#9742 kernel/svc: switch to generated wrappers
  src/core/CMakeLists.txt
  src/core/arm/arm_interface.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/svc.h
  src/core/hle/kernel/svc/svc_activity.cpp
  src/core/hle/kernel/svc/svc_address_arbiter.cpp
  src/core/hle/kernel/svc/svc_address_translation.cpp
  src/core/hle/kernel/svc/svc_cache.cpp
  src/core/hle/kernel/svc/svc_code_memory.cpp
  src/core/hle/kernel/svc/svc_condition_variable.cpp
  src/core/hle/kernel/svc/svc_debug.cpp
  src/core/hle/kernel/svc/svc_debug_string.cpp
  src/core/hle/kernel/svc/svc_device_address_space.cpp
  src/core/hle/kernel/svc/svc_event.cpp
  src/core/hle/kernel/svc/svc_exception.cpp
  src/core/hle/kernel/svc/svc_info.cpp
  src/core/hle/kernel/svc/svc_insecure_memory.cpp
  src/core/hle/kernel/svc/svc_interrupt_event.cpp
  src/core/hle/kernel/svc/svc_io_pool.cpp
  src/core/hle/kernel/svc/svc_ipc.cpp
  src/core/hle/kernel/svc/svc_kernel_debug.cpp
  src/core/hle/kernel/svc/svc_light_ipc.cpp
  src/core/hle/kernel/svc/svc_lock.cpp
  src/core/hle/kernel/svc/svc_memory.cpp
  src/core/hle/kernel/svc/svc_physical_memory.cpp
  src/core/hle/kernel/svc/svc_port.cpp
  src/core/hle/kernel/svc/svc_power_management.cpp
  src/core/hle/kernel/svc/svc_process.cpp
  src/core/hle/kernel/svc/svc_process_memory.cpp
  src/core/hle/kernel/svc/svc_processor.cpp
  src/core/hle/kernel/svc/svc_query_memory.cpp
  src/core/hle/kernel/svc/svc_register.cpp
  src/core/hle/kernel/svc/svc_resource_limit.cpp
  src/core/hle/kernel/svc/svc_secure_monitor_call.cpp
  src/core/hle/kernel/svc/svc_session.cpp
  src/core/hle/kernel/svc/svc_shared_memory.cpp
  src/core/hle/kernel/svc/svc_synchronization.cpp
  src/core/hle/kernel/svc/svc_thread.cpp
  src/core/hle/kernel/svc/svc_thread_profiler.cpp
  src/core/hle/kernel/svc/svc_tick.cpp
  src/core/hle/kernel/svc/svc_transfer_memory.cpp
  src/core/hle/kernel/svc_generator.py
  src/core/hle/kernel/svc_results.h
  src/core/hle/kernel/svc_types.h
  src/core/hle/kernel/svc_wrap.h
Labels: early-access-merge

#9744 gpu_thread: Remove OnCommandListEndCommand
  src/video_core/gpu.cpp
  src/video_core/gpu_thread.cpp
  src/video_core/gpu_thread.h
Labels: early-access-merge

#9768 biquad_filter: Fix rounding in ApplyBiquadFilterInt
  src/audio_core/renderer/command/effect/biquad_filter.cpp
  src/audio_core/renderer/voice/voice_state.h
Labels: early-access-merge

#9773 core: kernel: k_process: Use application system resource.
  src/core/hle/kernel/k_process.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
Labels: hle-fix, kernel-fix, early-access-merge

#9746 texture_cache: OpenGL: Implement MSAA uploads and copies
  src/video_core/host_shaders/CMakeLists.txt
  src/video_core/host_shaders/convert_msaa_to_non_msaa.comp
  src/video_core/host_shaders/convert_non_msaa_to_msaa.comp
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_opengl/gl_texture_cache.h
  src/video_core/renderer_opengl/util_shaders.cpp
  src/video_core/renderer_opengl/util_shaders.h
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
  src/video_core/texture_cache/formatter.cpp
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/util.cpp
Labels: early-access-merge

#9757 core: hid: Use gyro thresholds modes set by the game
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hid/hid_types.h
  src/core/hid/motion_input.cpp
  src/core/hid/motion_input.h
  src/core/hle/service/hid/controllers/npad.cpp
  src/core/hle/service/hid/controllers/npad.h
  src/core/hle/service/hid/hid.cpp
Labels: early-access-merge

#9795 [audio_core] Use different state offset for each biquad filter channel
  src/audio_core/renderer/command/command_buffer.cpp
Labels: early-access-merge

#9769 [audio_core] Fix depop prepare
  src/audio_core/renderer/command/command_generator.cpp
  src/audio_core/renderer/command/effect/aux_.cpp
Labels: mainline-merge

#9802 Re-add the invalidate_texture_data_cache register
  src/video_core/engines/maxwell_3d.cpp
Labels: early-access-merge

#9810 Allow >1 cpu threads on video decoding, disable multi-frame decoding
  src/video_core/host1x/codecs/codec.cpp
Labels: mainline-merge

#9825 kernel: add KObjectName
  src/core/CMakeLists.txt
  src/core/hle/kernel/init/init_slab_setup.cpp
  src/core/hle/kernel/k_object_name.cpp
  src/core/hle/kernel/k_object_name.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc/svc_port.cpp
Labels: kernel-new

#9815 Qt: Fix mouse scalling
  src/core/hid/emulated_console.cpp
  src/core/hid/emulated_devices.cpp
  src/input_common/drivers/mouse.cpp
  src/input_common/drivers/mouse.h
  src/input_common/input_mapping.cpp
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
  src/yuzu/configuration/configure_input_player.cpp
  src/yuzu/configuration/configure_ringcon.cpp
  src/yuzu/main.cpp
  src/yuzu_cmd/emu_window/emu_window_sdl2.cpp
Labels: early-access-merge

#9588 Revert "shader_recompiler: Align SSBO offsets to meet host requirements"
  src/shader_recompiler/frontend/maxwell/translate_program.cpp
  src/shader_recompiler/host_translate_info.h
  src/shader_recompiler/ir_opt/global_memory_to_storage_buffer_pass.cpp
  src/shader_recompiler/ir_opt/passes.h
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_opengl/gl_buffer_cache.h
  src/video_core/renderer_opengl/gl_shader_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.cpp
  src/video_core/renderer_vulkan/vk_buffer_cache.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
Labels: gpu-fix, mainline-merge

#9771 kernel: Refactor thread_local variable usage
  src/core/hle/kernel/kernel.cpp
Labels: early-access-merge

#9834 Qt: Reintroduce scaling for touch input
  src/yuzu/bootmanager.cpp
  src/yuzu/bootmanager.h
Labels: mainline-merge

#9848 input_common: Implement dedicated motion from mouse
  src/core/hid/emulated_controller.cpp
  src/core/hid/motion_input.cpp
  src/core/hid/motion_input.h
  src/input_common/drivers/mouse.cpp
  src/input_common/drivers/mouse.h
  src/input_common/input_mapping.cpp
Labels: early-access-merge

#9849 texture_cache: Add asynchronous ASTC texture decoding
  src/common/scratch_buffer.h
  src/common/settings.cpp
  src/common/settings.h
  src/video_core/renderer_opengl/gl_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/texture_cache/image_base.h
  src/video_core/texture_cache/texture_cache.h
  src/video_core/texture_cache/texture_cache_base.h
  src/video_core/textures/astc.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_graphics_advanced.cpp
  src/yuzu/configuration/configure_graphics_advanced.h
  src/yuzu/configuration/configure_graphics_advanced.ui
  src/yuzu_cmd/config.cpp
  src/yuzu_cmd/default_ini.h
Labels: early-access-merge

#9871 Revert "yuzu: config: Remove player 8 and 9 from config file"
  src/common/settings.h
  src/core/hid/emulated_controller.cpp
  src/core/hid/emulated_controller.h
  src/core/hid/hid_types.h
  src/yuzu/applets/qt_controller.cpp
  src/yuzu/configuration/config.cpp
  src/yuzu/configuration/configure_input_per_game.cpp
  src/yuzu/configuration/configure_input_player.cpp
Labels: mainline-merge

#9872 Partial LTO
  .ci/templates/build-msvc.yml
  CMakeLists.txt
  src/core/CMakeLists.txt
  src/video_core/CMakeLists.txt
Labels: early-access-merge

#9874 service: btm: Fix handle functions
  src/core/hle/service/btm/btm.cpp
Labels: mainline-merge

#9859 service: avoid direct pointer access of transfer memory objects
  src/core/hle/service/am/am.cpp
  src/core/hle/service/hid/controllers/console_sixaxis.cpp
  src/core/hle/service/hid/controllers/console_sixaxis.h
  src/core/hle/service/hid/controllers/palma.cpp
  src/core/hle/service/hid/controllers/palma.h
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid.h
  src/core/hle/service/hid/hidbus.cpp
  src/core/hle/service/hid/hidbus.h
  src/core/hle/service/hid/hidbus/hidbus_base.cpp
  src/core/hle/service/hid/hidbus/hidbus_base.h
  src/core/hle/service/hid/hidbus/ringcon.cpp
  src/core/hle/service/hid/hidbus/ringcon.h
  src/core/hle/service/hid/hidbus/starlink.cpp
  src/core/hle/service/hid/hidbus/starlink.h
  src/core/hle/service/hid/hidbus/stubbed.cpp
  src/core/hle/service/hid/hidbus/stubbed.h
  src/core/hle/service/hid/irs.cpp
  src/core/hle/service/hid/irs.h
  src/core/hle/service/hid/irsensor/image_transfer_processor.cpp
  src/core/hle/service/hid/irsensor/image_transfer_processor.h
Labels: hle-fix, early-access-merge

#9844 cmake: fix cpp-jwt build
  CMakeLists.txt
  externals/CMakeLists.txt
Labels: early-access-merge

#9862 cmake: support components in find modules
  CMakeLists.txt
  CMakeModules/FindLLVM.cmake
  CMakeModules/Findhttplib.cmake
  CMakeModules/Findinih.cmake
Labels: early-access-merge

#9877 cmake: use correct boost imported targets
  CMakeLists.txt
  src/common/CMakeLists.txt
  src/core/CMakeLists.txt
  src/input_common/CMakeLists.txt
  src/network/CMakeLists.txt
  src/yuzu/CMakeLists.txt
Labels: early-access-merge
