Repository yuzu-emu/yuzu, pull requests merged in 2024-02, with the labels that each got.

#12780 service: hid: Fully implement touch resource
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hid_debug_server.cpp
  src/core/hle/service/hid/hid_debug_server.h
  src/core/hle/service/hid/hid_server.cpp
  src/core/hle/service/hid/hid_system_server.cpp
  src/core/hle/service/hid/hid_system_server.h
  src/core/hle/service/set/setting_formats/system_settings.h
  src/core/hle/service/set/system_settings_server.cpp
  src/core/hle/service/set/system_settings_server.h
  src/frontend_common/config.cpp
  src/hid_core/CMakeLists.txt
  src/hid_core/hid_result.h
  src/hid_core/hid_types.h
  src/hid_core/resource_manager.cpp
  src/hid_core/resource_manager.h
  src/hid_core/resources/applet_resource.cpp
  src/hid_core/resources/applet_resource.h
  src/hid_core/resources/npad/npad.cpp
  src/hid_core/resources/npad/npad.h
  src/hid_core/resources/npad/npad_resource.cpp
  src/hid_core/resources/touch_screen/gesture.cpp
  src/hid_core/resources/touch_screen/gesture.h
  src/hid_core/resources/touch_screen/gesture_handler.cpp
  src/hid_core/resources/touch_screen/gesture_handler.h
  src/hid_core/resources/touch_screen/gesture_types.h
  src/hid_core/resources/touch_screen/touch_screen.cpp
  src/hid_core/resources/touch_screen/touch_screen.h
  src/hid_core/resources/touch_screen/touch_screen_driver.cpp
  src/hid_core/resources/touch_screen/touch_screen_driver.h
  src/hid_core/resources/touch_screen/touch_screen_resource.cpp
  src/hid_core/resources/touch_screen/touch_screen_resource.h
  src/hid_core/resources/touch_screen/touch_types.h
Labels: early-access-merge, android-merge

#12848 service: capsrv: Migrate to new IPC
  src/core/hle/service/caps/caps_a.cpp
  src/core/hle/service/caps/caps_a.h
  src/core/hle/service/caps/caps_c.cpp
  src/core/hle/service/caps/caps_c.h
  src/core/hle/service/caps/caps_manager.cpp
  src/core/hle/service/caps/caps_manager.h
  src/core/hle/service/caps/caps_ss.cpp
  src/core/hle/service/caps/caps_ss.h
  src/core/hle/service/caps/caps_su.cpp
  src/core/hle/service/caps/caps_su.h
  src/core/hle/service/caps/caps_types.h
  src/core/hle/service/caps/caps_u.cpp
  src/core/hle/service/caps/caps_u.h
Labels: mainline-merge, android-merge

#12875 SwBlitter: Fix Pitch linear reading/writting
  src/video_core/engines/sw_blitter/blitter.cpp
Labels: mainline-merge, android-merge

#12885 structured_control_flow: Add Samsung Proprietary Driver ID to Reorder Pass
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/vulkan_common/vulkan_device.cpp
Labels: android-merge

#12845 notif: rewrite for new IPC
  src/core/hle/service/glue/glue.cpp
  src/core/hle/service/glue/notif.cpp
  src/core/hle/service/glue/notif.h
Labels: early-access-merge, android-merge

#12857 service: use const references for input raw data
  src/core/hle/service/glue/time/static.cpp
  src/core/hle/service/glue/time/static.h
  src/core/hle/service/glue/time/time_zone.cpp
  src/core/hle/service/glue/time/time_zone.h
  src/core/hle/service/glue/time/time_zone_binary.cpp
  src/core/hle/service/glue/time/time_zone_binary.h
  src/core/hle/service/jit/jit.cpp
  src/core/hle/service/mii/mii.cpp
  src/core/hle/service/psc/time/clocks/context_writers.cpp
  src/core/hle/service/psc/time/clocks/context_writers.h
  src/core/hle/service/psc/time/clocks/standard_local_system_clock_core.cpp
  src/core/hle/service/psc/time/clocks/standard_local_system_clock_core.h
  src/core/hle/service/psc/time/clocks/standard_network_system_clock_core.cpp
  src/core/hle/service/psc/time/clocks/standard_network_system_clock_core.h
  src/core/hle/service/psc/time/clocks/standard_user_system_clock_core.cpp
  src/core/hle/service/psc/time/clocks/standard_user_system_clock_core.h
  src/core/hle/service/psc/time/clocks/system_clock_core.cpp
  src/core/hle/service/psc/time/clocks/system_clock_core.h
  src/core/hle/service/psc/time/service_manager.cpp
  src/core/hle/service/psc/time/service_manager.h
  src/core/hle/service/psc/time/shared_memory.cpp
  src/core/hle/service/psc/time/shared_memory.h
  src/core/hle/service/psc/time/static.cpp
  src/core/hle/service/psc/time/static.h
  src/core/hle/service/psc/time/system_clock.cpp
  src/core/hle/service/psc/time/system_clock.h
  src/core/hle/service/psc/time/time_zone.cpp
  src/core/hle/service/psc/time/time_zone.h
  src/core/hle/service/psc/time/time_zone_service.cpp
  src/core/hle/service/psc/time/time_zone_service.h
  src/core/hle/service/ro/ro.cpp
Labels: early-access-merge, android-merge

#12877 service: hid: Multiple fixes
  src/hid_core/resource_manager.cpp
  src/hid_core/resource_manager.h
  src/hid_core/resources/digitizer/digitizer.cpp
  src/hid_core/resources/digitizer/digitizer.h
  src/hid_core/resources/npad/npad.cpp
  src/hid_core/resources/npad/npad.h
  src/hid_core/resources/unique_pad/unique_pad.cpp
  src/hid_core/resources/unique_pad/unique_pad.h
Labels: early-access-merge, android-merge

#12892 cmif_serialization: enforce const for references
  src/core/hle/service/cmif_serialization.h
  src/core/hle/service/cmif_types.h
Labels: mainline-merge, android-merge

#12915 dmnt: cheats: Update cheat vm to latest version
  src/core/memory/cheat_engine.cpp
  src/core/memory/cheat_engine.h
  src/core/memory/dmnt_cheat_types.h
  src/core/memory/dmnt_cheat_vm.cpp
  src/core/memory/dmnt_cheat_vm.h
Labels: mainline-merge, android-merge

#12924 typed_address: test values are unsigned
  src/common/typed_address.h
Labels: android-merge

#12905 nvnflinger: release buffers before presentation sleep
  src/core/hle/service/nvnflinger/hardware_composer.cpp
  src/core/hle/service/nvnflinger/hardware_composer.h
  src/core/hle/service/nvnflinger/nvnflinger.cpp
Labels: gpu-fix, mainline-merge, android-merge

#12883 MemoryManager: Reduce the page table size based on last big page address.
  src/core/hle/service/nvdrv/devices/nvhost_as_gpu.cpp
  src/video_core/host1x/host1x.cpp
  src/video_core/memory_manager.cpp
  src/video_core/memory_manager.h
Labels: gpu-new, early-access-merge

#12932 yuzu: Make controller keys easier to assign
  src/yuzu/configuration/configure_hotkeys.cpp
  src/yuzu/configuration/configure_hotkeys.h
  src/yuzu/hotkeys.cpp
Labels: early-access-merge

#12939 dmnt: cheat: Invalidate cache on memory writes
  src/core/memory/cheat_engine.cpp
Labels: mainline-merge

#12954 service: hid: Migrate hidbus to new interface
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/hid/hidbus.cpp
  src/core/hle/service/hid/hidbus.h
  src/hid_core/hidbus/hidbus_base.h
  src/hid_core/hidbus/ringcon.cpp
  src/hid_core/hidbus/ringcon.h
  src/hid_core/hidbus/starlink.cpp
  src/hid_core/hidbus/starlink.h
  src/hid_core/hidbus/stubbed.cpp
  src/hid_core/hidbus/stubbed.h
Labels: early-access-merge

#12903 shader_recompiler: use only ConstOffset for OpImageFetch
  src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
Labels: gpu-fix, vulkan, android-merge

#12966 service: hid: Free npad applet resource
  src/core/hle/service/hid/hid_system_server.cpp
  src/hid_core/resource_manager.cpp
  src/hid_core/resources/npad/npad.cpp
  src/hid_core/resources/npad/npad.h
  src/hid_core/resources/npad/npad_resource.cpp
  src/hid_core/resources/npad/npad_resource.h
Labels: early-access-merge

#12968 android: Thermal throttling indicator
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/BooleanSetting.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AboutFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AddonsFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AppletLauncherFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/DriverManagerFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EarlyAccessFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GameFoldersFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GameInfoFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GamePropertiesFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/HomeSettingsFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/InstallableFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/LicensesFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/SettingsSearchFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/ui/GamesFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/ViewUtils.kt
  src/android/app/src/main/jni/android_settings.h
  src/android/app/src/main/res/layout/fragment_emulation.xml
  src/android/app/src/main/res/menu/menu_overlay_options.xml
  src/android/app/src/main/res/values/strings.xml
Labels: android-merge

#12927 dmnt: cheat: Add pause and resume support
  src/core/memory/cheat_engine.cpp
  src/core/memory/cheat_engine.h
  src/core/memory/dmnt_cheat_vm.cpp
  src/core/memory/dmnt_cheat_vm.h
Labels: early-access-merge

#12920 android: Move JNI setup and helpers to common
  src/android/app/src/main/jni/CMakeLists.txt
  src/android/app/src/main/jni/emu_window/emu_window.cpp
  src/android/app/src/main/jni/game_metadata.cpp
  src/android/app/src/main/jni/native.cpp
  src/android/app/src/main/jni/native.h
  src/android/app/src/main/jni/native_config.cpp
  src/android/app/src/main/jni/native_log.cpp
  src/common/CMakeLists.txt
  src/common/android/android_common.cpp
  src/common/android/android_common.h
  src/common/android/applets/software_keyboard.cpp
  src/common/android/applets/software_keyboard.h
  src/common/android/id_cache.cpp
  src/common/android/id_cache.h
  src/common/fs/fs_android.cpp
  src/common/fs/fs_android.h
Labels: frontend-fix, android-merge

#12949 service: add os types and multi wait API
  src/core/CMakeLists.txt
  src/core/hle/service/am/applet.h
  src/core/hle/service/am/applet_data_broker.h
  src/core/hle/service/glue/time/worker.cpp
  src/core/hle/service/os/event.cpp
  src/core/hle/service/os/event.h
  src/core/hle/service/os/multi_wait.cpp
  src/core/hle/service/os/multi_wait.h
  src/core/hle/service/os/multi_wait_holder.cpp
  src/core/hle/service/os/multi_wait_holder.h
  src/core/hle/service/os/multi_wait_utils.h
  src/core/hle/service/os/mutex.cpp
  src/core/hle/service/os/mutex.h
  src/core/hle/service/server_manager.cpp
  src/core/hle/service/server_manager.h
Labels: early-access-merge, android-merge

#12969 service: bcat: Migrate and refractor service to new IPC
  src/core/CMakeLists.txt
  src/core/file_sys/errors.h
  src/core/hle/service/bcat/backend/backend.cpp
  src/core/hle/service/bcat/backend/backend.h
  src/core/hle/service/bcat/bcat.cpp
  src/core/hle/service/bcat/bcat.h
  src/core/hle/service/bcat/bcat_module.cpp
  src/core/hle/service/bcat/bcat_module.h
  src/core/hle/service/bcat/bcat_result.h
  src/core/hle/service/bcat/bcat_service.cpp
  src/core/hle/service/bcat/bcat_service.h
  src/core/hle/service/bcat/bcat_types.h
  src/core/hle/service/bcat/bcat_util.h
  src/core/hle/service/bcat/delivery_cache_directory_service.cpp
  src/core/hle/service/bcat/delivery_cache_directory_service.h
  src/core/hle/service/bcat/delivery_cache_file_service.cpp
  src/core/hle/service/bcat/delivery_cache_file_service.h
  src/core/hle/service/bcat/delivery_cache_progress_service.cpp
  src/core/hle/service/bcat/delivery_cache_progress_service.h
  src/core/hle/service/bcat/delivery_cache_storage_service.cpp
  src/core/hle/service/bcat/delivery_cache_storage_service.h
  src/core/hle/service/bcat/news/newly_arrived_event_holder.cpp
  src/core/hle/service/bcat/news/newly_arrived_event_holder.h
  src/core/hle/service/bcat/news/news_data_service.cpp
  src/core/hle/service/bcat/news/news_data_service.h
  src/core/hle/service/bcat/news/news_database_service.cpp
  src/core/hle/service/bcat/news/news_database_service.h
  src/core/hle/service/bcat/news/news_service.cpp
  src/core/hle/service/bcat/news/news_service.h
  src/core/hle/service/bcat/news/overwrite_event_holder.cpp
  src/core/hle/service/bcat/news/overwrite_event_holder.h
  src/core/hle/service/bcat/news/service_creator.cpp
  src/core/hle/service/bcat/news/service_creator.h
  src/core/hle/service/bcat/service_creator.cpp
  src/core/hle/service/bcat/service_creator.h
  src/core/hle/service/service.cpp
Labels: early-access-merge, android-merge

#12978 host_shaders: add vendor workaround for adreno drivers
  src/video_core/host_shaders/vulkan_present.vert
Labels: vulkan, early-access-merge, android-merge

#12998 android: Swap confirmation buttons for delete save data dialog
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/GamePropertiesFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/MessageDialogFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/model/MessageDialogViewModel.kt
Labels: android-merge

#12989 yuzu: Allow non npad hotkeys and disable controller navigation requirement
  src/yuzu/hotkeys.cpp
Labels: early-access-merge

#12975 Texture Cache: Fix untracking on GPU remap
  src/video_core/texture_cache/image_info.cpp
  src/video_core/texture_cache/image_info.h
  src/video_core/texture_cache/texture_cache.h
Labels: gpu-fix, early-access-merge, android-merge

#12974 service: ldn: Migrate and refractor service to new IPC
  src/core/CMakeLists.txt
  src/core/hle/service/ldn/lan_discovery.cpp
  src/core/hle/service/ldn/lan_discovery.h
  src/core/hle/service/ldn/ldn.cpp
  src/core/hle/service/ldn/ldn.h
  src/core/hle/service/ldn/ldn_types.h
  src/core/hle/service/ldn/monitor_service.cpp
  src/core/hle/service/ldn/monitor_service.h
  src/core/hle/service/ldn/sf_monitor_service.cpp
  src/core/hle/service/ldn/sf_monitor_service.h
  src/core/hle/service/ldn/sf_service.cpp
  src/core/hle/service/ldn/sf_service.h
  src/core/hle/service/ldn/sf_service_monitor.cpp
  src/core/hle/service/ldn/sf_service_monitor.h
  src/core/hle/service/ldn/system_local_communication_service.cpp
  src/core/hle/service/ldn/system_local_communication_service.h
  src/core/hle/service/ldn/user_local_communication_service.cpp
  src/core/hle/service/ldn/user_local_communication_service.h
Labels: early-access-merge

#13007 android: Expose FSR slider and add vertical alignment setting
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/IntSetting.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/Settings.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/model/view/SettingsItem.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/settings/ui/SettingsFragmentPresenter.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/EmulationFragment.kt
  src/android/app/src/main/jni/android_settings.h
  src/android/app/src/main/res/values/arrays.xml
  src/android/app/src/main/res/values/strings.xml
Labels: android-merge

#13009 android: Message dialog tweaks
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/AddonsFragment.kt
  src/android/app/src/main/java/org/yuzu/yuzu_emu/fragments/MessageDialogFragment.kt
Labels: android-merge

#12996 service: set: Migrate ISettingsServer to new interface
  src/core/CMakeLists.txt
  src/core/hle/service/set/key_code_map.h
  src/core/hle/service/set/private_settings.h
  src/core/hle/service/set/settings_server.cpp
  src/core/hle/service/set/settings_server.h
  src/core/hle/service/set/settings_types.h
Labels: mainline-merge, android-merge

#13011 vi: rewrite for new IPC
  src/core/CMakeLists.txt
  src/core/hle/service/am/service/common_state_getter.cpp
  src/core/hle/service/nvnflinger/binder.h
  src/core/hle/service/nvnflinger/buffer_queue_producer.cpp
  src/core/hle/service/nvnflinger/buffer_queue_producer.h
  src/core/hle/service/vi/application_display_service.cpp
  src/core/hle/service/vi/application_display_service.h
  src/core/hle/service/vi/application_root_service.cpp
  src/core/hle/service/vi/application_root_service.h
  src/core/hle/service/vi/hos_binder_driver.cpp
  src/core/hle/service/vi/hos_binder_driver.h
  src/core/hle/service/vi/manager_display_service.cpp
  src/core/hle/service/vi/manager_display_service.h
  src/core/hle/service/vi/manager_root_service.cpp
  src/core/hle/service/vi/manager_root_service.h
  src/core/hle/service/vi/service_creator.cpp
  src/core/hle/service/vi/service_creator.h
  src/core/hle/service/vi/system_display_service.cpp
  src/core/hle/service/vi/system_display_service.h
  src/core/hle/service/vi/system_root_service.cpp
  src/core/hle/service/vi/system_root_service.h
  src/core/hle/service/vi/vi.cpp
  src/core/hle/service/vi/vi.h
  src/core/hle/service/vi/vi_m.cpp
  src/core/hle/service/vi/vi_m.h
  src/core/hle/service/vi/vi_s.cpp
  src/core/hle/service/vi/vi_s.h
  src/core/hle/service/vi/vi_types.h
  src/core/hle/service/vi/vi_u.cpp
  src/core/hle/service/vi/vi_u.h
Labels: mainline-merge, android-merge

#13016 service: set: Migrate ISystemSettingsServer to new IPC
  src/core/hle/service/audio/audctl.cpp
  src/core/hle/service/glue/time/manager.cpp
  src/core/hle/service/glue/time/static.cpp
  src/core/hle/service/glue/time/worker.cpp
  src/core/hle/service/mii/mii.cpp
  src/core/hle/service/set/setting_formats/system_settings.h
  src/core/hle/service/set/settings_types.h
  src/core/hle/service/set/system_settings_server.cpp
  src/core/hle/service/set/system_settings_server.h
  src/hid_core/resources/hid_firmware_settings.cpp
  src/hid_core/resources/npad/npad_vibration.cpp
  src/hid_core/resources/touch_screen/touch_screen_resource.cpp
Labels: mainline-merge, android-merge

#13017 kernel: add and enable system suspend type
  src/core/core.cpp
  src/core/hle/kernel/k_thread.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
Labels: core-fix, kernel-fix, mainline-merge, android-merge

#13066 android: Map touches to touchscreen
  src/android/app/src/main/jni/emu_window/emu_window.cpp
  src/android/app/src/main/jni/emu_window/emu_window.h
  src/android/app/src/main/jni/native_input.cpp
Labels: android-merge

#13064 android: Only do first startup automapping if nothing has been mapped
  src/android/app/src/main/java/org/yuzu/yuzu_emu/activities/EmulationActivity.kt
Labels: android-merge

#13032 service: Implement functions needed by Qlaunch
  src/core/hle/service/acc/profile_manager.cpp
  src/core/hle/service/am/applet_manager.cpp
  src/core/hle/service/am/service/library_applet_self_accessor.cpp
  src/core/hle/service/am/service/library_applet_self_accessor.h
  src/core/hle/service/caps/caps_a.cpp
  src/core/hle/service/caps/caps_a.h
  src/core/hle/service/erpt/erpt.cpp
Labels: mainline-merge, android-merge

#13067 android: Flip AB/XY for xbox controllers during auto-mapping
  src/input_common/drivers/android.h
Labels: android-merge

#13030 service: audio: Rewrite IAudioController to new IPC
  src/core/CMakeLists.txt
  src/core/hle/service/audio/audctl.cpp
  src/core/hle/service/audio/audctl.h
  src/core/hle/service/audio/audio.cpp
  src/core/hle/service/audio/audio_controller.cpp
  src/core/hle/service/audio/audio_controller.h
Labels: mainline-merge, android-merge

#13070 am: account for offset in transfer memory storage
  src/core/hle/service/am/library_applet_storage.cpp
Labels: mainline-merge, android-merge

#13048 ns: rewrite for new IPC
  src/core/CMakeLists.txt
  src/core/file_sys/system_archive/shared_font.cpp
  src/core/hle/service/am/frontend/applet_web_browser.cpp
  src/core/hle/service/am/service/application_functions.cpp
  src/core/hle/service/am/service/library_applet_self_accessor.cpp
  src/core/hle/service/ns/account_proxy_interface.cpp
  src/core/hle/service/ns/account_proxy_interface.h
  src/core/hle/service/ns/application_manager_interface.cpp
  src/core/hle/service/ns/application_manager_interface.h
  src/core/hle/service/ns/application_version_interface.cpp
  src/core/hle/service/ns/application_version_interface.h
  src/core/hle/service/ns/content_management_interface.cpp
  src/core/hle/service/ns/content_management_interface.h
  src/core/hle/service/ns/develop_interface.cpp
  src/core/hle/service/ns/develop_interface.h
  src/core/hle/service/ns/document_interface.cpp
  src/core/hle/service/ns/document_interface.h
  src/core/hle/service/ns/download_task_interface.cpp
  src/core/hle/service/ns/download_task_interface.h
  src/core/hle/service/ns/dynamic_rights_interface.cpp
  src/core/hle/service/ns/dynamic_rights_interface.h
  src/core/hle/service/ns/ecommerce_interface.cpp
  src/core/hle/service/ns/ecommerce_interface.h
  src/core/hle/service/ns/factory_reset_interface.cpp
  src/core/hle/service/ns/factory_reset_interface.h
  src/core/hle/service/ns/ns.cpp
  src/core/hle/service/ns/ns.h
  src/core/hle/service/ns/ns_results.h
  src/core/hle/service/ns/ns_types.h
  src/core/hle/service/ns/pdm_qry.cpp
  src/core/hle/service/ns/platform_service_manager.cpp
  src/core/hle/service/ns/platform_service_manager.h
  src/core/hle/service/ns/query_service.cpp
  src/core/hle/service/ns/query_service.h
  src/core/hle/service/ns/read_only_application_control_data_interface.cpp
  src/core/hle/service/ns/read_only_application_control_data_interface.h
  src/core/hle/service/ns/read_only_application_record_interface.cpp
  src/core/hle/service/ns/read_only_application_record_interface.h
  src/core/hle/service/ns/service_getter_interface.cpp
  src/core/hle/service/ns/service_getter_interface.h
  src/core/hle/service/ns/system_update_control.cpp
  src/core/hle/service/ns/system_update_control.h
  src/core/hle/service/ns/system_update_interface.cpp
  src/core/hle/service/ns/system_update_interface.h
  src/core/hle/service/ns/vulnerability_manager_interface.cpp
  src/core/hle/service/ns/vulnerability_manager_interface.h
Labels: hle-new, mainline-merge, android-merge

#13026 shader_recompiler: fix non-const offset for arrayed image types
  src/shader_recompiler/backend/spirv/emit_spirv_image.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_instructions.h
Labels: gpu-fix, mainline-merge, vulkan, android-merge

#13006 buffer_cache: use mapped range with large vertex buffer size
  src/video_core/buffer_cache/buffer_cache.h
Labels: mainline-merge, android-merge

#13031 service: btm: Migrate service to new IPC
  src/core/CMakeLists.txt
  src/core/hle/service/btm/btm.cpp
  src/core/hle/service/btm/btm.h
  src/core/hle/service/btm/btm_debug.cpp
  src/core/hle/service/btm/btm_debug.h
  src/core/hle/service/btm/btm_system.cpp
  src/core/hle/service/btm/btm_system.h
  src/core/hle/service/btm/btm_system_core.cpp
  src/core/hle/service/btm/btm_system_core.h
  src/core/hle/service/btm/btm_user.cpp
  src/core/hle/service/btm/btm_user.h
  src/core/hle/service/btm/btm_user_core.cpp
  src/core/hle/service/btm/btm_user_core.h
Labels: early-access-merge, android-merge

#13079 vi: misc fixes
  src/core/hle/service/nvnflinger/display.h
  src/core/hle/service/nvnflinger/hardware_composer.cpp
  src/core/hle/service/nvnflinger/surface_flinger.cpp
  src/core/hle/service/nvnflinger/surface_flinger.h
  src/core/hle/service/vi/container.cpp
  src/core/hle/service/vi/container.h
  src/core/hle/service/vi/layer.h
  src/core/hle/service/vi/layer_list.h
  src/core/hle/service/vi/shared_buffer_manager.cpp
Labels: hle-fix, mainline-merge, android-merge

#13105 android: Misc controller fixes
  src/android/app/src/main/java/org/yuzu/yuzu_emu/features/input/model/PlayerInput.kt
  src/android/app/src/main/jni/native.cpp
  src/android/app/src/main/jni/native_input.cpp
Labels: android-merge

#13075 shader_recompiler: throw on missing geometry streams in geometry shaders
  src/shader_recompiler/backend/spirv/emit_spirv.cpp
  src/shader_recompiler/backend/spirv/emit_spirv_special.cpp
  src/shader_recompiler/profile.h
  src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
  src/video_core/vulkan_common/vulkan_device.h
Labels: mainline-merge, vulkan, android-merge

#13001 vulkan_device: don't use fixed cap for memory limits
  src/common/settings.h
  src/common/settings_enums.h
  src/video_core/vulkan_common/vulkan_device.cpp
  src/yuzu/configuration/shared_translation.cpp
Labels: mainline-merge

#12982 fs: Add FileSystemAccessor and use cmif serialization
  src/core/CMakeLists.txt
  src/core/file_sys/fs_filesystem.h
  src/core/file_sys/fs_memory_management.h
  src/core/file_sys/fs_path.h
  src/core/file_sys/fs_path_utility.h
  src/core/file_sys/fs_string_util.h
  src/core/file_sys/fsa/fs_i_directory.h
  src/core/file_sys/fsa/fs_i_file.h
  src/core/file_sys/fsa/fs_i_filesystem.h
  src/core/file_sys/fssrv/fssrv_sf_path.h
  src/core/hle/service/filesystem/fsp/fs_i_directory.cpp
  src/core/hle/service/filesystem/fsp/fs_i_directory.h
  src/core/hle/service/filesystem/fsp/fs_i_file.cpp
  src/core/hle/service/filesystem/fsp/fs_i_file.h
  src/core/hle/service/filesystem/fsp/fs_i_filesystem.cpp
  src/core/hle/service/filesystem/fsp/fs_i_filesystem.h
Labels: mainline-merge, android-merge

#13117 psc: stub overlay notification channel
  src/core/CMakeLists.txt
  src/core/hle/service/psc/ovln/ovln_types.h
  src/core/hle/service/psc/ovln/receiver.cpp
  src/core/hle/service/psc/ovln/receiver.h
  src/core/hle/service/psc/ovln/receiver_service.cpp
  src/core/hle/service/psc/ovln/receiver_service.h
  src/core/hle/service/psc/ovln/sender.cpp
  src/core/hle/service/psc/ovln/sender.h
  src/core/hle/service/psc/ovln/sender_service.cpp
  src/core/hle/service/psc/ovln/sender_service.h
  src/core/hle/service/psc/pm_control.cpp
  src/core/hle/service/psc/pm_control.h
  src/core/hle/service/psc/pm_module.cpp
  src/core/hle/service/psc/pm_module.h
  src/core/hle/service/psc/pm_service.cpp
  src/core/hle/service/psc/pm_service.h
  src/core/hle/service/psc/psc.cpp
  src/core/hle/service/psc/psc.h
Labels: early-access-merge, android-merge

#13073 fsp: Migrate remaining interfaces to cmif serialization
  src/android/app/src/main/jni/native.cpp
  src/core/CMakeLists.txt
  src/core/file_sys/fs_save_data_types.h
  src/core/file_sys/savedata_factory.cpp
  src/core/file_sys/savedata_factory.h
  src/core/hle/service/am/service/application_functions.cpp
  src/core/hle/service/filesystem/fsp/fs_i_filesystem.h
  src/core/hle/service/filesystem/fsp/fs_i_multi_commit_manager.cpp
  src/core/hle/service/filesystem/fsp/fs_i_multi_commit_manager.h
  src/core/hle/service/filesystem/fsp/fs_i_save_data_info_reader.cpp
  src/core/hle/service/filesystem/fsp/fs_i_save_data_info_reader.h
  src/core/hle/service/filesystem/fsp/fs_i_storage.cpp
  src/core/hle/service/filesystem/fsp/fs_i_storage.h
  src/core/hle/service/filesystem/fsp/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp/fsp_srv.h
  src/core/hle/service/filesystem/fsp/fsp_types.h
  src/yuzu/main.cpp
Labels: mainline-merge, android-merge

#13100 audio: move to new ipc
  src/CMakeLists.txt
  src/audio_core/audio_in_manager.cpp
  src/audio_core/audio_in_manager.h
  src/audio_core/device/audio_buffers.h
  src/audio_core/opus/decoder.cpp
  src/audio_core/opus/decoder.h
  src/audio_core/opus/decoder_manager.cpp
  src/audio_core/opus/decoder_manager.h
  src/audio_core/opus/hardware_opus.cpp
  src/audio_core/opus/hardware_opus.h
  src/audio_core/opus/parameters.h
  src/audio_core/renderer/audio_device.cpp
  src/audio_core/renderer/audio_device.h
  src/audio_core/renderer/audio_renderer.cpp
  src/audio_core/renderer/audio_renderer.h
  src/audio_core/renderer/behavior/info_updater.cpp
  src/audio_core/renderer/behavior/info_updater.h
  src/audio_core/renderer/memory/pool_mapper.cpp
  src/audio_core/renderer/memory/pool_mapper.h
  src/audio_core/renderer/system.cpp
  src/audio_core/renderer/system.h
  src/audio_core/sink/oboe_sink.cpp
  src/common/string_util.cpp
  src/common/string_util.h
  src/core/CMakeLists.txt
  src/core/hle/service/audio/audin_u.cpp
  src/core/hle/service/audio/audin_u.h
  src/core/hle/service/audio/audio.cpp
  src/core/hle/service/audio/audio_controller.cpp
  src/core/hle/service/audio/audio_controller.h
  src/core/hle/service/audio/audio_device.cpp
  src/core/hle/service/audio/audio_device.h
  src/core/hle/service/audio/audio_in.cpp
  src/core/hle/service/audio/audio_in.h
  src/core/hle/service/audio/audio_in_manager.cpp
  src/core/hle/service/audio/audio_in_manager.h
  src/core/hle/service/audio/audio_out.cpp
  src/core/hle/service/audio/audio_out.h
  src/core/hle/service/audio/audio_out_manager.cpp
  src/core/hle/service/audio/audio_out_manager.h
  src/core/hle/service/audio/audio_renderer.cpp
  src/core/hle/service/audio/audio_renderer.h
  src/core/hle/service/audio/audio_renderer_manager.cpp
  src/core/hle/service/audio/audio_renderer_manager.h
  src/core/hle/service/audio/audout_u.cpp
  src/core/hle/service/audio/audout_u.h
  src/core/hle/service/audio/audren_u.cpp
  src/core/hle/service/audio/audren_u.h
  src/core/hle/service/audio/final_output_recorder_manager.cpp
  src/core/hle/service/audio/final_output_recorder_manager.h
  src/core/hle/service/audio/final_output_recorder_manager_for_applet.cpp
  src/core/hle/service/audio/final_output_recorder_manager_for_applet.h
  src/core/hle/service/audio/hardware_opus_decoder.cpp
  src/core/hle/service/audio/hardware_opus_decoder.h
  src/core/hle/service/audio/hardware_opus_decoder_manager.cpp
  src/core/hle/service/audio/hardware_opus_decoder_manager.h
  src/core/hle/service/audio/hwopus.cpp
  src/core/hle/service/audio/hwopus.h
  src/core/hle/service/cmif_serialization.h
Labels: mainline-merge, android-merge

#13141 fs: fix argument order
  src/core/hle/service/filesystem/fsp/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp/fsp_srv.h
Labels: mainline-merge, android-merge

#13142 android: Play vibrations asynchronously
  src/input_common/drivers/android.cpp
  src/input_common/drivers/android.h
  src/input_common/drivers/sdl_driver.h
  src/input_common/input_engine.h
Labels: android-merge

#13081 aoc: Migrate to use cmif serialization
  src/core/CMakeLists.txt
  src/core/hle/service/aoc/addon_content_manager.cpp
  src/core/hle/service/aoc/addon_content_manager.h
  src/core/hle/service/aoc/aoc_u.cpp
  src/core/hle/service/aoc/aoc_u.h
  src/core/hle/service/aoc/purchase_event_manager.cpp
  src/core/hle/service/aoc/purchase_event_manager.h
  src/core/hle/service/services.cpp
Labels: mainline-merge, android-merge

#13160 glue: load initial year setting as s32
  src/core/hle/service/glue/time/manager.cpp
Labels: mainline-merge, android-merge

#13154 core: hid: Reintroduce vibration filter
  src/hid_core/frontend/emulated_controller.cpp
  src/hid_core/frontend/emulated_controller.h
  src/hid_core/hid_types.h
  src/hid_core/resources/npad/npad.cpp
Labels: mainline-merge, android-merge

#13149 video_core: make gpu context aware of rendering program
  src/common/settings.h
  src/core/core.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp
  src/core/hle/service/nvdrv/devices/nvhost_gpu.h
  src/video_core/control/channel_state.cpp
  src/video_core/control/channel_state.h
  src/video_core/control/channel_state_cache.cpp
  src/video_core/control/channel_state_cache.h
  src/video_core/control/channel_state_cache.inc
  src/video_core/gpu.cpp
  src/video_core/gpu.h
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
Labels: gpu-fix, mainline-merge, android-merge

#13159 core: enable error applet, add stubs for web applet
  src/common/settings.h
  src/core/CMakeLists.txt
  src/core/hle/service/acc/acc.cpp
  src/core/hle/service/acc/acc_u1.cpp
  src/core/hle/service/am/am_types.h
  src/core/hle/service/am/service/common_state_getter.cpp
  src/core/hle/service/am/service/common_state_getter.h
  src/core/hle/service/erpt/erpt.cpp
  src/core/hle/service/filesystem/fsp/fsp_srv.cpp
  src/core/hle/service/filesystem/fsp/fsp_srv.h
  src/core/hle/service/ldn/monitor_service.cpp
  src/core/hle/service/ldn/monitor_service.h
  src/core/hle/service/set/settings_types.h
  src/core/hle/service/set/system_settings_server.cpp
  src/core/hle/service/set/system_settings_server.h
  src/core/hle/service/ssl/cert_store.cpp
  src/core/hle/service/ssl/cert_store.h
  src/core/hle/service/ssl/ssl.cpp
  src/core/hle/service/ssl/ssl_types.h
  src/yuzu/configuration/configure_applets.cpp
Labels: mainline-merge, android-merge

#13172 renderer_opengl: declare geometry stream support in profile
  src/video_core/renderer_opengl/gl_shader_cache.cpp
Labels: gpu-fix, mainline-merge

#13166 buffer_cache: avoid overflow in usage tracker
  src/video_core/buffer_cache/usage_tracker.h
Labels: early-access-merge, android-merge

#13122 vk_rasterizer: flip scissor y on lower left origin mode
  src/video_core/engines/draw_manager.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_rasterizer.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.cpp
  src/video_core/renderer_vulkan/vk_texture_cache.h
Labels: gpu-fix, mainline-merge, vulkan, android-merge

#12749 general: workarounds for SMMU syncing issues
  src/video_core/buffer_cache/buffer_cache.h
  src/video_core/renderer_vulkan/vk_query_cache.cpp
Labels: mainline-merge, android-merge

#13171 texture_cache: do not track invalid addresses
  src/video_core/texture_cache/texture_cache.h
Labels: gpu-fix, mainline-merge, android-merge

#13135 service: hid: Migrate HidServer to new IPC
  src/core/CMakeLists.txt
  src/core/hle/service/hid/active_vibration_device_list.cpp
  src/core/hle/service/hid/active_vibration_device_list.h
  src/core/hle/service/hid/applet_resource.cpp
  src/core/hle/service/hid/applet_resource.h
  src/core/hle/service/hid/hid_server.cpp
  src/core/hle/service/hid/hid_server.h
  src/hid_core/hid_types.h
  src/hid_core/resource_manager.cpp
  src/hid_core/resource_manager.h
  src/hid_core/resources/palma/palma.cpp
  src/hid_core/resources/palma/palma.h
Labels: mainline-merge, android-merge
